<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<?= $this->headTitle() ?>
		<meta name="description" content="">
		<?= $this->headLink() . PHP_EOL ?>
		<?= $this->headScript() . PHP_EOL ?>
	</head>
	<body>
		<?php echo $this->layout()->content; ?>
		<?= $this->inlineScript() . PHP_EOL ?>
	</body>
</html>