SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE study ADD status TINYINT NOT NULL AFTER study_type , ADD INDEX ( status ) ;

ALTER TABLE `study` CHANGE `status` `status` TINYINT( 4 ) UNSIGNED NOT NULL DEFAULT '0';

SET FOREIGN_KEY_CHECKS=1;