ALTER TABLE survey_trailer_info MODIFY COLUMN category ENUM(
'pre-release movie',
'current movie',
'sneak-peek movie',
'retro movie',
'pre-release game',
'current game',
'sneak-peek game',
'retro game',
'pre-release TV show',
'current TV show',
'sneak-peek TV show',
'retro TV show',
'pre-release music video',
'current music video',
'sneak-peek music video',
'retro music video',
'Pre-Release Machinima Series Trailer',
'Current  Machinima Series Trailer',
'Sneak-Peek Machinima Series Trailer',
'Retro  Machinima Series Trailer',
'Machinima Episode',
'YouTube Clip',
'Movie Clip',
'TV Clip',
'TV Commercial',
'Behind the Scenes Clip'
);