<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Say.So | App</title>
        <?= $this->headLink() . PHP_EOL ?>
        <?= $this->headScript() . PHP_EOL ?>
    </head>
    <body>
        <div id="layout">
            <header>
                <h1>Say.So</h1>
                <img height="60" width="230" alt="Say.So Logo" src="/img/say-so.png" style="width: 230px; height: 60px;">
                <nav class="main">
                    <ul>                        
                        <li><a href="/admin" title="Admin"><span>Admin</span></a></li>
                        <li><a href="/admin/metrics/" title="Real-Time Metrics"><span>Metrics</span></a></li>
                    </ul>
                    <?php //echo $this->partial('partials/user-login.phtml', 'default') ?>
                </nav>
            </header>
            <div id="main" role="main">
                <?= $this->layout()->content ?>
            </div>
            <footer></footer>
        </div>
    </body>
</html>