<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Say.So Dashboard <?= (in_array(APPLICATION_ENV, array('development', 'sandbox', 'testing', 'staging')) ? " - " . APPLICATION_ENV : "") ?></title>
		<?= $this->headLink() . PHP_EOL ?>
		<?= $this->headScript() . PHP_EOL ?>
	</head>
	<body>
		<div id="layout">
			<header>
				<h1>Say.So</h1>
				<img width="183" height="80" alt="Say.So Logo" src="/img/say-so.png" style="margin-left: 10px; width: 183px; height: 80px;">
				<nav class="main">
					<ul>
						<li><a href="/admin" title="Admin"><span>Admin</span></a></li>
						<li><a href="/admin/metrics/" title="Real-Time Metrics"><span>Metrics</span></a></li>
					</ul>
					<?php echo $this->partial('partials/common-auth.phtml', 'admin') ?>
					<div class="clear"></div>
				</nav>
			</header>
			<div id="main" role="main">
				<?= $this->layout()->content ?>
			</div>
			<footer></footer>
		</div>
		<div id="system-message" title="System message"></div>
	</body>
</html>