<h3>ADjuster DEV</h3>
<p><a href="/install/ADjuster/ADjusterDEV.xpi" title="Click to install the ADjusterDEV app in your browser">Install ADjusterDEV in your browser</a></p>
<h3>SaySo</h3>
<p><a href="/install/Sayso/Sayso.xpi" title="Click to install the SaySo app in your browser">Install SaySo in your browser</a></p>
<h3>Starbar</h3>
<p><a href="/install/StarBar/Starbar.xpi" title="Click to install the StarBar app in your browser">Install StarBar in your browser</a></p>