<?php
$baseUrl = 'http://' . Registry::getConfig()->baseDomain;
?>

<div id="sayso-onboard">
	<div id="sso_wrapper">
				<div id="sso_close">x</div>
	  	<div id="sso_logo">
			<a href=""><img src="<?= $baseUrl ?>/client/machinima/images/logo_machinima_onboard.png" alt="Snakkle Logo" /></a>
		</div><!-- #sso_logo -->
		
	  	<div class="sso_content">
	  		<div class="hr"></div>
			<?php
			 if( $this->onboarding_type == "new_user" ) {?>
			<div id="sso_new_users" class="ssp_panel1">
				<h2 class="sso_content_title">What is Say So?</h2>
				<p>
				Are you a Machinima junkie? Do you eagerly await new shows and trailers? Are you interested in making Machinima better for everyone? If so, you might be a perfect recruit for Machinima | Recon!
				</p>
				<p>
				Earn real prizes and entry into awesome giveaways by answering polls, rating Machinima content and giving your Say So about anything and everything Machinima related.
				</p>
				<div style="width: 634px;height: 308px; margin-right: auto; margin-left: auto; border-radius: 8px;">
					<a href='#' class="goto2">
						<img src="<?= $baseUrl ?>/client/machinima/images/Onboarding1-01.png" alt="Snakkle Say.So Offers" />
					</a>
				</div>
			</div>
			<div class="navbar ssp_panel1">
				<h2 id="go-now"><a href='#' class="goto4">I'm ready to get started now!</a></h2><img src="<?= $baseUrl ?>/client/machinima/images/1whatissayso_blue.jpg" alt="What is Say.so" /><a href='#' class="goto2"><img src="<?= $baseUrl ?>/client/machinima/images/2whatcanido_blue-grey.jpg" alt="What Can I Do?" /></a><a href='#' class="goto3"><img src="<?= $baseUrl ?>/client/machinima/images/3whatdoiget_grey.jpg" alt="What Do I Get?" /></a><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/4getstarted_grey.jpg" alt="Get Started" /></a>
			</div>

			<div id="sso_new_users2" class="ssp_panel2 sso_hidden">
			<h2>What can I do?</h2>
				<p>Earn Coins by taking polls, answering surveys and giving your opinion on Machinima content.<br />Redeem Coins for items in our Reward Center.</p>
				<div style="width: 634px;height: 308px; margin-right: auto; margin-left: auto;border-radius: 8px;"><a href='#' class="goto3"><img src="<?= $baseUrl ?>/client/machinima/images/Onboarding2-01.png" alt="Snakkle Say.So - What can I do?" /></a></div>
			</div>
			<div class="navbar ssp_panel2 sso_hidden">
				<h2 id="go-now"><a href='#' class="goto4">I'm ready to get started now!</a></h2><a href='#' class="goto1"><img src="<?= $baseUrl ?>/client/machinima/images/1whatissayso_grey.jpg" alt="What is Say.so" /></a><img src="<?= $baseUrl ?>/client/machinima/images/2whatcanido_grey-blue.jpg" alt="What Can I Do?" /><a href='#' class="goto3"><img src="<?= $baseUrl ?>/client/machinima/images/3whatdoiget_blue-grey.jpg" alt="What Do I Get?" /></a><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/4getstarted_grey.jpg" alt="Get Started" /></a>
			</div><!-- /navbar -->

			<div id="sso_new_users3" class="ssp_panel3 sso_hidden">
			<h2>What do I get?</h2>
				<p>Great Prizes - The Reward Center is full of prizes designed specifically for the Machinima fans.</p>
				<div style="width: 637px;height: 308px; margin-right: auto; margin-left: auto;border-radius: 8px;"><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/Onboarding3-01.png" alt="Snakkle Say.So - What do I get?" /></a></div>

			</div>
			<div class="navbar ssp_panel3 sso_hidden">
				<h2 id="go-now"><a href='#' class="goto4">I'm ready to get started now!</a></h2><a href='#' class="goto1"><img src="<?= $baseUrl ?>/client/machinima/images/1whatissayso_grey.jpg" alt="What is Say.so" /></a><a href='#' class="goto2"><img src="<?= $baseUrl ?>/client/machinima/images/2whatcanido_grey.jpg" alt="What Can I Do?" /></a><img src="<?= $baseUrl ?>/client/machinima/images/3whatdoiget_grey-blue.jpg" alt="What Do I Get?" /><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/4getstarted_blue-grey.jpg" alt="Get Started" /></a>
			</div><!-- /navbar -->

			<?php } elseif( $this->onboarding_type == "pilot_user" ) {?>
			<div id="sso_new_users" class="ssp_panel1">
				<h2>Are you a celebrity addict? Do you crave your next dose of Reality TV?<br />Do you follow all the trending celebrity news?</h2>
				<p>Earn real prizes and entry into awesome giveaways by taking fun celebrity polls and quizzes and giving your Say So about anything and everything celebrity related!</p>
				<div style="width: 640px;height: 345px; background-color: gray; margin-right: auto; margin-left: auto;border-radius: 8px;"><a href='#' class="goto2"><img src="<?= $baseUrl ?>/client/machinima/images/Onboarding1-01.png" alt="Snakkle Say.So Offers" /></a></div>
			</div>
			<div class="navbar ssp_panel1">
				<h2 id="go-now"><a href='#' class="goto4">I'm ready to get started now!</a></h2><img src="<?= $baseUrl ?>/client/machinima/images/1whatissayso_blue.jpg" alt="What is Say.so" /><a href='#' class="goto2"><img src="<?= $baseUrl ?>/client/machinima/images/2whatcanido_blue-grey.jpg" alt="What Can I Do?" /></a><a href='#' class="goto3"><img src="<?= $baseUrl ?>/client/machinima/images/3whatdoiget_grey.jpg" alt="What Do I Get?" /></a><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/4getstarted_grey.jpg" alt="Get Started" /></a>
			</div>

			<div id="sso_new_users2" class="ssp_panel2 sso_hidden">
			<h2>What can I do?</h2>
				<p>Earn Snakkle Bucks by giving your opinion on pop culture polls, answering surveys and<br />taking fun celebrity quizzes. Redeem Snakkle Bucks for items in our Reward Center.</p>
				<div style="width: 634px;height: 342px; background-color: gray; margin-right: auto; margin-left: auto;border-radius: 8px;"><a href='#' class="goto3"><img src="<?= $baseUrl ?>/client/machinima/images/Onboarding2-01.png" alt="Snakkle Say.So - What can I do?" /></a></div>
			</div>
			<div class="navbar ssp_panel2 sso_hidden">
				<h2 id="go-now"><a href='#' class="goto4">I'm ready to get started now!</a></h2><a href='#' class="goto1"><img src="<?= $baseUrl ?>/client/machinima/images/1whatissayso_grey.jpg" alt="What is Say.so" /></a><img src="<?= $baseUrl ?>/client/machinima/images/2whatcanido_grey-blue.jpg" alt="What Can I Do?" /><a href='#' class="goto3"><img src="<?= $baseUrl ?>/client/machinima/images/3whatdoiget_blue-grey.jpg" alt="What Do I Get?" /></a><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/4getstarted_grey.jpg" alt="Get Started" /></a>
			</div><!-- /navbar -->

			<div id="sso_new_users3" class="ssp_panel3 sso_hidden">
			<h2>What do I get?</h2>
				<p>Great Prizes - The Reward Center is full of prizes designed specifically for the celebrity devotee.</p>
				<div style="width: 637px;height: 341px; background-color: gray; margin-right: auto; margin-left: auto;border-radius: 8px;"><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/Onboarding3-01.png" alt="Snakkle Say.So - What do I get?" /></a></div>

			</div>
			<div class="navbar ssp_panel3 sso_hidden">
				<h2 id="go-now"><a href='#' class="goto4">I'm ready to get started now!</a></h2>
				<a href='#' class="goto1"><img src="<?= $baseUrl ?>/client/machinima/images/1whatissayso_grey.jpg" alt="What is Say.so" /></a><a href='#' class="goto2"><img src="<?= $baseUrl ?>/client/machinima/images/2whatcanido_grey.jpg" alt="What Can I Do?" /></a><img src="<?= $baseUrl ?>/client/machinima/images/3whatdoiget_grey-blue.jpg" alt="What Do I Get?" /><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/4getstarted_blue-grey.jpg" alt="Get Started" /></a>
			</div><!-- /navbar -->


			<?php } elseif( $this->onboarding_type == "share" ) {?>
			<div id="sso_new_users" class="ssp_panel1">
				<h2>Are you a celebrity addict? Do you crave your next dose of Reality TV?<br />Do you follow all the trending celebrity news?</h2>
				<p>Earn real prizes and entry into awesome giveaways by taking fun celebrity polls and quizzes and giving your Say So about anything and everything celebrity related!</p>
				<div style="width: 640px;height: 345px; background-color: gray; margin-right: auto; margin-left: auto;border-radius: 8px;"><a href='#' class="goto2"><img src="<?= $baseUrl ?>/client/machinima/images/Onboarding1-01.png" alt="Snakkle Say.So Offers" /></a></div>
			</div>
			<div class="navbar ssp_panel1">
				<h2 id="go-now"><a href='#' class="goto4">I'm ready to get started now!</a></h2>
				<img src="<?= $baseUrl ?>/client/machinima/images/1whatissayso_blue.jpg" alt="What is Say.so" />
				<a href='#' class="goto2"><img src="<?= $baseUrl ?>/client/machinima/images/2whatcanido_blue-grey.jpg" alt="What Can I Do?" /></a><a href='#' class="goto3"><img src="<?= $baseUrl ?>/client/machinima/images/3whatdoiget_grey.jpg" alt="What Do I Get?" /></a><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/4getstarted_grey.jpg" alt="Get Started" /></a>
			</div>

			<div id="sso_new_users2" class="ssp_panel2 sso_hidden">
			<h2>What can I do?</h2>
				<p>Earn Snakkle Bucks by giving your opinion on pop culture polls, answering surveys and<br />taking fun celebrity quizzes. Redeem Snakkle Bucks for items in our Reward Center.</p>
				<div style="width: 634px;height: 342px; background-color: gray; margin-right: auto; margin-left: auto;border-radius: 8px;"><a href='#' class="goto3"><img src="<?= $baseUrl ?>/client/machinima/images/Onboarding2-01.png" alt="Snakkle Say.So - What can I do?" /></a></div>
			</div>
			<div class="navbar ssp_panel2 sso_hidden">
				<h2 id="go-now"><a href='#' class="goto4">I'm ready to get started now!</a></h2>
				<a href='#' class="goto1"><img src="<?= $baseUrl ?>/client/machinima/images/1whatissayso_grey.jpg" alt="What is Say.so" /></a><img src="<?= $baseUrl ?>/client/machinima/images/2whatcanido_grey-blue.jpg" alt="What Can I Do?" /><a href='#' class="goto3"><img src="<?= $baseUrl ?>/client/machinima/images/3whatdoiget_blue-grey.jpg" alt="What Do I Get?" /></a><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/4getstarted_grey.jpg" alt="Get Started" /></a>
			</div><!-- /navbar -->

			<div id="sso_new_users3" class="ssp_panel3 sso_hidden">
			<h2>What do I get?</h2>
				<p>Great Prizes - The Reward Center is full of prizes designed specifically for the celebrity devotee.</p>
				<div style="width: 637px;height: 341px; background-color: gray; margin-right: auto; margin-left: auto;border-radius: 8px;"><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/Onboarding3-01.png" alt="Snakkle Say.So - What do I get?" /></a></div>

			</div>
			<div class="navbar ssp_panel3 sso_hidden">
				<h2 id="go-now"><a href='#' class="goto4">I'm ready to get started now!</a></h2>
				<a href='#' class="goto1"><img src="<?= $baseUrl ?>/client/machinima/images/1whatissayso_grey.jpg" alt="What is Say.so" /></a><a href='#' class="goto2"><img src="<?= $baseUrl ?>/client/machinima/images/2whatcanido_grey.jpg" alt="What Can I Do?" /></a><img src="<?= $baseUrl ?>/client/machinima/images/3whatdoiget_grey-blue.jpg" alt="What Do I Get?" /><a href='#' class="goto4"><img src="<?= $baseUrl ?>/client/machinima/images/4getstarted_blue-grey.jpg" alt="Get Started" /></a>
			</div><!-- /navbar -->

			<?php } ?>
			<div id="sso_enter_password" class="ssp_panel4 sso_hidden">
			<?php if( !$this->user_has_password ) {?>
					<h1>Create your Say.So account</h1>
					<h2 id="sso_protected">So we can make sure your points and rewards are protected</h2>
					<!--<p><strong><?php // = $this->client_email ?></strong></p>-->
					<span class="sso_textError" style="display: none;"></span>
					<form action="" name="" method="">
					<div id="sso_form_flds">
						<p><input id="sso_fld_client_email" name="client_email" type=text class="sso_fld" /><input id="sso_fld_client_email_txt" value="Enter Your Email Address"  /></p>
						<p><input id="sso_fld_password" name="password" type=password class="sso_fld"/>
						<input id="sso_fld_password_txt" value="Enter your desired password (6-12 character limit)"/></p>
						<p><input id="sso_fld_password_vfy" type=password class="sso_fld"/>
						<input id="sso_fld_password_vfy_txt" value="Verify Your Password"/></p>
					</div>
					<p><a id="sayso-get-app" href="" class="sso_theme_button sso_theme_button_disabled sso_theme_buttonXL">GRAB IT</a></p>
					<input type="hidden" id="sayso-install-token" value="<?= $this->token ?>"/>
					</form>
					<p class="sso_noshare_notice">We don't share your email or passwords with anyone... period.</p>

			<?php } else {?>
					<h1>Please enter your Say.So password</h1>
					<p><strong><?= $this->client_email ?></strong></p>
					<span class="sso_textError" style="display: none;"></span>
					<form action="" name="" method="">
					<p><input id="sso_fld_password" name="password" type=password class="sso_fld"/>
					<input id="sso_fld_password_txt" value="Enter your Say.So password"/></p>
					<p><a id="sayso-get-app" href="" class="sso_theme_button sso_theme_button_disabled sso_theme_buttonXL">GRAB IT</a></p>
					<input type="hidden" id="sayso-install-token" value="<?= $this->token ?>"/>
					</form>
					<p class="sso_noshare_notice">We don't share your email or passwords with anyone... period.</p>

			<?php }?>
			</div>
			<div class="navbar ssp_panel4 sso_hidden">
						<a href='#' class="goto1"><img src="<?= $baseUrl ?>/client/machinima/images/1whatissayso_grey.jpg" alt="What is Say.so" /></a><a href='#' class="goto2"><img src="<?= $baseUrl ?>/client/machinima/images/2whatcanido_grey.jpg" alt="What Can I Do?" /></a><a href='#' class="goto3"><img src="<?= $baseUrl ?>/client/machinima/images/3whatdoiget_grey.jpg" alt="What Do I Get?" /></a><img src="<?= $baseUrl ?>/client/machinima/images/4getstarted_grey-blue.jpg" alt="Get Started" />
				</div><!-- /navbar -->
			<div id="sso_allow_install" class="sso_panel sso_hidden">
				<h2 id="sso_allow_install_text"></h2>
			</div>

		</div><!-- .sso_content -->
	</div><!-- #sso_wraper -->
	<script type="text/javascript" src="<?= $baseUrl ?>/client/global/js/starbar-onboard.js"></script>
</div><!-- #sayso-onboard -->

