<?php
$baseUrl = 'http://' . Registry::getConfig()->baseDomain;
?>

<div id="sayso-onboard">
	<div id="sso_wrapper">
				<div id="sso_close">x</div>
	  	<div id="sso_logo">
			<a href=""><img src="<?= $baseUrl ?>/client/snakkle/images/logo_snakkle.png" alt="Snakkle Logo" /></a>
		</div><!-- #sso_logo -->
	  	<div class="sso_content">
			<?php
			 if( $this->onboarding_type == "new_user" ) {?>
			<div id="sso_new_users" class="sso_panel">
				<h1>Are you a Snakkle Fan?</h1>
				<h2>Let your celebrity knowledge earn for you!</h2>
				<p>Become a Super Snakkler and participate in
				Snakkle Say.So<br />- your source for all things celebrity and pop culture.</p>
				<div style="width: 469px;height: 109px; background-color: gray; margin-right: auto; margin-left: auto;border-radius: 8px;"><img src="<?= $baseUrl ?>/client/snakkle/images/offer_snakkle.png" alt="Snakkle Say.So Offers" /></div>
				<h3>
					<strong>GRAB</strong> the Snakkle Say.So browser extension.<br />
					<strong>PROVE</strong> your celebrity knowledge.<br />
					<strong>GET</strong> awesome prizes.<br />
				</h3>
				<h4 style="font-weight: 500"><strong style="color: #1f80c2;">BONUS</strong> Snakkle Bucks when you download the Snakkle Say.So browser<br />extension and become a Super Snakkler today!</h4>
				<div style="height: 20px;">
				<p style="font-size: 12px;"><input type="radio" /> I agree to the <a href="<?= $baseUrl ?>/docs/Say.So_App_EULA.pdf" target="_blank">terms and conditions</a></p>
				</div>
			</div>
			<?php } elseif( $this->onboarding_type == "pilot_user" ) {?>
			<div id="sso_pilot_users" class="sso_panel">
				<h1>Welcome Back!</h1>
				<h3>
					<strong>GRAB</strong> the Snakkle Say.So browser extension.<br />
					<strong>GIVE</strong> your opinion.<br />
					<strong>GET</strong> exclusive deals and awesome prices.<br />
				</h3>
				<div style="width: 230px;height: 135px; background-color: gray; margin-right: auto; margin-left: auto;border-radius: 8px; margin-top: 15px; margin-bottom: 20px;"></div>
				<h4 style="font-weight: 500"><strong style="color: #1f80c2;">BONUS</strong> Snakkle Bucks when you download the Snakkle Say.So browser<br />extension and become a Snakkle Say.So member today!</h4>
				<h4 style="font-weight: 500"><strong style="color: #1f80c2;">PLUS A BONUS for being a previous member</strong></h4>
				<div style="height: 20px;">
				<p style="font-size: 12px;"><input type="radio" /> I agree to the <a href="<?= $baseUrl ?>/docs/snakkle/Say.So_App_EULA.pdf" target="_blank">terms and conditions</a></p>
				</div>
			</div>
			<?php } elseif( $this->onboarding_type == "share" ) {?>
			<div id="sso_share_users" class="sso_panel">
				<h1>Are you a Snakkle Fan?<br>Your opinion counts!</h1>
				<h4>You've been invited to participate in the Snakkle Say.So program - a service for keeping Snakkle products and deals in sync with you, our customers.</h4>
				<div style="margin-right: auto; margin-left: auto; margin-top: 25px; margin-bottom: 30px;">
				<span style="width: 145px;height: 100px; background-color: gray; border-radius: 8px; display: inline-block;"></span>
				<span style="width: 145px;height: 100px; background-color: gray; border-radius: 8px; display: inline-block;"></span>
				<span style="width: 145px;height: 100px; background-color: gray; border-radius: 8px; display: inline-block;"></span>
				</div>
				<h3>
					<strong>GRAB</strong> the Snakkle Say.So browser extension.<br />
					<strong>GIVE</strong> your opinion.<br />
					<strong>GET</strong> exclusive deals and awesome prices.<br />
				</h3>
				<div style="height: 20px;">
				<p style="font-size: 12px;"><input type="radio" /> I agree to the <a href="<?= $baseUrl ?>/docs/snakkle/Say.So_App_EULA.pdf" target="_blank">terms and conditions</a></p>
				</div>
			</div>
			<?php } ?>
			<div id="sso_enter_password" class="sso_panel sso_hidden">
			<?php if( !$this->user_has_password ) {?>
					<h1>Create your Say.So account</h1>
					<h2 id="sso_protected">So we can make sure your points and rewards are protected</h2>
					<!--<p><strong><?php // = $this->client_email ?></strong></p>-->
					<span class="sso_textError" style="display: none;"></span>
					<form action="" name="" method="">
					<div id="sso_form_flds">
						<p><label for="sso_fld_client_email">Email Address </label><input id="sso_fld_client_email" name="client_email" type=text class="sso_fld" /><input id="sso_fld_client_email_txt" value="Enter Your Email Address"  /></p>
						<p><label for="sso_fld_password">Password </label><input id="sso_fld_password" name="password" type=password class="sso_fld"/>
						<input id="sso_fld_password_txt" value="Enter your desired password (6-12 character limit)"/></p>
						<p><label for="sso_fld_password_vfy">Confirm Password </label><input id="sso_fld_password_vfy" type=password class="sso_fld"/>
						<input id="sso_fld_password_vfy_txt" value="Verify Your Password"/></p>
					</div>
					<p><a id="sayso-get-app" href="" class="sso_theme_button sso_theme_button_disabled sso_theme_buttonXL">GRAB IT</a></p>
					<input type="hidden" id="sayso-install-token" value="<?= $this->token ?>"/>
					</form>
					<p class="sso_noshare_notice"><strong>We don't share your email or passwords with anyone... period.</strong></p>
			<?php } else {?>
					<h1>Please enter your Say.So password</h1>
					<p><strong><?= $this->client_email ?></strong></p>
					<span class="sso_textError" style="display: none;"></span>
					<form action="" name="" method="">
					<p><input id="sso_fld_password" name="password" type=password class="sso_fld"/>
					<input id="sso_fld_password_txt" value="Enter your Say.So password"/></p>
					<p><a id="sayso-get-app" href="" class="sso_theme_button sso_theme_button_disabled sso_theme_buttonXL">GRAB IT</a></p>
					<input type="hidden" id="sayso-install-token" value="<?= $this->token ?>"/>
					</form>
					<p class="sso_noshare_notice"><strong>We don't share your email or passwords with anyone... period.</strong></p>
			<?php }?>
			</div>
			<div id="sso_allow_install" class="sso_panel sso_hidden">
				<h2 id="sso_allow_install_text"></h2>
			</div>
		</div><!-- .sso_content -->
	</div><!-- #sso_wraper -->
	<script type="text/javascript" src="<?= $baseUrl ?>/client/global/js/starbar-onboard.js"></script>
</div><!-- #sayso-onboard -->

