<div class="generic_container">
    <h1 class="big_header">Get The Browser App!</h1>
    <div class="get_app_content">
        <p>
            Now you have seen what you can do, take it a step further and get the browser app.
            The app has exclusive content and higher earning potential etc... The app works like
            this etc... etc...
        </p>
            <span class="terms_and_conditions">
                <!-- js wireup for changing enabled/disabled of get_app_button needed -->
                <input type="checkbox" value="" id="agreeterms">
                <label for="agreeterms">
                    I agree to the <a id="terms" href="#main/terms">terms</a> and <a id="conditions" href="#main/conditions">conditions</a>.
                </label>
            </span>
        <a class="get_app_button" id="grab_it" href="#main/grab-it"></a>
    </div>
</div>