<div class="generic_container">
    <h1 class="big_header">Get The Browser App!</h1>
    <div class="get_app_content">
        <p id="browser_install_instructions">
            Please follow these browser specific instructions. Please follow these browser specific
            instructions. Please follow these browser specific instructions. Please follow these
            instructions. Please follow these browser specific instructions. Please follow these
            instructions. Please follow these browser specific instructions. Please follow these
            browser specific instructions.
        </p>
        <p>
            If your download does not start please click <a id="terms" href="#main/download-app">here</a>.
        </p>
    </div>
</div>