<div class="generic_container">
    <h1 class="big_header">Welcome To Recon</h1>
    <p class="initial_welcome_content">
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
    </p>
    <a class="initial_welcome_option1" href="#main/install"></a>
    <a class="initial_welcome_option2" href="#main/landing">Go To My Dashboard<img src="images/arrow.png"/></a>
</div>