<div class="generic_container">
    <h1 class="initial_welcome_header">Welcome To Recon</h1>
    <p class="initial_welcome_content">
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
    </p>
    <a class="initial_welcome_option1" href="#"></a><!-- we will need to throw id's on these to wire them up-->
    <a class="initial_welcome_option2" href="#">Go To My Dashboard<img src="images/arrow.png"/></a>
</div>