<div class="generic_container">
    <h1 class="initial_welcome_header">Welcome To Recon</h1>
    <p class="initial_welcome_content">
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
        Welcome text goes here. Welcome text goes here. Welcome text goes here.
    </p>
    <!-- option one, "get the browser app" goes here when we have an img -->
    <a class="initial_welcome_option2" href="#">Go To My Dashboard<img src="images/arrow.png"/></a>
</div>