<!-- not logged in -->
<div class="welcome_container">
    <h1 class="welcome_header">Welcome</h1>
    <br/>
    <p class="welcome_content">Machinima Recon is a place to share Lorem ipsum dolor sit amet,
        consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
        dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
        laboris nisi ut aliquip ex ea commodo consequat.
    </p>
    <div class="welcome_join_now">Join Now <img src="images/arrow.png"/></div>
</div>
<!-- logged in, do logic on server side -->
<!-- logged in code here -->