<div class="landing_content_left">
    <div class="landing_profile">
        <img class="landing_profile_picture" id="landing_profile_picture" src="images/profile_pic_default.png"/>
        <h2>Welcome Back, <!-- PHP code for name -->
            <span id="landing_welcome_name" class="landing_welcome_name">SaySo'er</span>
        </h2>
    </div>
    <hr/>
    <div class="landing_stats">
        <h2>My Stats</h2>
        <div class="landing_stats_block">
            <img class="landing_level_image" id="landing_level_image" src="images/level_blank.png"/>
            <aside>
                <span id="landing_level_text">Level 1,</span>&nbsp;
                <span id="landing_level_name" class="landing_level_name">Musician</span>
                <br/>
                <span id="landing_currency_count">193</span>&nbsp;
                <span id="landing_currency_name">Music PaySo</span>
                <br/>
                <span id="landing_experience_count">1932</span>&nbsp;
                <span id="landing_experience_name">Music SaySo</span>
            </aside>
        </div>
    </div>
    <hr/>
    <div class="landing_left_banner">
        <a href="#main/browser-app" class="landing_download_banner"></a>
    </div>
</div>
<div class="landing_content_right">
    <div class="landing_right_banner">
        <h2>PLACEHOLDER!</h2>
    </div>
</div>