<div class="tour_content_left">
    <div class="tour_step">
        <span id="tour_step_number">5 of 9</span>
    </div>
    <h1 class="big_header">Spotlight</h1>
    <p>
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
    </p>
    <div class="join_now"><a href="#main/join">Join Now <img src="images/arrow.png"/></a></div>
    <a class="tour_next" href="#tour/6"></a>
</div>
<div class="tour_content_right">
    <img src="images/tour/spotlight_pop.png"/>
</div>