<div class="tour_content_left">
    <div class="tour_step">
        <span id="tour_step_number">8 of 9</span>
    </div>
    <h1 class="big_header">Rewards Center</h1>
    <p>
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
        Tour text goes here.Tour text goes here.Tour text goes here.
    </p>
    <div class="join_now"><a href="#main/join">Join Now <img src="images/arrow.png"/></a></div>
    <a class="tour_next" href="#tour/9"></a>
</div>
<div class="tour_content_right">
    <img src="images/tour/rewards_pop.png"/>
</div>