<div id="sb_slideshow">
	<div class="sb_promoBG sb_promo_week1">
		<div class="sb_slide">
			<div class="sb_header">
				<img src="//<?= BASE_DOMAIN ?>/images/snakkle/logo_snakkle_lg.png" alt="Snakkle logo" />
			</div><!-- .sb_header -->
			
			<div class="sb_promo_details" style="width: 250px; top: 80px; left: 5px;">
				<p><big>Use your snakkles to buy tokens to enter the Giveaway – the more tokens you get the better your chances of winning!</big></p>
				<p class="sb_promo_link"><a href="#" class="sb_theme_textHighlight_alt">GET YOUR TOKENS</a></p>
				<p><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="">Influencer Survey</a> to be eligible for the giveaways.</small></p>
			</div><!-- .sb_promo_details -->
			
		</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week1 -->	
</div><!-- #sb_slideshow -->