<div id="sb_slideshow">
	<div class="sb_promoBG sb_promo_week1">
		<div class="sb_slide">
			<div class="sb_header">
				<img src="//<?= BASE_DOMAIN ?>/images/snakkle/logo_snakkle_lg.png" alt="Snakkle logo" />
			</div><!-- .sb_header -->

			<div class="sb_promo_details" style="width: 250px; top: 80px; left: 5px;">
				<p><big>Use your Snakkle Bucks to buy tokens to enter the Giveaway – the more tokens you get the better your chances of winning!</big></p>
				<p class="sb_promo_link"><a href="//<?= BASE_DOMAIN ?>/starbar/snakkle/rewards?chosen_good_id=first" class="sb_nav_element sb_theme_textHighlight_alt" rel="sb_popBox_rewards">GET YOUR TOKENS</a></p>
				<p><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="//<?= BASE_DOMAIN ?>/starbar/snakkle/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg">Profile Survey</a> to be eligible for the giveaways.</small></p>
			</div><!-- .sb_promo_details -->

		</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week1 -->
</div><!-- #sb_slideshow -->