<div id="sb_slideshow">
	<div class="sb_promoBG sb_promo_week4">
	<div class="sb_slide">
		<div class="sb_header" style="margin: 10px 0px 0px 20px;">
		<img src="//<?= BASE_DOMAIN ?>/images/snakkle/logo_snakkle.png" alt="Snakkle logo" width="70" />
		</div><!-- .sb_header -->
		<div class="sb_promo_details" style="width: 375px; top: 50px; left: 25px;">
		<p><big>Use your Notes to buy tokens to enter the Giveaway – the more tokens you get the better your chances of winning!</big></p>
		<p style="margin-right: 60px">This month we are giving away an awesome opportunity to have your music played on Hello Music's Independent Channel on Delta Airlines $1500 MSRP. A Takamini Tsunami Relief Acoustic Guitar $500 MSRP, and a Arturia The Laboratory 61 Keyboard $419 MSRP</p>
		<p><a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards?chosen_good_id=2054" class="sb_nav_element" rel="sb_popBox_rewards" style="background-image: none; text-indent: -9999px; width: 210px; height: 30px; display: block; margin: 15px 0px -10px 0px;">Get Entry Tokens</a></p>
		<p style="line-height: 15px; margin-right: 180px"><small style="color: #fff"><strong style="color: #fff">Remember</strong> - Take the <a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_hg" style="color: #fff; text-decoration: underline">Profile Survey</a> to be eligible for the giveaways.</small></p>
		</div><!-- .sb_promo_details -->
	</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week4 -->
	
	<div class="sb_promoBG sb_promo_week1">
	<div class="sb_slide">
		<div class="sb_header">
		<img src="//<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" />
		</div><!-- .sb_header -->
		<div class="sb_promo_details">
		<p>Marshall Electronics V89 Condenser<br />Microphone and Sony 7506 Headphones</p>
		<p><a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards?chosen_good_id=2036" class="sb_nav_element sb_theme_button" rel="sb_popBox_rewards"><span class="sb_theme_buttonArrow">Get Entry Tokens</span></a></p>
		<p style="line-height: 15px"><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_hg">Influencer Survey</a> to be eligible for the giveaways.</small></p>
		</div><!-- .sb_promo_details -->
	</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week1 -->
	<div class="sb_promoBG sb_promo_week2">
	<div class="sb_slide">
		<div class="sb_header">
		<img src="//<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" />
		</div><!-- .sb_header -->
		<div class="sb_promo_details">
		<p>Toca Synergy Series Congas, SDVR12 Djembe, and a LP Black Beauty Cowbell.</p>
		<p><a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards?chosen_good_id=2038" class="sb_nav_element sb_theme_button" rel="sb_popBox_rewards"><span class="sb_theme_buttonArrow">Get Entry Tokens</span></a></p>
		<p style="line-height: 15px"><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_hg">Influencer Survey</a> to be eligible for the giveaways.</small></p>
		</div><!-- .sb_promo_details -->
	</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week2 -->
	<div class="sb_promoBG sb_promo_week3">
	<div class="sb_slide">
		<div class="sb_header">
		<img src="//<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" />
		</div><!-- .sb_header -->
		<div class="sb_promo_details">
		<p>Akai MiniAK and a Arturia Dr. Bob Synth Software.</p>
		<p><a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards?chosen_good_id=2044" class="sb_nav_element sb_theme_button" rel="sb_popBox_rewards"><span class="sb_theme_buttonArrow">Get Entry Tokens</span></a></p>
		<p style="line-height: 15px"><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_hg">Influencer Survey</a> to be eligible for the giveaways.</small></p>
		</div><!-- .sb_promo_details -->
	</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week3 -->
	
</div><!-- #sb_slideshow -->
<?php /*
<div id="sb_slideshow_nav">
	<span class="sb_prev">prev</span>
	<span class="sb_next">next</span>
</div><!-- #sb_slideshow_nav -->
*/ ?>