<div class="sb_header">
	<img src="//<?= BASE_DOMAIN ?>/images/snakkle/logo_snakkle_lg.png" alt="Snakkle logo" />
</div><!-- .sb_header -->
<div class="sb_quiz">
	<? if ($this->quiz && $this->quiz->id) { ?>
		<div class="sb_quiz_main">
			<h2 class="sb_title">Who is this?</h2>
			<p><img src="<?= $this->quiz_question->image_url ?>" alt="<?= $this->quiz_hint ?>" /></p>

			<div class="sb_quiz_question">
				<? if ($this->quiz_hint) { ?>
					<p>
						<strong class="sb_theme_textHighlight">HINT</strong> - <?= $this->quiz_hint ?>
					</p>
				<? } ?>
				<div class="sb_quiz_options">
					<div class="sb_quiz_row">
						<? $choiceCounter = 1 ?>
						<? foreach ($this->quiz_choices as $choice) { ?>
							<? if (($choiceCounter > 1) && (($choiceCounter % 2) == 1)) { ?>
								</div><!-- .sb_quiz_row -->
								<div class="sb_quiz_row">
							<? } ?>
							<div class="sb_quiz_option">
								<input type="radio" class="sb_quiz_option_input" name="quiz" value="<?= $choice->id ?>" id="answer<?= $choice->id ?>"> <label for="answer<?= $choice->id ?>"><?= $choice->title ?></label>
							</div><!-- .sb_quiz_option -->
							<? $choiceCounter++ ?>
						<? } ?>
						<? if (($choiceCounter % 2) == 0) { ?>
							<div class="sb_quiz_option">&nbsp;</div>
						<? } ?>
					</div><!-- .sb_quiz_row -->
				</div><!-- .sb_quiz_options -->
			</div><!-- .sb_quiz_question -->

			<div id="sb_quiz_results_container" style="display: none">
				<div class="sb_quiz_results">
					<div class="sb_quiz_options">
						<div class="sb_quiz_row">
							<? $choiceCounter = 1 ?>
							<? foreach ($this->quiz_choices as $choice) { ?>
								<? if (($choiceCounter > 1) && (($choiceCounter % 2) == 1)) { ?>
									</div><!-- .sb_quiz_row -->
									<div class="sb_quiz_row">
								<? } ?>
								<div id="result_<?= $choice->id ?>" class="sb_quiz_option">
									<p><?= $choice->title ?> - <span id="percentage_of_responses_<?= $choice->id ?>" class="sb_theme_textHighlight"></span></p>

									<div class="sb_progress_bar"></span><span class="sb_currency_percent" style="width: 0px"></span></div>
								</div><!-- .sb_quiz_option -->
								<? $choiceCounter++ ?>
							<? } ?>
							<? if (($choiceCounter % 2) == 0) { ?>
								<div class="sb_quiz_option">&nbsp;</div>
							<? } ?>
						</div><!-- .sb_quiz_row -->
					</div><!-- .sb_quiz_options -->
				</div><!-- .sb_quiz_results -->

				<p id="right_answer_message" style="display: none"><span class="sb_theme_textHighlight_alt">Excellent!</span> You earned <strong class="sb_theme_textHighlight_alt">11 Bucks</strong> &amp; <strong class="sb_theme_textHighlight_alt">150 Stars</strong></p>
				<p id="wrong_answer_message" style="display: none"><span class="sb_textError">Whoops! Better luck on the next quiz!</span></p>

				<div class="sb_externalShares" style="display: none">
					<!-- FACEBOOK -->
					<a class="sb_externalShare sb_externalShare_facebook" rel="sb_mini-snakkle-reward_facebook" 	href="#"
						onclick="return $SQ('#sayso-starbar').trigger('frameCommunication', ['handleFacebookShare', { shared_type: 'quiz', shared_id: <?= $this->quiz->id ?>, link: '//www.facebook.com/dialog/feed?app_id=<?= urlencode($this->facebook_app_id) ?>&link=<?= urlencode($this->share_link) ?>&caption=<?= urlencode($this->facebook_share_caption) ?>&picture=<?= urlencode($this->facebook_share_image_url) ?>&redirect_uri=<?= urlencode($this->facebook_share_callback_url) ?>&name=<?= urlencode($this->facebook_title) ?>&description=<?= urlencode($this->facebook_description) ?>'}]); return false;">
						Facebook Share
					</a>
					<span class="sb_mini-snakkle-reward sb_mini-snakkle-reward_facebook" id="sb_mini-snakkle-reward_facebook">+8</span>
					<!-- / facebook -->

					<! -- TWITTER -->
					<script type="text/javascript">
						$SQ.getScript("//platform.twitter.com/widgets.js", function(){
							function handleTweetEvent(event){
								if (event) {
									$SQ('#sayso-starbar').trigger('frameCommunication', ['handleTweet', {
										shared_type: 'quiz',
										shared_id: <?= $this->quiz->id ?>
									}]);
									$SQ('.sb_externalShare_twitter').bind('click', function(e) {
										e.preventDefault();
										e.stopPropagation();
										return false;
									});
								}
							}
							twttr.events.bind('tweet', function(event) { handleTweetEvent(event) });
						});
					</script>

					<div class="sb_externalShare sb_externalShare_twitter" rel="sb_mini-snakkle-reward_twitter">
						<a class="twitter-share-button"
							data-related="<?= $this->twitter_share_related_users ?>"
							data-hashtags="<?= $this->twitter_share_hashtags ?>"
							data-via="<?= $this->twitter_share_via_user ?>"
							data-url="<?= $this->share_link ?>"
							data-text="<?= $this->twitter_share_text ?>"
							data-count="none"
							href="https://twitter.com/intent/tweet">
						</a>
					</div>

					<span class="sb_mini-snakkle-reward sb_mini-snakkle-reward_twitter" id="sb_mini-snakkle-reward_twitter">+8</span>
					<!-- / twitter -->

					<p class="sb_quizShare"><strong>Share this quiz to earn extra points</strong></p>
				</div><!-- .sb_externalShares -->

			</div>
			<script type="text/javascript">
				var results = new Array();
				<? foreach ($this->quiz_results as $choiceId => $result) { ?>
					results[<?= $choiceId ?>] = <?= $result ?>;
				<? } ?>
				var numberOfResponses = <?= $this->total_quiz_responses ?>;
				var quizIndex = <?= $this->quiz_index ?>;

				var elemRadios = $SQ('.sb_quiz_option_input');
				elemRadios.each(function(){
					$SQ(this).bind({
						click: function(event){
							var selectedChoiceId = parseInt($SQ(this).attr('value'));

							$SQ(this).attr('checked', 'checked');

							$SQ.ajax({
								dataType:"jsonp",
								url : "//<?= BASE_DOMAIN ?>/api/survey/user-quiz-submit?renderer=jsonp&survey_id=<?= $this->quiz->id ?>&user_id=<?= $this->user_id ?>&user_key=<?= $this->user_key ?>&starbar_id=<?= $this->starbar_id ?>&survey_question_choice_id="+selectedChoiceId,
								beforeSend : function(x) {
									if (x && x.overrideMimeType) {
										x.overrideMimeType("application/j-son;charset=UTF-8");
									}
								},
								success : function (response, status, jqXHR) {
									if (response.data.correct_survey_question_choice_id && response.data.correct_survey_question_choice_id == selectedChoiceId) {
										$SQ('#sayso-starbar').trigger('frameCommunication', ['updateGame', {
											newGame: response.game
										}]);
										$SQ('#right_answer_message').show();
									} else {
										$SQ('#result_'+selectedChoiceId+' .sb_theme_textHighlight').removeClass('sb_theme_textHighlight').addClass('sb_textError');
										$SQ('#result_'+selectedChoiceId+' .sb_progress_bar').addClass('sb_progress_bar_error');
										$SQ('#wrong_answer_message').show();
									}

									$SQ('#result_'+response.data.correct_survey_question_choice_id+' .sb_theme_textHighlight').removeClass('sb_theme_textHighlight').addClass('sb_theme_textHighlight_alt');
									$SQ('#result_'+response.data.correct_survey_question_choice_id+' .sb_progress_bar').addClass('sb_progress_bar_alt');

									$SQ('#sb_next_quiz_link').attr('href', '//<?= BASE_DOMAIN ?>/starbar/snakkle/quiz?quiz_index='+quizIndex);

									results[selectedChoiceId]++;
									numberOfResponses++;

									for (var choiceId in results) {
										var percentageOfResponses = Math.round((results[choiceId] / numberOfResponses) * 100);
										$SQ('#percentage_of_responses_'+choiceId).html(percentageOfResponses+'%');
										$SQ('#result_'+choiceId+' .sb_currency_percent').css('width', percentageOfResponses+'%');
									}

									$SQ('.sb_quiz_question').hide();
									$SQ('#sb_quiz_results_container').fadeTo(500, 1);

									setTimeout(function() {
										$SQ('.sb_externalShares').fadeTo(500, 1);
									}, 1500);
								}
							});
						}
					});
				});
			</script>
		</div><!-- .sb_quiz_main -->
		<p class="sb_quiz_next"><a id="sb_next_quiz_link" href="//<?= BASE_DOMAIN ?>/starbar/snakkle/quiz?quiz_index=<?= ($this->quiz_index + 1) ?>" class="sb_nav_element" rel="sb_popBox_quizzes">Next Quiz</a></p>
	<? } else { ?>
		<p>Nice job, looks like you've taken all the quizzes! Check back tomorrow for new quizzes!</p>
	<? } ?>
</div><!-- .sb_quiz -->