<div class="sb_header">
	<img src="//<?= BASE_DOMAIN ?>/images/snakkle/logo_snakkle_lg.png" alt="Snakkle logo" />
</div><!-- .sb_header -->
<div class="sb_quiz">
	<div class="sb_quiz_main">
		<h2 class="sb_title">Who is this?</h2>
		<p><img src="//<?= BASE_DOMAIN ?>/images/snakkle/img_quiz-temp.jpg" alt="Quiz Photo" /></p>	
		
		<div class="sb_quiz_question">
			<p>
				<strong class="sb_theme_textHighlight">HINT</strong> - His name is the same as the name of a city. He's good with swords and bows. He just had his first child.
			</p>
			<div class="sb_quiz_options">
				<div class="sb_quiz_row">
					<div class="sb_quiz_option">
						<input type="radio" name="quiz" value="Brad Pitt" id="answer1"> <label for="answer1">Brad Pitt</label>
					</div><!-- .sb_quiz_option -->
					<div class="sb_quiz_option">
						<input type="radio" name="quiz" value="Leonardo DiCaprio" id="answer2"> <label for="answer2">Leonardo DiCaprio</label>
					</div><!-- .sb_quiz_option -->
				</div><!-- .sb_quiz_row -->
				<div class="sb_quiz_row">
					<div class="sb_quiz_option">
						<input type="radio" name="quiz" value="Ryan Gosling" id="answer3"> <label for="answer3">Ryan Gosling</label>
					</div><!-- .sb_quiz_option -->
					<div class="sb_quiz_option">
						<input type="radio" name="quiz" value="George Clooney" id="answer4"> <label for="answer4">George Clooney</label>
					</div><!-- .sb_quiz_option -->
				</div>
			</div><!-- .sb_quiz_options -->		
		</div><!-- .sb_quiz_main -->	
	</div><!-- .sb_quiz_question -->
	
	<!-- WHAT A CORRECT ANSWER LOOKS LIKE -->	
	<div style="display: none"><!-- useless wrapper div for development -->
	<div class="sb_quiz_results">
		<div class="sb_quiz_options">
			<div class="sb_quiz_row">
				<div class="sb_quiz_option">
					<p>Brad Pitt - <span class="sb_theme_textHighlight">15%</span></p>
					
					<div class="sb_progress_bar"></span><span class="sb_currency_percent" style="width: 15%"></span></div>
				</div><!-- .sb_quiz_option -->	
				
				<div class="sb_quiz_option">
					<p>Leonardo DiCaprio - <span class="sb_theme_textHighlight">5%</span></p>
					
					<div class="sb_progress_bar"></span><span class="sb_currency_percent" style="width: 5%"></span></div>
				</div><!-- .sb_quiz_option -->	
							
			</div><!-- .sb_quiz_row -->
			
			<div class="sb_quiz_row">
				<div class="sb_quiz_option sb_quiz_option_correct">
					<p>Ryan Gosling - <span class="sb_theme_textHighlight_alt">75%</span></p>
					
					<div class="sb_progress_bar sb_progress_bar_alt"></span><span class="sb_currency_percent" style="width: 75%"></span></div>
				</div><!-- .sb_quiz_option -->	
				
				<div class="sb_quiz_option">
					<p>George Clooney - <span class="sb_theme_textHighlight">5%</span></p>
					
					<div class="sb_progress_bar"></span><span class="sb_currency_percent" style="width: 5%"></span></div>
				</div><!-- .sb_quiz_option -->	
							
			</div><!-- .sb_quiz_row -->
						
		</div><!-- .sb_quiz_options -->				
	</div><!-- .sb_quiz_results -->
	
	<p><span class="sb_theme_textHighlight_alt">Excellent!</span> You earned <a href="">25 Snakkles</a> & <a href="">250 XP’s</a></p>
	
	<p class="sb_quizShare"><strong>Share this quiz to earn extra points</strong></p>
	<div class="sb_externalShares">


			<!-- FACEBOOK -->
			<a class="sb_externalShare sb_externalShare_facebook" rel="sb_mini-snakkle-reward_facebook" 	href="#"
				onclick="return $SQ.openWindow('//www.facebook.com/dialog/feed?app_id=<?= urlencode($this->facebook_app_id) ?>&link=<?= urlencode($this->share_link) ?>&caption=<?= urlencode($this->facebook_share_caption) ?>&picture=<?= urlencode($this->facebook_share_image_url) ?>&redirect_uri=<?= urlencode($this->facebook_share_callback_url) ?>&name=<?= urlencode($this->facebook_title) ?>&description=<?= urlencode($this->facebook_description) ?>', 'sb_window_open', 'location=1,status=1,scrollbars=0,width=981,height=450');">
				Facebook Share
			</a>
			<span class="sb_mini-snakkle-reward sb_mini-snakkle-reward_facebook" id="sb_mini-snakkle-reward_facebook">+50</span>
			<!-- / facebook -->

			<! -- TWITTER -->
			<script type="text/javascript">
				$SQ.getScript("//platform.twitter.com/widgets.js", function(){
					function handleTweetEvent(event){
						if (event) {
							$SQ('#sayso-starbar').trigger('frameCommunication', ['handleTweet', {
								shared_type: 'starbar',
								shared_id: window.sayso.starbar.id
							}]);
						}
					}
					twttr.events.bind('tweet', function(event) { handleTweetEvent(event) });
				});
			</script>

			<div class="sb_externalShare sb_externalShare_twitter" rel="sb_mini-snakkle-reward_twitter">
				<a class="twitter-share-button"
					data-related="<?= $this->twitter_share_related_users ?>"
					data-hashtags="<?= $this->twitter_share_hashtags ?>"
					data-via="<?= $this->twitter_share_via_user ?>"
					data-url="<?= $this->share_link ?>"
					data-text="<?= $this->twitter_share_text ?>"
					data-count="none"
					href="https://twitter.com/intent/tweet">
				</a>
			</div>

			<span class="sb_mini-snakkle-reward sb_mini-snakkle-reward_twitter" id="sb_mini-snakkle-reward_twitter">+50</span>
			<!-- / twitter -->
	</div><!-- .sb_externalShares -->	
	
	</div><!-- end useless wrapper div -->
	
	<!-- END CORRECT ANSWER -->
	
	
	<!-- WHAT AN INCORRECT ANSWER LOOKS LIKE -->
	<div style="display: none"><!-- useless wrapper div -->
	<div class="sb_quiz_results">
		<div class="sb_quiz_options">
			<div class="sb_quiz_row">
				<div class="sb_quiz_option">
					<p>Brad Pitt - <span class="sb_theme_textHighlight">15%</span></p>
					
					<div class="sb_progress_bar"></span><span class="sb_currency_percent" style="width: 15%"></span></div>
				</div><!-- .sb_quiz_option -->	
				
				<div class="sb_quiz_option">
					<p>Leonardo DiCaprio - <span class="sb_textError">5%</span></p>
					
					<div class="sb_progress_bar sb_progress_bar_error"></span><span class="sb_currency_percent" style="width: 5%"></span></div>
				</div><!-- .sb_quiz_option -->	
							
			</div><!-- .sb_quiz_row -->
			
			<div class="sb_quiz_row">
				<div class="sb_quiz_option">
					<p>Ryan Gosling - <span class="sb_theme_textHighlight">75%</span></p>
					
					<div class="sb_progress_bar"></span><span class="sb_currency_percent" style="width: 75%"></span></div>
				</div><!-- .sb_quiz_option -->	
				
				<div class="sb_quiz_option">
					<p>George Clooney - <span class="sb_theme_textHighlight">5%</span></p>
					
					<div class="sb_progress_bar"></span><span class="sb_currency_percent" style="width: 5%"></span></div>
				</div><!-- .sb_quiz_option -->	
							
			</div><!-- .sb_quiz_row -->
						
		</div><!-- .sb_quiz_options -->				
	</div><!-- .sb_quiz_results -->
	
	<p><span class="sb_textError">Whoops try again.</span></p>
	
	<p class="sb_quizShare"><strong>Share this quiz to earn extra points</strong></p>
	<div class="sb_externalShares">


			<!-- FACEBOOK -->
			<a class="sb_externalShare sb_externalShare_facebook" rel="sb_mini-snakkle-reward_facebook" 	href="#"
				onclick="return $SQ.openWindow('//www.facebook.com/dialog/feed?app_id=<?= urlencode($this->facebook_app_id) ?>&link=<?= urlencode($this->share_link) ?>&caption=<?= urlencode($this->facebook_share_caption) ?>&picture=<?= urlencode($this->facebook_share_image_url) ?>&redirect_uri=<?= urlencode($this->facebook_share_callback_url) ?>&name=<?= urlencode($this->facebook_title) ?>&description=<?= urlencode($this->facebook_description) ?>', 'sb_window_open', 'location=1,status=1,scrollbars=0,width=981,height=450');">
				Facebook Share
			</a>
			<span class="sb_mini-snakkle-reward sb_mini-snakkle-reward_facebook" id="sb_mini-snakkle-reward_facebook">+50</span>
			<!-- / facebook -->

			<! -- TWITTER -->
			<script type="text/javascript">
				$SQ.getScript("//platform.twitter.com/widgets.js", function(){
					function handleTweetEvent(event){
						if (event) {
							$SQ('#sayso-starbar').trigger('frameCommunication', ['handleTweet', {
								shared_type: 'starbar',
								shared_id: window.sayso.starbar.id
							}]);
						}
					}
					twttr.events.bind('tweet', function(event) { handleTweetEvent(event) });
				});
			</script>

			<div class="sb_externalShare sb_externalShare_twitter" rel="sb_mini-snakkle-reward_twitter">
				<a class="twitter-share-button"
					data-related="<?= $this->twitter_share_related_users ?>"
					data-hashtags="<?= $this->twitter_share_hashtags ?>"
					data-via="<?= $this->twitter_share_via_user ?>"
					data-url="<?= $this->share_link ?>"
					data-text="<?= $this->twitter_share_text ?>"
					data-count="none"
					href="https://twitter.com/intent/tweet">
				</a>
			</div>

			<span class="sb_mini-snakkle-reward sb_mini-snakkle-reward_twitter" id="sb_mini-snakkle-reward_twitter">+50</span>
			<!-- / twitter -->
	</div><!-- .sb_externalShares -->	
	
	</div><!-- end useless wrapper div -->
	<!-- END INCORRECT CORRECT ANSWER -->
	
		
	<p class="sb_quiz_next"><a href="#">Next Guess</a></p>
</div><!-- .sb_quiz -->