<div class="sb_header">
	<img src="//<?= BASE_DOMAIN ?>/images/snakkle/logo_snakkle_lg.png" alt="Snakkle logo" />
</div><!-- .sb_header -->
<div class="sb_tabs">
	<ul>
		<? if ($this->count_new_surveys) { ?>
			<li><a href="#surveys_tabs_1"><?= $this->count_new_surveys ?> New!</a></li>
		<? } else { ?>
			<li><a href="#surveys_tabs_1">New</a></li>
		<? } ?>
		<? if ($this->count_completed_surveys || $this->count_disqualified_surveys) { ?>
			<li><a href="#surveys_tabs_2">Completed</a></li>
		<? } ?>
		<? if ($this->count_archived_surveys) { ?>
			<li><a href="#surveys_tabs_3">Archive</a></li>
		<? } ?>
	</ul>
	<div id="surveys_tabs_1" class="sb_tabPane">
		<h2 class="sb_title">Surveys</h2>
		<p class="sb_tabHeader">
			Here's where your SaySo really counts&ndash;Surveys&ndash;where your input can truly alter the course of commerce. And your <strong class="sb_theme_textHighlight sb_tooltip" title="Bucks - are almost as good as cash and can be redeemed for goods in the Rewards Center.">Bucks</strong> &amp; <strong class="sb_theme_textHighlight sb_tooltip" title="Stars - determine your  access to increasingly important levels of influence.">Stars</strong> are commensurately rewarded. Share them for bonuses, and keep watch for those Premium Surveys!
		</p>
		<? if (!$this->primary_survey_taken) { ?>
			<p class="sb_tabHeader">
				More surveys and more ways to earn Bucks will be available to you when you complete the <a href="//<?= BASE_DOMAIN ?>/starbar/snakkle/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_hg">Influencer Survey</a>.
			</p>
		<? } ?>
		<div class="sb_scrollPane">
			<? $this->displaySurveys('new') ?>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tabs_1 -->

	<? if ($this->count_completed_surveys || $this->count_disqualified_surveys) { ?>
		<div id="surveys_tabs_2" class="sb_tabPane">
			<h2 class="sb_title">Surveys</h2>
			<p class="sb_tabHeader">All of your completed surveys are listed below.</p>
			<div class="sb_scrollPane">
				<ul class="sb_outlineList">
					<? $this->displaySurveys('completed') ?>
					<? $this->displaySurveys('disqualified') ?>
				</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tabs_2 -->
	<? } ?>

	<? if ($this->count_archived_surveys) { ?>
		<div id="surveys_tabs_3" class="sb_tabPane">
			<h2 class="sb_title">Surveys</h2>
			<p class="sb_tabHeader">No shelf-life on these babies totally take-able Surveys. SaySo immortality awaits. We await your SaySo.</p>
			<div class="sb_scrollPane">
				<? $this->displaySurveys('archived') ?>
				<br />
				<? if ($this->count_new_surveys) { ?>
					<p align="right"><a href="#" class="sb_nav_tabs sb_theme_button" rel="1"><span class="sb_theme_buttonArrow">Take a New Survey</span></a></p>
				<? } ?>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tabs_3 -->
	<? } ?>

</div><!-- .tabs -->
