  <div class="sb_header">
  	<a href="http://www.saysollc.com" target="_blank"><img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_sayso_lg.png" alt="Say.So" /></a>
  </div><!-- .sb_header -->  
  <div class="sb_popBoxInner">
    <div class="sb_popContent">
    	<div class="sb_tabs">
        <ul>
          <li><a href="#about_tabs_1">About</a></li>
          <li><a href="#about_tabs_2">Help</a></li>
          <li><a href="#about_tabs_3">FAQs</a></li>
          <li><a href="#about_tabs_4">Video</a></li>
        </ul>
        <div id="about_tabs_1" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2>About SaySo</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vehicula justo dui, id porta turpis. Morbi fringilla, nulla at lacinia laoreet, libero massa ornare metus, vitae vulputate metus neque blandit est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam purus quam, dapibus non lobortis vitae, aliquam in nulla.</p>
            <p>Proin elit diam, imperdiet vel iaculis nec, laoreet nec libero. Curabitur tincidunt sem et nisl hendrerit vel fermentum elit vestibulum. Suspendisse arcu purus, sollicitudin non lacinia sit amet, auctor quis ligula. Duis consequat euismod mauris, ac aliquet lorem elementum vel. Aenean id tincidunt arcu. Vestibulum interdum sagittis posuere. Ut tortor risus, aliquam sed lobortis sed, pulvinar in quam.</p>
            <p>Nulla mattis scelerisque egestas. Proin sed mi diam, et gravida velit. Phasellus rutrum lobortis neque, non fringilla tortor viverra eu.</p>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_1 -->
        <div id="about_tabs_2" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2>Help</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vehicula justo dui, id porta turpis. Morbi fringilla, nulla at lacinia laoreet, libero massa ornare metus, vitae vulputate metus neque blandit est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam purus quam, dapibus non lobortis vitae, aliquam in nulla.</p>
            <p>Proin elit diam, imperdiet vel iaculis nec, laoreet nec libero. Curabitur tincidunt sem et nisl hendrerit vel fermentum elit vestibulum. Suspendisse arcu purus, sollicitudin non lacinia sit amet, auctor quis ligula. Duis consequat euismod mauris, ac aliquet lorem elementum vel. Aenean id tincidunt arcu. Vestibulum interdum sagittis posuere. Ut tortor risus, aliquam sed lobortis sed, pulvinar in quam.</p>
            <p>Nulla mattis scelerisque egestas. Proin sed mi diam, et gravida velit. Phasellus rutrum lobortis neque, non fringilla tortor viverra eu.</p>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_2 -->
        <div id="about_tabs_3" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2>FAQ</h2>
            <p><strong>How do I sign up?</strong><br />
Signing up is easy. You can use your existing Hello Music account, your facebook account, or twitter account. Just sign into your Hello Music account and follow the directions to download the app.</p>
						<p><strong>Can I use my facebook / twitter account to sign up?</strong><br />
Yes, you can use your facebook account / twitter account that you use to sign into Hello Music.</p>
						<p><strong>How do I play?</strong><br />
After signing up, you will opt in to play and our Hello Music Beat Bar will be installed on your browser. From here, you will be taken through a short tutorial and you can jump right in to earning by answering polls, taking surveys and sharing deals. The more points you have the better chance you have to win prizes.</p>
						<p><strong>What are the prizes?</strong><br />
We will give away prizes weekly and then a grand prize at the end of the month. In order to be eligible for the giveaways you need to redeem your Notes for a entry token. You can buy as many entry tokens as you want to increase your chances of winning.</p>
						<p><strong>Do you really give away the prizes?</strong><br />
YES! Every prize that is won will be shipped to within 4-6 Weeks. You guys will get the prizes for playing, not the CEO's nephew or cousin. Every week we will send out a notification to everyone, letting you know who the lucky player is, and at the end of the month, a grand prize will be given away.</p>
						<p><strong>How do I get my prize?</strong><br />
When you win a prize, we will contact you to get your mailing address and information needed to send the prize to you.</p>
						<p><strong>Do I have to pay for anything?</strong><br />
No, this is completely free to you. The only thing we want you to do is participate.</p>
						<p><strong>Do I have to play every day?</strong><br />
No you do not have to play every day, but the more you play, the better chance you have at winning a weekly prize or even the monthly prize. The more you participate, the more points you will earn, and the more points you earn, the better chance you have the winning prizes.</p>
						<p><strong>Can I stop playing at any time?</strong><br />
Yes, play as much as you want, but remember, the more you play the better your chances of winning cool prizes.</p>
						<p><strong>What are Chops and Notes</strong><br />
“Chops” are the currency of influence. You earn them for sharing your expertise, experience and opinion, and your Chops determine your access to increasingly important levels of access and influence.</p>
						<p>
“Notes” are almost as good as cash. Virtually everything you do in the Beat Bar earns you Notes, which can be redeemed for all manner of Hello Music goodies (see the Rewards Center).</p>
						<p><strong>How long do the surveys / games take to complete?</strong><br />
Generally between 5 and 15 minutes. The longer surveys earn you more points.</p>
						<p><strong>What if I stop a survey in the middle of taking it? Do I still get credit? Do I have to restart it?</strong><br />
Most Surveys only take about 3-5 minutes while some bonus surveys take 10-15 minutes once you start a survey you must complete it in order to earn your points.</p>
						<p><strong>What are you doing with the information you are collecting?</strong><br />
We are using it to help make Hello Music better for everyone.</p>
						<p><strong>Can I invite other people to play?</strong><br />
Yes, you can invite friends through Facebook or Twitter or with our Send To A Friend form found in the settings section of the app. The more of your friends that you can get to play too, the more points you will earn.</p>
						<p><strong>Can I trade my prize for another prize?</strong><br />
No, the prize you win is the prize you get.</p>
						<p><strong>How do you select the Weekly Winner? Monthly winner?</strong><br />
You must redeem your points for entry tokens for the weekly and monthly giveaways. Winners will be chosen at random from all entrants.</p>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_3 -->
        <div id="about_tabs_4" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2>Video</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vehicula justo dui, id porta turpis. Morbi fringilla, nulla at lacinia laoreet, libero massa ornare metus, vitae vulputate metus neque blandit est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam purus quam, dapibus non lobortis vitae, aliquam in nulla.</p>
            <p>Proin elit diam, imperdiet vel iaculis nec, laoreet nec libero. Curabitur tincidunt sem et nisl hendrerit vel fermentum elit vestibulum. Suspendisse arcu purus, sollicitudin non lacinia sit amet, auctor quis ligula. Duis consequat euismod mauris, ac aliquet lorem elementum vel. Aenean id tincidunt arcu. Vestibulum interdum sagittis posuere. Ut tortor risus, aliquam sed lobortis sed, pulvinar in quam.</p>
            <p>Nulla mattis scelerisque egestas. Proin sed mi diam, et gravida velit. Phasellus rutrum lobortis neque, non fringilla tortor viverra eu.</p>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_4 -->
      </div><!-- .sb_tabs -->
    </div><!-- .sb_popContent -->
  </div><!-- .sb_popBoxInner -->
