  <div class="sb_header">
  	<a href="http://www.saysollc.com" target="_blank"><img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_sayso_lg.png" alt="Say.So" /></a>
  </div><!-- .sb_header -->  
  <div class="sb_popBoxInner">
    <div class="sb_popContent">
    	<div class="sb_tabs">
        <ul>
          <li><a href="#about_tabs_1">About</a></li>
          <li><a href="#about_tabs_2">Help</a></li>
          <li><a href="#about_tabs_3">FAQs</a></li>
          <li><a href="#about_tabs_4">Video</a></li>
        </ul>
        <div id="about_tabs_1" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2>About SaySo</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vehicula justo dui, id porta turpis. Morbi fringilla, nulla at lacinia laoreet, libero massa ornare metus, vitae vulputate metus neque blandit est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam purus quam, dapibus non lobortis vitae, aliquam in nulla.</p>
            <p>Proin elit diam, imperdiet vel iaculis nec, laoreet nec libero. Curabitur tincidunt sem et nisl hendrerit vel fermentum elit vestibulum. Suspendisse arcu purus, sollicitudin non lacinia sit amet, auctor quis ligula. Duis consequat euismod mauris, ac aliquet lorem elementum vel. Aenean id tincidunt arcu. Vestibulum interdum sagittis posuere. Ut tortor risus, aliquam sed lobortis sed, pulvinar in quam.</p>
            <p>Nulla mattis scelerisque egestas. Proin sed mi diam, et gravida velit. Phasellus rutrum lobortis neque, non fringilla tortor viverra eu.</p>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_1 -->
        <div id="about_tabs_2" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2>Help</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vehicula justo dui, id porta turpis. Morbi fringilla, nulla at lacinia laoreet, libero massa ornare metus, vitae vulputate metus neque blandit est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam purus quam, dapibus non lobortis vitae, aliquam in nulla.</p>
            <p>Proin elit diam, imperdiet vel iaculis nec, laoreet nec libero. Curabitur tincidunt sem et nisl hendrerit vel fermentum elit vestibulum. Suspendisse arcu purus, sollicitudin non lacinia sit amet, auctor quis ligula. Duis consequat euismod mauris, ac aliquet lorem elementum vel. Aenean id tincidunt arcu. Vestibulum interdum sagittis posuere. Ut tortor risus, aliquam sed lobortis sed, pulvinar in quam.</p>
            <p>Nulla mattis scelerisque egestas. Proin sed mi diam, et gravida velit. Phasellus rutrum lobortis neque, non fringilla tortor viverra eu.</p>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_2 -->
        <div id="about_tabs_3" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2>FAQ</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vehicula justo dui, id porta turpis. Morbi fringilla, nulla at lacinia laoreet, libero massa ornare metus, vitae vulputate metus neque blandit est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam purus quam, dapibus non lobortis vitae, aliquam in nulla.</p>
            <p>Proin elit diam, imperdiet vel iaculis nec, laoreet nec libero. Curabitur tincidunt sem et nisl hendrerit vel fermentum elit vestibulum. Suspendisse arcu purus, sollicitudin non lacinia sit amet, auctor quis ligula. Duis consequat euismod mauris, ac aliquet lorem elementum vel. Aenean id tincidunt arcu. Vestibulum interdum sagittis posuere. Ut tortor risus, aliquam sed lobortis sed, pulvinar in quam.</p>
            <p>Nulla mattis scelerisque egestas. Proin sed mi diam, et gravida velit. Phasellus rutrum lobortis neque, non fringilla tortor viverra eu.</p>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_3 -->
        <div id="about_tabs_4" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2>Video</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vehicula justo dui, id porta turpis. Morbi fringilla, nulla at lacinia laoreet, libero massa ornare metus, vitae vulputate metus neque blandit est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam purus quam, dapibus non lobortis vitae, aliquam in nulla.</p>
            <p>Proin elit diam, imperdiet vel iaculis nec, laoreet nec libero. Curabitur tincidunt sem et nisl hendrerit vel fermentum elit vestibulum. Suspendisse arcu purus, sollicitudin non lacinia sit amet, auctor quis ligula. Duis consequat euismod mauris, ac aliquet lorem elementum vel. Aenean id tincidunt arcu. Vestibulum interdum sagittis posuere. Ut tortor risus, aliquam sed lobortis sed, pulvinar in quam.</p>
            <p>Nulla mattis scelerisque egestas. Proin sed mi diam, et gravida velit. Phasellus rutrum lobortis neque, non fringilla tortor viverra eu.</p>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_4 -->
      </div><!-- .sb_tabs -->
    </div><!-- .sb_popContent -->
  </div><!-- .sb_popBoxInner -->
