  <div class="sb_popBoxInner sb_triangle-solid">
    <div class="sb_popContent">
      <div class="sb_header">
        <h2 class="sb_title"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" /> Polls</h2>
      </div><!-- .sb_header -->
      <div class="sb_tabs">
        <ul>
          <li><a href="#polls_tabs_1">3 New!</a></li>
           <li><a href="#polls_tabs_2">Completed</a></li>
          <li><a href="#polls_tabs_3">Archive</a></li>
        </ul>
        <div id="polls_tabs_1" class="sb_tabPane">

            <div class="sb_scrollPane">

            <!-- BEGIN POLL BOX LANDING -->
            <p>Earn <strong class="sb_theme_textHighlight">10 Notes</strong> for each poll you complete. Check back often to keep earning and for your chance to win the Weekly Giveaway!</p>
            <div class="sb_accordion">
            	<? foreach ($this->new_surveys as $survey) { ?>
	                <h3><a href="http://<?= BASE_DOMAIN ?>/starbar/content/embed-poll?survey_id=<?= $survey->id ?>"><?= $survey->title ?></a></h3>
	                <div>
	                    <iframe src="" width="470" height="120" frameborder="0" marginheight="0" marginwidth="0" scrollbar="no"></iframe>
	                </div><!-- / END ACCORDION CONTENT -->
	            <? } ?>
            </div><!-- .accordion -->
            <!-- END POLL BOX LANDING -->

          </div><!-- .sb_scrollPane -->

        </div><!-- #tabs_1 -->

        <div id="polls_tabs_2" class="sb_tabPane">
            <div class="sb_scrollPane">
              <ul class="sb_outlineList">
                <li><h3><span class="sb_theme_iconComplete"></span>Bob Dylan pre or post Newport? <span class="sb_pointsEarned">+25</span></h3></li>
              <li><h3><span class="sb_theme_iconComplete"></span>Everything Gibson <span class="sb_pointsEarned">+25</span></h3></li>
              <li><h3><span class="sb_theme_iconComplete"></span>Guitar Center or the Corner Music Shop <span class="sb_pointsEarned">+25</span></h3></li>
            </ul>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tabs_2 -->

        <div id="polls_tabs_3" class="sb_tabPane">
            <div class="sb_scrollPane">
            <!--
                Programming note:
              to show how each section should flow, I have wrapped the 3 poll views into divs called "sb_pollView_x"
              *** this should not be seen as permanent code. ***
              it's only purpose is to show the 3 states when taking a poll.
            -->

               <!-- ********************************************* -->
            <div id="sb_pollView_1"><!-- REMOVE THIS CONTAINER FOR PRODUCTION / FOR DEV USE ONLY -->
            <!-- ********************************************* -->

            <!-- BEGIN POLL BOX LANDING -->
            <p>Earn <strong class="sb_theme_textHighlight">10 Notes</strong> for each poll you complete. Check back often to keep earning and for your chance to win the Weekly Giveaway!</p>
            <div class="sb_accordion">
                <h3><a href="#"><span class="sb_questionCount"><span class="sb_questionCurrent">1</span> of 10</span>Bob Dylan pre or post Newport?</a></h3>
                <div>
                    <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_poll.jpg" alt="Poll Image" class="sb_pollImage" />
                  <div class="sb_pollContent">
                  <p><strong>Do you play electric or acoustic instruments?</strong></p>
                  <form action="" name="">
                  <div class="sb_column50">
                         <p><input type="radio" /> <label>Electric</label></p>
                    <p><input type="radio" /> <label>Acoustic</label></p>
                  </div><!-- .sb_column50 -->
                  <div class="sb_column50">
                      <p><input type="radio" / ><label>Both</label></p>
                  </div><!-- .sb_column50 -->
                  </form>
                  </div><!-- .sb_questionAnswers -->
                </div><!-- / END ACCORDION CONTENT -->
                <h3><a href="#"><span class="sb_questionCount"><span class="sb_questionCurrent">1</span> of 10</span>Everything Gibson</a></h3>
                <div>
                    <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_poll.jpg" alt="Poll Image" class="sb_pollImage" />
                  <div class="sb_pollContent">
                  <p><strong>Do you play electric or acoustic instruments?</strong></p>
                  <form action="" name="">
                  <div class="sb_column50">
                         <p><input type="radio" /> <label>Electric</label></p>
                    <p><input type="radio" /> <label>Acoustic</label></p>
                  </div><!-- .sb_column50 -->
                  <div class="sb_column50">
                      <p><input type="radio" / ><label>Both</label></p>
                  </div><!-- .sb_column50 -->
                  </form>
                  </div><!-- .sb_questionAnswers -->
                </div><!-- / END ACCORDION CONTENT -->
                <h3><a href="#"><span class="sb_questionCount"><span class="sb_questionCurrent">1</span> of 10</span>Guitar Center or the Corner Music Shop</a></h3>
                <div>
                    <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_poll.jpg" alt="Poll Image" class="sb_pollImage" />
                  <div class="sb_pollContent">
                  <p><strong>Do you play electric or acoustic instruments?</strong></p>
                  <form action="" name="">
                  <div class="sb_column50">
                         <p><input type="radio" /> <label>Electric</label></p>
                    <p><input type="radio" /> <label>Acoustic</label></p>
                  </div><!-- .sb_column50 -->
                  <div class="sb_column50">
                      <p><input type="radio" / ><label>Both</label></p>
                  </div><!-- .sb_column50 -->
                  </form>
                  </div><!-- .sb_questionAnswers -->
                </div><!-- / END ACCORDION CONTENT -->
            </div><!-- .accordion -->
            <!-- END POLL BOX LANDING -->

            <!-- ********************************************* -->
            </div><!-- REMOVE THIS CONTAINER FOR PRODUCTION / FOR DEV USE ONLY -->
            <!-- ********************************************* -->

          </div><!-- .sb_scrollPane -->
        </div><!-- #tabs_3 -->

      </div><!-- .tabs -->
    </div><!-- .sb_popContent -->
  </div><!-- .sb_popBoxInner -->
