  <div class="sb_popBoxInner sb_triangle-solid">
    <div class="sb_popContent">
      <div class="sb_header">
        <h2 class="sb_title"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" /> Surveys</h2>
      </div><!-- .sb_header -->
      <div class="sb_tabs">
        <ul>
          <li><a href="#surveys_tabs_1">3 New!</a></li>
          <li><a href="#surveys_tabs_2">Completed</a></li>
          <li><a href="#surveys_tabs_3">Archive</a></li>
        </ul>
        <div id="surveys_tabs_1" class="sb_tabPane">
            <div class="sb_scrollPane">
              <p>Earn <strong class="sb_theme_textHiglight">25 Notes</strong> for each survey you take. Check back often to keep earning</p>
              <ul class="sb_solidList">
                <li class="sb_listOdd"><h3>What's going on in music today?</h3>
              <br />
              <a href="#" class="sb_surveyLaunch sb_theme_button sb_nav_element" rel="sb_popBox_surveys_lg"><span class="sb_imgNote"></span><span class="sb_theme_buttonArrow">25 Notes Await</span></a></li>
              <li class="sb_listEven"><h3>Pop Music - where are we now?</h3>
              <br />
              <a href="#" class="sb_surveyLaunch sb_theme_button sb_nav_element" rel="sb_popBox_surveys_lg"><span class="sb_imgNote"></span><span class="sb_theme_buttonArrow">25 Notes Await</span></a></li>
              <li class="sb_listOdd"><h3>What's going on in music today?</h3>
              <br />
              <a href="#" class="sb_surveyLaunch sb_theme_button sb_nav_element" rel="sb_popBox_surveys_lg"><span class="sb_imgNote"></span><span class="sb_theme_buttonArrow">25 Notes Await</span></a></li>
              <li class="sb_listEven"><h3>Pop Music - where are we now?</h3>
              <br />
              <a href="#" class="sb_surveyLaunch sb_theme_button sb_nav_element" rel="sb_popBox_surveys_lg"><span class="sb_imgNote"></span><span class="sb_theme_buttonArrow">25 Notes Await</span></a></li>
            </ul>
          </div><!-- .sb_scrollPane -->

        </div><!-- #tabs_1 -->

        <div id="surveys_tabs_2" class="sb_tabPane">
            <div class="sb_scrollPane">
              <ul class="sb_outlineList">
                <li><h3><span class="sb_theme_iconComplete"></span>Bob Dylan pre or post Newport? <span class="sb_pointsEarned">+25</span></h3></li>
              <li><h3><span class="sb_theme_iconComplete"></span>Everything Gibson <span class="sb_pointsEarned">+25</span></h3></li>
              <li><h3><span class="sb_theme_iconComplete"></span>Guitar Center or the Corner Music Shop <span class="sb_pointsEarned">+25</span></h3></li>
            </ul>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tabs_2 -->

        <div id="surveys_tabs_3" class="sb_tabPane">
            <div class="sb_scrollPane">
                 <p>Earn <strong class="sb_theme_textHiglight">25 Notes</strong> for each survey you take. Check back often to keep earning</p>
            <ul class="sb_solidList">
                <li class="sb_listOdd"><h3>What's going on in music today?</h3>
              <br />
              <a href="#" class="sb_surveyLaunch sb_theme_button sb_nav_element" rel="sb_popBox_surveys_lg"><span class="sb_imgNote"></span><span class="sb_theme_buttonArrow">25 Notes Await</span></a></li>
              <li class="sb_listEven"><h3>Pop Music - where are we now?</h3>
              <br />
              <a href="#" class="sb_surveyLaunch sb_theme_button sb_nav_element" rel="sb_popBox_surveys_lg"><span class="sb_imgNote"></span><span class="sb_theme_buttonArrow">25 Notes Await</span></a></li>
              <li class="sb_listOdd"><h3>What's going on in music today?</h3>
              <br />
              <a href="#" class="sb_surveyLaunch sb_theme_button sb_nav_element" rel="sb_popBox_surveys_lg"><span class="sb_imgNote"></span><span class="sb_theme_buttonArrow">25 Notes Await</span></a></li>
              <li class="sb_listEven"><h3>Pop Music - where are we now?</h3>
              <br />
              <a href="#" class="sb_surveyLaunch sb_theme_button sb_nav_element" rel="sb_popBox_surveys_lg"><span class="sb_imgNote"></span><span class="sb_theme_buttonArrow">25 Notes Await</span></a></li>
            </ul>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tabs_3 -->

      </div><!-- .tabs -->
    </div><!-- .sb_popContent -->
  </div><!-- .sb_popBoxInner -->
