<div class="sb_popBoxInner sb_triangle-solid">
	<div class="sb_popContent">
		<div class="sb_header">
			<h2 class="sb_title"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" /> Polls</h2>
		</div><!-- .sb_header -->
		<div class="sb_tabs">
			<ul>
				<li><a href="#polls_tabs_1">3 New!</a></li>
				<li><a href="#polls_tabs_2">Completed</a></li>
				<li><a href="#polls_tabs_3">Archive</a></li>
			</ul>
			<div id="polls_tabs_1" class="sb_tabPane">

				<div class="sb_scrollPane">

					<!-- BEGIN POLL BOX LANDING -->
					<p>Earn <strong class="sb_theme_textHighlight">1 Notes</strong> &amp; <strong class="sb_theme_textHighlight">250 Chops</strong> for each Poll you complete. Share with your friends to earn extra points and you’ll be that much closer to winning the big giveaway.</p>
					<div class="sb_accordion">
						<? foreach ($this->new_surveys as $survey) { ?>
							<h3><a href="http://<?= BASE_DOMAIN ?>/starbar/content/embed-poll?survey_id=<?= $survey->id ?>"><?= $survey->title ?></a></h3>
							<div>
								<iframe src="" width="470" height="120" frameborder="0" marginheight="0" marginwidth="0" scrollbar="no"></iframe>
							</div><!-- / END ACCORDION CONTENT -->
						<? } ?>
					</div><!-- .accordion -->
					<!-- END POLL BOX LANDING -->

				</div><!-- .sb_scrollPane -->

			</div><!-- #tabs_1 -->

			<div id="polls_tabs_2" class="sb_tabPane">
				<div class="sb_scrollPane">
          <p>All of your completed polls are listed below.</p>
					<ul class="sb_outlineList">
              <li><h3 class="sb_theme_iconComplete">Bob Dylan pre or post Newport? </h3>
              	<div class="sb_pointsEarnedTotal">
                	<span class="sb_chopsEarned">+250</span>
                	<span class="sb_notesEarned">+1</span>
                </div><!-- .sb_pointsEarnedTotal -->
              </li>
              <li><h3 class="sb_theme_iconComplete">Bob Dylan pre or post Newport? </h3>
              	<div class="sb_pointsEarnedTotal">
                	<span class="sb_chopsEarned">+250</span>
                	<span class="sb_notesEarned">+1</span>
                </div><!-- .sb_pointsEarnedTotal -->
              </li>
              <li><h3 class="sb_theme_iconComplete">Bob Dylan pre or post Newport? </h3>
              	<div class="sb_pointsEarnedTotal">
                	<span class="sb_chopsEarned">+250</span>
                	<span class="sb_notesEarned">+1</span>
                </div><!-- .sb_pointsEarnedTotal -->
              </li>
              <li><h3 class="sb_theme_iconComplete">Bob Dylan pre or post Newport? </h3>
              	<div class="sb_pointsEarnedTotal">
                	<span class="sb_chopsEarned">+250</span>
                	<span class="sb_notesEarned">+1</span>
                </div><!-- .sb_pointsEarnedTotal -->
              </li>
            </ul>
				</div><!-- .sb_scrollPane -->
			</div><!-- #tabs_2 -->

			<div id="polls_tabs_3" class="sb_tabPane">
				<div class="sb_scrollPane">					

						<!-- BEGIN POLL BOX LANDING -->
						<p>Earn <strong class="sb_theme_textHighlight">10 Notes</strong> for each poll you complete. Check back often to keep earning and for your chance to win the Weekly Giveaway!</p>
						<div class="sb_accordion">
							<h3><a href="#"><span class="sb_img_doubleValue"></span>Bob Dylan pre or post Newport?</a></h3>
							<div>
								<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_poll.jpg" alt="Poll Image" class="sb_pollImage" />
								<div class="sb_pollContent">
									<p><strong>Do you play electric or acoustic instruments?</strong></p>
									<form action="" name="">
										<div class="sb_column50">
											<p><input type="radio" /> <label>Electric</label></p>
											<p><input type="radio" /> <label>Acoustic</label></p>
										</div><!-- .sb_column50 -->
										<div class="sb_column50">
											<p><input type="radio" / ><label>Both</label></p>
										</div><!-- .sb_column50 -->
									</form>
								</div><!-- .sb_questionAnswers -->
							</div><!-- / END ACCORDION CONTENT -->
							<h3><a href="#">Everything Gibson</a></h3>
							<div>
								<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_poll.jpg" alt="Poll Image" class="sb_pollImage" />
								<div class="sb_pollContent">
									<p><strong>Do you play electric or acoustic instruments?</strong></p>
									<form action="" name="">
										<div class="sb_column50">
											<p><input type="radio" /> <label>Electric</label></p>
											<p><input type="radio" /> <label>Acoustic</label></p>
										</div><!-- .sb_column50 -->
										<div class="sb_column50">
											<p><input type="radio" / ><label>Both</label></p>
										</div><!-- .sb_column50 -->
									</form>
								</div><!-- .sb_questionAnswers -->
							</div><!-- / END ACCORDION CONTENT -->
							<h3><a href="#">Guitar Center or the Corner Music Shop</a></h3>
							<div>
								<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_poll.jpg" alt="Poll Image" class="sb_pollImage" />
								<div class="sb_pollContent">
									<p><strong>Do you play electric or acoustic instruments?</strong></p>
									<form action="" name="">
										<div class="sb_column50">
											<p><input type="radio" /> <label>Electric</label></p>
											<p><input type="radio" /> <label>Acoustic</label></p>
										</div><!-- .sb_column50 -->
										<div class="sb_column50">
											<p><input type="radio" / ><label>Both</label></p>
										</div><!-- .sb_column50 -->
									</form>
								</div><!-- .sb_questionAnswers -->
							</div><!-- / END ACCORDION CONTENT -->
						</div><!-- .accordion -->
						<!-- END POLL BOX LANDING -->
            <br />
						<p align="right"><a href="#" class="sb_nav_tabs sb_theme_button" rel="1"><span class="sb_theme_buttonArrow">Take a New Poll</span></a></p>
				</div><!-- .sb_scrollPane -->
			</div><!-- #tabs_3 -->

		</div><!-- .tabs -->
	</div><!-- .sb_popContent -->
  </div><!-- .sb_popBoxInner -->
