  <div class="sb_popBoxInner sb_triangle-solid">
    <div class="sb_popContent">
			<div class="sb_header">
        <h2 class="sb_title"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" /> Deals</h2>
      </div><!-- .sb_header -->
      <p>Act fast, deals don't last long! And remember to keep earning <strong class="sb_theme_textHighlight">Notes</strong> by <a href="">sharing</a>.</p>
      <ul class="sb_listDeals">
      	<li><a href=""><img src="http://www.chompon.com/uploads/deals/8885.jpg" alt="" class="sb_dealImage" />
          <span class="sb_dealStatusBG sb_dealStatusBG_orange">
          	<span class="sb_dealStatus">Almost Sold Out</span>
          </span>
        </a>
        <div class="sb_dealInfo">
          <p>Special 6 Ultra Tube Combo<br />
          <a href="" target="_blank" class="sb_theme_button_flat">View</a>
          <span class="sb_dealPrice">$250 Deal</span>
          <span class="sb_dealMsrp">$439 MSRP</span>        
          </p>
        </div><!-- .sb_dealInfo -->
        <a href=""><img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_facebook.png" alt="Facebook" /></a> 
        <a href=""><img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_twitter.png" alt="Twitter" /></a> 
        </li>
        <li><a href=""><img src="http://www.chompon.com/uploads/deals/8885.jpg" alt="" class="sb_dealImage" />
          <span class="sb_dealStatusBG">
          	<span class="sb_dealStatus"></span>
          </span>
        </a>
        <div class="sb_dealInfo">
        <p>ew 572 G3 Pro Instrument...<br />
        <a href="" target="_blank" class="sb_theme_button_flat">View</a>
        <span class="sb_dealPrice">$675 Deal</span>
        <span class="sb_dealMsrp">$1274 MSRP</span>        
        </p>
        </div><!-- .sb_dealInfo -->
        <a href=""><img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_facebook.png" alt="Facebook" /></a> 
        <a href=""><img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_twitter.png" alt="Twitter" /></a> 
        </li>
        <li><a href=""><img src="http://www.chompon.com/uploads/deals/8885.jpg" alt="" class="sb_dealImage" />
          <span class="sb_dealStatusBG sb_dealStatusBG_orange">
          	<span class="sb_dealStatus">Almost Sold Out</span>
          </span>
        </a>
        <div class="sb_dealInfo">
        <p>UltraLite-mk3 Hybrid<br />
        <a href="" target="_blank" class="sb_theme_button_flat">View</a>
        <span class="sb_dealPrice">$675 Deal</span>
        <span class="sb_dealMsrp">$1274 MSRP</span>        
        </p>
        </div><!-- .sb_dealInfo -->
        <a href=""><img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_facebook.png" alt="Facebook" /></a> 
        <a href=""><img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_twitter.png" alt="Twitter" /></a> 
        </li>
        <li><a href=""><img src="http://www.chompon.com/uploads/deals/8885.jpg" alt="" class="sb_dealImage" />
          <span class="sb_dealStatusBG sb_dealStatusBG_red">
          	<span class="sb_dealStatus">Sold Out</span>
          </span>
        </a>
        <div class="sb_dealInfo">
        <p>Solo Vintage Electric<br />
        <a href="" target="_blank" class="sb_theme_button_flat">View</a>
        <span class="sb_dealPrice">$450 Deal</span>
        <span class="sb_dealMsrp">$869 MSRP</span>        
        </p>
        </div><!-- .sb_dealInfo -->
        <a href=""><img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_facebook.png" alt="Facebook" /></a> 
        <a href=""><img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_twitter.png" alt="Twitter" /></a> 
        </li>
      </ul><!-- .sb_dailyDeal -->
    </div><!-- .sb_popContent -->
  </div><!-- .sb_popBoxInner -->
