	<div class="sb_header">
	<a href="http://say.so/" target="_blank"><img src="//<?= BASE_DOMAIN ?>/images/<?= $this->text('CONFIG_SHORT_TITLE') ?>/logo_<?= $this->text('CONFIG_SHORT_TITLE') ?>.png" alt="<?= $this->text('CONFIG_TITLE') ?>" /></a>
	<div class="sb_popBoxInner">
	<div class="sb_popContent">
		<div class="sb_tabs">
		<ul>
			<li><a href="#onboard_tabs_1">I'm In!</a></li>
			<li><a href="#onboard_tabs_2">What Can I Do?</a></li>
			<li><a href="#onboard_tabs_3">What Do I Get?</a></li>
			<li><a href="#onboard_tabs_4">Get Started</a></li>
		</ul>

		<div id="onboard_tabs_1" class="sb_tabPane">
			<div class="sb_scrollPane">
				<?= $this->text('ONBOARDING_TAB_1') ?>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_1 -->
		<div id="onboard_tabs_2" class="sb_tabPane">
			<div class="sb_scrollPane">
				<?= $this->text('ONBOARDING_TAB_2') ?>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_2 -->
		<div id="onboard_tabs_3" class="sb_tabPane">
			<div class="sb_scrollPane">
				<?= $this->text('ONBOARDING_TAB_3') ?>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_3 -->
		<div id="onboard_tabs_4" class="sb_tabPane">
			<div class="sb_scrollPane">
				<?= $this->text('ONBOARDING_TAB_4') ?>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_4 -->

		</div><!-- .sb_tabs -->
	</div><!-- .sb_popContent -->
	</div><!-- .sb_popBoxInner -->
