<?php

$good = $this->model;
?>

<div class="sb_rewardItem <?= ($good->can_purchase ? '' : 'sb_rewardItem_disabled') ?>" data-id="<?= $good->getId() ?>">
	<?php if ($good->cant_purchase_message) : ?>
		<div class="sb_rewardItem_disabledMsg">
			<h1 class="sb_textError">!</h1>
			<p><?= $good->cant_purchase_message ?></p>
		</div><!-- .sb_rewardItem_disabledMsg -->
	<?php endif ?>
	<div class="sb_rewardHeader">
		<?= $good->name ?>
	</div><!-- .sb_rewardHeader -->
	<div class="sb_rewardImg">
		<img src="<?= $good->img_url_preview ?>" alt="Reward" />
	</div><!-- .sb_rewardImg -->
	<div class="sb_rewardBase">
		<div class="sb_user-points-box">
			<span class="sb_imgRedeemable"></span>
			<div class="sb_progress_bar"><span class="sb_currency_percent" style="width: <?= $good->percentage ?>%"></span><span class="sb_progressBarValue"><span><?= $good->price ?></span></span></div>
		</div><!-- .user-points-box -->
		<?php if ($good->comment) : ?>
			<?php if ($good->can_purchase) : ?>
				<p class="sb_reward_comment"><span><?= $good->comment ?></span></p>
			<?php else : ?>
				<p class="sb_reward_levelReq"><span><?= $good->comment ?></span></p>
			<?php endif ?>
		<?php endif ?>
		<?php if ($good->can_purchase) : ?>
			<span class="sb_theme_button sb_theme_button_alt">Redeem</span>
		<?php else : ?>
			<span class="sb_theme_button sb_theme_button_grey">Redeem</span>
		<?php endif ?>
	</div><!-- .sb_rewardBase -->
</div><!-- .sb_rewardItem -->
<script type="text/javascript">
	$SQ(function(){
		$SQ('#sayso-starbar #sb_popBox_rewards .sb_rewardItem[data-id=<?= $good->getId() ?>]').dataContainer().setObject(<?= $good->export(new ObjectExporter_Json()) ?>);
	});
</script>
