<?php
	$auth = Zend_Auth::getInstance();
	$identity = $auth->getIdentity();
?>
<div id="common-auth">
<?php if ($auth->hasIdentity()): ?>
	<?php echo $identity ?> - <a href="javascript:void(null);" id="login" rel="1">Logout</a>
<?php else: ?>
	<a href="javascript:void(null);" id="login" rel="0">Login</a>
<?php endif; ?> | <a href="javascript:void(null);">Help</a>
</div>
<div id="login-dialog" title="Login" style="display:none"></div>