<div id="last-updated" class="ui-corner-top"></div>
<div class="clear"></div>
<div id="poll-time">
    <form id="dummy">
        <div id="controls">
            Poll time <select>
                <option selected>5</option>
                <option>10</option>
                <option>20</option>
                <option>30</option>
                <option>60</option>
                <option>80</option>
                <option>120</option>
                <option>300</option>
                <option>450</option>
            </select> s.
            <label for="control-social"><input type="checkbox" id="control-social" /> Social activity</label>
            <label for="control-page-view"><input type="checkbox" id="control-page-view" /> Page views</label>
            <label for="control-metrics"><input type="checkbox" id="control-metrics" /> Searches</label>
            <label for="control-tags"><input type="checkbox" id="control-tags" /> Tags</label>
            <label for="control-creatives"><input type="checkbox" id="control-creatives" /> Creatives</label>
        </div>        
        <div class="clear"></div>
    </form>
</div>
<div class="panel">    
    <div class="clear"></div>
    <div id="updates"></div>
    <div class="clear"></div>
</div>