<div class="panel">

    <h1>Real-Time Metrics</h1>
    
    <div id="poll-time">
        <form id="dummy">
            Poll time <select>
                <option>5</option>
                <option>10</option>
                <option>20</option>
                <option selected>30</option>
                <option>60</option>
                <option>60</option>
                <option>120</option>
                <option>300</option>
            </select> s.
        </form>
    </div>
    <div id="last-updated"></div>
    <div class="clear"></div>    
    <div id="updates"></div>

</div>