<?php
$data_format = json_encode(array("api_user"=>314, "api_key"=>"JUHkjh234JH9", "action_class"=>"survey", "action"=>"getAllSurveys"));
?>
getAllSurveys -
<form action="http://local.saysollc.com/api3/" method="post">
	<input type="hidden" name="data" value='<?= $data_format; ?>' />
	<input type="submit" />
</form>

<hr />
<?php
$data_format = json_encode(array("api_user"=>314, "api_key"=>"JUHkjh234JH9", "action_class"=>"survey", "action"=>"getAllSurveys", "results_per_page"=>25, "page_number"=>15 ));
?>
getAllSurveys - with page limits
<form action="http://local.saysollc.com/api3/" method="post">
	<input type="hidden" name="data" value='<?= $data_format; ?>' />
	<input type="submit" />
</form>

<hr />
<?php
$data_format = json_encode(array("api_user"=>314, "api_key"=>"JUHkjh234JH9", "requests"=>array("firstRequest"=>array( "action_class"=>"survey", "action"=>"getAllSurveys"), "secondRequest"=>array( "action_class"=>"user", "action"=>"getAllUsers"))));
?>
multi request getAllSurveys & getAllUsers
<form action="http://local.saysollc.com/api3/" method="post">
	<input type="hidden" name="data" value='<?= $data_format; ?>' />
	<input type="submit" />
</form>

<hr />
<?php
$data_format = json_encode(array("api_user"=>314, "api_key"=>"JUHkjh234JH9", "requests"=>array("firstRequest"=>array( "action_class"=>"survey", "action"=>"getAllSurveys","results_per_page"=>25, "page_number"=>15), "secondRequest"=>array( "action_class"=>"user", "action"=>"getAllUsers","results_per_page"=>10, "page_number"=>100))));
?>
multi request getAllSurveys & getAllUsers - with page limits
<form action="http://local.saysollc.com/api3/" method="post">
	<input type="hidden" name="data" value='<?= $data_format; ?>' />
	<input type="submit" />
</form>

<hr />
<?php
$data_format = json_encode(array("api_user"=>314, "api_key"=>"JUHkjh234JH9", "requests"=>array("firstRequest"=>array( "action_class"=>"survey", "action"=>"getAllSurveys","results_per_page"=>"abc", "page_number"=>15), "secondRequest"=>array( "action_class"=>"user", "action"=>"getAllUsers","results_per_page"=>10, "page_number"=>100))));
?>
multi request getAllSurveys & getAllUsers - with page limits - invalid data type
<form action="http://local.saysollc.com/api3/" method="post">
	<input type="hidden" name="data" value='<?= $data_format; ?>' />
	<input type="submit" />
</form>


<hr />
<?php
$data_format = json_encode(array("api_user"=>314, "api_key"=>"JUHkjh234JH9", "requests"=>array("firstRequest"=>array( "action_class"=>"survey", "action"=>"getAllSurveys","results_per_page"=>"abc", "page_number"=>"15asdf"), "secondRequest"=>array( "action_class"=>"user", "action"=>"getAllUsers","results_per_page"=>10, "page_number"=>100))));
?>
multi request getAllSurveys & getAllUsers - with page limits - invalid data type x2
<form action="http://local.saysollc.com/api3/" method="post">
	<input type="hidden" name="data" value='<?= $data_format; ?>' />
	<input type="submit" />
</form>
<!-- TEST MISSING REQUIRED PARAMS -->
<hr />
<?php
$data_format = json_encode(array("api_user"=>314, "api_key"=>"JUHkjh234JH9", "requests"=>array("firstRequest"=>array( "action_class"=>"survey", "action"=>"getAllSurveys","results_per_page"=>25, "page_number"=>15), "secondRequest"=>array( "action_class"=>"user", "action"=>"getAllffffUsers","results_per_page"=>10, "page_number"=>100))));
?>
multi request getAllSurveys & getAllUsers - with page limits - error on one request - bad action
<form action="http://local.saysollc.com/api3/" method="post">
	<input type="hidden" name="data" value='<?= $data_format; ?>' />
	<input type="submit" />
</form>

<hr />
<?php
$data_format = json_encode(array("api_user"=>314, "api_key"=>"JUHkjh234JH9", "requests"=>array("firstRequest"=>array( "action_class"=>"survey", "action"=>"getAllSurveys","results_per_page"=>25, "page_number"=>15), "secondRequest"=>array( "action_class"=>"ussdfsdfer", "action"=>"getAllUsers","results_per_page"=>10, "page_number"=>100))));
?>
multi request getAllSurveys & getAllUsers - with page limits - error on one request - bad class
<form action="http://local.saysollc.com/api3/" method="post">
	<input type="hidden" name="data" value='<?= $data_format; ?>' />
	<input type="submit" />
</form>

<hr />
<?php
$data_format = json_encode(array("api_user"=>314, "api_key"=>"JUHkjh234JH9", "continue_on_error"=>FALSE, "requests"=>array("firstRequest"=>array( "action_class"=>"survey", "action"=>"getAllSurveys","results_per_page"=>25, "page_number"=>15), "secondRequest"=>array( "action_class"=>"ussdfsdfer", "action"=>"getAllUsers","results_per_page"=>10, "page_number"=>100))));
?>
multi request getAllSurveys & getAllUsers - with page limits - error on one request - bad class - continue_on_error == FALSE
<form action="http://local.saysollc.com/api3/" method="post">
	<input type="hidden" name="data" value='<?= $data_format; ?>' />
	<input type="submit" />
</form>

<hr />
<?php
$data_format = json_encode(array("apieeeee_user"=>314, "api_key"=>"JUHkjh234JH9", "requests"=>array("firstRequest"=>array( "action_class"=>"survey", "action"=>"getAllSurveys","results_per_page"=>25, "page_number"=>15), "secondRequest"=>array( "action_class"=>"user", "action"=>"getAllUsers","results_per_page"=>10, "page_number"=>100))));
?>
multi request getAllSurveys & getAllUsers - with page limits - - bad user id field
<form action="http://local.saysollc.com/api3/" method="post">
	<input type="hidden" name="data" value='<?= $data_format; ?>' />
	<input type="submit" />
</form>

<hr />

<?php

$apiUser = 314;
$apiKey = "JUHkjh234JH9";
$api = Api3_Api::getInstance($apiUser, $apiKey);



//****************//
//
//error - missing parameters - user id and key
//
//
//****************//
//$api2 = Api3_Api::getInstance();
$params9 = array(	"results_per_page"=>1,
				"page_number"=>6,
				"action_class" => "Survey",
				"action" => "getAllSurveys"
		);
//$api2->setRequest($params9);

//echo $api2->getResponse();

//echo "<hr />";


//****************//
//
//error - missing parameters - set params
//
//
//****************//
$params8 = array(	"results_per_page"=>1,
				"page_number"=>6,
				"action_class" => "Survey",
				"action" => "getAllSurveys"
		);
//$api->setRequest($params8);

//echo $api->getResponse();

//echo "<hr />";


//****************//
//
//error - bad class
//this represents the first call from code
//
//****************//
$params6 = array(	"results_per_page"=>1,
				"page_number"=>6,
				"action_class" => "sadf",
				"action" => "getAllSurveys"
		);
//$api->setRequest($params6);

//echo $api->getResponse();

//echo "<hr />";

//****************//
//
//error - bad action
//this represents the first call from code
//
//****************//
$params7 = array(	"results_per_page"=>1,
				"page_number"=>6,
				"action_class" => "Survey",
				"action" => "asdf"
		);
//$api->setRequest($params7);

//echo $api->getResponse();

//echo "<hr />";

//****************//
//
//json
//this represents the first call from code
//
//****************//
$params1 = array(	"results_per_page"=>7,
				"page_number"=>177,
				"action_class" => "Survey",
				"action" => "getAllSurveys"
		);
$api->setRequest($params1);

echo $api->getResponse();

echo "<hr />";

//****************//
//
//second json request
//this represents a reuse option of the api object
//
//****************//
$params2 = array(	"results_per_page"=>1,
				"page_number"=>4,
				"action_class" => "Survey",
				"action" => "getAllSurveys"
		);
$api->setRequest($params2);

echo $api->getResponse();
echo "<hr />";

//****************//
//
//array
//this is another reuse but with an array output for use in the code
//
//****************//
$params3 = array(	"results_per_page"	=>1,
				"page_number"		=>4,
				"action_class"		=> "User",
				"action"			=> "getAllUsers",
				"response_format"	=> "array"
		);
$api->setRequest($params3);

echo "<pre>";
print_r($api->getResponse());
echo "</pre>";
echo "<hr />";

//****************//
//
//object
//this is another reuse but with an object output for use in the code
//
//****************//
$params4 = array(	"results_per_page"	=>1,
				"page_number"		=>4,
				"action_class"		=> "User",
				"action"			=> "getAllUsers",
				"response_format"	=> "php"
		);
$api->setRequest($params4);
echo "<pre>";
print_r($api->getResponse());
echo "</pre>";
echo "<hr />";

//****************//
//
// json request with no pagination parameters
//this represents a reuse option of the api object
//
$params5 = array(	"action_class" => "User",
				"action" => "getAllUsers"
		);
$api->setRequest($params5);

echo $api->getResponse();
echo "<hr />";



?>
multi request getAllSurveys & getAllUsers - with page limits - php response - direct call to API end point