<?php 

	$starbar = $this->starbar;
	/* @var $starbar Starbar */

	$user = $this->user;
	/* @var $user User */

	switch ($starbar->getVisibility()){
		case 'sb_starbar-visClosed':
			$buttonVisibility = 'sb_btnStarbar-closed';
			break;
		case 'sb_starbar-visStowed':
			$buttonVisibility = 'sb_btnStarbar-stowed';
			break;
		case 'sb_starbar-visOpen':
		default :
			$buttonVisibility = 'sb_btnStarbar-open';
			break;
	}
?>
<link type="text/css" rel="stylesheet" media="screen" href="http://<?= BASE_DOMAIN ?>/css/jquery.jscrollpane.css" />
<div id="starbar-player-semiStowed">
	<div id="sb_starbar-logoSemiStowed">
		<span class="sb_starbar-logo"></span>
	</div><!-- #starbar-toggleVis -->
</div>
<div id="starbar-player-console" class="<?= $starbar->getVisibility() ?>">
	<div id="starbar-wrapper">
		<div id="starbar-visControls">
			<div id="starbar-toggleVis" class="<?= $buttonVisibility ?>"></div><!-- #starbar-toggleVis -->
			<a href="http://<?= BASE_DOMAIN ?>/starbar/content/about-sayso" class="sb_nav_element sb_starbar-logo" id="sb_starbar-logo" rel="sb_popBox_about-saySo">say.so</a>
			<div id="sb_popBox_about-saySo" class="sb_popBox">
			</div><!-- .sb_popBox -->
			<div id="sb_popBox_onboard" class="sb_popBox" href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/onboard">
			</div><!-- #sb_popBox_onboard -->
		</div><!-- #starbar-visControls -->
		<div id="starbar-main">
			<div id="starbar-type">
				<div class="sb_inner">
					<div class="sb_changeTheme"><span>Check out other starbars</span></div><!-- .changeTheme -->
					<div class="sb_logo">
						<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" />
					</div><!-- .logo -->
					<div class="sb_userImg">
						<? if ($this->facebook_social->identifier) { ?>
							<img class="sb_userImg" src="http://graph.facebook.com/<?= $this->facebook_social->identifier ?>/picture?type=square" alt="<?= $user->getTitle() ?>" />
						<? } else { ?>
							<img class="sb_userImg" src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_user.jpg" alt="<?= $user->getTitle() ?>" />
						<? } ?>
					</div><!-- .userImg -->
					<div class="sb_content">
						<h2>Hi <?= $user->getTitle() ?></h2>
						<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/user-profile" class="sb_nav_element" rel="sb_popBox_user-profile">Edit Profile</a>						
					</div><!-- .sb_content -->
          <div id="sb_popBox_user-profile" class="sb_popBox sb_triangle-border">
						</div><!-- .sb_popBox -->
						<div id="sb_popBox_user-profile_lg" class="sb_popBox sb_popBoxLg sb_triangle-border">
						</div><!-- .sb_popBox -->
            <div id="sb_popBox_user-share" class="sb_popBox sb_triangle-border">
						</div><!-- .sb_popBox -->
				</div><!-- .inner -->
			</div><!-- #starbar-type -->
			<div id="starbar-alert-container-promos">
			</div>
			<div id="starbar-nav">
				<ul>
					<li id="nav_polls" class="sb_theme_bgGradient"><span href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/polls" class="sb_nav_element"><span class="sb_nav_border">Polls</span></span>
						<div id="sb_popBox_polls" class="sb_popBox sb_triangle-border">
						</div><!-- .sb_popBox -->
					</li>
					<li id="nav_surveys" class="sb_theme_bgGradient"><span href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/surveys" class="sb_nav_element"><span class="sb_nav_border">Surveys</span></span>
						<div id="sb_popBox_surveys" class="sb_popBox sb_triangle-border">
						</div><!-- .sb_popBox -->

						<div id="sb_popBox_surveys_lg" class="sb_popBox sb_popBoxLg sb_triangle-border">
						</div><!-- .sb_popBox -->
					</li>
					<li id="nav_daily-deals" class="sb_theme_bgGradient"><span href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/daily-deals" class="sb_nav_element"><span class="sb_nav_border">Daily Deals</span></span>
						<div id="sb_popBox_daily-deals" class="sb_popBox sb_triangle-border">
						</div><!-- .sb_popBox -->
					</li>
				</ul>
			</div><!-- #starbar-nav -->
			<div id="starbar-promo">
				<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/promos" class="sb_nav_element">
					<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_promo.png" alt="Promo" />
				</a>
				<div id="sb_popBox_promo" class="sb_popBox sb_triangle-border">
				</div><!-- .sb_popBox -->
			</div><!-- #starbar-promo -->
			<div id="starbar-alert-container-alerts">
			</div>
			<div id="starbar-level">    
				<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/user-level" class="sb_nav_element" rel="sb_popBox_user-level">  
					<div class="sb_content">        	
						<div class="sb_user-level">Level 1. <span class="sb_theme_textHighlight">Musician</span></div>
						<div class="sb_user-level-box">
							<span class="sb_user-level-star"></span>
							<div class="sb_progressBar"><span class="sb_progressBarPercent">60</span><span class="sb_progressBarValue">450</span></div>
						</div><!-- .user-level-box -->
					</div><!-- .sb_content -->     
				</a>      
				<div id="sb_popBox_user-level" class="sb_popBox sb_triangle-border"></div><!-- .sb_popBox -->      
			</div><!-- #starbar-level -->      
			<div id="starbar-points">
				<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards" class="sb_nav_element" rel="sb_popBox_rewards">
					<div class="sb_content">
						<div class="sb_user-points-box">
							<span class="sb_imgNote"></span>
							<div class="sb_progressBar"><span class="sb_progressBarPercent">0</span><span class="sb_progressBarValue">125</span></div>
						</div><!-- .user-points-box -->
					</div><!-- .sb_content -->
				</a>
				<div id="sb_popBox_rewards" class="sb_popBox sb_popBoxLg sb_triangle-border"></div><!-- .sb_popBox_rewards -->
			</div><!-- #starbar-points -->  
		</div><!-- #starbar-main -->
	</div><!-- #starbar-wrapper -->
</div><!-- #starbar-player-console -->
