<link type="text/css" rel="stylesheet" media="screen" href="http://<?= BASE_DOMAIN ?>/css/jquery.jscrollpane.css" />
<div id="starbar-player-console" class="sb_starbar-visOpen">
	<div id="starbar-wrapper">
		<div id="starbar-visControls">
			<div id="starbar-toggleVis" class="sb_starbar-visOpen sb_btnStarbar-open"></div><!-- #starbar-toggleVis -->
      <a href="http://<?= BASE_DOMAIN ?>/starbar/content/about-sayso" class="sb_nav_element" id="sb_starbar-logo" rel="sb_popBox_about-saySo">say.so</a>
      <div id="sb_popBox_about-saySo" class="sb_popBox">
      </div><!-- .sb_popBox -->
      <span id="sb_starbar-logoBorder" class=""></span>
		</div><!-- #starbar-visControls -->
    <div id="starbar-main">
      <div id="starbar-type">
        <div class="sb_inner">
          <div class="sb_changeTheme"><span>Check out other starbars</span></div><!-- .changeTheme -->
          <div class="sb_logo">
            <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" />
          </div><!-- .logo -->
          <div class="sb_userImg">
          	<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_user.jpg" alt="User Image" />
          </div><!-- .userImg -->
          <div class="sb_content">
            <h2>Hi Tatanisha</h2>
            <a href="http://<?= BASE_DOMAIN ?>/starbar/content/hellomusic-user-profile" class="sb_nav_element" rel="sb_popBox_user-profile">Edit Profile</a>
            <div id="sb_popBox_user-profile" class="sb_popBox sb_triangle-border">
            </div><!-- .sb_popBox -->
          </div><!-- .sb_content -->
        </div><!-- .inner -->
      </div><!-- #starbar-type -->
      <div class="sb_starbar-alert" id="starbar-alert-new">
        <div class="sb_inner">
          <div class="sb_content sb_theme_bgAlertRed">
          	<a href="http://<?= BASE_DOMAIN ?>/starbar/content/hellomusic-daily-deals" class="sb_nav_element sb_alert sb_alert-arrow" rel="sb_popBox_daily-deals">You have 2 new Daily Deals</a>
       		</div><!-- .sb_content -->
      	</div><!-- .sb_inner -->
      </div><!-- #sb_alert-new -->
      <div id="starbar-nav">
        <ul>
          <li id="nav_polls" class="sb_theme_bgGradient"><span href="http://<?= BASE_DOMAIN ?>/starbar/content/hellomusic-polls" class="sb_nav_element"><span class="sb_nav_border">Polls</span></span>
            <div id="sb_popBox_polls" class="sb_popBox sb_triangle-border">
            </div><!-- .sb_popBox -->
          </li>
          <li id="nav_surveys" class="sb_theme_bgGradient"><span href="http://<?= BASE_DOMAIN ?>/starbar/content/hellomusic-surveys" class="sb_nav_element"><span class="sb_nav_border">Surveys</span></span>
          	<div id="sb_popBox_surveys" class="sb_popBox sb_triangle-border">
            </div><!-- .sb_popBox -->
          </li>
          <li id="nav_daily-deals" class="sb_theme_bgGradient"><span href="http://<?= BASE_DOMAIN ?>/starbar/content/hellomusic-daily-deals" class="sb_nav_element"><span class="sb_nav_border">Daily Deals</span></span>
          	<div id="sb_popBox_daily-deals" class="sb_popBox sb_triangle-border">
            </div><!-- .sb_popBox -->
          </li>
        </ul>
      </div><!-- #starbar-nav -->
      <div id="starbar-promo">
      	<a href="http://<?= BASE_DOMAIN ?>/starbar/content/hellomusic-promos" class="sb_nav_element">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_promo.png" alt="Promo" />
        </a>
        <div id="sb_popBox_promo" class="sb_popBox sb_triangle-border">
        </div><!-- .sb_popBox -->
      </div><!-- #starbar-promo -->
      <div class="sb_starbar-alert sb_starbar-alert-wide" id="starbar-alert-earned">
        <div class="sb_inner">
          <div class="sb_content sb_theme_bgAlertGreen">
          	<a href="#" class="sb_nav_element sb_alert" rel="">You have completed your first survey!<br />You Earned +5 Notes!</a>
       		</div><!-- .sb_content -->
      	</div><!-- .sb_inner -->
      </div><!-- #sb_alert-new -->
      <a href="http://<?= BASE_DOMAIN ?>/starbar/content/hellomusic-user-level" class="sb_nav_element" rel="sb_popBox_user-level">
      <div id="starbar-level">      	
        <div class="sb_content">
          <div class="sb_user-level">Level 1. <span class="sb_theme_textHighlight">Musician</span></div>
          <div class="sb_user-level-box">
            <span class="sb_user-level-star"></span>
            <div class="sb_progressBar"><span class="sb_progressBarPercent">60</span><span class="sb_progressBarValue">450</span></div>
          </div><!-- .user-level-box -->
        </div><!-- .sb_content -->
          <div id="sb_popBox_user-level" class="sb_popBox sb_triangle-border">
          </div><!-- .sb_popBox -->
      </div><!-- #starbar-level -->
      <div id="starbar-points">
        <div class="sb_content">
          <div class="sb_user-points-box">
            <span class="sb_imgNote"></span>
            <div class="sb_progressBar"><span class="sb_progressBarPercent">0</span><span class="sb_progressBarValue">125</span></div>
          </div><!-- .user-points-box -->
        </div><!-- .sb_content -->
        <div id="sb_popBox_user-points" class="sb_popBox sb_triangle-border">
       	</div><!-- .sb_popBox -->
      </div><!-- #starbar-points -->
      </a>
    </div><!-- #starbar-main -->


	</div><!-- #starbar-wrapper -->
</div><!-- #starbar-player-console -->
<script type="text/javascript" src="http://<?= BASE_DOMAIN ?>/js/starbar/starbar-new.js"></script>