<script type="text/javascript">
    $SQ(function () {
        var baseDomain = "<?= BASE_DOMAIN ?>";
        if (!window.sayso) window.sayso = {};
        window.sayso.debug = true;
        window.sayso.baseDomain = baseDomain;
        window.sayso.log = _log('log'); 
        window.sayso.warn = _log('warn');
        function _log (type) { // <-- closure here allows re-use for log() and warn()
            return function () {
                if (window.sayso.debug && typeof window.console !== 'undefined' && typeof window.console.log !== 'undefined') {
                    var args = Array.prototype.slice.call(arguments);
                    if (typeof console.log.apply === 'function') {
                        args.unshift('SaySo:');
                        window.console[type].apply(window.console, args);
                    } else {
                        // must be IE
                        if (typeof args[0] !== 'object') {
                            window.console.log(args[0]);
                        }
                    }
                }
            }
        };
        window.sayso.starbar = {
            id : 1, // hellomusic
            kynetxAppId : 'a239x18',
            authKey : '<?= Api_Registry::getConfig()->api->helloMusic->authKey ?>',
            user : {
                id : <?= Api_UserSession::getInstance()->getId() ?>,
                key : '<?= Api_UserSession::getInstance()->getKey() ?>'
            },
            state : {
                visibility : 'starbar-visOpen'
            }
        };
        if (typeof(KOBJ) === 'undefined') {
            KOBJ = { 
                warn : function () { 
                    console.warn('Requested action has limited functionality outside of browser app.'); 
                },
                get_application : function () { 
                    return { 
                        raise_event : function () { KOBJ.warn(); }
                    } 
                }
            };
        }
    });
</script>
