<?php

$starbar = $this->starbar;
/* @var $starbar Starbar */

$game = $this->game;
/* @var $game Game_Starbar */

?>
<script type="text/javascript">
    /**
     * Purpose of this code is to represent the browser app for testing/development
     * Whatever app state is set in the KRL, should be represented here.
     * Starbar, auth key are hard coded to Hello Music
     * User is hard-coded 
     * User session is dynamic
     */
    $SQ(function () {
        if (!window.sayso) window.sayso = {};
        window.sayso.debug = true;
        window.sayso.baseDomain = '<?= BASE_DOMAIN ?>';
        window.sayso.environment = '<?= Registry::getPseudoEnvironmentName() ?>';
        window.sayso.log = _log('log'); 
        window.sayso.warn = _log('warn');
        function _log (type) { // <-- closure here allows re-use for log() and warn()
	        return function () {
	            if (window.sayso.debug && typeof window.console !== 'undefined' && typeof window.console.log !== 'undefined') {
	                var args = Array.prototype.slice.call(arguments);
	                if (typeof console.log.apply === 'function') {
	                    args.unshift('SaySo:');
	                    window.console[type].apply(window.console, args);
	                } else {
	                    // must be IE
	                    if (typeof args[0] !== 'object') {
	                        window.console.log(args[0]);
	                    }
	                }
	            }
	        }
        };
        window.sayso.starbar = {
            id : <?= $starbar->getId() ?>, 
            shortName : '<?= $starbar->short_name ?>',
            kynetxAppId : 'a239x20', // <-- this doesn't matter in this context
            authKey : '<?= $starbar->auth_key ?>',
            user : {
                id : <?= Api_UserSession::getInstance()->getId() ?>,
                key : '<?= Api_UserSession::getInstance()->getKey() ?>'
            },
            <? if ($game && $game->getGamer() && $game->getLevels()) { ?>
            	game : {
                	_gamer : <?= $this->game->getGamer()->export(new ObjectExporter_Json()) ?>,
                	_levels : <?= $this->game->getLevels()->export(new ObjectExporter_Json()) ?>
				},
            <? } ?>
            state : {
                visibility : 'starbar-visOpen',
            	local : {}
            },
            loaded : true
        };
        
        sayso.log(window.sayso.starbar);

        if (typeof(KOBJ) === 'undefined') {
            KOBJ = { 
                warn : function () { 
                    console.warn('Requested action has limited functionality outside of browser app.'); 
                },
                get_application : function () { 
                    return { 
                        raise_event : function () { KOBJ.warn(); }
                    } 
                }
            };
        }
    });

	$SQ('body').css('margin', 0);
</script>
<script src="http://<?= BASE_DOMAIN ?>/js/starbar/easyXDM.min.js" type="text/javascript"></script>
<script src="http://<?= BASE_DOMAIN ?>/js/starbar/sayso-shared.js" type="text/javascript"></script>
<script type="text/javascript">

	easyXDM.DomHelper.requiresJSON("http://<?= BASE_DOMAIN ?>/js/starbar/json2.min.js");

	$SQ.remoteControl = new easyXDM.Rpc({
		remote: "http://<?= BASE_DOMAIN ?>/html/communicator.html",
		local: "http://<?= BASE_DOMAIN ?>/html/communicator.html",
		swf: "http://<?= BASE_DOMAIN ?>/swf/easyxdm.swf",
	}, {
		// functions available to remote pages
		remote: {
			loadComplete: {},
			updateGame: {},
			handleTweet: {},
			openSurvey: {},
			hideOverlay: {},
			alertMessage: {}
		},
		local: {}
	});

</script>
