<?php

$starbar = $this->starbar;
/* @var $starbar Starbar */

$game = $this->game;
/* @var $game Game_Starbar */

?>
<script type="text/javascript">
	(function () {
		var sayso = {};
		sayso.debug = false;
		sayso.baseDomain = '<?= BASE_DOMAIN ?>';
		sayso.environment = '<?= Registry::getPseudoEnvironmentName() ?>';
		sayso.log = _log('log');
		sayso.warn = _log('warn');
		function _log (type) { // <-- closure here allows re-use for log() and warn()
			return function () {
				if (sayso.debug && typeof window.console !== 'undefined' && typeof window.console.log !== 'undefined') {
					var args = Array.prototype.slice.call(arguments);
					if (typeof console.log.apply === 'function') {
						args.unshift('SaySo:');
						window.console[type].apply(window.console, args);
					} else {
						// must be IE
						if (typeof args[0] !== 'object') {
							window.console.log(args[0]);
						}
					}
				}
			}
		};
		sayso.starbar = {
			id : <?= $starbar->getId() ?>,
			shortName : '<?= $starbar->short_name ?>',
			user : {
				id : <?= $this->user_id ? $this->user_id : 0 ?>,
				key : '<?= $this->user_key ? $this->user_key : "" ?>'
			},
			<? if ($game && $game->getGamer() && $game->getLevels()) { ?>
				game : <?= $this->game->export(new ObjectExporter_Json()) ?>,
			<? } ?>
			state : {
				visibility : 'open',
				local : {}
			},
			loaded : true
		};
		<?= $this->frame_id ? 'sayso.frameId = "' . $this->frame_id . '"' : '' ?>

		// Support for stupid browsers

		function getInternetExplorerVersion() {
			var rv = -1; // Return value assumes failure.
			if (navigator.appName == 'Microsoft Internet Explorer') {
				var ua = navigator.userAgent;
				var re = new RegExp("MSIE ([0-9]{1,}[\.0-9]{0,})");
				if (re.exec(ua) != null)
					rv = parseFloat(RegExp.$1);
			}
			return rv;
		}

		var ieVersion = getInternetExplorerVersion();
		if (ieVersion > -1 && ieVersion < 9) {
			sayso.disableJqueryEffects = true;
			sayso.jsonSupportMissing = true;
		} else {
			sayso.disableJqueryEffects = false;
			sayso.jsonSupportMissing = false;
		}

		// test if HTML5 placeholder is supported or not
		if (ieVersion > -1) {
			sayso.placeholderSupportMissing = true;
		} else {
			sayso.placeholderSupportMissing = false;
		}

		if (sayso.disableJqueryEffects) {
			$SQ.fx.off = true;
		}

		sayso.log(sayso.starbar);

		$SQ.sayso = sayso;
	})();

	$SQ('body').css('margin', 0);
</script>
<script src="//<?= BASE_DOMAIN ?>/js/starbar/sayso-shared.js" type="text/javascript"></script>
<script type="text/javascript">
	
	$SQ.frameComm = function( par ) {
		$SQ('#sayso-frame-comm').append($SQ(document.createElement("div")).attr( {
			value: JSON.stringify({
				type: 'sayso-frame-comm-' + $SQ.sayso.frameId
			, content: par })}));
		var hiddenDiv = document.getElementById('sayso-frame-comm');
		if( document.createEvent ) {
			var ev = document.createEvent('Event');
			ev.initEvent('saysoFrameComm', false, false);
			hiddenDiv.dispatchEvent(ev);
		} else if( document.createEventObject ) {
			var evObj = document.createEventObject();
		    hiddenDiv.fireEvent( 'onclick', evObj );
		}
	}

	$SQ.remoteControl = {
		loadComplete: function (hideLoadingElem, newFrameHeight) {
			$SQ.frameComm( ['loadComplete', {
				hideLoadingElem: hideLoadingElem,
				newFrameHeight: newFrameHeight
			}]);
		},
		updateGame: function (newGame) {
			$SQ.frameComm( ['updateGame', {
				newGame: newGame
			}]);
		},
		handleTweet: function (sharedType, sharedId) {
			$SQ.frameComm( ['handleTweet', {
				shared_type: sharedType,
				shared_id: sharedId
			}]);
		},
		handleFacebookShare: function (link, sharedType, sharedId) {
			$SQ.frameComm( ['handleFacebookShare', {
				link: link,
				shared_type: sharedType,
				shared_id: sharedId
			}]);
		},
		openSurvey: function (surveyId) {
			$SQ.frameComm( ['openSurvey', {
				survey_id: surveyId
			}]);
		},
		hideOverlay: function () {
			$SQ.frameComm( ['hideOverlay']);
		},
		alertMessage: function (alertMessage) {
			$SQ.frameComm( ['alertMessage', {
				alert_message: alertMessage
			}]);
		}
	};
</script>
<div id="sayso-frame-comm" style="display: none;"></div>