<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Starbar</title>
        <meta name="description" content="">
    </head>
    <body style="margin: 0; padding: 0; background: url('<?= $this->screenshot ?>') top center no-repeat;">
        <div id="my_ad" style="background: url('/images/hellomusic/img_reward.jpg'); width: 100px; height: 100px; margin: 0px; border: solid 3px black; font-weight: bold;">My Ad!</div>
        <div id="my_other_ad" style="background: url('/images/hellomusic/img_reward.jpg'); width: 100px; height: 100px; margin: 0px; border: solid 3px black; font-weight: bold;">My Other Ad!</div>
        <?php echo $this->layout()->content; ?>
        <?= $this->headScript() . PHP_EOL ?>
    </body>
</html>