<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>Starbar</title>
		<meta name="description" content="">
	</head>
	<body style="margin: 0; padding: 0; background: <?= $this->color ? $this->color : '' ?> url('<?= $this->screenshot ?>') top center no-repeat;">
		<?php echo $this->layout()->content; ?>
		<?= $this->headScript() . PHP_EOL ?>
	</body>
</html>