<h1>Edit Admin Roles<span class="italic">"<?php echo $this->entry->first_name, ", ", $this->entry->last_name; ?>"</span></h1>

<nav class="admin_menu">
    <ul id="leftMenuNav">
        <li><?php echo $this->addLink ; ?></li>
    </ul>
    <ul id="rightMenuNav">
        <li><?php echo $this->indexLink ; ?></li>
    </ul>
    <div class="clear"></div>
</nav>

<div class="panel">
    <?php echo $this->form ; ?>
</div>