<script type="text/javascript">
    if (!window.sayso) window.sayso = {};
    if (!window.sayso.client) {
        window.sayso.client = {
            name : 'hellomusic',
            uuid : '',
            uuidType : 'email',
            userLoggedIn : false,
            meta : {
                uuidKey : 'MyEmail',
                userLoggedInKey : 'CHOMPUID',
                customStartMessage : 'Start the Music!'
            }    
        };
    }
</script>
<script type="text/javascript" src="http://<?= Registry::getConfig()->baseDomain ?>/client/global/js/starbar-embed.js"></script>