<script type="text/javascript">if(!window.sayso)window.sayso={};if(!window.sayso.client)window.sayso.client={name:"hellomusic",uuid:"",uuidType:"email",userLoggedIn:false,authKey:"309e34632c2ca9cd5edaf2388f5fa3db",meta:{uuidKey:"MyEmail",userLoggedInKey:"CHOMPUID",customStartMessage:"Start the Music!"}};if(!window.sayso.baseDomain)window.sayso.baseDomain="app-qa.saysollc.com",window.sayso.environment="TEST";</script>
<script type="text/javascript" src="http://app-qa.saysollc.com/client/global/js/starbar-embed.js"></script>

