<script type="text/javascript">
    $S(function () {
        var baseDomain = "<?= BASE_DOMAIN ?>";
        if (!window.sayso) window.sayso = {};
        window.sayso.debug = true;
        window.sayso.baseDomain = baseDomain;
        window.sayso.starbar = {
            id : 1,
            kynetxAppId : 'a239x18',
            authKey : '<?= Api_Registry::getConfig()->api->helloMusic->authKey ?>',
            user : {
                id : 1,
                key : '<?= Api_UserSession::getInstance()->getKey() ?>'
            },
            state : {
                visibility : 'starbar-visOpen'
            }
        };
        if (typeof(KOBJ) === 'undefined') {
            KOBJ = { 
                warn : function () { 
                    console.warn('Requested action has limited functionality outside of browser app.'); 
                },
                get_application : function () { 
                    return { 
                        raise_event : function () { KOBJ.warn(); }
                    } 
                }
            };
        }
    });
</script>
<div id="sayso-starbar" style=""><?= $this->partial('remote/hellomusic.phtml'); ?></div>