<section id="player-console" class="visMax">
  <div id="popBoxDialog">
    <iframe src=" " width="580" height="400" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
  </div>
  <!-- /popBoxDialog -->
  <div class="contain">
    <div id="visControls">
      <div id="" class="controls">
        <div id="toggleVis" class="hide">hide</div>
        <a id="logo">say.so <span id="logoBorder" class="hidden setColorShadow setColorHover"></span> </a>
        <div id="_sayso" class="popBoxContent">
          <div class="column_left popBoxScrollbar">
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <p align="center"><img src="images/logo_large.png" alt="say.so" class="imgBorder" /></p>
                <div class="columnContent">
                  <p><strong>What is Say.So?</strong><br />
                    Say.So is a great way for you to connect with the stars and brands that you're most loyal to. </p>
                  <p><strong>And what about StarBars?</strong><br />
                    StarBars are the crux of the Say.So experience. By adding StarBars, you'll get the latest news, polls, and questions for the celebrities and brands you love.</p>
                  <p><strong>How do I use Say.So?</strong><br />
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eu lobortis diam.</p>
                </div>
                <!-- /columnContent -->
              </div>
              <!-- /overview -->
            </div>
            <!-- /viewport -->
          </div>
          <!-- /column_left -->
          <div class="column_right popBoxScrollbar">
            <div class="scrollbar">
              <div class="track">
                <div class="thumb">
                  <div class="end"></div>
                </div>
              </div>
            </div>
            <div class="viewport">
              <div class="overview">
                <div class="columnContent">
                  <p><strong>What are the Say.So currencies?</strong></p>
                  <ul class="currency">
                    <li class="icon_fansay"><strong>Fan.Say</strong> is your measure of credebility within a StarBar community. You earn it by engaging within a StarBar, and the more you earn, the higher your rank.</li>
                    <li class="icon_fanfare"><strong>Fan.Fare</strong> comes from accumulating Fan.Say, and it's where things get interesting. You can redeem Fan.Fare for real-world goods!</li>
                    <li class="icon_sayso"><strong>Say.So</strong> is like Fan.Say, but it's not tied to any particular StarBar. The more you participate overall, the more you move up in the Say.So community.</li>
                  </ul>
                </div>
                <!-- /columnContent -->
              </div>
              <!-- /overview -->
            </div>
            <!-- /viewport -->
          </div>
          <!-- /column_right -->
        </div>
        <!-- /sayso -->
      </div>
      <!-- /controls -->
    </div>
    <!-- /visControls -->
    <div id="mainContent">
      <!-- empty popBox to be filled with content from each section -->
      <div id="" class="popBox triangle-border">
        <div class="popInner triangle-solid"> </div>
        <!-- /popInner -->
      </div>
      <!-- /popBox -->
      <div class="starbar">
        <div class="top setColor" id=""> <a href="#" class="icon_change navLink">change starbars</a>
          <div id="_starbarChange" class="popBoxContent">
            <div class="popBoxSingle">
              <div class="controls"> <a href="#" class="closePop">hide this panel</a> </div>
              <!-- /top -->
              <h3>Search for new <strong>StarBars</strong></h3>
              <div class="columnContent columnContentBorderBottom">
                <input type="text" class="text" style="width: 65%;">
                <input type="submit" value="Search" class="button alignRight">
              </div>
              <!-- /column_content -->
              <div class="column_single popBoxScrollbar">
                <h3>My Installed <strong>StarBars</strong></h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent" id="theme_gaga"> <img src="images/gaga_icon.jpg" class="alignLeft">
                      <div class="popImgContent">
                        <h4>Lady Gaga</h4>
                        <h5>138,523 Little Monsters <span>&bull; <a href="#de40b2" class="changeTheme">Switch</a></span></h5>
                      </div>
                      <!-- /popImgContent -->
                    </div>
                    <!-- /columnContent -->
                    <div class="columnContent columnContentBG" id="theme_coca-cola"> <img src="images/coca-cola_icon.png" class="alignLeft">
                      <div class="popImgContent">
                        <h4>Coca-Cola</h4>
                        <h5>120,000 followers <span>&bull; <a href="#fb0302" class="changeTheme">Switch</a></span></h5>
                      </div>
                      <!-- /popImgContent -->
                    </div>
                    <!-- /columnContent -->
                    <div class="columnContent" id="theme_michael-jordan"> <img src="images/michael-jordan_icon.png" class="alignLeft">
                      <div class="popImgContent">
                        <h4>Michael Jordan</h4>
                        <h5>40,000 followers <span>&bull; <a href="#d98f00" class="changeTheme">Switch</a></span></h5>
                      </div>
                      <!-- /popImgContent -->
                    </div>
                    <!-- /columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_single -->
            </div>
            <!-- /popBoxSingle -->
          </div>
          <!-- /starbarChange -->
        </div>
        <!-- /top -->
        <div class="main setColor"></div>
        <div class="content"> <img class="icon" src="images/gaga_icon.jpg" alt="section icon"/>
          <h3>Lady Gaga</h3>
          <h5>138,523 Little Monsters</h5>
        </div>
        <!-- /content -->
      </div>
      <!-- /starbar -->
      <div id="nav">
        <ul>
          <li class="nav_news" id=""> <a href="#" class="navLink"><span class="navBorder setColorShadow setColorHover"></span><span class="hidden">news</span></a>
            <div id="_news" class="popBoxContent">
              <div class="column_left popBoxScrollbar">
                <h3>News from <strong>Social Media</strong></h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent"> <img src="images/gaga_icon.jpg" class="alignLeft">
                      <div class="popImgContent">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eu lobortis diam. </p>
                      </div>
                      <!-- /popImgContent -->
                      <p class="source">Charlie Sheen &bull; Facebook &bull; <a href="">Share</a></p>
                    </div>
                    <!-- /columnContent -->
                    <div class="columnContent columnContentBG"> <img src="images/gaga_icon.jpg" class="alignLeft">
                      <div class="popImgContent">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eu lobortis diam. </p>
                      </div>
                      <!-- /popImgContent -->
                      <p class="source">David Letterman &bull; Twitter &bull; <a href="">Share</a></p>
                    </div>
                    <!-- /columnContent -->
                    <div class="columnContent"> <img src="images/gaga_icon.jpg" class="alignLeft">
                      <div class="popImgContent">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eu lobortis diam. </p>
                      </div>
                      <!-- /popImgContent -->
                      <p class="source">Oprah &bull; Facebook &bull; <a href="">Share</a></p>
                    </div>
                    <!-- /columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_left -->
              <div class="column_right popBoxScrollbar">
                <h3>News in the <strong>Blogosphere</strong></h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent"> <img src="images/cnn_icon.png" class="alignLeft">
                      <div class="popImgContent">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eu lobortis diam. </p>
                      </div>
                      <!-- /popImgContent -->
                      <p class="source">Charlie Sheen &bull; Facebook &bull; <a href="">Share</a></p>
                    </div>
                    <!-- /columnContent -->
                    <div class="columnContent columnContentBG"> <img src="images/tmz_icon.png" class="alignLeft">
                      <div class="popImgContent">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eu lobortis diam. </p>
                      </div>
                      <!-- /popImgContent -->
                      <p class="source">David Letterman &bull; Twitter &bull; <a href="">Share</a></p>
                    </div>
                    <!-- /columnContent -->
                    <div class="columnContent"> <img src="images/cnn_icon.png" class="alignLeft">
                      <div class="popImgContent">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eu lobortis diam. </p>
                      </div>
                      <!-- /popImgContent -->
                      <p class="source">Oprah &bull; Facebook &bull; <a href="">Share</a></p>
                    </div>
                    <!-- /columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_right -->
            </div>
            <!-- /popBoxContent -->
          </li>
          <li class="nav_polls" id=""> <a href="#" class="navLink"><span class="navBorder setColorShadow setColorHover"></span><span class="hidden">polls</span></a>
            <div id="_polls" class="popBoxContent">
              <div class="column_left popBoxScrollbar">
                <h3>Popular <strong>Gaga Polls</strong> &bull; 3 new!</h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent columnContentBG"> <img src="images/gaga_icon.jpg" alt="Starbar Icon" class="alignLeft" />
                      <div class="popImgContent">
                        <p>Do you think my Los Angeles performance was outrageous enough?</p>
                        <form>
                          <p>
                            <input type="radio" name="poll" value="yes">
                            <strong>Yes</strong> - Be careful!<br />
                            <input type="radio" name="poll" value="no">
                            <strong>No</strong> - Push the envelope more! </p>
                        </form>
                      </div>
                      <!-- /popImgContent -->
                    </div>
                    <!-- /columnContent -->
                    <div class="columnContent"> <img src="images/gaga_icon.jpg" alt="Starbar Icon" class="alignLeft" />
                      <div class="popImgContent">
                        <p>Which late night show should I perform on next week?</p>
                      </div>
                      <!-- /popImgContent -->
                      <br clear="all">
                      <div class="barGraph">
                        <p> <span class="barKey">Leno</span> <span class="barContainer"><span class="bar" style="width: 15%"></span></span> <span class="barValue">15%</span> </p>
                        <p> <span class="barKey">Letterman</span> <span class="barContainer"><span class="bar" style="width: 14%"></span></span> <span class="barValue">14%</span> </p>
                        <p class="barWinner setTextColor"> <span class="barKey">Conan</span> <span class="barContainer"><span class="bar setColor" style="width: 71%"></span></span> <span class="barValue">100%</span> </p>
                      </div>
                      <!-- barGraph -->
                    </div>
                    <!-- /columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_left -->
              <div class="column_right popBoxScrollbar">
                <h3>Earn With <strong>Other Polls</strong></h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent">
                      <p><img src="images/logo_dark.png" alt="Say.So" class="alignLeft" />Say.so is a way to participate with the brands you know and love to help them deliver you products and services that matter most to you. When you participate in these polls, surveys, and questions, you earn points that have real-world value.</p>
                      <br />
                      <h4 class="earnValue"><span class="icon_pay">2 Pay.so</span></h4>
                      <p>Which of the following pictures do you most associate with cleaning the house?s</p>
                      <form action="" method="">
                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                          <tr>
                            <td width="25%" align="center" valign="top"><img src="images/img_placeholder.jpg" alt=""><br />
                              <input type="radio" name="form" value=""></td>
                            <td width="25%" align="center" valign="top"><img src="images/img_placeholder.jpg" alt=""><br />
                              <input type="radio" name="form" value=""></td>
                            <td width="25%" align="center" valign="top"><img src="images/img_placeholder.jpg" alt=""><br />
                              <input type="radio" name="form" value=""></td>
                            <td width="25%" align="center" valign="top"><img src="images/img_placeholder.jpg" alt=""><br />
                              <input type="radio" name="form" value=""></td>
                          </tr>
                        </table>
                      </form>
                    </div>
                    <!-- /columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_right -->
            </div>
            <!-- /popBoxContent -->
          </li>
          <li class="nav_surveys" id=""> <a href="#" class="navLink"><span class="navBorder setColorShadow setColorHover"></span><span class="hidden">surveys</span></a>
            <div id="_surveys" class="popBoxContent">
              <div class="column_left popBoxScrollbar">
                <h3><strong>Lady Gaga Surveys</strong> &bull; 1 new!</h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent">
                      <p>How Ga-ga are you over Gaga?</p>
                      <p>Strut your monstrosity. <br />
                        <a href="https://spreadsheets.google.com/spreadsheet/embeddedform?formkey=dDlxNkNyc1pnS1I0NWk5U3BEYU1tbFE6MQ" class="popDialog">10 Fan.Fare awaits! &raquo;</a></p>
                      <p>Schizmo Your Gizmo. <br />
                        <a href="http://www.surveygizmo.com/s3/iframe/600155/4bb299a0f84f" class="popDialog">1 million Fan.Fare awaits! &raquo;</a></p>
                    </div>
                    <!-- /columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_left -->
              <div class="column_right popBoxScrollbar">
                <h3>Earn With <strong>Other Surveys</strong></h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent">
                      <p><img src="images/logo_dark.png" alt="Say.So" class="alignLeft" />Say.so is a way to participate with the brands you know and love to help them deliver you products and services that matter most to you. When you participate in these polls, surveys, and questions, you earn points that have real-world value.</p>
                      <div class="accordion">
                        <h4>Hello Hybrids! <span class="icon_pay">25 Pay.so</span></h4>
                        <div>
                          <p>Think you know your hybrids?</p>
                          <p>Let's see. <br />
                            <a href="https://spreadsheets.google.com/embeddedform?formkey=dFQyd04zdGpSVVJWZENhaE1nUkR3MEE6MQ" class="popDialog">25 Pay.Sos are waiting for your Say.So &raquo;</a></p>
                        </div>
                        <h4>Fashionista <span class="icon_pay">2 Pay.so</span></h4>
                        <div>
                          <p>Think you know the hottest styles?</p>
                          <p>Let's see. <br />
                            <a href="https://spreadsheets.google.com/embeddedform?formkey=dFQyd04zdGpSVVJWZENhaE1nUkR3MEE6MQ" class="popDialog">2 Pay.Sos are waiting for your Say.So &raquo;</a></p>
                        </div>
                        <h4>Live Action Hero <span class="icon_pay">1 Pay.so</span></h4>
                        <div>
                          <p>Do you have what it takes to be a real-life hero?</p>
                          <p>Let's see. <br />
                            <a href="https://spreadsheets.google.com/embeddedform?formkey=dFQyd04zdGpSVVJWZENhaE1nUkR3MEE6MQ" class="popDialog">2 Pay.Sos are waiting for your Say.So &raquo;</a></p>
                        </div>
                      </div>
                      <!-- /accordion -->
                    </div>
                    <!--/columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_right -->
            </div>
            <!-- /popBoxContent -->
          </li>
          <li class="nav_questions" id=""> <a href="#" class="navLink"><span class="navBorder setColorShadow setColorHover"></span><span class="hidden">questions</span></a>
            <div id="_questions" class="popBoxContent">
              <div class="column_left popBoxScrollbar">
                <h3>Questions from <strong>Gaga</strong></h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent columnContentTriangle"> <img alt="Starbar Icon" src="images/gaga_icon.jpg" class="alignLeft">
                      <div class="popImgContent">
                        <p>I'm thinking of playing a surprise show. Where do you think I should play?</p>
                        <p align="right"><a href="">Answer It</a> &bull; <a href="">Hide 28 Answers</a></p>
                      </div>
                      <!-- /popImgContent -->
                    </div>
                    <!-- /columnContent -->
                    <div class="columnContent">
                      <p>
                        <input type="text" class="text alignLeft" value="Your Name">
                        <input type="text" class="text alignRight" value="Your City">
                        <span class="clear"></span> </p>
                      <p>
                        <textarea>Your Answer</textarea>
                      </p>
                      <p>
                        <input type="submit" value="Answer This Question" class="button alignRight">
                      </p>
                    </div>
                    <!-- /columnContent -->
                    <div class="columnContent">
                      <p class="qa_answer">OMG!!!! Come play at East Westchester Elementary School!!!</p>
                      <p class="source"><em>Diane from Rochester, CT</em></p>
                      <p class="qa_answer">Is this even really a question? You have got to come play in Portland again!</p>
                      <p class="source"><em>Ben from Portland, OR</em></p>
                    </div>
                    <!-- /columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_left -->
              <div class="column_right popBoxScrollbar">
                <h3>Questions to <strong>Gaga</strong></h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent">
                      <div class="qa_ask">
                        <p>
                          <textarea></textarea>
                        </p>
                        <p>
                          <input type="submit" value="Ask Your Question" class="button alignRight">
                        </p>
                      </div>
                    </div>
                    <!-- /columnContent -->
                    <div class="columnContent columnContentBG">
                      <p><em>John from Lansing, MI</em><br />
                        What will you wear for your next show?</p>
                      <p><em>And Lady Gaga responded:</em></p>
                      <img src="images/gaga_icon.jpg" alt="Starbar Icon" class="alignLeft" />
                      <div class="popImgContent">
                        <p> I can’t decide yet, but it will certainly make you wonder if I’m doing avant garde performance art or if I actually think that. </p>
                      </div>
                      <!-- /popImgContent -->
                    </div>
                    <!-- /columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_right -->
            </div>
            <!-- /popBoxContent -->
          </li>
        </ul>
      </div>
      <!-- /nav -->
      <div id="nav_user">
        <div id="userBox">
          <div id="" class="content"> Hi, John!<br />
            <a href="#" class="navLink">My Settings</a>
            <div id="_userbox" class="popBoxContent">
              <div class="column_left popBoxScrollbar">
                <h3>Your Say.So <strong>Profile</strong></h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent"> <img alt="User" src="images/img_user.jpg" class="imgBorder alignLeft">
                      <div class="popImgContent"> <big>John Thompson</big>
                        <p><strong>Display Name:</strong> johnt<br />
                          <strong>Email:</strong> j_thompson@gmail.com<br />
                          <strong>Twitter:</strong> @jpcody<br />
                          <strong>Facebook:</strong> not connected</p>
                        <p><strong>Level:</strong> Newbie<br />
                          <strong>Say.So:</strong> 1,200<br />
                          <strong>Pay.So:</strong> 8<br />
                          <em>Tip: Earn 100 more Say.So points by participating in more surveys</em></p>
                      </div>
                      <!-- /popImgContent -->
                    </div>
                    <!-- /columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_left -->
              <div class="column_right popBoxScrollbar">
                <h3>Your Say.So <strong>Preferences</strong></h3>
                <div class="scrollbar">
                  <div class="track">
                    <div class="thumb">
                      <div class="end"></div>
                    </div>
                  </div>
                </div>
                <div class="viewport">
                  <div class="overview">
                    <div class="columnContent">
                      <p><strong>Types:</strong> Show me polls and surveys related to:</p>
                      <table cellpadding="0" cellspacing="0" border="0" width="100%" class="userPreferences">
                        <tr valign="top">
                          <td width="33%"><input type="checkbox" checked="true">
                            Technology</td>
                          <td width="33%"><input type="checkbox" checked="true">
                            News</td>
                          <td width="33%"><input type="checkbox" checked="true">
                            Sports</td>
                        </tr>
                        <tr valign="top">
                          <td width="33%"><input type="checkbox" checked="true">
                            Food</td>
                          <td width="33%"><input type="checkbox" checked="true">
                            Celebrities</td>
                          <td width="33%"><input type="checkbox" checked="true">
                            Household</td>
                        </tr>
                        <tr valign="top">
                          <td width="33%"><input type="checkbox" checked="true">
                            Religion</td>
                          <td width="33%"><input type="checkbox" checked="true">
                            Politics</td>
                          <td width="33%"><input type="checkbox" checked="true">
                            Television</td>
                        </tr>
                      </table>
                      <br />
                      <p><strong>Poll Frequency:</strong> Show me Say.So Polls:</p>
                      <table cellpadding="0" cellspacing="0" border="0" width="100%" class="userPreferences">
                        <tr valign="top">
                          <td><input type="checkbox" checked="true">
                            Often - earn the most Pay.So!</td>
                        </tr>
                        <tr valign="top">
                          <td><input type="checkbox" checked="true">
                            Occasionally - earn a little Pay.So</td>
                        </tr>
                        <tr valign="top">
                          <td><input type="checkbox" checked="true">
                            Never - no Pay.So :(</td>
                        </tr>
                      </table>
                      <br />
                      <p><strong>Email Frequency:</strong> Send me Say.So emails</p>
                      <table cellpadding="0" cellspacing="0" border="0" width="100%" class="userPreferences">
                        <tr valign="top">
                          <td><input type="checkbox" checked="true">
                            Often - earn the most Pay.So!</td>
                        </tr>
                        <tr valign="top">
                          <td><input type="checkbox" checked="true">
                            Occasionally - earn a little Pay.So</td>
                        </tr>
                        <tr valign="top">
                          <td><input type="checkbox" checked="true">
                            Never - no Pay.So :(</td>
                        </tr>
                      </table>
                      <br />
                      <p align="right">
                        <input type="submit" class="button" value="Save Preferences">
                      </p>
                    </div>
                    <!-- /columnContent -->
                  </div>
                  <!-- /overview -->
                </div>
                <!-- /viewport -->
              </div>
              <!-- /column_right -->
            </div>
            <!-- /popBoxContent -->
          </div>
          <!-- /content -->
        </div>
        <!-- /userBox -->
        <div id="fanBox">
          <div id="" class="fanSay"> <a href="#" class="navLink"><span></span>25</a>
            <div id="_fanSay" class="popBoxContent">
              <div class="popBoxSingle">
                <div class="column_single">
                  <h3 align="center"><img src="images/icon_fansay.png" /> You have <strong>115 Fan.Say</strong></h3>
                  <div class="columnContentBubble"> That makes you an <strong>expert</strong> </div>
                  <!-- /columnContentBubble -->
                  <table cellpadding="0" cellspacing="0" border="0" class="userRank">
                    <tr class="odd">
                      <td class="rank">47</td>
                      <td class="pic"><img src="images/img_user.jpg" /></td>
                      <td class="name">John Doe</td>
                      <td class="score">109</td>
                    </tr>
                    <tr class="eve">
                      <td class="rank">48</td>
                      <td class="pic"><img src="images/img_user.jpg" /></td>
                      <td class="name">Jane Smith</td>
                      <td class="score">108</td>
                    </tr>
                    <tr id="user" class="odd">
                      <td class="rank">49</td>
                      <td class="pic"><img src="images/img_user.jpg" /></td>
                      <td class="name">John Thompson</td>
                      <td class="score">102</td>
                    </tr>
                    <tr class="even">
                      <td class="rank">50</td>
                      <td class="pic"><img src="images/img_user.jpg" /></td>
                      <td class="name">Michael Hemmingway</td>
                      <td class="score">100</td>
                    </tr>
                    <tr class="odd">
                      <td class="rank">51</td>
                      <td class="pic"><img src="images/img_user.jpg" /></td>
                      <td class="name">Susan Murphy</td>
                      <td class="score">99</td>
                    </tr>
                  </table>
                  <br />
                  <p align="center">When you participate in the StarBar of your favorite star, you earn Fan.Say. Watch as you move up the ranks to achieve ultimate fandom!</p>
                  <br />
                  <p align="center">
                    <input type="submit" value="Earn More Fan.Say" class="button button2" />
                  </p>
                </div>
                <!-- /column_single -->
              </div>
              <!-- /popBoxSingle -->
            </div>
            <!-- /fanSay -->
          </div>
          <!-- /fanSay -->
          <div id="" class="fanFare"> <a href="#" class="navLink"><span></span>1218</a>
            <div id="_fanFare" class="popBoxContent">
              <div class="popBoxSingle">
                <div class="column_single">
                  <h3 align="center"><img src="images/icon_fanfare.png" /> You have <strong>115 Fan.Fare</strong></h3>
                  <div class="columnContentBubble">With 100 Fan.Fare you could get <br />
                  <strong>A Lady Gaga Horse Saddle</strong></div>
                  <!-- /columnContentBubble -->
                  <br />
                  <p align="center">
                  	<img src="images/img_fanfarePrize.jpg" alt="" class="imgBorder" />
                  </p>
                  <p align="center" style="padding:0px 20px;">
                  Participating in StarBars earns you Fan.Fare, which you can redeem for items from your star. Don't see anything you like? <a href="">Trade it up for Pay.So!</a>
                  </p>
                  <br />
                  <p align="center">
                    <input type="submit" value="Redeem Fan.Fare" class="button button2" />
                  </p>
                </div>
                <!-- /column_single -->
              </div>
              <!-- /popBoxSingle -->
            </div>
            <!-- /fanFare -->          
          </div>
          <!-- /fanFare -->
        </div>
        <!-- /fanBox -->
        <div id="saysoBox">
        	<div id="" class="sayso">
          	<a href="#" class="navLink"><span class="hidden">$ay.$so</span></a>
            
            <div id="_saySoCurrency" class="popBoxContent">
              <div class="popBoxSingle">
                <div class="column_single">
                	<div class="toggleNav">
                  	<ul>
                    	<li class="listDivider"></li>
                    	<li class="toggle_payso"><a href="#" class="toggleLink">Pay.So</a></li>
                    	<li class="listDivider"></li>
                      <li class="toggle_sayso"><a href="#" class="toggleLink">Say.So</a></li>
                    	<li class="listDivider"></li>
                    </ul>
                  </div><!-- /toggleNav -->
                  <div class="toggleElement" id="toggle_payso">
                  	<h3 align="center"><img src="images/icon_payso.png" /> You Have <strong>5 Pay.So</strong></h3>
                    
                      <div class="columnContent columnContentBG" style="width: auto; margin: 10px 5px;">
                        <p align="center">The most popular thing others are earning with about 5 Pay.So is:<br />
                        <strong>A hilarious photo of a laughing horse</strong></p>
                      </div><!-- /columnContent -->
                    <p align="center">
                    	<img src="images/img_fanfarePrize.jpg" alt="" class="imgBorder" />
                    </p>
                    <div class="columnContentBubble">
                    	<p>See what else you can do with your <a href="">Pay.So &raquo;</a></p>
                    </div><!-- /columnContentBubble -->
                    <br />
                    <div class="columnContent">
											<p align="center">
                      The best way to earn more Pay.So is participating in polls and surveys from Say.So partners. And more Pay.So means more real-world goods.
                      </p>                    	
                      <br />
                      <p align="center">
                        <input type="submit" value="Earn More Pay.So" class="button button2" />
                      </p>
                    </div>
                  </div><!-- /toggleElement -->
                  <div class="toggleElement" id="toggle_sayso">
                  	<h3 align="center"><img src="images/icon_sayso.png" /> You Have <strong>2,050 Say.So</strong></h3>
                    <div class="columnContentBubble" style="margin: 10px">
                    	<p align="center">That makes you an <strong>Expert</strong><br />
                      <em>Next stop: Maven</em></p>
                    </div><!-- /columnContentBubble -->
                    
                    <table cellpadding="0" cellspacing="0" border="0" class="userRank">
                    <tr class="odd">
                      <td class="rank">47</td>
                      <td class="pic"><img src="images/img_user.jpg" /></td>
                      <td class="name">John Doe</td>
                      <td class="score">2060</td>
                    </tr>
                    <tr class="eve">
                      <td class="rank">48</td>
                      <td class="pic"><img src="images/img_user.jpg" /></td>
                      <td class="name">Jane Smith</td>
                      <td class="score">2055</td>
                    </tr>
                    <tr id="user" class="odd">
                      <td class="rank">49</td>
                      <td class="pic"><img src="images/img_user.jpg" /></td>
                      <td class="name">John Thompson</td>
                      <td class="score">2050</td>
                    </tr>
                    <tr class="even">
                      <td class="rank">50</td>
                      <td class="pic"><img src="images/img_user.jpg" /></td>
                      <td class="name">Michael Hemmingway</td>
                      <td class="score">2045</td>
                    </tr>
                    <tr class="odd">
                      <td class="rank">51</td>
                      <td class="pic"><img src="images/img_user.jpg" /></td>
                      <td class="name">Susan Murphy</td>
                      <td class="score">2040</td>
                    </tr>
                  </table>
                  <br />
                  <div class="columnContent">
                  	<p align="center">Say.So is your measure of advancement in the Say.So community. The fastest way to earn more Say.So is participating in polls and surveys.</p>
                  </div><!-- /columnContent -->
                  
                  <br />
                      <p align="center">
                        <input type="submit" value="Earn More Say.So" class="button button2" />
                      </p>
                    
                  </div><!-- /toggleElement -->
                  
                </div>
                <!-- /column_single -->
              </div>
              <!-- /popBoxSingle -->
            </div>
            <!-- /_saySoCurrency -->
            
          </div><!-- /saySo -->
        </div>
        <!-- /saysobox -->
      </div>
      <!-- /nav_user -->
    </div>
    <!-- /mainContent -->
  </div>
  <!-- /contain -->
</section>
