<? if (count($this->notesRemainingPools)) { ?>
	<br /><br />
	Notes Remaining (Current Balance)
	<table border=1 cellpadding=2 cellspacing=0>
		<thead>
			<tr>
				<? for ($i=0 ; $i <= max(array_keys($this->notesRemainingPools)) ; $i++) { ?>
					<td><?= ($i*500) ?>-<?= ($i*500)+499 ?></td>
				<? } ?>
			</tr>
		</thead>
		<tbody>
			<tr>
				<? for ($i=0 ; $i <= max(array_keys($this->notesRemainingPools)) ; $i++) { ?>
					<td><?= (isset($this->notesRemainingPools[$i]) ? $this->notesRemainingPools[$i] : "&nbsp;") ?></td>
				<? } ?>
			</tr>
		</tbody>
	</table>
	<script type="text/javascript">
		var chart1; // globally available
		$SQ(document).ready(function() {
			chart1 = new Highcharts.Chart({
				chart: {
					renderTo: 'notes-remaining',
					type: 'column'
				},
				title: {
					text: 'Notes Remaining (Current Balance)'
				},
				xAxis: {
					categories: [
						<? for ($i=0 ; $i <= max(array_keys($this->notesRemainingPools)) ; $i++) { ?>
							<?= ($i ? "," : "") ?>
							'<?= ($i*500) ?>-<?= ($i*500)+499 ?>'
						<? } ?>
					]
				},
				yAxis: {
					title: {
						text: 'Number of Users'
					}
				},
				series: [{
					name: 'Users',
					data: [
						<? for ($i=0 ; $i <= max(array_keys($this->notesRemainingPools)) ; $i++) { ?>
							<?= ($i ? "," : "") ?>
							<?= (isset($this->notesRemainingPools[$i]) ? $this->notesRemainingPools[$i] : '0') ?>
						<? } ?>

					]
				}]
			});
		});
	</script>
	<div id="notes-remaining" style="margin-bottom: 20px;"></div>
<? } ?>
<? if (count($this->notesTotalPools)) { ?>
	<br /><br />
	Lifetime Notes Earned (* calculated from current chops balance)
	<table border=1 cellpadding=2 cellspacing=0>
		<thead>
			<tr>
				<? for ($i=0 ; $i <= max(array_keys($this->notesTotalPools)) ; $i++) { ?>
					<td><?= ($i*500) ?>-<?= ($i*500)+499 ?></td>
				<? } ?>
			</tr>
		</thead>
		<tbody>
			<tr>
				<? for ($i=0 ; $i <= max(array_keys($this->notesTotalPools)) ; $i++) { ?>
					<td><?= (isset($this->notesTotalPools[$i]) ? $this->notesTotalPools[$i] : "&nbsp;") ?></td>
				<? } ?>
			</tr>
		</tbody>
	</table>
	<script type="text/javascript">
		var chart2; // globally available
		$SQ(document).ready(function() {
			chart2 = new Highcharts.Chart({
				chart: {
					renderTo: 'notes-total',
					type: 'column'
				},
				title: {
					text: 'Lifetime Notes Earned (* calculated from current chops balance)'
				},
				xAxis: {
					categories: [
						<? for ($i=0 ; $i <= max(array_keys($this->notesTotalPools)) ; $i++) { ?>
							<?= ($i ? "," : "") ?>
							'<?= ($i*500) ?>-<?= ($i*500)+499 ?>'
						<? } ?>
					]
				},
				yAxis: {
					title: {
						text: 'Number of Users'
					}
				},
				series: [{
					name: 'Users',
					data: [
						<? for ($i=0 ; $i <= max(array_keys($this->notesTotalPools)) ; $i++) { ?>
							<?= ($i ? "," : "") ?>
							<?= (isset($this->notesTotalPools[$i]) ? $this->notesTotalPools[$i] : '0') ?>
						<? } ?>

					]
				}]
			});
		});
	</script>
	<div id="notes-total" style="margin-bottom: 20px;"></div>
<? } ?>
<? if (count($this->notesSpentPools)) { ?>
	<br /><br />
	Lifetime Notes Spent (* calculated from current chops balance)
	<table border=1 cellpadding=2 cellspacing=0>
		<thead>
			<tr>
				<? for ($i=0 ; $i <= max(array_keys($this->notesSpentPools)) ; $i++) { ?>
					<td><?= ($i*500) ?>-<?= ($i*500)+499 ?></td>
				<? } ?>
			</tr>
		</thead>
		<tbody>
			<tr>
				<? for ($i=0 ; $i <= max(array_keys($this->notesSpentPools)) ; $i++) { ?>
					<td><?= (isset($this->notesSpentPools[$i]) ? $this->notesSpentPools[$i] : "&nbsp;") ?></td>
				<? } ?>
			</tr>
		</tbody>
	</table>
	<script type="text/javascript">
		var chart3; // globally available
		$SQ(document).ready(function() {
			chart3 = new Highcharts.Chart({
				chart: {
					renderTo: 'notes-spent',
					type: 'column'
				},
				title: {
					text: 'Lifetime Notes Spent (* calculated from current chops balance)'
				},
				xAxis: {
					categories: [
						<? for ($i=0 ; $i <= max(array_keys($this->notesSpentPools)) ; $i++) { ?>
							<?= ($i ? "," : "") ?>
							'<?= ($i*500) ?>-<?= ($i*500)+499 ?>'
						<? } ?>
					]
				},
				yAxis: {
					title: {
						text: 'Number of Users'
					}
				},
				series: [{
					name: 'Users',
					data: [
						<? for ($i=0 ; $i <= max(array_keys($this->notesSpentPools)) ; $i++) { ?>
							<?= ($i ? "," : "") ?>
							<?= (isset($this->notesSpentPools[$i]) ? $this->notesSpentPools[$i] : '0') ?>
						<? } ?>

					]
				}]
			});
		});
	</script>
	<div id="notes-spent" style="margin-bottom: 20px;"></div>
<? } ?>
