<?= $this->doctype() . PHP_EOL ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Say.So | App</title>
		<?= $this->headLink() . PHP_EOL ?>
		<?= $this->headScript() . PHP_EOL ?>
	</head>
	<body>
		<div id="modal-window" class="modal-window" style="display: none;"></div>
		<div id="wrapper">
			<h1 class="title">Say.So App</h1>
			<?= $this->partial('partials/user-login.phtml', 'default') ?>
			<br />
			<?= $this->layout()->content ?>
		</div>
	</body>
</html>