<?= $this->doctype() . PHP_EOL ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>SaySo | App</title>
        <?= $this->headLink() . PHP_EOL ?>
        <?= $this->headScript() . PHP_EOL ?>
    </head>
    <body>
        <div id="wrapper">
            <h1 class="title">SaySo App</h1>
            <br />
            <?= $this->layout()->content ?>
        </div>
    </body>
</html>