<div class="sb_header">
	<a href="http://www.saysollc.com" target="_blank"><img src="//<?= BASE_DOMAIN ?>/images/movie/logo_movie.png" alt="Movie Say.So" /></a>
</div><!-- .sb_header -->
<div class="sb_tabs">
	<ul>
		<li><a href="#about_tabs_1">About</a></li>
		<li><a href="#about_tabs_2">Help</a></li>
		<li><a href="#about_tabs_3">FAQs</a></li>
		<li><a href="#about_tabs_4">Feedback</a></li>
		<? if ($this->show_testing_function) { ?>
			<li><a href="#about_tabs_5">Testing</a></li>
		<? } ?>
	</ul>
	<div id="about_tabs_1" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">About Say.So</h2>
			<p>What is Say.So? Say.So is where <em>your</em> "say so" has value. This all started because we had been duped. Enticed into joining research panels with the promise that our opinions would matter, and that our input would be reflected in new or improved products. Instead, what we got was mailboxes filled with irrelevant surveys, points systems that offered very little reward, and no other way to demonstrate that we are mavens who should be revered.</p>
			<p>Say.So's mission is to give you -- consumers, fans, brand acolytes, pundits -- an elegant way to more intimately connect with your favorite brands and affinities. In return, these companies learn how best to serve you, their customer. But, for this to truly mean something, the experience needs to be worthwhile.</p>
			<p>Say.So's experience is unique in that it is a browser application, not a web page, so interacting with it doesn't require you to leave what you are doing. It's there when you are ready and keeps you notified of new surveys, content and rewards. The app offers a variety of surveys and polls, but also powers activities that are intrinsically motivating – quests, trivia... These test your mettle. Some are available to you out of the gate, but others need to be earned by leveling up or demonstrating your unique knowledge.</p>
			<p>The more you participate, the more you gain, earning both experience points and currency points. Experience points are the currency of influence, earned by sharing your experience, expertise and opinion. These determine your status in the community, and reaching higher levels separates you as someone to be heard. Currency points are almost as good as cash and can be redeemed for a variety of unique and only available to you merchandise.</p>
			<p>Say.So. <em>What's yours?</em></p>
			<br />
			<p style="margin: 0; float: right;">
				<small>
					<a href="http://<?= BASE_DOMAIN ?>/docs/movie/Say.So_Privacy_Policy.pdf" target="_new">Privacy Policy</a>&nbsp;|&nbsp;
					<a href="http://<?= BASE_DOMAIN ?>/docs/movie/Say.So_Rewards_Rules.pdf" target="_new">Rewards Rules</a>&nbsp;|&nbsp;
					<a href="http://<?= BASE_DOMAIN ?>/docs/movie/Say.So_App_EULA.pdf" target="_new">EULA</a>
				</small>
			</p>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_1 -->
	<div id="about_tabs_2" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">Need Help?</h2>
			<p>We designed the steps below to help you get oriented with the Say.So Snakkle Bar. If you find you need additional help, feel free to <a href="mailto:snakkle@say.so">contact us</a><? //<span class="sb_theme_textHighlight" id="onboard_tabs_5" style="cursor: pointer;">contact us</span>?>.</p>
			<div class="sb_tabs">
				<ul>
					<li><a href="#onboard_tabs_1">Welcome!</a></li>
					<li><a href="#onboard_tabs_2">What Can I Do?</a></li>
					<li><a href="#onboard_tabs_3">What Do I Get?</a></li>
					<li><a href="#onboard_tabs_4">Get Started</a></li>
					<li style="display:none;"><a href="#onboard_tabs_5"> </a></li>
				</ul>

				<div id="onboard_tabs_1" class="sb_tabPane">
					<h3 class="sb_title" align="center" style="font-weight: bold; margin-bottom: 10px">Congratulations and Thank You!</h3>
					<h3>We designed the steps below to help you get oriented. If you find you need additional help, feel free to <a href="mailto:snakkle@say.so">contact us</a>.</h3>
					<p align="center"><big>By installing the Snakkle Say.So extension, you’ve achieved level 1, and earned 1000 Stars and 75 Snakkle Bucks.</big></p>
					<br />
					<ul class="sb_lineList">
						<li class="sb_img_chops"><strong class="sb_theme_textHighlight">"Cinestars"</strong> are the currency of influence. You earn them for sharing   your expertise, experience and opinion, and your <strong class="sb_theme_textHighlight">Cinebucks</strong> determine   your access to increasingly important levels of access and influence.</li>
						<li class="sb_img_cinebucks"><strong class="sb_theme_textHighlight">"Cinebucks"</strong> are almost as good as cash. Virtually everything you do earns you Snakkle Bucks, which can be redeemed for all manner of goodies from Snakkle.com. (<a class="sb_nav_element" rel="sb_popBox_rewards" href="/starbar/movie/rewards">see the Rewards Center</a>)</li>
					</ul>
				</div><!-- #tab_1 -->
				<div id="onboard_tabs_2" class="sb_tabPane">
					<h3 class="sb_title" align="center">Give Your Opinion, Share It and Earn!</h3>
					<p align="center">Your point of view and opinion are invaluable. Express yourself through fun polls and surveys, and earn points by taking fun quizzes.</p>
					<ul class="sb_lineList">
						<li class="sb_img_polls"><strong class="sb_theme_textHighlight">Polls</strong> are quick hits of opinion we’d like you to share. Answer as many or as few as you’d like, and for each one we’ll drop a little something in your Snakkle wallet.</li>
						<li class="sb_img_surveys"><strong class="sb_theme_textHighlight">Surveys</strong> are the big money opportunities. These are important efforts to gauge how we are doing, and we’ll make sure you are compensated accordingly.</li>
						<li class="sb_img_quizzes"><strong class="sb_theme_textHighlight">Spotlight - </strong> Challenge yourself and test your knowledge by taking fun quizzes, or share them to Facebook or Twitter, we'll compensate you with Snakkle Bucks and Stars. No purchase necessary. The more you participate the more you earn and the more you earn the bigger the rewards and discounts you get!</li>
					</ul>
				</div><!-- #tab_2 -->
				<div id="onboard_tabs_3" class="sb_tabPane">
					<h3 class="sb_title" align="center">Here's What You Get.</h3>
					<p align="center">Help us better serve your Snakkler needs and you’ll earn Snakkle Bucks, virtual currency redeemable for prizes and opportunities.</p>
					<ul class="sb_lineList">
						<li class="sb_img_prizes"><strong class="sb_theme_textHighlight">Great Prizes.</strong> Almost everything you do as a Super Snakkler earns you Snakkle Bucks. Use these to redeem prizes from the Rewards Center.<br /></li>
						<li class="sb_img_giveaways"><strong class="sb_theme_textHighlight">A Chance To Win A Prize Giveaways. </strong> Redeem your Snakkle Bucks for entry tokens for our giveaways. Buy as many entry tokens for each giveaway as you want and increase your odds of winning.</li>
					</ul>
				</div><!-- #tab_3 -->
				<div id="onboard_tabs_4" class="sb_tabPane">
					<h3 class="sb_title" align="center">Okay, Let’s Get Started!</h3>
					<p align="center" style="margin-top: 15px;"><a href="//<?= BASE_DOMAIN ?>/starbar/movie/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_profile-survey.png" alt="Take the Profile Survey" /></a><br /><strong>Completing the Profile Survey takes a minute, but we will reward you with a hefty amount of Snakkle Bucks and grant you automatic access to our giveaways.</strong></p>
					<br />
					<br />
					<h2 align="center">Already taken the Profile Survey?<br />Check out some quick-hit activities.</h2>
					<p align="center" style="margin-top: 10px;">
						<a href="//<?= BASE_DOMAIN ?>/starbar/movie/polls" class="sb_nav_element" rel="sb_popBox_polls"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_badge_polls.png" alt="Polls" style="margin: 0px 10px;" /></a>
						<a href="//<?= BASE_DOMAIN ?>/starbar/movie/surveys" class="sb_nav_element" rel="sb_popBox_surveys"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_badge_surveys.png" alt="Surveys" style="margin: 0px 10px;" /></a>
						<a href="//<?= BASE_DOMAIN ?>/starbar/movie/quiz" class="sb_nav_element" rel="sb_popBox_quizzes"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_badge_quizzes.png" alt="Quizzes" style="margin: 0px 10px;" /></a>
					</p>
				</div><!-- #tab_4 -->
				<div id="onboard_tabs_5" class="sb_tabPane">
					<p>
						<label><strong>Name</strong></label> <input type="text" />
					</p>
					<p>
						<label><strong>Email</strong></label> <input type="text" />
					</p>
					<p>
						<label><strong>Question</strong></label> <textarea rows="5"></textarea>
					</p>
					<p>
						<input type="submit" class="sb_theme_button" value="Send" />
					</p>
				</div><!-- #tab_5 -->
			</div><!-- .sb_tabs -->
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_2 -->
	<div id="about_tabs_3" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">FAQ</h2>
			<p><strong>What is Movie Say.So?</strong><br />
Movie Say.So is a way to directly influence the content seen on Snakkle.com. Members are rewarded by answering polls, participating in surveys, taking fun quizzes, and giving their opinion about Snakkle content. Members gain .Stars. (experience points) and .Snakkle Bucks. (currency). Snakkle Bucks can be redeemed for Snakkle rewards and "Entry Tokens" into Snakkle giveaways. (more…)</p>
<p><strong>Do I have to pay for anything? Is there any shipping & handling fees for prizes obtained or won?</strong><br />
No, this is completely free to you. The only thing we want you to do is participate. (more...)</p>
<p><strong>What are Cinestars used for?</strong><br />
Stars are the equivalent of experience points and determine your level of influence and involvement. Gaining Stars will increase your Snakkle Say.So level. (more…)</p>
<p><strong>What are Cinebucks used for?</strong><br />Snakkle Bucks are the currency you earn by participating in polls, answering surveys, and sharing your ideas. In fact, virtually everything you do in Snakkle Say.So will earn you Snakkle Bucks. These Snakkle Bucks can be exchanged for various prizes and Entry Tokens in the Reward Center. (more…)</p>
<p><strong>What are Entry Tokens?</strong><br />Entry Tokens are your way of entering prize giveaways. Users that have purchased an Entry Token with their Snakkle Bucks will be entered to win the giveaway. To view current giveaways. At the end of each giveaway period a prize will be given away to a user that has purchased an Entry Token for the giveaway. You can buy as many Entry Tokens as you want to increase your chance of winning. (more…)</p>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_3 -->
	<div id="about_tabs_4" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">Feedback</h2>
			<div id="sb_feedback_container"></div>
			<script src="//s3.amazonaws.com/getsatisfaction.com/javascripts/feedback-v2.js" type="text/javascript"></script>
			<script type="text/javascript" charset="utf-8">
				var $SQfeedbackWidgetOptions = {};
				$SQfeedbackWidgetOptions.display = "inline";
				$SQfeedbackWidgetOptions.container = "sb_feedback_container";
				$SQfeedbackWidgetOptions.company = "snakklesayso";
				$SQfeedbackWidgetOptions.style = "question";
				$SQfeedbackWidgetOptions.product = "snakklesayso_snakkle_sayso";
				$SQfeedbackWidgetOptions.limit = "5";
				$SQfeedbackWidgetOptions.width = "500px";
				$SQfeedbackWidgetOptions.height = "450px";
				var $SQfeedbackInterval = setInterval(function() { // Use interval to ensure that GS's JS is loaded
					if (
						typeof GSFN != 'undefined' &&
						typeof GSFN.feedback_widget != 'undefined' &&
						typeof GSFN.feedback_widget.prototype != 'undefined'
					) {
						clearInterval($SQfeedbackInterval);
						var $SQfeedbackWidget = new GSFN.feedback_widget($SQfeedbackWidgetOptions);
					}
				}, 200);
			</script>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_4 -->
	<? if ($this->show_testing_function) { ?>
		<div id="about_tabs_5" class="sb_tabPane">
			<div class="sb_scrollPane">
				<h2 class="sb_title">Top Secret Testing Functions</h2>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reset-surveys-and-polls?renderer=jsonp", success : function (r, s) {} })'>Reset surveys and polls</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reset-external?renderer=jsonp", success : function (r, s) {} })'>Reset Facebook and Twitter External accounts and username</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reset-notifications?renderer=jsonp", success : function (r, s) {} })'>Reset Notifications and User Creation Time</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reset-gamer?renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Reset Game info to just after install (1000 chops, 100 notes)</a></p>
				<p><a href="#" style="color: red;" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reset-all?renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  } })'>Reset this user to 'just created, just installed' state (i.e. All of the Above)</a></p>
				<br />
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_reward_category=profile&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing *the* profile survey</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_reward_category=premium&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing the primary survey (points only)</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_reward_category=standard&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing a regular survey (points only)</a></p><br />
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=poll&survey_reward_category=standard&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing a regular poll (points only)</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=poll&survey_reward_category=premium&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing a premium poll (points only)</a></p><br />
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=quiz&survey_reward_category=standard&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing a regular quiz (points only)</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=quiz&survey_reward_category=premium&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing a premium quiz (points only)</a></p>
				<p><a href="#" style="color: green;" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reward-notes?renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Receive 5000 notes</a></p>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_5 -->
	<? } ?>
</div><!-- .sb_tabs -->

<script language="javascript">
	$SQ('span#onboard_tabs_5').click(function(){
		$SQ("#about_tabs_2 .sb_tabs").tabs("select",4)
	});

	$SQ('#sb_popBox_about-saySo .sb_header').insertBefore('#sb_popBox_about-saySo .sb_popBoxInner');
</script>
