<div class="sb_header">
	<a href="http://www.saysollc.com" target="_blank"><img src="//<?= BASE_DOMAIN ?>/images/movie/logo_movie.png" alt="Movie Say.So" /></a>
</div><!-- .sb_header -->
<div class="sb_tabs">
	<ul>
		<li><a href="#about_tabs_1">About</a></li>
		<li><a href="#about_tabs_6">Bill of Rights</a></li>
		<li><a href="#about_tabs_2">Help</a></li>
		<li><a href="#about_tabs_3">FAQs</a></li>
		<li><a href="#about_tabs_4">Feedback</a></li>
		<? if ($this->show_testing_function) { ?>
			<li><a href="#about_tabs_5">Testing</a></li>
		<? } ?>
	</ul>
	<div id="about_tabs_1" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">About Say.So</h2>
			<p>What is Say.So? Say.So is where <em>your</em> "say so" has value. This all started because we had been duped. Enticed into joining research panels with the promise that our opinions would matter, and that our input would be reflected in new or improved products. Instead, what we got was mailboxes filled with irrelevant surveys, points systems that offered very little reward, and no other way to demonstrate that we are mavens who should be revered.</p>
			<p>Say.So's mission is to give you -- consumers, fans, brand acolytes, pundits -- an elegant way to more intimately connect with your favorite brands and affinities. In return, these companies learn how best to serve you, their customer. But, for this to truly mean something, the experience needs to be worthwhile.</p>
			<p>Say.So's experience is unique in that it is a browser application, not a web page, so interacting with it doesn't require you to leave what you are doing. It's there when you are ready and keeps you notified of new surveys, content and rewards. The app offers a variety of surveys and polls, but also powers activities that are intrinsically motivating – quests, trivia... These test your mettle. Some are available to you out of the gate, but others need to be earned by leveling up or demonstrating your unique knowledge.</p>
			<p>The more you participate, the more you gain, earning both experience points and currency points. Experience points are the currency of influence, earned by sharing your experience, expertise and opinion. These determine your status in the community, and reaching higher levels separates you as someone to be heard. Currency points are almost as good as cash and can be redeemed for a variety of unique and only available to you merchandise.</p>
			<p>Say.So. <em>What's yours?</em></p>
			<br />
			<p style="margin: 0; float: right;">
				<small>
					<a href="http://<?= BASE_DOMAIN ?>/docs/movie/Say.So_Privacy_Policy.pdf" target="_new">Privacy Policy</a>&nbsp;|&nbsp;
					<a href="http://<?= BASE_DOMAIN ?>/docs/movie/Say.So_Rewards_Rules.pdf" target="_new">Rewards Rules</a>&nbsp;|&nbsp;
					<a href="http://<?= BASE_DOMAIN ?>/docs/movie/Say.So_App_EULA.pdf" target="_new">EULA</a>
				</small>
			</p>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_1 -->
	<div id="about_tabs_2" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">Need Help?</h2>
			<p>We've designed the steps below to help you get oriented with Movie Say.So. If you find you need additional help, please don't hesitate to <a href="mailto:movie@say.so">contact us</a>.</p>
			<div class="sb_tabs">
				<ul>
					<li><a href="#onboard_tabs_1">Welcome!</a></li>
					<li><a href="#onboard_tabs_2">What Can I Do?</a></li>
					<li><a href="#onboard_tabs_3">What Do I Get?</a></li>
					<li><a href="#onboard_tabs_4">Get Started</a></li>
					<li style="display:none;"><a href="#onboard_tabs_5"> </a></li>
				</ul>

				<div id="onboard_tabs_1" class="sb_tabPane">
					<h3 class="sb_title" align="center" style="font-weight: bold; margin-bottom: 10px">Congratulations and Thank You!</h3>
					<h3>We designed the steps below to help you get oriented. If you find you need additional help, feel free to <a href="mailto:movie@say.so">contact us</a>.</h3>
					<p align="center"><big>By becoming a member of Movie Say.So, you've achieved level 1, and earned 1000 CineStars and 75 CineBucks.</big></p>
					<br />
					<ul class="sb_lineList">
						<li class="sb_img_chops"><strong class="sb_theme_textHighlight">"CineStars"</strong> are the currency of influence. You earn them for sharing your expertise, experience and opinion, and your <strong class="sb_theme_textHighlight">CineStars</strong> determine your access to increasingly important levels of access and influence.</li>
						<li class="sb_img_cinebucks"><strong class="sb_theme_textHighlight">"CineBucks"</strong> are almost as good as cash. Virtually everything you do earns you CineBucks, which can be redeemed for all manner of goodies. (<a class="sb_nav_element" rel="sb_popBox_rewards" href="//<?= BASE_DOMAIN ?>/starbar/movie/rewards">see the Rewards Center</a>)</li>
					</ul>
				</div><!-- #tab_1 -->
				<div id="onboard_tabs_2" class="sb_tabPane">
					<h3 class="sb_title" align="center">Give Your Opinion, Share It and Earn!</h3>
					<p align="center">Your point of view and opinion are invaluable. Express yourself through fun polls and surveys, and earn points by rating videos.</p>
					<ul class="sb_lineList">
						<li class="sb_img_polls"><strong class="sb_theme_textHighlight">Polls</strong> are quick hits of opinion we'd like you to share. Answer as many or as few as you'd like, and for each one we;ll drop a little something in your Movie Say.So wallet. Every day you'll get new polls to show off your movie knowledge so be sure to check back often.</li>
						<li class="sb_img_surveys"><strong class="sb_theme_textHighlight">Surveys</strong> are the big money opportunities. These are important efforts to gauge how we are doing, and we'll make sure you are compensated accordingly.</li>
						<li class="sb_img_quizzes"><strong class="sb_theme_textHighlight">Spotlight - </strong>Rate movie trailers and videos; share them to Facebook or Twitter and we'll compensate you with CineBucks and CineStars. No purchase necessary.</li>
					</ul>
				</div><!-- #tab_2 -->
				<div id="onboard_tabs_3" class="sb_tabPane">
					<h3 class="sb_title" align="center">Here's What You Get.</h3>
					<p align="center">Give us your opinion on movies , celebrities, and what's going on in Hollywood and you'll earn CineBucks, virtual currency redeemable for prizes and opportunities.</p>
					<ul class="sb_lineList">
						<li class="sb_img_prizes"><strong class="sb_theme_textHighlight">Great Prizes.</strong> Almost everything you do as a Say.So movie buff earns you CineBucks. Use these to redeem prizes from the Rewards Center that are geared to movie lovers like you.</li>
						<li class="sb_img_giveaways">You can also exchange your CineBucks for <strong class="sb_theme_textHighlight">entry tokens for our giveaways</strong>. Buy as many entry tokens for each giveaway as you want to increase your odds of winning.</li>
					</ul>
				</div><!-- #tab_3 -->
				<div id="onboard_tabs_4" class="sb_tabPane">
					<h3 class="sb_title" align="center">Okay, Let’s Get Started!</h3>
					<p align="center" style="margin-top: 15px;"><a href="//<?= BASE_DOMAIN ?>/starbar/movie/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_profile-survey.png" alt="Take the Profile Survey" /></a><br /><strong>Completing the Profile Survey takes a minute, but we will reward you with a hefty amount of CineBucks and grant you automatic access to our giveaways.</strong></p>
					<br />
					<br />
					<h2 align="center">Already taken the Profile Survey?<br />Check out some quick-hit activities.</h2>
					<p align="center" style="margin-top: 10px;">
						<a href="//<?= BASE_DOMAIN ?>/starbar/movie/polls" class="sb_nav_element" rel="sb_popBox_polls"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_badge_polls.png" alt="Polls" style="margin: 0px 10px;" /></a>
						<a href="//<?= BASE_DOMAIN ?>/starbar/movie/surveys" class="sb_nav_element" rel="sb_popBox_surveys"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_badge_surveys.png" alt="Surveys" style="margin: 0px 10px;" /></a>
						<a href="//<?= BASE_DOMAIN ?>/starbar/movie/spotlight" class="sb_nav_element" rel="sb_popBox_spotlight"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_badge_trailers.png" alt="Trailers" style="margin: 0px 10px;" /></a>
					</p>
				</div><!-- #tab_4 -->
				<div id="onboard_tabs_5" class="sb_tabPane">
					<p>
						<label><strong>Name</strong></label> <input type="text" />
					</p>
					<p>
						<label><strong>Email</strong></label> <input type="text" />
					</p>
					<p>
						<label><strong>Question</strong></label> <textarea rows="5"></textarea>
					</p>
					<p>
						<input type="submit" class="sb_theme_button" value="Send" />
					</p>
				</div><!-- #tab_5 -->
			</div><!-- .sb_tabs -->
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_2 -->
	<div id="about_tabs_3" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">FAQ</h2>
                        <p>
                                <strong>What is Movie Say.So?</strong><br />
                                Members of Movie Say.So are rewarded for their film fandom by answering polls, participating in surveys, and rating new and retro movie trailers. Members gain "CineStars" (experience points) and "CineBucks" (currency). CineBucks can be redeemed for rewards and "Entry Tokens" into giveaways.
                        <a href="http://bit.ly/KNaagZ" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Do I have to pay for anything? Is there any shipping & handling fees for prizes obtained or won?</strong><br />
                                No, this is completely free to you. The only thing we want you to do is participate.
                        <a href="http://bit.ly/KfqO67" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>What are CineStars used for?</strong><br />
                                CineStars are the equivalent of experience points and determine your level of influence and involvement. Gaining CineStars will increase your Movie Say.So level.
                        <a href="http://bit.ly/JU4l1U" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>What are CineBucks used for?</strong><br />
                                CineBucks are the currency you earn by participating in polls, answering surveys, and sharing your ideas. In fact, virtually everything you do in Movie Say.So will earn you CineBucks. CineBucks can be exchanged for various prizes and Entry Tokens in the Reward Center.
                        <a href="http://bit.ly/KfqV1v" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>What are Entry Tokens?</strong><br />
                                 Entry Tokens are your way of entering prize giveaways. Users that have purchased an Entry Token with their CineBucks will be entered to win the giveaway. At the end of each giveaway period a prize will be given away to a user that has purchased an Entry Token for the giveaway. You can buy as many Entry Tokens as you want to increase your chance of winning.
                        <a href="http://bit.ly/LxoojL" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Do you really give away the prizes?</strong><br />
                                YES! Every prize that is won will be shipped within 4-6 weeks. Users and fans of Movie Say.So will get the prizes for playing, not the CEO's nephew or cousin. At the end of each giveaway we will send out an email to all the Movie Say.So users, letting you know who the lucky player is.
                        <a href="http://bit.ly/KaKhtn" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>How do I get my prize?</strong><br />
                                When you win a prize we will contact you by email to get the information and mailing address needed to send the prize to you.
                        <a href="http://bit.ly/KMg55A" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Are there any geographic restrictions for playing??</strong><br />
                                Yes, you must reside in the USA to redeem points for prizes. Unfortunately, we cannot ship items out of the USA.
                        <a href="http://bit.ly/KMhcm3" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Do I have to play every day?</strong><br />
                                No, you do not have to play every day, but the more you play and participate, the more CineBucks you can earn to exchange for Entry Tokens and other prizes.
                        <a href="http://bit.ly/MAwFbx" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Can I stop playing at any time?</strong><br />
                                Yes, particpate as much (or as little) as you want, but remember, the more you play the better your chances of winning cool prizes.
                        <a href="http://bit.ly/L1nVHi" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>How long do the surveys / games take to complete?</strong><br />
                                Usually between 5 and 15 minutes. Generally, the longer the survey is, the more CineBucks you can earn.
                        <a href="http://bit.ly/HsvOXp" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>What if I stop a survey in the middle of taking it? Do I still get credit? Do I have to restart it?</strong><br />
                                Once you start a survey you must complete it in order to earn your CineStars and CineBucks.
                        <a href="http://bit.ly/LniMKG" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>How often can I get CineStars/CineBucks for sharing??</strong><br />
                                For details on sharing, click here
                        <a href="http://bit.ly/MdZRSy" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>What are you doing with the information you are collecting?</strong><br />
                                We use the opinions and information you give us to (a) provide your
collective say-so to movie studio, producer & director clients to
help inform their creative ideas for movies, marketing and other
movie-related content; and (b) provide say.so members with a better
Movie Say.So experience!
                        <a href="http://bit.ly/OvqzVf" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Can I trade my prize for another prize?</strong><br />
                                No, the prize you win, or redeem for, is the prize you get.
                        <a href="http://bit.ly/LniQtY" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Can I track the status of the orders I have redeemed/won?</strong><br />
                                You will be sent a confirmation of your redemption or win. The delivery time of your item depends on the type of item you have redeemed or won. If you feel like there is a problem with your order, please contact us at snakkle@say.so.
                        <a href="http://bit.ly/JJPBOh" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>How do you select the winner(s)s for drawings?</strong><br />
                                You must redeem your CineBucks for Entry Tokens to be entered in the giveaways. Winners will be chosen at random from all entrants.
                        <a href="http://bit.ly/Kv1628" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>I am missing CineStars or CineBucks!</strong><br />
                                For missing CineStars or CineBucks
                        <a href="http://bit.ly/L7nqLX" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>I have a question that is not included in this FAQ!</strong><br />
                                You can check <a href="http://bit.ly/L1obWE" target="_blank">HERE</a> to see if there is an answer to a question that is not included in this FAQ. If you don't see your question or answer, please feel free to send your question using the feedback section.
                        </p>
                        <p>
                                <strong>How do I contact someone?</strong><br />
                                We value our users feedback, concerns, and suggestions and want to hear from you. You can contact us by sending us feedback section of the bar, or by emailing us directly at movie@say.so. You can also use http://www.twitter.com/saysoapp or http://www.facebook.com/moviesayso to get in touch or send feedback.
                        <a href="http://bit.ly/KCKsgi" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Where can I find the official Reward and Giveaway rules?</strong><br />
                                Links to the current Rules, Terms and Conditions, and Privacy Policies are all located at the bottom of the 'Edit Profile' tab on the bar. You can also see them
                        <a href="http://bit.ly/Kv1k9i" target="_blank">here.</a>
                        </p>
                        <p>
                                <strong>How do I temporarily disable, or uninstall the Movie Say.So app?</strong><br />
                                Once registered, your account, CineBucks and content are always waiting for you, whether you have the app installed or not; but modern browsers are pretty slick now in letting us turn apps on and off without uninstalling them. You can leave Movie Say.So installed, and only activate it when you need it, or want to take advantage of a Movie Say.So offer, then deactivate it after you’re done. No more uninstalling and reinstalling! <a href="http://bit.ly/X0XyJO" target="_blank">Click here</a> link for further instructions on how to disable this app.
                        </p>
                        <p>
                                <strong>How do I remove the Movie Say.So browser app?</strong><br />
                                For Movie bar removal instructions...
                        <a href="http://bit.ly/MAxyAO" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>How do I link my Facebook or Twitter account?</strong><br />
                                You can check <a href="http://bit.ly/L7nnQk" target="_blank">HERE</a> for instructions on how to link your Facebook / Twitter account, or see below.
                        </p>
                        <ol>
                                <li>Click .Edit Profile.</li>
                                <li>Click to link your Twitter or Facebook account.</li>
                                <li>Allow access in order for the accounts to be linked.</li>
                        </ol>
                        <p>
                                <strong>How do I disconnect my Facebook / Twitter account from the Say.So bar?</strong><br />
                                You can check <a href="http://bit.ly/Lo1Y1W" target="_blank">HERE</a> for instructions on how to unlink your Facebook / Twitter account, or see below.
                        </p>
                        <p>
                                <strong>Facebook:</strong><br />
                        </p>
                        <ol>
                                <li>Log into Facebook.</li>
                                <li>Click on <em>Home</em> &gt; <em>Account Settings.</em></li>
                                <li>Click on <em>Apps</em>. You will see <em>Say.So Bar</em> listed here.</li>
                        </ol>
                        <p>
                                <strong>Twitter:</strong><br />
                        </p>
                        <ol>
                                <li>Log into Twitter.</li>
                                <li>Click on your name &gt; <em>Settings</em>.</li>
                                <li>Open the <em>Applications</em> tab and you will see the <em>Say.So Bar</em> listed here.</li>
                        </ol>
                        <br /><br />
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_3 -->
	<div id="about_tabs_4" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">Feedback</h2>
			<div id="sb_feedback_container"></div>
			<script type="text/javascript" charset="utf-8">
				$SQ.getScript("//s3.amazonaws.com/getsatisfaction.com/javascripts/feedback-v2.js", function() {
					sayso.evalInPageContext(function() {
						new GSFN.feedback_widget({
							display : "inline",
							container : "sb_feedback_container",
							company : "moviesayso",
							style : "question",
							product : "moviesayso_movie_sayso",
							limit : "5",
							width : "520px",
							height : "450px"
						});
					});
				});
			</script>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_4 -->
	<div id="about_tabs_6" class="sb_tabPane">
		<div class="sb_scrollPane">
		<div id="bill_of_rights">
			<h2 class="sb_title" >Say.So Member Bill of Rights</h2>

                               <div><p>In order to ensure members are openly and unequivocally made aware of the core values embodied by Say.So with which we imbue our member relations and product roadmap, we provide this Say.So Member Bill of Rights.
                      </p></div>
			<h3>(1) Say.So</h3>
                                <div><p>Above all else, members' say-so will be honored and exalted. Your influence, opinion and personal authority are the core reason for the existence of Say.So.
                        </p></div>
			<h3>(2) Consent - Unambiguous Opt-In</h3>
				<div><p>By agreeing to participate in a Say.So community you accept that from time to time anonymous usage, behavioral, and poll/survey data will be collected, but we will never collect personally identifiable or sensitive information without your explicit permission.
			</p></div>
			<h3>(3) Anonymity</h3>
				<div><p>
No personally identifiable information will be associated to your member account – ever. You will remain anonymous – what we know about you is what you agree to provide us. Period.
			</p></div>
			<h3>(4) Transparency</h3>
				 <div><p>
You have the right to know how Say.So uses your anonymous information and not see details buried deep in the "terms and conditions". Hence, this Bill of Rights, which will be posted in multiple, easily accessible places. We will also provide you several ways to provide feedback and input on how we're doing and hope you don’t hesitate to share your thoughts, concerns, opinions, suggestions.</p></div>
			<h3>(5) Privacy</h3>
				<div><p>
Say.So will keep all data you provide to us private – your email address, or personally identifiable info we may need to collect to send you rewards (e.g. name, physical
 address, phone number). This information will not be sold or given to third-parties. Not gonna happen.
			</p></div>
			<h3>(6) Fun</h3>
				<div><p>
It is a member's right to enjoy themselves, and to let Say.So know what is fun, relevant and interesting, and what is lame and boring (please be kind). Though Say.So will sometimes need to ask you to do a few boring things so we can pay the bills, Say.So will always ensure the product roadmap reflects more fun stuff than boring stuff. We're listening!
			</p></div>
			<h3>(7) Reward</h3>
				<div><p>
Say.So members have a right to be rewarded for their Say.So. That will be provided in the form of exclusive access and privileges, as well as through explicit rewards like redeemable points or simple cash.
			</p></div>

			<br /><br />
			</div><!-- /faq_outer -->
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_6 -->
	<? if ($this->show_testing_function) { ?>
		<div id="about_tabs_5" class="sb_tabPane sb_testingFunctions">
			<div class="sb_scrollPane">
				<h2 class="sb_title">Top Secret Testing Functions</h2>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reset-surveys-and-polls">Reset surveys and polls</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reset-external">Reset Facebook and Twitter External accounts and username</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reset-notifications">Reset Notifications and User Creation Time</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reset-gamer">Reset Game info to just after install (1000 chops, 100 notes)</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reset-all" style="color: red;">Reset this user to 'just created, just installed' state (i.e. All of the Above)</a></p>
				<br />
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_reward_category=profile">Simulate completing *the* profile survey</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_reward_category=premium">Simulate completing the primary survey (points only)</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_reward_category=standard">Simulate completing a regular survey (points only)</a></p><br />
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=poll&survey_reward_category=standard">Simulate completing a regular poll (points only)</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=poll&survey_reward_category=premium">Simulate completing a premium poll (points only)</a></p><br />
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reward-notes" style="color: green;">Receive 5000 notes</a></p>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_5 -->
	<? } ?>
</div><!-- .sb_tabs -->

<script language="javascript">
	$SQ('span#onboard_tabs_5').click(function(){
		$SQ("#about_tabs_2 .sb_tabs").tabs("select",4)
	});

	$SQ('#sb_popBox_about-saySo .sb_header').insertBefore('#sb_popBox_about-saySo .sb_popBoxInner');

	$SQ('.sb_testingFunctions a').on('click', function(e){
		e.preventDefault();
		$SQ.ajaxWithAuth( {
			url : $SQ(this).attr('href'),
			success : function(r) {
				if( r.game )
					$SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);
			}
		} );
	});
</script>
