	<div class="sb_header">
	<a href="http://www.saysollc.com" target="_blank"><img src="//<?= BASE_DOMAIN ?>/images/movie/logo_movie.png" alt="Movie Say.So" /></a>
	</div><!-- .sb_header -->
	<div class="sb_popBoxInner">
	<div class="sb_popContent">
		<div class="sb_tabs">
		<ul>
			<li><a href="#onboard_tabs_1">I'm In!</a></li>
			<li><a href="#onboard_tabs_2">What Can I Do?</a></li>
			<li><a href="#onboard_tabs_3">What Do I Get?</a></li>
			<li><a href="#onboard_tabs_4">Get Started</a></li>
		</ul>

		<div id="onboard_tabs_1" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Welcome!</h2>
			<h3>We've designed the steps below to help you get oriented with Movie Say.So. If you find you need additional help, please don't hesitate to <a href="mailto:movie@say.so">contact us</a>.</h3>
			<p align="center"><big>By becoming a member of Movie Say.So, you've achieved the level of "Extra", and you've also earned extra CineStars and CineBucks.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_chops"><strong class="sb_theme_textHighlight">"CineStars"</strong> show the level of influence you've gained by sharing your expertise, experience and opinion. As you gain more CineStars your access to higher levels of influence on Movie Say.so will grow.</li>
				<li class="sb_img_cinebucks"><strong class="sb_theme_textHighlight">"CineBucks"</strong>  are almost as good as cash. Virtually everything you do earns you CineBucks, which can be redeemed for all types of goodies from the Say.So <a class="sb_nav_element" rel="sb_popBox_rewards" href="/starbar/movie/rewards">Rewards Center</a>.</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_1 -->
		<div id="onboard_tabs_2" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Give Your Opinion, Share It and Earn!</h2>
			<p align="center"><big>Your point of view and opinion are invaluable. Express yourself through fun polls and surveys, and earn points by rating videos.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_polls"><strong class="sb_theme_textHighlight">Polls</strong> are quick hits of opinion we'd like you to share. Answer as many or as few as you'd like, and for each one we;ll drop a little something in your Movie Say.So wallet. Every day you'll get new polls to show off your movie knowledge so be sure to check back often.</li>
				<li class="sb_img_surveys"><strong class="sb_theme_textHighlight">Surveys</strong> are the big money opportunities. These are important efforts to gauge how we are doing, and we'll make sure you are compensated accordingly.</li>
				<li class="sb_img_quizzes"><strong class="sb_theme_textHighlight">Spotlight - </strong>Rate movie trailers and videos; share them to Facebook or Twitter and we'll compensate you with CineBucks and CineStars. No purchase necessary.</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_2 -->
		<div id="onboard_tabs_3" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Here's What You Get.</h2>
			<p align="center"><big>Give us your opinion on movies , celebrities, and what's going on in Hollywood and you'll earn CineBucks, virtual currency redeemable for prizes and opportunities.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_prizes"><strong class="sb_theme_textHighlight">Great Prizes.</strong> Almost Almost everything you do as a Say.So movie buff earns you CineBucks. Use these to redeem prizes from the Rewards Center that are gears to movie lovers like you.</li>
				<li class="sb_img_giveaways">You can also exchange your CineBucks for <strong class="sb_theme_textHighlight">entry tokens for our giveaways</strong>. Buy as many entry tokens for each giveaway as you want to increase your odds of winning.</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_3 -->

		<div id="onboard_tabs_4" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Okay, Let’s Get Started!</h2>
			<p align="center" style="margin-top: 15px;"><a href="//<?= BASE_DOMAIN ?>/starbar/movie/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_profile-survey.png" alt="Take the Profile Survey" /></a><br /><strong>Completing the Profile Survey takes a minute, but we will reward you with a hefty amount of CineBucks and grant you automatic access to our giveaways.</strong></p>
			<br />
			<br />
			<h2 align="center">Not ready to take the Profile Survey yet?  <br />Check out some quick-hit activities.</h2>
			<p align="center" style="margin-top: 10px;">
				<a href="//<?= BASE_DOMAIN ?>/starbar/movie/polls" class="sb_nav_element" rel="sb_popBox_polls"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_badge_polls.png" alt="Polls" style="margin: 0px 10px;" /></a>
				<a href="//<?= BASE_DOMAIN ?>/starbar/movie/surveys" class="sb_nav_element" rel="sb_popBox_surveys"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_badge_surveys.png" alt="Surveys" style="margin: 0px 10px;" /></a>
				<a href="//<?= BASE_DOMAIN ?>/starbar/movie/spotlight" class="sb_nav_element" rel="sb_popBox_spotlight"><img src="//<?= BASE_DOMAIN ?>/images/movie/img_badge_quizzes.png" alt="Spotlight" style="margin: 0px 10px;" /></a>
			</p>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_4 -->

		</div><!-- .sb_tabs -->
	</div><!-- .sb_popContent -->
	</div><!-- .sb_popBoxInner -->
