<div class="sb_tabs">
	<ul>
		<? if ($this->count_new_polls) { ?>
			<li><a href="#polls_tabs_1"><?= $this->count_new_polls ?> New!</a></li>
		<? } else { ?>
			<li><a href="#polls_tabs_1">New</a></li>
		<? } ?>
		<? if ($this->count_completed_polls || $this->count_disqualified_polls) { ?>
			<li><a href="#polls_tabs_2">Completed</a></li>
		<? } ?>
		<? if ($this->count_archived_polls) { ?>
			<li><a href="#polls_tabs_3">Archive</a></li>
		<? } ?>
	</ul>

	<div id="polls_tabs_1" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_polls.png" alt="Polls" />
		<p class="sb_tabHeader">
			Earn <strong class="sb_theme_textHighlight sb_tooltip" title="CineStars - are almost as good as cash and can be redeemed for goods in the Rewards Center.">250 Cinestars</strong> & <strong class="sb_theme_textHighlight sb_tooltip" title="CineBucks - determine your access to increasingly important levels of influence.">2 Cinebucks</strong> for each Poll you complete. Share with your friends to earn extra points and you’ll be that much closer to winning the big giveaway.</p>
		<div class="sb_scrollPane">

			<!-- BEGIN POLL BOX LANDING -->
			<? $this->displayPolls('new', $this->starbar) ?>
			<!-- END POLL BOX LANDING -->
		</div><!-- .sb_scrollPane -->
	</div><!-- #tabs_1 -->

	<? if ($this->count_completed_polls || $this->count_disqualified_polls) { ?>
		<div id="polls_tabs_2" class="sb_tabPane">
			<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_polls.png" alt="Polls" />
			<p class="sb_tabHeader">These are polls you've completed</p>
			<div class="sb_scrollPane">
				<ul class="sb_outlineList">
					<? $this->displayPolls('completed', $this->starbar) ?>
					<? $this->displayPolls('disqualified', $this->starbar) ?>
				</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tabs_2 -->
	<? } ?>

	<? if ($this->count_archived_polls) { ?>
		<div id="polls_tabs_3" class="sb_tabPane">
			<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_polls.png" alt="Polls" />
			<p class="sb_tabHeader">
				We'd still love your opinion on these archived polls, and you can still earn by completing them! Same deal &ndash; earn <strong class="sb_theme_textHighlight">Cinebucks</strong> &amp; <strong class="sb_theme_textHighlight"> Stars</strong> for each one you complete.
			</p>
			<div class="sb_scrollPane">

				<!-- BEGIN POLL BOX LANDING -->
				<? $this->displayPolls('archived', $this->starbar) ?>
				<!-- END POLL BOX LANDING -->
				<br />
				<? if ($this->count_new_polls) { ?>
					<p align="right"><a href="#" class="sb_nav_tabs sb_theme_button" rel="1"><span class="sb_theme_buttonArrow">Take a New Poll</span></a></p>
				<? } ?>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tabs_3 -->
	<? } ?>

</div><!-- .tabs -->
