<div id="sb_slideshow">
	<div class="sb_promoBG sb_promo_week1">
		<div class="sb_slide">
			<div class="sb_header">
				<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_giveaway.png" alt="Giveaway" />
			</div><!-- .sb_header -->

			<div class="sb_promo_details" style="width: 250px; top: 60px; left: 5px;">
				<p>
				<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_ticket-giveaway.png" alt="Ticket Giveaway" /><br />
				<big>Use your XX’s to buy tokens to enter the Giveaway – the more tokens you get the better your chances of winning!</big></p>
				<br />
				<p><a href="//<?= BASE_DOMAIN ?>/starbar/movie/rewards?chosen_good_id=first" class="" rel="sb_popBox_rewards">
				<img src="//<?= BASE_DOMAIN ?>/images/movie/img_get-your-tokens.png" alt="Get Your Tokens" />
				</a></p>
				
				<p><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="//<?= BASE_DOMAIN ?>/starbar/movie/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg">Profile Survey</a> to be eligible for the giveaways.</small></p>
			</div><!-- .sb_promo_details -->

		</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week1 -->
</div><!-- #sb_slideshow -->