<div id="sb_slideshow">
	<div class="sb_promoBG sb_promo_week1">
		<div class="sb_slide">
			<img id="promo_image_1" usemap="#promo_map_1" src="//<?= BASE_DOMAIN ?>/images/movie/img_promo_1.png" style="width: 533px; height: 297px;"><br>
			<map name="promo_map_1">
				<area shape="rect" coords="193,225,363,247" href="//<?= BASE_DOMAIN ?>/starbar/movie/rewards" class="sb_nav_element"  rel="sb_popBox_rewards"><!-- GET YOUR TOKENS -->
				<area shape="rect" coords="314,225,384,271" href="//<?= BASE_DOMAIN ?>/starbar/movie/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg"><!-- TAKE THE PROFILE SURVEY -->
				<area shape="rect" coords="197,273,356,295" class="sb_next" href="#"><!-- NEXT PROMO -->
			</map>
		</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week1 -->
	<div class="sb_promoBG sb_promo_week2">
		<div class="sb_slide">
			<img id="promo_image_2" usemap="#promo_map_2" src="//<?= BASE_DOMAIN ?>/images/movie/img_promo_2.png" style="width: 533px; height: 297px;"><br>
			<map name="promo_map_2">
				<area shape="rect" coords="193,225,363,247" href="//<?= BASE_DOMAIN ?>/starbar/movie/rewards" class="sb_nav_element"  rel="sb_popBox_rewards">
				<area shape="rect" coords="314,225,384,271" href="//<?= BASE_DOMAIN ?>/starbar/movie/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg"><!-- TAKE THE PROFILE SURVEY -->
				<area shape="rect" coords="197,273,356,295" class="sb_next" href="#">
			</map>
		</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week2 -->
	<!--
<div class="sb_promoBG sb_promo_3">
		<div class="sb_slide">
			<img id="promo_image_3" usemap="#promo_map_3" src="//<?= BASE_DOMAIN ?>/images/movie/img_promo_3.png" style="width: 518px; height: 312px;"><br>
			<map name="promo_map_3">
				<area shape="rect" coords="268,265,488,310" href="//<?= BASE_DOMAIN ?>/starbar/movie/rewards" class="sb_nav_element"  rel="sb_popBox_rewards">
				<area shape="rect" coords="0,265,203,290" class="sb_next" href="#">
			</map>
		</div>
	</div>-->
</div><!-- #sb_slideshow -->
