<div class="sb_tabs">
	<ul>
			<li><a href="#spotlight_tabs_1">Retro</a></li>
			<li><a href="#spotlight_tabs_2">In Release</a></li>
			<li><a href="#spotlight_tabs_3">Test Trailers</a></li>
	</ul>
	
	<div id="spotlight_tabs_1" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_spotlight.png" alt="Spotlight" />
		
		<div class="sb_scrollPane">
			<div class="sb_video_container" id="sb_video_container"></div>
			<div class="sb_spotlight-questions" id="sb_spotlight-q1">
				<h2>What&#39;s your Say.So on this trailer?</h2>
				<p id="individual_vid_title"></p>
			</div><!-- .sb_spotlight-questions -->
			
			<div id="sb_vid_question_phase1" class="sb_mv_questions_flow">
				<p class="inactive">How many thumbs up would you give the <span class="sb_sel_vid_title"></span> (not the movie) ?</p>
				
				<div class="sb_mv_questions_opts">
					<input type="radio" name="sb_rating" class="sb_rating" value="1" disabled="disabled">
						<div class="sb_rating_icon stars_one">
							<div class="icon"></div>
						</div>
					<input type="radio" name="sb_rating" class="sb_rating" value="2" disabled="disabled">
						<div class="sb_rating_icon stars_two">
							<div class="icon"></div>
						</div>
					<input type="radio" name="sb_rating" class="sb_rating" value="3" disabled="disabled">
						<div class="sb_rating_icon stars_three">
							<div class="icon"></div>
						</div>
					<input type="radio" name="sb_rating" class="sb_rating" value="4" disabled="disabled">
						<div class="sb_rating_icon stars_four">
							<div class="icon"></div>
						</div>
					<input type="radio" name="sb_rating" class="sb_rating" value="5" disabled="disabled">
						<div class="sb_rating_icon stars_five">
							<div class="icon"></div>
						</div>
				</div>
					
			</div>
			
			<div id="sb_vid_question_phase2" class="sb_mv_questions_flow">
				<p>Did you see the movie <span class="sb_sel_vid_title"></span></p>
				<div class="sb_mv_questions_opts">
					<input type="radio" name="sb_seen_or_not" id="sb_y" class="sb_seen_or_not" value="yes"> 
						<label class="sb_radio_text" for="sb_y">Yes</label>
					<input type="radio" name="sb_seen_or_not" id="sb_n" class="sb_seen_or_not" value="no">
						<label class="sb_radio_text" for="sb_n">No</label>
				</div>
			</div>
			
			<div id="sb_vid_question_final" class="sb_mv_questions_flow">
				<p>Congratulations! You earned <span class="hl">250 Cinesters</span> &amp; <span class="hl">2 Cinebucks</span></p>
				<div class="sb_final_info">
					<span class="txt">50% Thumbs Up</span>
					<span class="txt">25% Saw the Movie</span>
					<span class="txt">15% Thought The trailes was better than the movie</span>
				</div>
				<div class="sb_final_share">
					<div>
						<a class="sb_externalShare sb_externalShare_facebook" rel="sb_mini-cinebucks-reward_facebook" href="#"
							onclick="$SQ.openWindow('//www.facebook.com/dialog/feed?app_id=<?= urlencode($this->facebook_app_id) ?>&link=<?= urlencode($this->share_link) ?>&caption=<?= urlencode($this->facebook_share_caption) ?>&picture=<?= urlencode($this->facebook_share_image_url) ?>&redirect_uri=<?= urlencode($this->facebook_share_callback_url) ?>&name=<?= urlencode($this->facebook_title) ?>&description=<?= urlencode($this->facebook_description) ?>', 'sb_window_open', 'location=1,status=1,scrollbars=0,width=981,height=450'); return false;">
							<img src="//<?= BASE_DOMAIN ?>/images/generic/facebook-share-icon.png" alt="Facebook" />
						</a>
					</div>
					<div class="sb_externalShare sb_externalShare_twitter" rel="sb_mini-cinebucks-reward_twitter">
						<a class="twitter-share-button"
							data-related="<?= $this->twitter_share_related_users ?>"
							data-hashtags="<?= $this->twitter_share_hashtags ?>"
							data-via="<?= $this->twitter_share_via_user ?>"
							data-url="<?= $this->share_link ?>"
							data-text="<?= $this->twitter_share_text ?>"
							data-count="none"
							href="https://twitter.com/intent/tweet">
								<img src="//<?= BASE_DOMAIN ?>/images/generic/logo_twitter.png" alt="Twitter" />
						</a>
					</div>
					<div><span class="share_text">Share the results to earn extra points</span></div>
				</div>
			
			</div>
			
			<div class="sb_video_carousel">
				<div class="arrow_left"></div>
				<div class="scroll_content">
				
				<!--  Sample video thumbs  -->
				
					 <div class="line_group active">
						<div class="thumb first" id="A8ViCl9xMDA" title="The Clientele - I Can't Seem"><img src="http://img.youtube.com/vi/A8ViCl9xMDA/1.jpg" /></div>
						<div class="thumb" id="cWfhaRFUHZY" title="Brett Simpson Air Reverse"><img src="http://img.youtube.com/vi/cWfhaRFUHZY/1.jpg" /></div>
						<div class="thumb" id="E9muZAOhHag" title="Dirt Showdown"><img src="http://img.youtube.com/vi/E9muZAOhHag/1.jpg" /></div>
						<div class="thumb" id="YygroWtZbh4" title="Andra - nu plange iubirea mea"><img src="http://img.youtube.com/vi/YygroWtZbh4/1.jpg" /></div>
						<div class="thumb last" id="wmpygzjf40c" title="Lloras - Plan B"><img src="http://img.youtube.com/vi/wmpygzjf40c/1.jpg" /></div>
					 </div>
					 
					 <div class="line_group">
						<div class="thumb first" id="67CeZZ52zZw" title="Farukko - Holla Beba"><img src="http://img.youtube.com/vi/67CeZZ52zZw/1.jpg" /></div>
						<div class="thumb" id="owjl5xRhr4g" title="Florin Salam - Nebunia lui Salam"><img src="http://img.youtube.com/vi/owjl5xRhr4g/1.jpg" /></div>
						<div class="thumb" id="iolCLx7lJRc" title="Florin Salam - A venit nebunu de Salam"><img src="http://img.youtube.com/vi/iolCLx7lJRc/1.jpg" /></div>
						<div class="thumb" id="BR4K2lE31Iw" title="Florin Salam - Regina Reginelor"><img src="http://img.youtube.com/vi/BR4K2lE31Iw/1.jpg" /></div>
						<div class="thumb last" id="rm4Tvh8oOvE" title="Florin Salam - Are de unde"><img src="http://img.youtube.com/vi/rm4Tvh8oOvE/1.jpg" /></div>
					 </div>
					 
					 <div class="line_group">
						<div class="thumb first" id="3jE6gq4LQAU" title="Liviu Mititelu - Cand apari in fata mea"><img src="http://img.youtube.com/vi/3jE6gq4LQAU/1.jpg" /></div>
						<div class="thumb" id="cv23GGQUUeI" title="Liviu Mititelu - De trei zile stau si beau"><img src="http://img.youtube.com/vi/cv23GGQUUeI/1.jpg" /></div>
						<div class="thumb" id="a40_WmAWsIA" title="Liviu Guta - Ultima intalnire"><img src="http://img.youtube.com/vi/a40_WmAWsIA/1.jpg" /></div>
						<div class="thumb" id="NZX-84u00u8" title="Liviu & Giulia - Te privesc..."><img src="http://img.youtube.com/vi/NZX-84u00u8/1.jpg" /></div>
						<div class="thumb last" id="_KSyWS8UgA4" title="Cali - Yo te esperare"><img src="http://img.youtube.com/vi/_KSyWS8UgA4/1.jpg" /></div>
					 </div>
					 
					 <div class="line_group">
						<div class="thumb first" id="3o4S8QOeybs" title="Un acoperis deasupra capului REMASTERIZAT HD"><img src="http://img.youtube.com/vi/3o4S8QOeybs/1.jpg" /></div>
						<div class="thumb" id="4RE6iBY4SFQ" title="Buna!Ce faci? (2011)"><img src="http://img.youtube.com/vi/4RE6iBY4SFQ/1.jpg" /></div>
						<div class="thumb" id="ersJLrA9NQo" title="Stefan Hrusca - Nunta de flori"><img src="http://img.youtube.com/vi/ersJLrA9NQo/1.jpg" /></div>
						<div class="thumb" id="6h0VVQU1S6k" title="IUBITA MEA, SA NE-ARUNCAM IN VALURI - Vasile SEICARU"><img src="http://img.youtube.com/vi/6h0VVQU1S6k/1.jpg" /></div>
						<div class="thumb last" id="KTK8zPjnLd0" title="Asta seara dansam In familie"><img src="http://img.youtube.com/vi/KTK8zPjnLd0/1.jpg" /></div>
					 </div>
					 
					 <div class="line_group">
						<div class="thumb first" id="X5Xt3bH0d_Y" title="B.D. in alerta"><img src="http://img.youtube.com/vi/X5Xt3bH0d_Y/1.jpg" /></div>
						<div class="thumb" id="TT1hIsn-TzQ" title="B.D. la munte şi la mare REMASTERIZAT HD"><img src="http://img.youtube.com/vi/TT1hIsn-TzQ/1.jpg" /></div>
						<div class="thumb" id="pNxm2h0qee4" title="Schimb valutar 2008 FULL MOVIE"><img src="http://img.youtube.com/vi/pNxm2h0qee4/1.jpg" /></div>
						<div class="thumb" id="VFZ5aVTsN1Q" title="Binecuvantata fii, inchisoare (2002) - Full Movie - Bless You, Prison"><img src="http://img.youtube.com/vi/VFZ5aVTsN1Q/1.jpg" /></div>
						<div class="thumb last" id="LcJ7bOK7OnM" title="Terminus Paradis"><img src="http://img.youtube.com/vi/LcJ7bOK7OnM/1.jpg" /></div>
					 </div>
					 
				<!--  End Sample video thumbs  -->
				</div>
				<div class="arrow_right"></div>
			</div>
		</div>
		
		
		
	</div><!-- #tabs_1 -->
	
	<div id="spotlight_tabs_2" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_spotlight.png" alt="Spotlight" />
		<p class="sb_tabHeader">
			
		</p>
		<div class="sb_scrollPane">

		</div><!-- .sb_scrollPane -->
	</div><!-- #tabs_2 -->
	
	<div id="spotlight_tabs_3" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_spotlight.png" alt="Spotlight" />
		<p class="sb_tabHeader">
			
		</p>
		<div class="sb_scrollPane">

		</div><!-- .sb_scrollPane -->
	</div><!-- #tabs_3 -->
	
	
</div><!-- .tabs -->
<script src="http://www.youtube.com/player_api"></script>
<script>
/* On Document Ready, first we hide the carousel according to the flow.  */

var player;
var defaults	=	{ 
		vid : 'HGekjZd5LPk'
};
var answers		=	{
	q1	:	false,
	q2	:	false,
	q3	:	false	
};

$('input.sb_rating').bind('change' , function(){
	
	answers.q1	=	$(this).val();

	if( answers.q1 ) {
		
		$('#sb_vid_question_phase1').hide();
		$('#sb_vid_question_phase2').show();
		
	}
});

$('input.sb_seen_or_not').bind('change', function(){
	answers.q2	=	$(this).val();

	if(answers.q2) {
		
		$('#sb_vid_question_phase1').hide();
		$('#sb_vid_question_phase2').hide();
		$('#sb_vid_question_final').show();
		$('.sb_video_carousel').show();
		
	}
});


function onYouTubePlayerAPIReady() {

  player = new YT.Player('sb_video_container', {
	  
    height: '390',
    width: '635',
    videoId: defaults.vid,
    events: {
        'onReady': onPlayerReady,
        'onStateChange': onPlayerStateChange
      },
      playerVars : {
        'iv_load_policy' :	3
      }
        
  });
  
  setTimeout(function(){
  	getVideoInfo(defaults.vid); 
  }, 700);
  
}

function onPlayerReady(event) {
	event.target.playVideo();
}

function onPlayerStateChange(event) {

	if(event.data == YT.PlayerState.ENDED){
		
		$('input.sb_rating').removeAttr('disabled');
		$('.sb_mv_questions_flow p').removeClass('inactive');
		
	}
	
}

$('.thumb').click(function(){

	answers.q1 	= 	false;
	answers.q2	=	false;
	answers.q3	=	false;

	$('.sb_sel_vid_title').empty().html("");
	$('#sb_vid_question_phase1').show();
	$('#sb_vid_question_phase2').hide();
	$('#sb_vid_question_final').hide();
	$('.sb_video_carousel').hide();
	
	var vid		=	$(this).attr('id');
    player.stopVideo();
    player.loadVideoById( vid );

    setTimeout(function(){
    	getVideoInfo(vid);
    }, 700);
   	 

});

$('.arrow_left, .arrow_right').bind('click', function(){

	var selected	=	false;
	var prev		=	false;
	var next		=	false;
	var dir 		= 	$(this).attr('class').split("_")[1];
	
	if($('.line_group.active').length > 0)					selected =	$('.line_group.active');
	if( $(selected[0].previousElementSibling).length > 0 ) 	prev	 = 	$(selected[0].previousElementSibling);
	if( $(selected[0].nextElementSibling).length > 0 ) 		next 	 = 	$(selected[0].nextElementSibling);
	
	switch(dir)
	{
		case 'left' :
			
				if( prev !== false ) {
					$('.line_group').hide();
					selected.removeClass('active');
					prev.addClass('active');
					$('.line_group.active').fadeIn("slow");
				}
			
		break;
			
		case 'right' :
			
				if( next !== false ) {
					$('.line_group').hide();
					selected.removeClass('active');
					next.addClass('active');
					$('.line_group.active').fadeIn("slow");
				}
				
		break;
	}
	
});

function getVideoInfo(video_id)
{
	$.getJSON('http://gdata.youtube.com/feeds/api/videos/'+video_id+'?v=2&alt=jsonc', function(d){

		if(d.data.title)
		{
			$('#individual_vid_title').html( d.data.title );
			$('.sb_sel_vid_title').html( d.data.title );
		}
		else
		{
			$('#individual_vid_title').empty().html("");
			$('.sb_sel_vid_title').empty().html("");
		}
		
	});	
}
</script>