<div class="sb_tabs">
	<ul>
			<li><a href="#spotlight_tabs_1">Retro</a></li>
			<li><a href="#spotlight_tabs_2">In Release</a></li>
			<li><a href="#spotlight_tabs_3">Test Trailers</a></li>
	</ul>
	
	<div id="spotlight_tabs_1" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_spotlight.png" alt="Spotlight" />
		
		<div class="sb_scrollPane">
			<div class="sb_video_container" id="sb_video_container">
			<!-- 
				<object width="635" height="390">
					<param name="movie" value="http://www.youtube.com/v/OXQDeyKaW-I?version=3&amp;hl=en_US"></param>
					<param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param>
					<embed id="video_source" src="http://www.youtube.com/v/OXQDeyKaW-I?version=3&amp;hl=en_US" type="application/x-shockwave-flash" width="635" height="390" allowscriptaccess="always" allowfullscreen="true"></embed>
				</object>
			 -->
			 
			</div>
			
			<div class="sb_spotlight-questions" id="sb_spotlight-q1">
				<h2>What's your Say.So on this trailer?</h2>
				<p>Caddyshack trailer (1980)</p>
			</div><!-- .sb_spotlight-questions -->
			
			<div class="sb_video_carousel">
				<div class="arrow_left"></div>
				<div class="scroll_content">
				
					 <div class="line_group active" id="l1">
						<div class="thumb first" id="A8ViCl9xMDA"><img src="http://img.youtube.com/vi/A8ViCl9xMDA/1.jpg" /></div>
						<div class="thumb" id="cWfhaRFUHZY"><img src="http://img.youtube.com/vi/cWfhaRFUHZY/1.jpg" /></div>
						<div class="thumb" id="E9muZAOhHag"><img src="http://img.youtube.com/vi/E9muZAOhHag/1.jpg" /></div>
						<div class="thumb" id="YygroWtZbh4"><img src="http://img.youtube.com/vi/YygroWtZbh4/1.jpg" /></div>
						<div class="thumb last" id="wmpygzjf40c"><img src="http://img.youtube.com/vi/wmpygzjf40c/1.jpg" /></div>
					 </div>
					 
					 <div class="line_group" id="l2">
						<div class="thumb first" id="67CeZZ52zZw"><img src="http://img.youtube.com/vi/67CeZZ52zZw/1.jpg" /></div>
						<div class="thumb" id="owjl5xRhr4g"><img src="http://img.youtube.com/vi/owjl5xRhr4g/1.jpg" /></div>
						<div class="thumb" id="iolCLx7lJRc"><img src="http://img.youtube.com/vi/iolCLx7lJRc/1.jpg" /></div>
						<div class="thumb" id="BR4K2lE31Iw"><img src="http://img.youtube.com/vi/BR4K2lE31Iw/1.jpg" /></div>
						<div class="thumb last" id="rm4Tvh8oOvE"><img src="http://img.youtube.com/vi/rm4Tvh8oOvE/1.jpg" /></div>
					 </div>
					 
					 <div class="line_group" id="l3">
						<div class="thumb first" id="3jE6gq4LQAU"><img src="http://img.youtube.com/vi/3jE6gq4LQAU/1.jpg" /></div>
						<div class="thumb" id="cv23GGQUUeI"><img src="http://img.youtube.com/vi/cv23GGQUUeI/1.jpg" /></div>
						<div class="thumb" id="a40_WmAWsIA"><img src="http://img.youtube.com/vi/a40_WmAWsIA/1.jpg" /></div>
						<div class="thumb" id="NZX-84u00u8"><img src="http://img.youtube.com/vi/NZX-84u00u8/1.jpg" /></div>
						<div class="thumb last" id="_KSyWS8UgA4"><img src="http://img.youtube.com/vi/_KSyWS8UgA4/1.jpg" /></div>
					 </div>
					 
				</div>
				<div class="arrow_right"></div>
			</div>
		</div>
		
		
		
	</div><!-- #tabs_1 -->
	
	<div id="spotlight_tabs_2" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_spotlight.png" alt="Spotlight" />
		<p class="sb_tabHeader">
			
		</p>
		<div class="sb_scrollPane">

		</div><!-- .sb_scrollPane -->
	</div><!-- #tabs_2 -->
	
	<div id="spotlight_tabs_3" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_spotlight.png" alt="Spotlight" />
		<p class="sb_tabHeader">
			
		</p>
		<div class="sb_scrollPane">

		</div><!-- .sb_scrollPane -->
	</div><!-- #tabs_3 -->
	
	
</div><!-- .tabs -->
<script src="http://www.youtube.com/player_api"></script>
<script>
var player;

function onYouTubePlayerAPIReady() {

  player = new YT.Player('sb_video_container', {
	  
    height: '390',
    width: '635',
    videoId: 'HGekjZd5LPk'
        
  });
  
}

$('.thumb').click(function(){
    player.stopVideo();
    player.loadVideoById( $(this).attr('id') );
});

$('.arrow_left, .arrow_right').bind('click', function(){

	var selected	=	false;
	var prev		=	false;
	var next		=	false;
	var dir 		= 	$(this).attr('class').split("_")[1];
	
	if($('.line_group.active').length > 0)					selected =	$('.line_group.active');
	if( $(selected[0].previousElementSibling).length > 0 ) 	prev	 = 	$(selected[0].previousElementSibling);
	if( $(selected[0].nextElementSibling).length > 0 ) 		next 	 = 	$(selected[0].nextElementSibling);
	
	switch(dir)
	{
		case 'left' :
			
				if( prev !== false ) {
					$('.line_group').hide();
					selected.removeClass('active');
					prev.addClass('active');
					$('.line_group.active').fadeIn("slow");
				}
			
			break;
			
		case 'right' :
			
				if( next !== false ) {
					$('.line_group').hide();
					selected.removeClass('active');
					next.addClass('active');
					$('.line_group.active').fadeIn("slow");
				}
				
			break;
	}
	
});
</script>