<div class="sb_tabs">
	<ul>
			<li><a href="#spotlight_tabs_1">Retro</a></li>
			<li><a href="#spotlight_tabs_2">In Release</a></li>
			<li><a href="#spotlight_tabs_3">Test Trailers</a></li>
	</ul>
	
	<div id="spotlight_tabs_1" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_spotlight.png" alt="Spotlight" />
		
		<div class="sb_scrollPane">
			<div class="sb_video_container" id="sb_video_container">
			<!-- 
				<object width="635" height="390">
					<param name="movie" value="http://www.youtube.com/v/OXQDeyKaW-I?version=3&amp;hl=en_US"></param>
					<param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param>
					<embed id="video_source" src="http://www.youtube.com/v/OXQDeyKaW-I?version=3&amp;hl=en_US" type="application/x-shockwave-flash" width="635" height="390" allowscriptaccess="always" allowfullscreen="true"></embed>
				</object>
			 -->
			 
			</div>
			
			<div class="sb_spotlight-questions" id="sb_spotlight-q1">
				<h2>What's your Say.So on this trailer?</h2>
				<p>Caddyshack trailer (1980)</p>
			</div><!-- .sb_spotlight-questions -->
			
			<div class="sb_video_carousel">
				<div class="arrow_left"></div>
				<div class="scroll_content">
				
					 <div class="line_group active">
						<div class="thumb first" id="A8ViCl9xMDA"></div>
						<div class="thumb" id="cWfhaRFUHZY"></div>
						<div class="thumb" id="E9muZAOhHag"></div>
						<div class="thumb" id="YygroWtZbh4"></div>
						<div class="thumb last" id="wmpygzjf40c"></div>
					 </div>
					 
					 <div class="line_group">
						<div class="thumb first" id="67CeZZ52zZw"></div>
						<div class="thumb" id="owjl5xRhr4g"></div>
						<div class="thumb" id="iolCLx7lJRc"></div>
						<div class="thumb" id="BR4K2lE31Iw"></div>
						<div class="thumb last" id="rm4Tvh8oOvE"></div>
					 </div>
					 
					 <div class="line_group">
						<div class="thumb first" id="3jE6gq4LQAU"></div>
						<div class="thumb" id="cv23GGQUUeI"></div>
						<div class="thumb" id="a40_WmAWsIA"></div>
						<div class="thumb" id="NZX-84u00u8"></div>
						<div class="thumb last" id="NZX-84u00u8"></div>
					 </div>
					 
				</div>
				<div class="arrow_right"></div>
			</div>
		</div>
		
		
		
	</div><!-- #tabs_1 -->
	
	<div id="spotlight_tabs_2" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_spotlight.png" alt="Spotlight" />
		<p class="sb_tabHeader">
			
		</p>
		<div class="sb_scrollPane">

		</div><!-- .sb_scrollPane -->
	</div><!-- #tabs_2 -->
	
	<div id="spotlight_tabs_3" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/movie/img_header_spotlight.png" alt="Spotlight" />
		<p class="sb_tabHeader">
			
		</p>
		<div class="sb_scrollPane">

		</div><!-- .sb_scrollPane -->
	</div><!-- #tabs_3 -->
	
	
</div><!-- .tabs -->
<script src="http://www.youtube.com/player_api"></script>
<script>
var player;

function onYouTubePlayerAPIReady() {

  player = new YT.Player('sb_video_container', {
	  
    height: '390',
    width: '635',
    videoId: 'HGekjZd5LPk'
        
  });
  
}

$('.thumb').click(function(){
    player.stopVideo();
    player.loadVideoById( $(this).attr('id') );
});

</script>