<div class="sb_header">
	<h2 class="sb_title">My Account</h2>
</div><!-- .sb_header -->
<div class="sb_scrollPane">
	<ul class="sb_lineList">
		<li>
			<h3 class="sb_title">Levels</h3>
			<div class="sb_userLevel_cycle">

				<div class="sb_userLevel_nav" id="sb_userLevel_prev"></div>

				<div class="sb_user_level_icons_container">

					<!-- all icons live inside of here, groups of 4 inside div class="sb_userLevelIcons_group" -->
					<!--
					The icon for the user's current level needs to be the active slide. Configurable in starbar-new.js
					Panels without the user's current level have 4 picks
					-->

					<div class="sb_userLevelIcons_group">

						<div class="sb_userLevelIcons sb_userLevel_earned"><div class="sb_userLevelImg" style="background-image: url(&quot;http://media.saysollc.com/media/hellomusic/level_2_sm.png&quot;);"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_earned"><div class="sb_userLevelImg" style="background-image: url(&quot;http://media.saysollc.com/media/hellomusic/level_3_sm.png&quot;);"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></p></div>

						<div class="sb_userLevelIcons sb_userLevel_earned"><div class="sb_userLevelImg" style="background-image: url(&quot;http://media.saysollc.com/media/hellomusic/level_2_sm.png&quot;);"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_earned"><div class="sb_userLevelImg" style="background-image: url(&quot;http://media.saysollc.com/media/hellomusic/level_3_sm.png&quot;);"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_earned"><div class="sb_userLevelImg" style="background-image: url(&quot;http://media.saysollc.com/media/hellomusic/level_2_sm.png&quot;);"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

					</div><!-- .sb_userLevelIcons_group -->

					<div class="sb_userLevelIcons_group">

						<div class="sb_userLevelIcons sb_userLevel_earned"><div class="sb_userLevelImg" style="background-image: url(&quot;http://media.saysollc.com/media/hellomusic/level_2_sm.png&quot;);"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_earned"><div class="sb_userLevelImg" style="background-image: url(&quot;http://media.saysollc.com/media/hellomusic/level_3_sm.png&quot;);"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_current"><div class="sb_userLevelImg" style="background-image: url(&quot;http://media.saysollc.com/media/hellomusic/level_1_b.png&quot;);"></div><p><strong class="sb_theme_textHighlight">Musician</strong><br><small class="sb_xpRequired">1000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_next"><div class="sb_userLevelImg"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_next"><div class="sb_userLevelImg"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

					</div><!-- .sb_userLevelIcons_group -->

					<div class="sb_userLevelIcons_group">
						<div class="sb_userLevelIcons sb_userLevel_next"><div class="sb_userLevelImg"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_next"><div class="sb_userLevelImg"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_next"><div class="sb_userLevelImg"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_next"><div class="sb_userLevelImg"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

						<div class="sb_userLevelIcons sb_userLevel_next"><div class="sb_userLevelImg"></div><p>Busker<br><small class="sb_xpRequired">10000</small></p></div>

					</div><!-- .sb_userLevelIcons_group -->

				</div><!-- .sb_user_level_icons_container -->

				<div class="sb_userLevel_nav" id="sb_userLevel_next"></div>

			</div><!-- .sb_userLevel_cycle -->
		</li>
		<li>
			<div class="sb_column5050">
				<div class="sb_column50">
					<h3 class="sb_title"><span class="sb_currency_title" data-currency-type="experience"></span></h3>
					<div class="sb_user-level-box">
						<span class="sb_user-level-star"></span>
						<div class="sb_progress_bar"><span class="sb_currency_percent" data-currency-type="experience"></span><span class="sb_progressBarValue sb_currency_balance" data-currency-type="experience"></span></div>
					</div><!-- .user-level-box -->
					<small>Level up at <span class="sb_currency_balance_next_level"></span> <span class="sb_currency_title" data-currency-type="experience"></span></small>
				</div><!-- .sb_column50 -->
				<div class="sb_column50">
					<div class="sb_alignLeft">
						<h3 class="sb_title"><span class="sb_currency_title" data-currency-type="redeemable"></span></h3>
						<div class="sb_user-points-box">
							<span class="sb_imgSnakkles"></span>
							<div class="sb_progress_bar"><span class="sb_currency_percent"></span><span class="sb_progressBarValue sb_currency_balance" data-currency-type="redeemable"></span></div>
						</div><!-- .user-points-box -->
					</div>
					<strong><a href="//<?= BASE_DOMAIN ?>/starbar/movie/rewards" class="sb_rewardsCenterLink sb_nav_element" rel="sb_popBox_rewards"><span class="sb_img_nextTriangle"></span>Rewards Center</a></strong>
				</div><!-- .sb_column50 -->
			</div><!-- .sb_column_5050 -->
		</li>
		<li>
			<h3 class="sb_title">My Purchases</h3>
			<div class="sb_user_purchases">
			</div>
		</li>
	</ul>
</div><!-- .sb_scrollPane -->
