<div class="sb_header">
	<a href="http://www.saysollc.com" target="_blank"><img src="//<?= BASE_DOMAIN ?>/images/social/logo_social.png" alt="Social Say.So" /></a>
</div><!-- .sb_header -->
<div class="sb_tabs">
	<ul>
		<li><a href="#about_tabs_1">About</a></li>
		<li><a href="#about_tabs_6">Bill of Rights</a></li>
		<li><a href="#about_tabs_2">Help</a></li>
		<li><a href="#about_tabs_3">FAQs</a></li>
		<li><a href="#about_tabs_4">Feedback</a></li>
		<? if ($this->show_testing_function) { ?>
			<li><a href="#about_tabs_5">Testing</a></li>
		<? } ?>
	</ul>
	<div id="about_tabs_1" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">About Say.So</h2>
			<p>What is Say.So? Say.So is where your "say so" has value. This all started because we had been duped. Enticed into joining research panels with the promise that our opinions would matter, and that our input would be reflected in new or improved products. Instead, what we got was mailboxes filled with irrelevant surveys, points systems that offered very little reward, and no other way to demonstrate that we are mavens who should be revered.</p>

<p>Say.So's mission is to give you -- consumers, fans, brand acolytes, pundits -- an elegant way to more intimately connect with your favorite brands and affinities. In return, these companies learn how best to serve you, their customer. But, for this to truly mean something, the experience needs to be worthwhile.</p>

<p>Say.So's experience is unique in that it is a browser application, not a web page, so interacting with it doesn't require you to leave what you are doing. It's there when you are ready and keeps you notified of new surveys, content and rewards. The app offers a variety of surveys and polls, but also powers activities that are intrinsically motivating – quests, trivia... These test your mettle. Some are available to you out of the gate, but others need to be earned by leveling up or demonstrating your unique knowledge.</p>

<p>The more you participate, the more you gain, earning both experience points and currency points. Experience points are the currency of influence, earned by sharing your experience, expertise and opinion. These determine your status in the community, and reaching higher levels separates you as someone to be heard. Currency points are almost as good as cash and can be redeemed for a variety of unique and only available to you merchandise.
</p>
			<p>Say.So. <em>What's yours?</em></p>
			<br />
			<p style="margin: 0; float: right;">
				<small>
					<a href="http://<?= BASE_DOMAIN ?>/docs/social/Say.So_Privacy_Policy.pdf" target="_new">Privacy Policy</a>&nbsp;|&nbsp;
					<a href="http://<?= BASE_DOMAIN ?>/docs/social/Say.So_Rewards_Rules.pdf" target="_new">Rewards Rules</a>&nbsp;|&nbsp;
					<a href="http://<?= BASE_DOMAIN ?>/docs/social/Say.So_App_EULA.pdf" target="_new">EULA</a>
				</small>
			</p>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_1 -->
	<div id="about_tabs_2" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">Need Help?</h2>
			<p>We designed the steps below to help you get oriented with Social Say.So. If you find you need additional help, feel free to <a href="mailto:social@say.so">contact us</a><? //<span class="sb_theme_textHighlight" id="onboard_tabs_5" style="cursor: pointer;">contact us</span>?>.</p>
			<div class="sb_tabs">
				<ul>
					<li><a href="#onboard_tabs_1">Welcome!</a></li>
					<li><a href="#onboard_tabs_2">What Can I Do?</a></li>
					<li><a href="#onboard_tabs_3">What Do I Get?</a></li>
					<li><a href="#onboard_tabs_4">Get Started</a></li>
					<li style="display:none;"><a href="#onboard_tabs_5"> </a></li>
				</ul>

				<div id="onboard_tabs_1" class="sb_tabPane">
					<h3 class="sb_title" align="center" style="font-weight: bold; margin-bottom: 10px">Congratulations and Thank You!</h3>
					<h3>We designed the steps below to help you get oriented with Social Say.So. If you find you need additional help, feel free to <a href="mailto:social@say.so">contact us</a>.</h3>
					<p align="center"><big>By becoming a member of Social Say.So, you've achieved the level "Spectator", and earned extra Social PaySos and SaySos.</big></p>
					<br />
					<ul class="sb_lineList">
						<li class="sb_img_chops"><strong class="sb_theme_textHighlight">"<big>"SaySos"</big>"</strong> is the currency of influence. You earn them for sharing your expertise, experience and opinion, and your<strong class="sb_theme_textHighlight"><big> SaySos</big></strong> determine your access to increasingly important levels of access and influence.</li>
						<li class="sb_img_cinebucks"><strong class="sb_theme_textHighlight">"PaySos"</strong> are almost as good as cash. Virtually everything you do earns you PaySos, which can be redeemed for all manner of goodies from Say.So. (<a class="sb_nav_element" rel="sb_popBox_rewards" href="//<?= BASE_DOMAIN ?>/starbar/social/rewards">see the Rewards Center</a>)</li>
					</ul>
				</div><!-- #tab_1 -->
				<div id="onboard_tabs_2" class="sb_tabPane">
					<h3 class="sb_title" align="center">Give Your Opinion, Share It and Earn!</h3>
					<p align="center">Your point of view and opinion are invaluable. Express yourself through fun polls and surveys, and earn Social SaySos and PaySos by completing Social Say.So missions.</p>
					<ul class="sb_lineList">
						<li class="sb_img_polls"><strong class="sb_theme_textHighlight">Polls</strong> are quick hits of opinion we’d like you to share. Answer as many or as few as you’d like, and for each one we’ll drop a little something in your Social Say.So wallet.</li>
						<li class="sb_img_surveys"><strong class="sb_theme_textHighlight">Surveys</strong> are the big money opportunities. These are important efforts to gauge how we are doing, and we’ll make sure you are compensated accordingly.</li>
						<li class="sb_img_quizzes"><strong class="sb_theme_textHighlight">Missions</strong> are multistage polls, quizzes and surveys that unlock exclusive badges, rewards and content.</li>
					</ul>
				</div><!-- #tab_2 -->
				<div id="onboard_tabs_3" class="sb_tabPane">
					<h3 class="sb_title" align="center">Here's What You Get.</h3>
					<p align="center">Give us your opinion on social and casual gaming and you'll earn Social PaySos, virtual currency redeemable for prizes and opportunities.</p>
					<ul class="sb_lineList">
						<li class="sb_img_prizes"><strong class="sb_theme_textHighlight">Great Prizes.</strong> Almost everything you do as a Social Say.So member earns you PaySos. Use these to redeem prizes from the Rewards Center.<br /></li>
						<li class="sb_img_giveaways"><strong class="sb_theme_textHighlight">A Chance To Win Prize Giveaways.</strong> Redeem your PaySos for entry tokens for our giveaways. Buy as many entry tokens for each giveaway as you want and increase your odds of winning.</li>
					</ul>
				</div><!-- #tab_3 -->
				<div id="onboard_tabs_4" class="sb_tabPane">
					<h3 class="sb_title" align="center">Okay, Let’s Get Started!</h3>
					<p align="center" style="margin-top: 15px;"><a href="//<?= BASE_DOMAIN ?>/starbar/social/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg"><img src="//<?= BASE_DOMAIN ?>/images/social/img_profile-survey.png" alt="Take the Profile Survey" /></a><br /><strong>Completing the Profile Survey takes a minute, but we will reward you with a hefty number of Social PaySos and grant you automatic access to our giveaways.</strong></p>
					<br />
					<br />
					<h2 align="center">Not ready to take the Profile Survey?<br />Check out some quick-hit activities.</h2>
					<p align="center" style="margin-top: 10px;">
						<a href="//<?= BASE_DOMAIN ?>/starbar/social/polls" class="sb_nav_element" rel="sb_popBox_polls"><img src="//<?= BASE_DOMAIN ?>/images/social/img_badge_polls.png" alt="Polls" style="margin: 0px 10px;" /></a>
						<a href="//<?= BASE_DOMAIN ?>/starbar/social/surveys" class="sb_nav_element" rel="sb_popBox_surveys"><img src="//<?= BASE_DOMAIN ?>/images/social/img_badge_surveys.png" alt="Surveys" style="margin: 0px 10px;" /></a>
						<a href="//<?= BASE_DOMAIN ?>/starbar/social/spotlight" class="sb_nav_element" rel="sb_popBox_spotlight"><img src="//<?= BASE_DOMAIN ?>/images/social/img_badge_trailers.png" alt="Trailers" style="margin: 0px 10px;" /></a>
					</p>
				</div><!-- #tab_4 -->
				<div id="onboard_tabs_5" class="sb_tabPane">
					<p>
						<label><strong>Name</strong></label> <input type="text" />
					</p>
					<p>
						<label><strong>Email</strong></label> <input type="text" />
					</p>
					<p>
						<label><strong>Question</strong></label> <textarea rows="5"></textarea>
					</p>
					<p>
						<input type="submit" class="sb_theme_button" value="Send" />
					</p>
				</div><!-- #tab_5 -->
			</div><!-- .sb_tabs -->
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_2 -->
	<div id="about_tabs_3" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">FAQ</h2>
                        <p>
                                <strong>What is Social Say.So?</strong><br />
                               Social Say.So is a way to get rewarded for your opinions on social and casual gaming.  Members gain "<strong class="sb_theme_textHighlight"><big>Social SaySos</big></strong>" (experience points) and "<strong class="sb_theme_textHighlight"><big>Social PaySos</big></strong>" (currency). <strong class="sb_theme_textHighlight"><big>Social PaySos</big></strong> can be redeemed for rewards and "Entry Tokens" into Social Say.So giveaways.
                        <a href="http://bit.ly/Rj3E6L" target="_blank">(more...)</a>
                        </p>
                        <p>
              <strong>Do I have to pay for anything? Is there any shipping & handling fees for prizes obtained or won?</strong><br />
                                No, this is completely free to you. The only thing we want you to do is participate.
                        <a href="http://bit.ly/Y5Xuu0" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>What are </strong><strong class="sb_theme_textHighlight"><big>Social SaySos</big></strong><strong> used for?</strong><br />
                                Social SaySos determine your level of influence and involvement. Gaining Social SaySos will increase your Social Say.So level. <a href="http://bit.ly/YrcnG7" target="_blank">(more...)</a>
                        </p>
                        <p>
                          <strong>What are </strong><strong class="sb_theme_textHighlight"><big>Social PaySos</big></strong><strong> used for?</strong><br />
                          PaySos are the currency you earn by participating in polls, answering surveys, and sharing your ideas. In fact, virtually everything you do in Social Say.So will earn you PaySos. These PaySos can be exchanged for various prizes and Entry Tokens in the Reward Center. <a href="http://bit.ly/U2UcPp" target="_blank">(more...)</a>
                        </p>
                        <p>
    <strong>What are Entry Tokens?</strong><br />
                                 Entry Tokens are your way of entering prize giveaways. Users that have purchased an Entry Token with their PaySos will be entered to win the giveaway. To view current giveaways click on the giveaway section of the bar.<br />At the end of each giveaway period a prize will be given away to a user that has purchased an Entry Token for the giveaway.<br />You can buy as many Entry Tokens as you want to increase your chance of winning.
                        <a href="http://bit.ly/U2UcPp" target="_blank">(more...)</a>
                        </p>
                        <p>
                          <strong>Do you really give away the prizes?</strong><br />
                                YES! Every prize that is won will be shipped within 4-6 weeks. Users and fans of Social Say.So will get the prizes for playing, not the CEO's nephew or cousin.<br />At the end of each giveaway we will send out an email to all the Social Say.So users, letting you know who the lucky player is.
                        <a href="http://bit.ly/U2UcPp">(more...)</a>
                        </p>
                        <p>
                                <strong>Are there any geographic restrictions for playing??</strong><br />
                                Yes, you must reside in the USA to redeem points for prizes. We cannot ship items out of the USA.
                        <a href="http://bit.ly/Sew4fr" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Do I have to play every day?</strong><br />
                                No, you do not have to play every day, but the more you play and participate, the more PaySos you can earn to exchange for Entry Tokens and other prizes.
                        <a href="http://bit.ly/SqCKse" target="_blank">(more...)</a>
                        </p>
                        <p>
                          <strong>Can I stop playing at any time?</strong><br />
                                Yes, particpate as much (or as little) as you want, but remember, the more you play the better your chances of winning cool prizes.
                        <a href="http://bit.ly/Qqzrl5" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>How long do the surveys / games take to complete?</strong><br />
                                Usually between 5 and 15 minutes. Generally, the longer the survey is, the more PaySos you can earn.
                        <a href="http://bit.ly/V3fi13" target="_blank">(more...)</a>
                        </p>
                        <p>
                          <strong>What if I stop a survey in the middle of taking it? Do I still get credit? Do I have to restart it?</strong><br />
                                Once you start a survey you must complete it in order to earn your PaySos.
                        <a href="http://bit.ly/10XcR6o" target="_blank">(more...)</a>
                        </p>
                        <p>
                    <strong>How often can I get SaySos/PaySos for sharing??</strong><br />
                                For details on sharing, click here
                        <a href="http://bit.ly/V3ht4y" target="_blank">(more...)</a>
                        </p>
                        <p>
                    <strong>What are you doing with the information you are collecting?</strong><br />
                               We use the opinions and information you give us to (a) provide your
collective say-so to gaming developers and companies to help inform their creative ideas for casual games, marketing and other social games related content; and (b) provide say.so members with a better Social Say.So experience!
                        <a href="http://bit.ly/10Xdpcy" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Can I invite other people to play?</strong><br />
                                Yes, you can invite friends through Facebook or Twitter. You can also invite friends using our “Send To A Friend” feature found in the settings section of the bar. You can earn additional PaySos by getting your friends to play.
                        <a href="http://bit.ly/Rj52Gv" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Can I trade my prize for another prize?</strong><br />
                                No, the prize you win or redeem is the prize you get.
                        <a href="http://bit.ly/UcqXvL" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Can I track the status of the orders I have redeemed/won?</strong><br />
                                You will be sent a confirmation of your redemption or win. The delivery time of your item depends on the type of item you have redeemed or won. If you feel like there is a problem with your order, please contact us at social@say.so.
                        <a href="http://bit.ly/ToC2Zx" target="_blank">(more...)</a>
                        </p>
                         <p>
                                <strong>What are Social Say.So missions?</strong><br />
                                Missions are multistage polls, quizzes and surveys that unlock exclusive badges, rewards and content.
                        <a href="http://bit.ly/X0SBkd" target="_blank">(more...)</a>
                        </p>
						<p>
                                <strong>What is the Promotion Period</strong><br />
                                <a href="http://bit.ly/ToCsPp" target="_blank">Click here</a> for detailed information on current, planned and previous giveaway information.
                        <a href="http://bit.ly/ToCsPp" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>How do you select the winner for drawings?</strong><br />
                                You must redeem your Social PaySos for Entry Tokens to be entered in the giveaways. Winners will be chosen at random from all entrants.
                        <a href="http://bit.ly/V0BYRy" target="_blank">(more...)</a>
                        </p>
                        <p>
                          <strong>I am missing Social SaySos or Social PaySos!</strong><br />
                                For missing SaySos or PaySos
                        <a href="http://bit.ly/Trd1gT" target="_blank">click here</a>
                        </p>
                        <p>
        <strong>I have a question that is not included in this FAQ!</strong><br />
                                You can check <a href="http://bit.ly/StGMOP" target="_blank">HERE</a> to see if there is an answer to a question that is not included in this FAQ. If you don't see your question or answer, please feel free to send your question using the feedback section.
                        </p>
                        <p>
                                <strong>How do I contact someone?</strong><br />
                                We value our users feedback, concerns, and suggestions and want to hear from you. You can contact us through the feedback section of the bar, or by emailing us directly at social@say.so. You can also use http://www.twitter.com/saysoapp or http://www.facebook.com/socialsayso to get in touch or send feedback.
                        <a href="http://bit.ly/SqCvgL" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>Where can I find the official Reward and Giveaway rules?</strong><br />
                                Links to the current Rules, Terms and Conditions, and Privacy Policies are all located at the bottom of the 'Edit Profile' tab on the bar.
                        <a href="http://bit.ly/TueCoo" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>How do I temporarily disable, or uninstall the Social Say.So app?</strong><br />
                                Once registered, your account, Social PaySos and content are always waiting for you, whether you have the app installed or not; but modern browsers are pretty slick now in letting us turn apps on and off without uninstalling them. You can leave Social Say.So installed, and only activate it when you need it, or want to take advantage of a Social Say.So offer, then deactivate it after you’re done. No more uninstalling and reinstalling! <a href="http://bit.ly/U2Wqyc" target="_blank">Click here</a> for further instructions on how to disable this app.
                        </p>
                        <p>
                                <strong>How do I remove the Social Say.So browser extension?</strong><br />
                                If you want to remove the app from your browser, here are instructions for each major browser type.  If you decide later to reinstall, use your original registration email and your PaySos, level progress and earning will be there where you left off! For removal instructions
                        <a href="http://bit.ly/V3ht4y" target="_blank">click here</a>.
                        </p>
                        <p>
                                <strong>How do I link my Facebook or Twitter account?</strong><br />
                                You can check <a href="http://bit.ly/V6wRNX" target="_blank">HERE</a> for instructions on how to link your Facebook / Twitter account, or see below.
                        </p>
                        <ol>
                                <li>Click "Edit Profile"</li>
                                <li>Click to link your Twitter or Facebook account.</li>
                                <li>Allow access in order for the accounts to be linked.</li>
                        </ol>
                        <p>
                                <strong>How do I disconnect my Facebook / Twitter account from the Say.So bar?</strong><br />
                                You can check <a href="http://bit.ly/Y62izt" target="_blank">HERE</a> for instructions on how to unlink your Facebook / Twitter account, or see below.
                        </p>
                        <p>
                                <strong>Facebook:</strong><br />
                        </p>
                        <ol>
                                <li>Log into Facebook.</li>
                                <li>Click on <em>Home</em> &gt; <em>Account Settings.</em></li>
                                <li>Click on <em>Apps</em>. You will see <em>Say.So app</em> listed here.</li>
                                <li>Click on the app and then <em>Remove App</em> in the top right area of the application info box.</li>
                        </ol>
                        <p>
                                <strong>Twitter:</strong><br />
                        </p>
                        <ol>
                                <li>Log into Twitter.</li>
                                <li>Click on your profile icon (top right part of your screen) &gt; <em>Settings</em>.</li>
                                <li>Open the <em>Applications</em> tab and you will see the <em>Say.So app</em> listed here.</li>
                                <li>Click on <em>Revoke Acess</em> to remove the app.</li>
                        </ol>
                        <br /><br />
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_3 -->
	<div id="about_tabs_4" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">Feedback</h2>
			<div id="sb_feedback_container"></div>
			<script type="text/javascript" charset="utf-8">
				$SQ.getScript("//s3.amazonaws.com/getsatisfaction.com/javascripts/feedback-v2.js", function() {
					sayso.evalInPageContext(function() {
						new GSFN.feedback_widget({
							display : "inline",
							container : "sb_feedback_container",
							company : "socialsayso",
							style : "question",
							product : "socialsayso_social_sayso",
							limit : "5",
							width : "520px",
							height : "450px"
						});
					});
				});
			</script>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_4 -->
	<div id="about_tabs_6" class="sb_tabPane">
		<div class="sb_scrollPane">
		<div id="bill_of_rights">
			<h2 class="sb_title" >Say.So Member Bill of Rights</h2>

                               <div><p>In order to ensure members are openly and unequivocally made aware of the core values embodied by Say.So with which we imbue our member relations and product roadmap, we provide this Say.So Member Bill of Rights.
                      </p></div>
			<h3>(1) Say.So</h3>
                                <div><p>Above all else, members' say-so will be honored and exalted. Your influence, opinion and personal authority are the core reason for the existence of Say.So.
                        </p></div>
			<h3>(2) Consent - Unambiguous Opt-In</h3>
				<div><p>By agreeing to participate in a Say.So community you accept that from time to time anonymous usage, behavioral, and poll/survey data will be collected, but we will never collect personally identifiable or sensitive information without your explicit permission.
			</p></div>
			<h3>(3) Anonymity</h3>
				<div><p>
No personally identifiable information will be associated to your member account – ever. You will remain anonymous – what we know about you is what you agree to provide us. Period.
			</p></div>
			<h3>(4) Transparency</h3>
				 <div><p>
You have the right to know how Say.So uses your anonymous information and not see details buried deep in the "terms and conditions". Hence, this Bill of Rights, which will be posted in multiple, easily accessible places. We will also provide you several ways to provide feedback and input on how we're doing and hope you don’t hesitate to share your thoughts, concerns, opinions, suggestions.</p></div>
			<h3>(5) Privacy</h3>
				<div><p>
Say.So will keep all data you provide to us private - your email address, or personally identifiable info we may need to collect to send you rewards (e.g. name, physical address, phone number). This information will not be sold or given to third-parties. Not gonna happen.
			</p></div>
			<h3>(6) Fun</h3>
				<div><p>
It is a member's right to enjoy themselves, and to let Say.So know what is fun, relevant and interesting, and what is lame and boring (please be kind). Though Say.So will sometimes need to ask you to do a few boring things so we can pay the bills, Say.So will always ensure the product roadmap reflects more fun stuff than boring stuff. We're listening!
			</p></div>
			<h3>(7) Reward</h3>
				<div><p>
Say.So members have a right to be rewarded for their Say.So. That will be provided in the form of exclusive access and privileges, as well as through explicit rewards like redeemable points or simple cash.
			</p></div>

			<br /><br />
			</div><!-- /faq_outer -->
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_6 -->
	<? if ($this->show_testing_function) { ?>
		<div id="about_tabs_5" class="sb_tabPane sb_testingFunctions">
			<div class="sb_scrollPane">
				<h2 class="sb_title">Top Secret Testing Functions</h2>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reset-surveys-and-polls">Reset surveys and polls</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reset-external">Reset Facebook and Twitter External accounts and username</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reset-notifications">Reset Notifications and User Creation Time</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reset-gamer">Reset Game info to just after install (1000 chops, 100 notes)</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reset-all" style="color: red;">Reset this user to 'just created, just installed' state (i.e. All of the Above)</a></p>
				<br />
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_reward_category=profile">Simulate completing *the* profile survey</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_reward_category=premium">Simulate completing the primary survey (points only)</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_reward_category=standard">Simulate completing a regular survey (points only)</a></p><br />
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=poll&survey_reward_category=standard">Simulate completing a regular poll (points only)</a></p>
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=poll&survey_reward_category=premium">Simulate completing a premium poll (points only)</a></p><br />
				<p><a href="//<?= BASE_DOMAIN ?>/api/test/reward-notes" style="color: green;">Receive 5000 notes</a></p>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_5 -->
	<? } ?>
</div><!-- .sb_tabs -->

<script language="javascript">
	$SQ('span#onboard_tabs_5').click(function(){
		$SQ("#about_tabs_2 .sb_tabs").tabs("select",4)
	});

	$SQ('#sb_popBox_about-saySo .sb_header').insertBefore('#sb_popBox_about-saySo .sb_popBoxInner');

	$SQ('.sb_testingFunctions a').on('click', function(e){
		e.preventDefault();
		$SQ.ajaxWithAuth( {
			url : $SQ(this).attr('href'),
			success : function(r) {
				if( r.game )
					$SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);
			}
		} );
	});
</script>
