	<div class="sb_header">
	<a href="http://www.saysollc.com" target="_blank"><img src="//<?= BASE_DOMAIN ?>/images/social/logo_social.png" alt="Social Say.So" /></a>
	</div><!-- .sb_header -->
	<div class="sb_popBoxInner">
	<div class="sb_popContent">
		<div class="sb_tabs">
		<ul>
			<li><a href="#onboard_tabs_1">I'm In!</a></li>
			<li><a href="#onboard_tabs_2">What Can I Do?</a></li>
			<li><a href="#onboard_tabs_3">What Do I Get?</a></li>
			<li><a href="#onboard_tabs_4">Get Started</a></li>
		</ul>

		<div id="onboard_tabs_1" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Welcome!</h2>
			<h3>We designed the steps below to help you get oriented. If you find you need additional help, feel free to <a href="mailto:social@say.so">contact us</a>.</h3>
			<p align="center"><big>By installing the Social Say.So extension, you've achieved the level "Spectator", and earned extra <span class="sb_img_chops">Social SaySos</span> and <span class="sb_img_chops">PaySos</span>.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_chops"><strong class="sb_theme_textHighlight">"Social SaySos"</strong> are the currency of influence. You earn them for sharing your expertise, experience and opinion, and your <span class="sb_img_chops">Social SaySos</span> determine your access to increasingly important levels of access and influence.</li>
				<li class="sb_img_cinebucks"><strong class="sb_theme_textHighlight">"Social PaySos"</strong> are almost as good as cash. Virtually everything you do earns you <span class="sb_img_chops">Social PaySos</span>, which can be redeemed for all manner of goodies from Say.So. (<a class="sb_nav_element" rel="sb_popBox_rewards" href="/starbar/social/rewards">see the Rewards Center</a>)</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_1 -->
		<div id="onboard_tabs_2" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Give Your Opinion, Share It and Earn!</h2>
			<p align="center"><big>Your point of view and opinion are invaluable. Express yourself through fun polls and surveys, and earn points by taking fun missions.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_polls"><strong class="sb_theme_textHighlight">Polls</strong> are quick hits of opinion we’d like you to share. Answer as many or as few as you’d like, and for each one we’ll drop a little something in your Say.so wallet.</li>
				<li class="sb_img_surveys"><strong class="sb_theme_textHighlight">Surveys</strong> are the big money opportunities. These are important efforts to gauge how we are doing, and we’ll make sure you are compensated accordingly.</li>
				<li class="sb_img_quizzes"><strong class="sb_theme_textHighlight">Spotlight - </strong> Challenge yourself and test your knowledge by taking fun missions, or share them to Facebook or Twitter. We'll compensate you with <span class="sb_img_chops">Social SaySos</span> and <span class="sb_img_chops">PaySos</span>. No purchase necessary.</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_2 -->
		<div id="onboard_tabs_3" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Here's What You Get.</h2>
			<p align="center"><big>Help us better serve your Social needs and you’ll earn <span class="sb_img_chops">Social PaySos</span>, virtual currency redeemable for prizes and opportunities.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_prizes"><strong class="sb_theme_textHighlight">Great Prizes.</strong> Almost everything you do as a Say.So social buff earns you <span class="sb_img_chops">Social PaySos</span>. Use these to redeem prizes from the Rewards Center.</li>
				<li class="sb_img_giveaways"><strong class="sb_theme_textHighlight">A Chance To Win Prize Giveaways. </strong> Redeem your <span class="sb_img_chops">Social PaySos</span> for entry tokens for our giveaways. Buy as many entry tokens for each giveaway as you want and increase your odds of winning.</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_3 -->

		<div id="onboard_tabs_4" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Okay, Let’s Get Started!</h2>
			<p align="center" style="margin-top: 15px;"><a href="//<?= BASE_DOMAIN ?>/starbar/social/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg"><img src="//<?= BASE_DOMAIN ?>/images/social/img_profile-survey.png" alt="Take the Profile Survey" /></a><br /><strong>Completing the Profile Survey takes a minute, but we will reward you with a hefty amount of <span class="sb_img_chops">Social PaySos</span> and grant you automatic access to our giveaways.</strong></p>
			<br />
			<br />
			<h2 align="center">Not ready to take the Profile Survey yet?  <br />Check out some quick-hit activities.</h2>
			<p align="center" style="margin-top: 10px;">
				<a href="//<?= BASE_DOMAIN ?>/starbar/social/polls" class="sb_nav_element" rel="sb_popBox_polls"><img src="//<?= BASE_DOMAIN ?>/images/social/img_badge_polls.png" alt="Polls" style="margin: 0px 10px;" /></a>
				<a href="//<?= BASE_DOMAIN ?>/starbar/social/surveys" class="sb_nav_element" rel="sb_popBox_surveys"><img src="//<?= BASE_DOMAIN ?>/images/social/img_badge_surveys.png" alt="Surveys" style="margin: 0px 10px;" /></a>
				<a href="//<?= BASE_DOMAIN ?>/starbar/social/spotlight" class="sb_nav_element" rel="sb_popBox_spotlight"><img src="//<?= BASE_DOMAIN ?>/images/social/img_badge_quizzes.png" alt="Spotlight" style="margin: 0px 10px;" /></a>
			</p>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_4 -->

		</div><!-- .sb_tabs -->
	</div><!-- .sb_popContent -->
	</div><!-- .sb_popBoxInner -->
