<div class="sb_tabs">
	<ul>
		<? if ($this->count_new_polls) { ?>
			<li><a href="#polls_tabs_1"><?= $this->count_new_polls ?> New!</a></li>
		<? } else { ?>
			<li><a href="#polls_tabs_1">New</a></li>
		<? } ?>
		<? if ($this->count_completed_polls || $this->count_disqualified_polls) { ?>
			<li><a href="#polls_tabs_2">Completed</a></li>
		<? } ?>
		<? if ($this->count_archived_polls) { ?>
			<li><a href="#polls_tabs_3">Archive</a></li>
		<? } ?>
	</ul>

	<div id="polls_tabs_1" class="sb_tabPane">
		<img src="//<?= BASE_DOMAIN ?>/images/social/img_header_polls.png" alt="Polls" />
		<p class="sb_tabHeader">
			Polls are a speedy and effective way to find out what you love about casual and social gaming. Each poll completed earns you <strong class="sb_theme_textHighlight sb_tooltip" title="Social PaySos - are almost as good as cash and can be redeemed for goods in the Rewards Center.">19 Social PaySos</strong> &amp; <strong class="sb_theme_textHighlight sb_tooltip" title="Social SaySo - determines your access to increasingly important levels of influence.">250 </strong><strong class="sb_theme_textHighlight sb_tooltip" title="Social SaySo - determines your access to increasingly important levels of influence.">Social SaySo</strong>. Gain bonus PaySos &amp; SaySo by sharing and tweeting your favorite polls, and look for special polls with point magnifiers.</p>
		<div class="sb_scrollPane">

			<!-- BEGIN POLL BOX LANDING -->
			<? $this->displayPolls('new', $this->starbar) ?>
			<!-- END POLL BOX LANDING -->
		</div><!-- .sb_scrollPane -->
	</div><!-- #tabs_1 -->

	<? if ($this->count_completed_polls || $this->count_disqualified_polls) { ?>
		<div id="polls_tabs_2" class="sb_tabPane">
			<img src="//<?= BASE_DOMAIN ?>/images/social/img_header_polls.png" alt="Polls" />
			<p class="sb_tabHeader">These are polls you've completed</p>
			<div class="sb_scrollPane">
				<ul class="sb_outlineList">
					<? $this->displayPolls('completed', $this->starbar) ?>
					<? $this->displayPolls('disqualified', $this->starbar) ?>
				</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tabs_2 -->
	<? } ?>

	<? if ($this->count_archived_polls) { ?>
		<div id="polls_tabs_3" class="sb_tabPane">
			<img src="//<?= BASE_DOMAIN ?>/images/social/img_header_polls.png" alt="Polls" />
			<p class="sb_tabHeader">
				We'd still love your opinion on these archived polls, and you can still earn by completing them! Same deal &ndash; earn<strong class="sb_theme_textHighlight sb_tooltip" title="Social PaySos - are almost as good as cash and can be redeemed for goods in the Rewards Center."> Social PaySos</strong> &amp;<strong class="sb_theme_textHighlight sb_tooltip" title="Social SaySo - determines your access to increasingly important levels of influence."> SaySo</strong> for each one you complete.
			</p>
			<div class="sb_scrollPane">

				<!-- BEGIN POLL BOX LANDING -->
				<? $this->displayPolls('archived', $this->starbar) ?>
				<!-- END POLL BOX LANDING -->
		    <br />
				<? if ($this->count_new_polls) { ?>
					<p align="right"><a href="#" class="sb_nav_tabs sb_theme_button" rel="1"><span class="sb_theme_buttonArrow">Take a New Poll</span></a></p>
				<? } ?>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tabs_3 -->
	<? } ?>

</div><!-- .tabs -->
