<div id="sb_slideshow">
	<div class="sb_promoBG sb_promo_week1">
		<div class="sb_slide">
			<img id="promo_image_1" usemap="#promo_map_1" src="//<?= BASE_DOMAIN ?>/images/social/img_promo_1.png" style="width: 535px; height: 343px;"><br>
			<map name="promo_map_1">
				<area shape="rect" coords="169,265,372,284" href="//<?= BASE_DOMAIN ?>/starbar/social/rewards" class="sb_nav_element"  rel="sb_popBox_rewards">
				<!--<area shape="rect" coords="302,259,365,274" href="//<?= BASE_DOMAIN ?>/starbar/social/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg">-->
				<area shape="rect" coords="179,319,359,339" class="sb_next" href="#">
			</map>
		</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week1 -->
	<div class="sb_promoBG sb_promo_week2">
		<div class="sb_slide">
			<img id="promo_image_2" usemap="#promo_map_2" src="//<?= BASE_DOMAIN ?>/images/social/img_promo_2.png" style="width: 535px; height: 343px;"><br>
			<map name="promo_map_2">
				<area shape="rect" coords="169,265,372,284" href="//<?= BASE_DOMAIN ?>/starbar/social/rewards" class="sb_nav_element"  rel="sb_popBox_rewards">
				<area shape="rect" coords="179,319,359,339" class="sb_prev" href="#">
			</map>
		</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week2 -->

</div><!-- #sb_slideshow -->
