<div id="sb_innerOverlay">
	<div class="sb_innerOverlayBackground"></div>
	<div class="sb_innerOverlayContent"></div>
</div>
<div class="sb_scrollPane">
	<img src="//<?= BASE_DOMAIN ?>/images/social/img_header_rewards-center.png" alt="Rewards Center" />
	<!--<p>Hundreds of items have been redeemed already -- grab the NEW items before they're gone! And remember to get your Giveaway Tokens!</p>-->
	<p><strong class="sb_theme_textHighlight">Select an item below</strong></p>

	<div class="sb_rewards">
	<?= $this->partialLoop('social/reward.phtml', $this->rewards) ?>
	</div><!-- .sb_rewards -->
</div><!-- .sb_scrollPane --><div id="footnote"><p class="termsandconditions"><strong>Social Say.So</strong> does not guarantee prizes for participation. Prizes are limited and are redeemed on a first come, first serve basis. Once an item is “Sold Out” it is not guaranteed to be replaced or restocked. Say.So does not take responsibility for Cinebucks not redeemed by the end of the program. Social Say.So can only ship items to the U.S. - Cinebucks will not be returned.</p></div><!-- /footnote -->

<script language="javascript">
	$SQ(function(){
		var sayso = window.sayso;
		var overlay = $SQ('#sayso-starbar #sb_innerOverlay');

		var overlayContent = $SQ('.sb_innerOverlayContent', overlay);

		$SQ(document).bind('sb_cbox_cleanup', function () {
			overlay.hide();
		});

		// select a reward
		$SQ('#sayso-starbar .sb_rewards .sb_rewardItem')
			.not('.sb_rewardItem_disabled')
			.unbind('click').bind('click', function(e){

				overlayContent.html('').fadeTo(0, 0);
				overlay.fadeOut(0).fadeIn(500);

				var container = $SQ(this).dataContainer();

				$SQ.ajaxWithAuth({
					url : '//' + sayso.baseDomain + '/starbar/social/reward-redeem',
					data : { good_id : container.getId() },
					success : function (response) {
						overlayContent.html(response.data.html).fadeTo(200, 1);
					}
				});
			});
		});

		<? if ($this->chosen_good_id == "first") { ?>
			var firstItem = $SQ('#sayso-starbar .sb_rewards .sb_rewardItem').first();
			if (!firstItem.hasClass('sb_rewardItem_disabled')) firstItem.trigger('click');
		<? } elseif ($this->chosen_good_id) { ?>
			$SQ('#sayso-starbar .sb_rewards .sb_rewardItem').not('.sb_rewardItem_disabled').each(function (index) {
				if (parseInt($SQ(this).attr('data-id')) == parseInt(<?= $this->chosen_good_id ?>)) {
					$SQ(this).trigger('click');
				}
			});
		<? } ?>
</script>
