<br>
<table cellspacing=0 cellpadding=0 border=0>
	<tr class="header">
		<th width="10%">Key</th>
		<? $columnWidth = (int) floor(90 / count($this->starbars)) ?>
		<? foreach ($this->starbars as $starbar) { ?>
			<th width="<?= $columnWidth ?>%"><?= $starbar['label'] ?></th>
		<? } ?>
	</tr>
	<? foreach ($this->keys as $key) { ?>
		<tr class="data" data-key_id="<?= $key ?>">
			<td class="key" data-original_content="<?= $key ?>"></td>
			<? foreach ($this->starbars as $starbar) { ?>
				<?
				$starbarContent = (isset($this->starbar_content[$starbar['id']][$key]) ? $this->starbar_content[$starbar['id']][$key] : '');
				$starbarContent = str_replace("\"", "&quot;", $starbarContent);
				$starbarContent = str_replace("<", "&lt;", $starbarContent);
				$starbarContent = str_replace(">", "&gt;", $starbarContent);
				?>
				<td class="content content_<?= $starbar['id'] ?>" data-original_content="<?= $starbarContent ?>"></td>
			<? } ?>
		</tr>
	<? } ?>
</table>
<script type="text/javascript">
	var starbars = new Array();
	<? $i = 0 ?>
	<? foreach ($this->starbars as $starbar) { ?>
		starbars[<?= $i ?>] = {id: <?= $starbar['id'] ?>, label: "<?= $starbar['label'] ?>"};
		<? $i++ ?>
	<? } ?>
	$('tr.data td').each(function(i) {
		var $this = $(this);
		var $div = $('<div></div>');
		var content = $this.data('original_content');
		$div.text(content);
		$this.append($div);
	});
</script>
<br><a href="#" onclick="addNewRow(); return false;">Add New Key</a><br>
<br><a href="#" onclick="addNewRow(5); return false;">Add 5 New Keys</a><br>
<br><br><br><br><br>
