	<style>
		body { background-color: #FFFFFF; font: 12px arial, sans-serif; }
		th { border-bottom: 1px solid #CCCCCC; padding: 4px; background-color: #555555; color: #EEEEEE; }
		td { background-color: #F5F5F5; padding: 4px; }
	</style>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<img border="0" src="https://s3.amazonaws.com/say.so/media/header_adjuster.jpg" style="width: 822px; height: 90px; margin: 13px 0 0 10px"><br />
	<div style="border: 1px solid #CCCCCC; background-color: #EEEEEE; padding: 10px; width: 800px; margin: 20px 0 20px 10px">
		<div style="margin: 3px 0 21px 0; color: #119922; cursor: pointer;" onclick="$(this).hide(); $('#the_form').show(); return false;">New Study +</div>
		<form id="the_form" method="POST">
			<input type="hidden" id="operation" name="operation" value="add" />
			<input type="hidden" id="study_ad_id_to_delete" name="study_ad_id_to_delete" value="" />
			New Study Type: <select name="study_type" onchange="UpdateStudyType(this.options[this.selectedIndex].value);">
				<option value=""></option>
				<option value="campaign">ADjuster Campaign</option>
				<option value="creative">ADjuster Creative</option>
			</select><br /><br />
			<div id="study_type_chosen">
				Type of AD to <span id="track_or_replace"></span>:
				<select name="tag_type" onchange="UpdateTagType(this.options[this.selectedIndex].value);">
					<option value=""></option>
					<option value="image">Image</option>
					<option value="flash">Flash</option>
					<option value="facebook">Facebook</option>
				</select><br /><br />
				<div id="tag_type_chosen">
					<span id="tag_instructions"></span>: <input type="text" name="tag" value=""><br /><br />
					<div id="domain">
						Domain the AD appears on (e.g. <b>coolmagazine.com</b>): <input type="text" name="domain" value=""><br /><br />
					</div>
					<div id="ad_target">
						Part of AD target URL (e.g. <b>publisher.com</b>): <input type="text" name="ad_target" value=""><br /><br />
					</div>
					<input type="submit" name="Add Study" value="Add Study"><br /><br />
				</div>
			</div>
		</form>
	</div>
	<div style="border: 1px solid #CCCCCC; background-color: #EEEEEE; padding: 10px; width: 800px; margin: 0 0 0 10px">
	Current Studies:<br />
	<? if (count($this->current_study_ads)) { ?>
		<table border="0" cellpadding="0" cellspacing="0" style="width: 798px; margin: 10px 0 5px 0; border: 1px solid #CCCCCC;">
			<tr>
				<th width="60%" align="left">Study Name</td>
				<th width="30%" align="left">Type of Study</td>
				<th width="10%" align="right">Delete</td>
			</tr>
			<? $i = 0 ?>
			<? foreach ($this->current_study_ads AS $study_ad) { ?>
				<tr>
					<td><?= $study_ad->existing_ad_type . " AD: " . $study_ad->existing_ad_tag ?></td>
					<td><?= ($study_ad->type == "campaign" ? "Campaign (track AD)" : "Creative (replace AD)") ?></td>
					<td align="right"><a href="#" onclick="$('#study_ad_id_to_delete').attr('value', <?= $study_ad->getId() ?>); $('#operation').attr('value', 'delete'); $('#the_form').submit(); return false;" style="color: red;">X</a></td>
				</tr>
				<tr>
					<td colspan="3">
						<? if ($study_ad->existing_ad_domain) { ?>
							<em>AD runs on <?= $study_ad->existing_ad_domain ?></em>
						<? } ?>
					</td>
				</tr>
				<? $i++ ?>
			<? } ?>
		</table>
	<? } else { ?>
		<br />
		&nbsp; &nbsp;<em>No studies found. You may add a study above.</em>
		<br />
	<? } ?>

	<script type="text/javascript">
		var study_type = "";
		$('#the_form').hide();
		$('#study_type_chosen').hide();
		$('#tag_type_chosen').hide();
		$('tr:even').children('td').css(
			{
				'padding' : '2px 2px 2px 10px',
				'background-color' : '#F9F9F9',
				'font-size' : '10px',
				'border-bottom' : '1px solid #D3D3D3'
			}
		);
		$('tr:last').children().css('border-bottom', '0');


		function UpdateStudyType(type) {
			$('#study_type_chosen').hide();

			study_type = type;

			if (type == "campaign") {
				$('#track_or_replace').html('TRACK');
				$('#ad_target').show();
				$('#study_type_chosen').show();
			} else if(type == "creative") {
				$('#track_or_replace').html('REPLACE');
				$('#ad_target').hide();
				$('#study_type_chosen').show();
			}
		}

		function UpdateTagType(type) {
			$('#tag_type_chosen').hide();
			if (type == "image") {
				$('#tag_instructions').html('Partial Image URL (e.g. <b>ad_123.jpg</b>)');
				$('#domain').show();
				$('#tag_type_chosen').show();
			} else if(type == "flash") {
				$('#tag_instructions').html('Partial Flash URL (e.g. <b>ad_123.swf</b>)');
				$('#domain').show();
				$('#tag_type_chosen').show();
			} else if(type == "facebook") {
				$('#tag_instructions').html('Facebook Ad ID (e.g. <b>6789012345</b>)');
				$('#domain').hide();
				$('#tag_type_chosen').show();
			}
		}
	</script>
