<br />
<style>
body {
	font: 11px Verdana;
	margin-left: 20px;
	margin-bottom: 50px;
	background-color: #CCC;
}

div#raffleSettings {
	position: relative;
	width: 980px;
	border: 1px solid #666;
	background-color: #FFF;
	padding: 10px;
}

</style>
<form id="raffleForm" method="get">
	<input type="hidden" id="operation" name="operation" value="">
	&nbsp; &nbsp; <b>RaffleMeister Pro 2012 Xtreme v12.001.000</b><br />
	&nbsp; &nbsp;
	<div id="raffleSettings">
		<b></b><br />
		<select id="starbar_id" name="starbar_id" onchange="$('#operation').val(''); $('#raffleForm').submit();">
			<option value="">Choose a starbar</option>
			<? foreach ($this->starbars as $starbar) { ?>
				<option value="<?= (int) $starbar['id'] ?>" <? if ($this->starbar_id == (int) $starbar['id']) { echo 'selected'; } ?>><?= $starbar['label'] ?></option>
			<? } ?>
		</select><br />
		<br />
		<? if (count($this->tokens)) { ?>
			<select id="good_id" name="good_id">
				<option value="">Choose a token</option>
				<? foreach ($this->tokens as $token) { ?>
					<option value="<?= $token['game_asset_id'] ?>" <? if ($this->good_id == $token['game_asset_id']) { echo 'selected'; } ?>><?= $token['name'] ?> (<?= $token['total_purchased'] ?> purchased)</option>
				<? } ?>
			</select><br />
			<br />
			<a href="javascript: $('#operation').val('pick-winner'); $('#raffleForm').submit();">Pick a<? if ($this->winning_transaction->id) echo "nother"; ?> winner!</a>
			<? if ($this->winning_transaction->id) { ?>
				<h1>Winner!</h1><br />
				User ID: <?= $this->winning_user->id ?><br />
				User First Name: <?= $this->winning_user->first_name ?><br />
				User Last Name: <?= $this->winning_user->last_name ?><br />
				User Email: <?= $this->winning_user_email->email ?><br />
				Order ID: <?= $this->winning_transaction->id?><br />
			<? } ?>
		<? } ?>
	</div>
</form>
