<br />
<style>
body {
	font: 11px Verdana;
	margin-left: 20px;
	margin-bottom: 50px;
	background-color: #CCC;
}

h1 {
	margin: 10px 0 20px 0;
	font-size: 20px;
	font-weight: bold;
}

div#report_header {
	margin-top: 30px;
	background-color: black;
	color: white;
	width: 1005px;
	padding: 11px;
	font-size: 13px;
}

div#report_header h1 {
	font-size: 17px;
	margin: 0;
	margin-bottom: 20px;
	color: #C02526;
}

div#report_header span {
	font-weight: bold;
	color: #C02526;
}

img.white_logo {
	width: 220px;
	display: inline;
	vertical-align: middle;
	margin-right: 10px;
}

h2 {
	margin: 0;
	font-weight: normal;
}

h3 {
	margin: 40px 0 5px 0;
}

div.chart {
	margin: auto;
	width: 975px;
	height: 300px;
}

div#reportSettings {
	position: relative;
	width: 1005px;
	border: 1px solid #666;
	background-color: #FFF;
	padding: 10px;
}

div#report {
	width: 1005px;
	border: 1px solid #666;
	background-color: #FFF;
	padding: 20px 10px 10px 10px;
}

select#survey_id {
	width: 780px;
}

.jqplot-point-label, table.jqplot-table-legend, table.jqplot-cursor-legend, .jqplot-axis {
	font-size: 1em;
	font-weight: bold;
}

.jqplot-axis.jqplot-yaxis {
	max-width: 485px;
}

.jqplot-yaxis-tick {
	background-color: #FFF;
	z-index: 300;
}

#reportSubmit {
	position: absolute;
	right: 22px;
	bottom: 22px;
}

@media print {
	.do_not_print {
		display:none;
	}

	#report h3 {
		page-break-before:always;
	}
}
</style>
<script type="text/javascript">
	$.jqplot.config.enablePlugins = true;

	function renderGraph(divId, labels, values) {
		var labels = labels.reverse();
		var values = values.reverse();
		$.jqplot(divId, [values], {
			series: [{
				renderer:$.jqplot.BarRenderer,
				rendererOptions: {
					barDirection: 'horizontal',
					varyBarColor: true,
					barMargin: 50 / labels.length
				}
			}],
			axes: {
				yaxis: {
					renderer: $.jqplot.CategoryAxisRenderer,
					ticks: labels,
					tickOptions:{
						showGridline:true,
						markSize:0
					}
				},
				xaxis:{
					tickOptions:{formatString:'%d\%'}
				}
			}
		});
	}

	var surveys = {
		<?
		// set up empty arrays for every starbar/content type combination
		$firstStarbar = true;
		foreach($this->starbars as $starbar) {
			if (!$firstStarbar) echo ",";
			echo "starbar" . $starbar['id'] . ": {";
			$firstSurveyType = true;
			foreach (array("survey", "poll", "trailer", "quiz") as $surveyType) {
				if (!$firstSurveyType) echo ",";
				echo $surveyType . ": new Array()";
				$firstSurveyType = false;
			}
			echo "}";
			$firstStarbar = false;
		}
		?>
	};

	<? foreach ($this->surveys as $survey) { ?>
		<? if ($this->survey_id == $survey['id']) { $chosenSurvey = $survey; } ?>
		surveys.starbar<?= $survey['unique_starbar_id'] ?>.<?= $survey['type'] ?>.push({
			id: <?= $survey['id'] ?>,
			title: "<?= str_replace('"', '\\"', $survey['title']) ?>"
		});
	<? } ?>

</script>
<form id="reportForm" action="survey-report" method="get">

	<div id="reportSettings" class="do_not_print">
		<div id="reportSubmit">
			<input type="button" onclick="$('#reportForm').attr('action', 'survey-report'); $('#reportForm').submit();" value="View Report">
			<input type="button" onclick="$('#reportForm').attr('action', 'survey-csv-export'); $('#reportForm').submit();" value="Download CSV Report">
		</div>
		<? if ($this->single_starbar_id) { ?>
			<h1><? if ($this->white_logo_url) { ?><img class="white_logo" src="<?= $this->white_logo_url ?>"><? } ?> STANDARD CONTENT REPORTINGS &amp; ANALYTICS</h1>
			<input type="hidden" id="starbar_id" name="starbar_id" value="<?= $this->starbar_id ?>">
			Content type:
		<? } else {?>
			<b>Filter content (not a filter for users!):</b><br />
			Content from:
			<select id="starbar_id" name="starbar_id" onchange="loadSurveysIntoSelect(parseInt($('#survey_id').val()));">
				<option value="">Please choose a starbar</option>
				<? foreach ($this->starbars as $starbar) { ?>
					<option value="<?= (int) $starbar['id'] ?>" <? if ($this->starbar_id == (int) $starbar['id']) { echo 'selected'; } ?>><?= $starbar['label'] ?></option>
				<? } ?>
			</select>
		<? } ?>
		<select id="survey_type" name="survey_type" onchange="loadSurveysIntoSelect(parseInt($('#survey_id').val()));">
			<option value="">Please choose a type of content</option>
			<? foreach (array("survey", "poll", "trailer", "quiz") as $surveyType) { ?>
				<option <? if ($this->survey_type == $surveyType) { echo 'selected'; } ?>><?= $surveyType ?></option>
			<? } ?>
		</select><br /><br />

		<b>Select content to report on:</b><br />
		<select id="survey_id" name="survey_id">
			<option value="0">Please choose a <?= ($this->survey_type ? $this->survey_type : "type of content first") ?></option>
		</select><br /><br />

		<? if (APPLICATION_ENV == "production" && $this->single_starbar_id) { ?>
			<b>Select user group to report on:</b><br />
			<select name="report_cell_id">
				<option value="">Please choose a group</option>
				<? foreach ($this->report_cells as $reportCell) { ?>
					<? if ($this->report_cell_id == $reportCell->id) { $chosenReportCell = $reportCell; } ?>>
					<option value="<?= $reportCell->id ?>" <? if ($this->report_cell_id == $reportCell->id) { echo 'selected'; } ?>><?= strtoupper($reportCell->category) . ": " . $reportCell->title . " (" . (int) $reportCell->number_of_users . " users)"?></option>
				<? } ?>
			</select><br /><br />
		<? } else { ?>
			<div id="report_cell_dig"></div>
			<script type="text/javascript">
				// pre-cache starbars and surveys .. this is optional but improves initial loading performance
				var originalCache = window.originalNodeCache;
				originalCache.starbar = {};
				<? $firstStarbar = true ?>
				<? foreach($this->starbars as $starbar) { ?>
					originalCache.starbar["<?= $starbar['id'] ?>"] = {
						id: <?= $starbar['id'] ?>,
						label: "<?= $starbar['label'] ?>",
						survey: {}
					};
				<? } ?>

				<? foreach ($this->surveys as $survey) { ?>
					originalCache.starbar["<?= $survey['unique_starbar_id'] ?>"].survey["<?= $survey['id'] ?>"] = {
						id: <?= $survey['id'] ?>,
						label: "<?= str_replace('"', '\\"', $survey['title']) ?>",
						type: "<?= $survey['type'] ?>"
					};
				<? } ?>

				$(document).ready(function () {
					var digOptions = {
						form_id: 'reportForm',
						single_starbar_id: <?= ($this->single_starbar_id ? $this->single_starbar_id : 0) ?>,
						hidden_by_default: true,
						label: "Select user group to report on: ",
						new_option: "New User Group",
						sort:[{field: 'ordinal'}]
					};
					window.reportCellTopNode = dig('report_cell_id', 'report_cell_dig', 'report_cell', '<?= ($this->report_cell_id ? $this->report_cell_id : 0) ?>', digOptions);
				});
			</script>
			<br style="clear :both" /><br />
		<? } ?>
	</div>
</form>

	<? if ($this->survey_id && $this->report_cell_id) { ?>
		<!--
		<form id="pdfForm" method="post" action="survey-pdf-export" target="_new">
			<input type="hidden" id="html_to_render" name="html_to_render" value="">
			<input type="button" class="do_not_print" onclick="$('#html_to_render').val($('html').html()); /*console.log($('#html_to_render').val());*/ $('#pdfForm').submit();" value="Download PDF Report">
		</form>
		-->
		<div id="report_header">
			<? if ($this->black_logo_url) { ?>
				<h1><img class="black_logo" src="<?= $this->black_logo_url ?>"></h1>
			<? } else { ?>
				<h1>REPORTING &amp; ANALYTICS</h1>
			<? } ?>
			<span class="content_type"><?= strtoupper($chosenSurvey['type']) ?> - </span>
			<?= $chosenSurvey['title'] ?>
		</div>
		<div id="report">
			<h2>User Group: <b><?= $this->chosen_report_cell->title ?></b></h2>
			<? $questionNumber = 1 ?>
			<? foreach ($this->survey_questions as $surveyQuestion) { ?>
				<? if ($surveyQuestion->data_type != "none" || $surveyQuestion->choice_type != "none") { ?>
					<? $questionCalculation = $this->calculation_array[$surveyQuestion->id][0] ?>

					<h3><a name="question_<?= $surveyQuestion->id ?>"></a><?= $questionNumber ?>. <?= $surveyQuestion->title ?></h3>
					<? if ($questionCalculation->number_of_responses) { ?>
						<? if ($surveyQuestion->piped_from_survey_question_id) { ?>
							<? $surveyQuestion->option_array = $this->survey_questions[$surveyQuestion->piped_from_survey_question_id]->option_array ?>
						<? } ?>

						<? if (count($surveyQuestion->option_array)) { ?>
							<br />Users can choose <b><?= ($surveyQuestion->choice_type == "single" ? "a single response" : "multiple responses") ?></b>
							<div id="chart_<?= $surveyQuestion->id ?>" class="chart" style="height: <?= (150 + (count($surveyQuestion->option_array) * 30)) ?>px;"></div>
							<script type="text/javascript">
								var data_<?= $surveyQuestion->id ?> = new Array();
								var labels_<?= $surveyQuestion->id ?> = new Array();
								<? foreach ($surveyQuestion->option_array as $surveyQuestionChoice) { ?>
									<? if (isset($this->calculation_array[$surveyQuestion->id][$surveyQuestionChoice->id])) { ?>
										<? $choiceCalculation = $this->calculation_array[$surveyQuestion->id][$surveyQuestionChoice->id] ?>
									<? } else { ?>
										<? $choiceCalculation = new ReportCell_SurveyCalculation() ?>
									<? } ?>

									data_<?= $surveyQuestion->id ?>.push(<?= round($choiceCalculation->number_of_responses / $questionCalculation->number_of_responses * 100, 2) ?>);
									labels_<?= $surveyQuestion->id ?>.push("<?= str_replace('"', '\\"', $surveyQuestionChoice->title) . " (" . (int) $choiceCalculation->number_of_responses . ")" ?>");
								<? } ?>

								renderGraph("chart_<?= $surveyQuestion->id ?>", labels_<?= $surveyQuestion->id ?>, data_<?= $surveyQuestion->id ?>);
							</script>
						<? } ?>


						<? /*if (count($surveyQuestion->option_array)) { ?>
							<ol>
							<? foreach ($surveyQuestion->option_array as $surveyQuestionChoice) { ?>
								<? if (isset($this->calculation_array[$surveyQuestion->id][$surveyQuestionChoice->id])) { ?>
									<? $choiceCalculation = $this->calculation_array[$surveyQuestion->id][$surveyQuestionChoice->id] ?>
								<? } else { ?>
									<? $choiceCalculation = new ReportCell_SurveyCalculation() ?>
								<? } ?>
								<li>
									<?= $surveyQuestionChoice->title ?> <b>(<?= (int) $choiceCalculation->number_of_responses ?> users</b> - <?= round($choiceCalculation->number_of_responses / $questionCalculation->number_of_responses * 100, 2) ?>%)<br />
								</li>
							<? } ?>
							</ol>
						<? }*/ ?>
					<? } ?>
					<br />Number of responses: <b><?= (int) $questionCalculation->number_of_responses ?></b>
					<? if ($questionCalculation->number_of_responses) { ?>
						<? if ($surveyQuestion->data_type != "none") { ?><span>(<a href="#" onclick="getResponsesForQuestion(this, <?= $this->report_cell_id ?>, <?= $surveyQuestion->id ?>); return false;">view all typed responses</a>)</span><? } ?>
						<br />
						<div id="responses_question_<?= $surveyQuestion->id ?>" style="display: hidden;"></div>

						<? if ($questionCalculation->average) echo "Average: " . $questionCalculation->average . "<br />" ?>
						<? if ($questionCalculation->median) echo "Median: " . $questionCalculation->median . "<br />" ?>
						<? if ($questionCalculation->stardard_deviation) echo "Std. Dev.: " . $questionCalculation->stardard_deviation . "<br />" ?>
					<? } ?>

					<? $questionNumber++ ?>
				<? } ?>
			<? } ?>
		</div>
	<? } ?>
<script type="text/javascript">
	function loadSurveysIntoSelect(chosen_survey_id) {
		var starbarId = parseInt($('#starbar_id').val());
		var starbarLabel = $('#starbar_id').text();
		if ($('#starbar_id option').length) {
			starbarLabel = $('#starbar_id option:selected').text();
		}
		var surveyType = $('select#survey_type').val();
		var survey;
		var selectedText;
		var options = '<option value="">Please choose a content type first</option>';
		if (starbarId > 0 && surveyType != "") {
			options = '<option value="">Please choose a '+starbarLabel+' '+surveyType+'</option>';
			for (surveyIndex in surveys['starbar'+starbarId][surveyType]) {
				survey = surveys['starbar'+starbarId][surveyType][surveyIndex];
				if (chosen_survey_id == survey['id']) selectedText = " selected ";
				else selectedText = "";
				options += '<option value="'+survey['id']+'" '+selectedText+'>'+survey['title']+'</option>';
			}
		}
		$('select#survey_id').html(options);
	}

	function getResponsesForQuestion(callingElement, cellId, questionId) {
		cellId = parseInt(cellId);
		questionId = parseInt(questionId);
		callingElement = $(callingElement);
		if (cellId > 0 && questionId > 0) {
			$.ajax({
				url : '../index/survey-question-responses',
				beforeSend : function(x) {
					if (x && x.overrideMimeType) {
						x.overrideMimeType("application/j-son;charset=UTF-8");
					}
				},
				data : {
					report_cell_id : cellId,
					survey_question_id : questionId
				},
				success : function (response, status) {
					responsesDiv = $('#responses_question_'+questionId);
					if (responsesDiv.length == 1) {
						responsesDiv.html(response);
						responsesDiv.css({
							'width' : '700px',
							'height' : '150px',
							'overflow-y' : 'scroll',
							'border' : '1px solid #CCCCCC',
							'display' : 'block'
						});
						callingElement.parent().html('(<a href="#" onclick="hideResponsesForQuestion(this, '+cellId+', '+questionId+'); return false;">hide</a>)');
						location.hash = 'question_'+questionId;
					}
				}
			});
		}
	}

	function hideResponsesForQuestion(callingElement, cellId, questionId) {
		cellId = parseInt(cellId);
		questionId = parseInt(questionId);
		callingElement = $(callingElement);
		responsesDiv = $('#responses_question_'+questionId);
		if (responsesDiv.length == 1) {
			responsesDiv.css({
				'display' : 'none'
			});
			callingElement.parent().html('(<a href="#" onclick="getResponsesForQuestion(this, '+cellId+', '+questionId+'); return false;">view</a>)');
		}

	}

	loadSurveysIntoSelect(<?= $this->survey_id ?>);

	$('.jqplot-yaxis-tick').each(function(index) {
		$(this).attr('title', $(this).text());
	});
</script>
