<link rel="stylesheet" href="/css/devadmin/dig.css" type="text/css" media="screen" />
<script type="text/javascript" src="/js/devadmin/dig.js"></script>
<script type="text/javascript">

$(document).ready(function () {
	// pre-cache starbars and surveys .. this is optional but improves initial loading performance
	var originalCache = window.originalNodeCache;
	originalCache.starbar = {};
	<? $firstStarbar = true ?>
	<? foreach($this->starbars as $starbar) { ?>
		originalCache.starbar["<?= $starbar['id'] ?>"] = {
			id: <?= $starbar['id'] ?>,
			label: "<?= $starbar['label'] ?>",
			survey: {}
		};
	<? } ?>

	<? foreach ($this->surveys as $survey) { ?>
		originalCache.starbar["<?= $survey['unique_starbar_id'] ?>"].survey["<?= $survey['id'] ?>"] = {
			id: <?= $survey['id'] ?>,
			label: "<?= str_replace('"', '\\"', $survey['title']) ?>",
			type: "<?= $survey['type'] ?>",
			fully_loaded: true
		};
	<? } ?>

	var digOptions = {
		select_name: 'report_cell_id',
		label: "Edit User Group: ",
		new_option: "New User Group",
		sort:[{field: 'ordinal'}]
	};
	window.reportCellTopNode = dig('some_container', 'report_cell', '<?= ($this->report_cell_id ? $this->report_cell_id : 0) ?>', digOptions);
});

</script>
<div id="some_container">
</div>
