<link rel="stylesheet" href="/css/dig/dig.css" type="text/css" media="screen" />
<script type="text/javascript" src="/js/dig/dig.js"></script>
<script type="text/javascript">

$(document).ready(function () {
	var digOptions = {
		label: "Edit User Group: ",
		new_option: "New User Group",
		sort:[{field: 'ordinal'}]
	};
	window.reportCellTopNode = dig('report_cell_id', 'some_container', 'report_cell', '<?= ($this->report_cell_id ? $this->report_cell_id : 0) ?>', digOptions);
});

</script>
<div id="some_container">
</div>
