<!-- views/scripts/admin/user.phtml file -->
<script>
	$SQ(function() {
		$SQ( "#tabs" ).tabs({
			ajaxOptions: {
				error: function( xhr, status, index, anchor ) {
					$SQ( anchor.hash ).html(
						"Sorry - Cannot continue. Please contact say.so technical support." );
				}
			}

		});
		$SQ( "#tabs" ).tabs({ spinner: "<img src='/images/spinners/spinner-12x12.gif' style='border:none' />" });
	});
	</script>
<h2>User Observation</h2>
<?php echo $this->form ?>
<div id="div_results" style="clear:both">
<?php

	if ($this->error) {
		printf("<p class='error'>%s</p>",$this->error);
	}
	if ($this->userdata) {
		printf("<div id='emailaddress'>%s</div>",$this->userdata[0]['email']);
		?>

<div id='tabs'>
	<ul>
<?php
		printf('<li><a href="/cms/admin/sboverview/user/%s"><span>Overview</span></a></li>',$this->userdata[0]['user_id']);
		if ($this->tabs) {
			// Only if we have any starbars that this user has used
			foreach ($this->tabs as $tabs) {

				printf("<li><a href='/cms/admin/sbinfo?starbar=%s&user=%s'><span>%s</span></a></li>\n\r",$tabs['starbar_id'],$tabs['user_id'],$tabs['label']);


			}
		}
		?>
		</ul>
		<?php

		printf("</div><!-- /tabs -->");
	}
?>
</div>
