<div class="sb_header">
	<a href="http://www.saysollc.com" target="_blank"><img src="//<?= BASE_DOMAIN ?>/images/generic/logo_sayso_lg.png" alt="Say.So" /></a>
</div><!-- .sb_header -->
<div class="sb_tabs">
	<ul>
		<li><a href="#about_tabs_1">About</a></li>
		<li><a href="#about_tabs_2">Help</a></li>
		<li><a href="#about_tabs_3">FAQs</a></li>
		<li><a href="#about_tabs_4">Feedback</a></li>
		<? if ($this->show_testing_function) { ?>
			<li><a href="#about_tabs_5">Testing</a></li>
		<? } ?>
	</ul>
	<div id="about_tabs_1" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">About Say.So</h2>
			<p>What is Say.So? Say.So is where <em>your</em> "say so" has value. This all started because we had been duped. Enticed into joining research panels with the promise that our opinions would matter, and that our input would be reflected in new or improved products. Instead, what we got was mailboxes filled with irrelevant surveys, points systems that offered very little reward, and no other way to demonstrate that we are mavens who should be revered.</p>
			<p>Say.So's mission is to give you -- consumers, fans, brand acolytes, pundits -- an elegant way to more intimately connect with your favorite brands and affinities. In return, these companies learn how best to serve you, their customer. But, for this to truly mean something, the experience needs to be worthwhile.</p>
			<p>Say.So's experience is unique in that it is a browser application, not a web page, so interacting with it doesn't require you to leave what you are doing. It's there when you are ready and keeps you notified of new surveys, content and rewards. The app offers a variety of surveys and polls, but also powers activities that are intrinsically motivating – quests, trivia... These test your mettle. Some are available to you out of the gate, but others need to be earned by leveling up or demonstrating your unique knowledge.</p>
			<p>The more you participate, the more you gain, earning both experience points and currency points. Experience points are the currency of influence, earned by sharing your experience, expertise and opinion. These determine your status in the community, and reaching higher levels separates you as someone to be heard. Currency points are almost as good as cash and can be redeemed for a variety of unique and only available to you merchandise.</p>
			<p>Say.So. <em>What's yours?</em></p>
			<br />
			<p style="margin: 0; float: right;">
				<small>
					<a href="http://<?= BASE_DOMAIN ?>/docs/hellomusic/Say.So_Privacy_Policy.pdf" target="_new">Privacy Policy</a>&nbsp;|&nbsp;
					<a href="http://<?= BASE_DOMAIN ?>/docs/hellomusic/Say.So_Rewards_Rules.pdf" target="_new">Rewards Rules</a>&nbsp;|&nbsp;
					<a href="http://<?= BASE_DOMAIN ?>/docs/hellomusic/Say.So_HelloMusic_Giveaway_Official_Rules.pdf" target="_new">Giveaway Rules</a>&nbsp;|&nbsp;
					<a href="http://<?= BASE_DOMAIN ?>/docs/hellomusic/Say.So_App_EULA.pdf" target="_new">EULA</a>
				</small>
			</p>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_1 -->
	<div id="about_tabs_2" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">Need Help?</h2>
			<p>We designed the steps below to help you get oriented with the Say.So Music Bar. If you find you need additional help, feel free to <a href="mailto:hellomusic@say.so">contact us</a><? //<span class="sb_theme_textHighlight" id="onboard_tabs_5" style="cursor: pointer;">contact us</span>?>.</p>
			<div class="sb_tabs">
				<ul>
					<li><a href="#onboard_tabs_1">Welcome!</a></li>
					<li><a href="#onboard_tabs_2">What Can I Do?</a></li>
					<li><a href="#onboard_tabs_3">What Do I Get?</a></li>
					<li><a href="#onboard_tabs_4">Get Started</a></li>
					<li style="display:none;"><a href="#onboard_tabs_5"> </a></li>
				</ul>

				<div id="onboard_tabs_1" class="sb_tabPane">
					<h3 class="sb_title" align="center" style="font-weight: bold; margin-bottom: 10px">Congratulations and Thank You!</h3>
					<h3>We designed the steps below to help you get oriented. If you find you need additional help, feel free to <a href="mailto:hellomusic@say.so">contact us</a>.</h3>
					<p align="center"><big>By installing the Say.So Music Bar, you’ve achieved Musician level, and earned 1000 Chops and 100 Notes.</big></p>
					<br />
					<ul class="sb_lineList">
						<li class="sb_img_chops"><strong class="sb_theme_textHighlight">"Chops"</strong> are the currency of influence. You earn them for sharing your expertise, experience and opinion, and your Chops determine your access to increasingly important levels of access and influence.</li>
						<li class="sb_img_notes"><strong class="sb_theme_textHighlight">"Notes"</strong> are almost as good as cash. Virtually everything you do earns you Notes, which can be redeemed for all manner of Hello Music goodies (<a class="sb_nav_element" rel="sb_popBox_rewards" href="//local.sayso.com/starbar/hellomusic/rewards">see the Rewards Center</a>)</li>
					</ul>
				</div><!-- #tab_1 -->
				<div id="onboard_tabs_2" class="sb_tabPane">
					<h3 class="sb_title" align="center">Give Your Opinion, Share It and Earn!</h3>
					<p align="center">Your point of view and opinion are invaluable. Express yourself through fun polls and surveys, and earn points by sharing Daily Deals.</p>
					<ul class="sb_lineList">
						<li class="sb_img_polls"><strong class="sb_theme_textHighlight">Polls</strong> are quick hits of opinion we’d like you to share. Answer as many or as few as you’d like, and for each one we’ll drop a little something in your gig bag.</li>
						<li class="sb_img_surveys"><strong class="sb_theme_textHighlight">Surveys</strong> are the big money gigs. These are important efforts to gauge how we are doing, and we’ll make sure you are compensated accordingly. </li>
						<li class="sb_img_deals"><strong class="sb_theme_textHighlight">Deals - </strong> You know about the Daily Deals. We've incorporated them into the Hello Music Say.So and any time you check them out, or share them to Facebook or Twitter, we'll compensate you with Notes and Chops. Plus we have added exclusive deals for Hello Music Say.So members only. No purchase necessary.</li>
					</ul>
				</div><!-- #tab_2 -->
				<div id="onboard_tabs_3" class="sb_tabPane">
					<h3 class="sb_title" align="center">Here's What You Get.</h3>
					<p align="center">Help us better serve your musical needs and you’ll earn Notes, virtual currency redeemable for rewards and entry to giveaways.</p>
					<ul class="sb_lineList">
						<li class="sb_img_gear"><strong class="sb_theme_textHighlight">Great Prizes.</strong> Almost everything you do in Hello Music Say.So earns you Notes. Use these to redeem prizes from the Rewards Center.</li>
						<li class="sb_img_prizes"><strong class="sb_theme_textHighlight">A Chance To Win A Prize Giveaways.</strong> Redeem your Notes for entry tokens for our giveaways. Buy as many entry tokens for each giveaway as you want and increase your odds of winning.</li>
						<li class="sb_img_hottest"><strong class="sb_theme_textHighlight">Hottest Daily Deals.</strong> Ever log in to the Daily Deals only to find that perfect piece of gear was already sold out? Never Again! Get the jump on the masses and get the gear you need. Hello Music Say.So members also get access to EXCLUSIVE deals - so check back often!</li>
					</ul>
				</div><!-- #tab_3 -->
				<div id="onboard_tabs_4" class="sb_tabPane">
					<h3 class="sb_title" align="center">Okay, Let’s Get Started!</h3>
					<p align="center" style="margin-top: 15px;"><a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_hg"><img src="//<?= BASE_DOMAIN ?>/images/hellomusic/img_profile-survey.png" alt="Take the Profile Survey" /></a><br /><strong>Completing the Profile Survey takes a minute, but we will reward you with a hefty amount of Notes and grant you automatic access to our giveaways.</strong></p>
					<br />
					<br />
					<h2 align="center">Already taken the Profile Survey?<br />Check out some quick-hit activities.</h2>
					<p align="center" style="margin-top: 10px;">
						<a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/polls" class="sb_nav_element" rel="sb_popBox_polls"><img src="//<?= BASE_DOMAIN ?>/images/hellomusic/img_badge_polls.png" alt="Polls" style="margin: 0px 10px;" /></a>
						<a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/surveys" class="sb_nav_element" rel="sb_popBox_surveys"><img src="//<?= BASE_DOMAIN ?>/images/hellomusic/img_badge_surveys.png" alt="Surveys" style="margin: 0px 10px;" /></a>
						<a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/daily-deals" class="sb_nav_element" rel="sb_popBox_daily-deals"><img src="//<?= BASE_DOMAIN ?>/images/hellomusic/img_badge_deals.png" alt="Deals" style="margin: 0px 10px;" /></a>
					</p>
				</div><!-- #tab_4 -->
				<div id="onboard_tabs_5" class="sb_tabPane">
					<p>
						<label><strong>Name</strong></label> <input type="text" />
					</p>
					<p>
						<label><strong>Email</strong></label> <input type="text" />
					</p>
					<p>
						<label><strong>Question</strong></label> <textarea rows="5"></textarea>
					</p>
					<p>
						<input type="submit" class="sb_theme_button" value="Send" />
					</p>
				</div><!-- #tab_5 -->
			</div><!-- .sb_tabs -->
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_2 -->
	<div id="about_tabs_3" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">FAQ</h2>
			<p>
				<strong>What is Hello Music Say.So?</strong><br />
				Hello Music Say.So is a way to directly influence the products and services seen on HelloMusic.com. Members are rewarded by answering polls, participating in surveys, checking out Hello Music daily deals, and giving their opinion about Hello Music products and services.
			<a href="http://bit.ly/I4Qcdy" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>Do I have to pay for anything? Is there any shipping & handling fees for prizes obtained or won?</strong><br />
				No, this is completely free to you. The only thing we want you to do is participate.
			<a href="http://bit.ly/IhZi5s" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>What are Chops used for?</strong><br />
				Chops are the equivalent of experience points and determine your level of influence and involvement. Gaining Chops will increase your Hello Music Say.So level.
			<a href="http://bit.ly/HmMdrD" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>What are Notes used for?</strong><br />
				Notes are the currency you earn by participating in polls, answering surveys, and sharing your ideas. In fact, virtually everything you do in Hello Music Say.So will earn you Notes. These Notes can be exchanged for various prizes and Entry Tokens in the [Reward Center].
			<a href="http://bit.ly/HlFBJQ" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>What are Entry Tokens?</strong><br />
				Entry Tokens are your way of entering prize giveaways. Users that have purchased an Entry Token with their Notes will be entered to win the giveaway. At the end of each giveaway period a prize will be given away to a user that has purchased an Entry Token for the monthly giveaway. You can buy as many Entry Tokens as you want to increase your chance of winning.
			<a href="http://bit.ly/HmTnky" target="_blank">(more...)</a>
	    	        </p>
			<p>
				<strong>Do you really give away the prizes?</strong><br />
				YES! Every prize that is won will be shipped within 4-6 weeks. Users and fans of Hello Music Say.So will get the prizes for playing, not the CEO's nephew or cousin. At the end of each giveaway we will send out an email to all the Hello Music Say.So users, letting you know who the lucky player is. 
			<a href="http://bit.ly/Hn0sRU" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>How do I get my prize?</strong><br />
				When you win a prize we will contact you by email to get the information and mailing address needed to send the prize to you.
			<a href="http://bit.ly/HhxM9o" target="_blank">(more...)</a>
			</p>
                        <p>
                                <strong>Are there any geographic restrictions for playing??</strong><br />
                                Yes, you must reside in the USA to redeem points for prizes. Unfortunately, we cannot ship items out of the USA.
			<a href="http://bit.ly/HAqmlt" target="_blank">(more...)</a>
                        </p>
			<p>
				<strong>Do I have to play every day?</strong><br />
				No, you do not have to play every day, but the more you play and participate, the more Notes you can earn to exchange for Entry Tokens and other prizes.
			<a href="http://bit.ly/HybHS8" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>Can I stop playing at any time?</strong><br />
				Yes, particpate as much (or as little) as you want, but remember, the more you play the better your chances of winning cool prizes.
			<a href="http://bit.ly/IaDAE2" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>How long do the surveys / games take to complete?</strong><br />
				Usually between 5 and 15 minutes. Generally, the longer the survey is, the more Notes you can earn.
			<a href="http://bit.ly/I0gXnH" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>What if I stop a survey in the middle of taking it? Do I still get credit? Do I have to restart it?</strong><br />
				Once you start a survey you must complete it in order to earn your Notes.
			<a href="http://bit.ly/IlkE4U" target="_blank">(more...)</a>
			</p>
			<p>
                                <strong>How often can I get notes/chops for sharing??</strong><br />
                                For details on sharing, click here
                        <a href="http://bit.ly/IRooIa" target="_blank">(more...)</a>
                        </p>
			<p>
				<strong>What are you doing with the information you are collecting?</strong><br />
				We are using it to help make Hello Music better for everyone.
			<a href="http://bit.ly/HvKovH" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>Can I invite other people to play?</strong><br />
				Yes, you can invite friends through Facebook or Twitter. You can also invite friends using our .Send To A Friend. feature found in the settings section of the bar. You can earn additional Notes by getting your friends to play.
                        <a href="http://bit.ly/HpnG8V" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>Can I trade my prize for another prize?</strong><br />
				No, the prize you win, or redeem for, is the prize you get.
                        <a href="http://bit.ly/Hqofhf" target="_blank">(more...)</a>
			</p>
			<p>
				<strong>Can I track the status of the orders I have redeemed/won?</strong><br />
				You will be sent a confirmation of your redemption or win. The delivery time of your item depends on the type of item you have redeemed or won. If you feel like there is a problem with your order, please contact us at hellomusic@say.so.
                        <a href="http://bit.ly/HSWWMw" target="_blank">(more...)</a>
                        </p>
			<p>
				<strong>What are the Daily Deals?</strong><br />
				The Daily Deals are special offers from Hello Music. Hello Music Say.So members also receive EXCLUSIVE deals. We can't leak Hello Music Say.So exclusive daily deals beforehand and they can change daily, so check back regularly to find [new deals and discounts].
                        <a href="http://bit.ly/Hvkgk6" target="_blank">(more...)</a>
			</p>
                        <p>
                                <strong>What is the Promotion Period?</strong><br />
                        <a href="http://bit.ly/InloD4" target="_blank">CLICK HERE</a> for detailed information on current, planned and previous giveaway information.
                        </p>
                        <p>
                                <strong>How do you select the winner(s)s for drawings?</strong><br />
                                You must redeem your Notes for Entry Tokens to be entered in the giveaways. Winners will be chosen at random from all entrants.
			<a href="http://bit.ly/I4Sbyp" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>I am missing Notes or Chops!</strong><br />
                                For missing Notes or Chops
                        <a href="http://bit.ly/HIsXUi" target="_blank">(more...)</a>
                        </p>
                        <p>
                                <strong>I have a question that is not included in this FAQ!</strong><br />
                                You can check <a href="http://bit.ly/HoMfEW" target="_blank">HERE</a> to see if there is an answer to a question that is not included in this FAQ. If you don't see your question or answer, please feel free to send your question using the feedback section.
                        </p>
                        <p>
                                <strong>How do I contact someone?</strong><br />
                                We value our users feedback, concerns, and suggestions and want to hear from you. You can contact us by clicking on the Feedback option at the top of the help menu, or by emailing us directly at hellomusic@say.so. You can also use Twitter or Facebook to get in touch or send feedback.
			<a href="http://bit.ly/HoMgbO" target="_blank">(more...)</a>
			</p>
                        <p>
                                <strong>Where can I find the official Reward and Giveaway rules?</strong><br />
                                Links to all of the official music bar documents are located at the bottom of the 'about' tab.You can also see them 
                        <a href="http://bit.ly/Hpp2QV " target="_blank">here</a>
			</p>
                        <p>
                                <strong>How do I remove the Hello Music Say.So browser extension?</strong><br />
                                For music bar removal instructions...
                        <a href="http://bit.ly/HT0Kdw" target="_blank">(more...)</a>
			</p>
                        <p>
                                <strong>How do I link my Facebook or Twitter account?</strong><br />
 				You can check <a href="http://bit.ly/HIsVeX" target="_blank">HERE</a> for instructions on how to unlink your Facebook / Twitter account, or see below.
			</p>
                        <ol>
				<li>Click .Edit Profile.</li>
				<li>Click to link your Twitter or Facebook account.</li>
				<li>Allow access in order for the accounts to be linked.</li>
                        </ol>
			<p>
				<strong>How do I disconnect my Facebook / Twitter account from the music bar?</strong><br />
			</p>
			<p>
				<strong>Facebook:</strong><br />
			</p>
			<ol>
				<li>Log into Facebook.</li>
				<li>Click on <em>Home</em> &gt; <em>Account Settings.</em></li>
				<li>Click on <em>Apps</em>. You will see <em>Say.So Music Bar</em> listed here.</li>
			</ol>
			<p>
				<strong>Twitter:</strong><br />
			</p>
			<ol>
				<li>Log into Twitter.</li>
				<li>Click on your name &gt; <em>Settings</em>.</li>
				<li>Open the <em>Applications</em> tab and you will see the <em>Say.So Music Bar</em> listed here.</li>
			</ol>
			<br /><br />
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_3 -->
	<div id="about_tabs_4" class="sb_tabPane">
		<div class="sb_scrollPane">
			<h2 class="sb_title">Feedback</h2>
			<div id="sb_feedback_container"></div>
			<script src="//s3.amazonaws.com/getsatisfaction.com/javascripts/feedback-v2.js" type="text/javascript"></script>
			<script type="text/javascript" charset="utf-8">
				var $SQfeedbackWidgetOptions = {};
				$SQfeedbackWidgetOptions.display = "inline";
				$SQfeedbackWidgetOptions.container = "sb_feedback_container";
				$SQfeedbackWidgetOptions.company = "hellomusicsayso";
				$SQfeedbackWidgetOptions.style = "question";
				$SQfeedbackWidgetOptions.product = "sayso_beat_bar";
				$SQfeedbackWidgetOptions.limit = "5";
				$SQfeedbackWidgetOptions.width = "500px";
				$SQfeedbackWidgetOptions.height = "450px";
				var $SQfeedbackInterval = setInterval(function() { // Use interval to ensure that GS's JS is loaded
					if (
						typeof GSFN != 'undefined' &&
						typeof GSFN.feedback_widget != 'undefined' &&
						typeof GSFN.feedback_widget.prototype != 'undefined'
					) {
						clearInterval($SQfeedbackInterval);
						var $SQfeedbackWidget = new GSFN.feedback_widget($SQfeedbackWidgetOptions);
					}
				}, 200);
			</script>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tab_4 -->
	<? if ($this->show_testing_function) { ?>
		<div id="about_tabs_5" class="sb_tabPane">
			<div class="sb_scrollPane">
				<h2 class="sb_title">Top Secret Testing Functions</h2>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reset-surveys-and-polls?renderer=jsonp", success : function (r, s) {} })'>Reset surveys and polls</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reset-external?renderer=jsonp", success : function (r, s) {} })'>Reset Facebook and Twitter External accounts and username</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reset-notifications?renderer=jsonp", success : function (r, s) {} })'>Reset Notifications and User Creation Time</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reset-gamer?renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Reset Game info to just after install (1000 chops, 100 notes)</a></p>
				<p><a href="#" style="color: red;" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reset-all?renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  } })'>Reset this user to 'just created, just installed' state (i.e. All of the Above)</a></p>
				<br />
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_premium=true&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing the primary survey</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=survey&survey_premium=false&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing a regular survey (points only)</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=poll&survey_premium=false&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing a regular poll (points only)</a></p>
				<p><a href="#" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/complete-survey?survey_type=poll&survey_premium=true&renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Simulate completing a premium poll (points only)</a></p>
				<p><a href="#" style="color: green;" onclick='$SQ.ajaxWithAuth({url : "//<?= BASE_DOMAIN ?>/api/test/reward-notes?renderer=jsonp", success : function (r, s) {  if (r.game) $SQ("#sayso-starbar").trigger("frameCommunication", ["updateGame", { newGame: r.game }]);  }})'>Receive 5000 notes</a></p>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_5 -->
	<? } ?>
</div><!-- .sb_tabs -->

<script language="javascript">
	$SQ('span#onboard_tabs_5').click(function(){
		$SQ("#about_tabs_2 .sb_tabs").tabs("select",4)
	});

	$SQ('#sb_popBox_about-saySo .sb_header').insertBefore('#sb_popBox_about-saySo .sb_popBoxInner');
</script>
