<div class="sb_header">
	<h2 class="sb_title"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" /> Surveys</h2>
	<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_header_survey.png" alt="Surveys" class="sb_alignRight" />
</div><!-- .sb_header -->
<p align="right"><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/surveys" class="sb_theme_iconChange sb_nav_element" rel="sb_popBox_surveys">Switch Survey</a></p>

<div id="starbar-survey-<?= $this->survey->id ?>" class="sb_survey_container"></div>
<script type="text/javascript">
	var link="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/survey-redirect?survey_id=<?= $this->survey->id ?>";
	var iframeContainerId = "starbar-survey-<?= $this->survey->id ?>";
	$SQ.insertCommunicationIframe(link, iframeContainerId, 500, 290, "yes"); // Add new iframe!
</script>
