<div id="sayso-starbar-loading-external">
	<span class="sb_img_loading">Loading</span>
</div>
<div id="sayso-starbar-external">
	<script type="text/javascript">document.write("<scr"+"ipt type=\"text/javascript\" src=\"http://www.surveygizmo.com/s3/polljs/<?= $this->survey->external_id ?>-<?= $this->survey->external_key ?>/?cookie="+document.cookie.match(/sg-response-<?= $this->survey->external_id ?>/gi)+"\"></scr"+"ipt>");</script>
</div>
<script type="text/javascript">
	var loadingElement = $S('#sayso-starbar-loading-external');
	var externalContentContainer = $S('#sayso-starbar-external');

	// Hide the container while it loads.
	externalContentContainer.fadeTo(0,0);

	function enableClickableRadios() {
		// Ensure that poll.js is loaded (it's loaded at the bottom of the SG content)
		if ((typeof SG_init_page) != 'undefined' && (typeof SGSurvey) != 'undefined') {
			var domain = $S('#sg_SubmitButton').data("domain");
			var survey = null;

			// SG_init_page still fails sometimes, if poll.js is partially loaded
	        try
	        {
				SG_init_page($S('#survey-wrapper-<?= $this->survey->external_id ?>'));
				survey = new SGSurvey(SGAPI.surveyData["<?= $this->survey->external_id ?>"], false);
				survey.InitPage(3);

				// If we've made it this far, everything has loaded properly.
				clearInterval(repeatUntilEmbedLoads);

				// Fade in the container.
				loadingElement.fadeTo(500, 0);
				externalContentContainer.fadeTo(500, 1);

				// Make the radio buttons clickable
				var elemRadios = $S('input:radio');
				elemRadios.each(function(){
					$S(this).bind({
						click: function(event){
							$S(this).attr('checked', 'checked');
							survey.Vote(domain);
							survey.ShowResults(domain);
							setTimeout(function() {
								$('#sb-survey-completed').fadeIn(500)
							}, 1000);
						}
					});
				});
	        }
	        catch (err) {}
		}
	}

	var repeatUntilEmbedLoads = setInterval(enableClickableRadios, 100);

</script>
<div id="sayso-starbar-embed">
	<div id="sb-survey-completed">
		<? if ($this->survey->premium) { ?>
			<p>Congratulations! You earned <strong class="sb_theme_textHighlight_alt">2 Notes</strong> &amp;  <strong class="sb_theme_textHighlight_alt">500 Chops</strong></p>
		<? } else { ?>
			<p>Congratulations! You earned <strong class="sb_theme_textHighlight">1 Note</strong> &amp;  <strong class="sb_theme_textHighlight">250 Chops</strong></p>
		<? } ?>
	</div>
</div>
