<?= $this->partial('remote/init-remote.phtml'); ?>
<div id="sayso-starbar-external">
	<script type="text/javascript">document.write("<scr"+"ipt type=\"text/javascript\" src=\"http://www.surveygizmo.com/s3/polljs/<?= $this->survey->external_id ?>-<?= $this->survey->external_key ?>/?bundle_of_joy=<?= $this->bundle_of_joy ?>\"></scr"+"ipt>");</script>
</div>
<script type="text/javascript">
	function enableClickableRadios() {
		// Ensure that poll.js is loaded (it's loaded at the bottom of the SG content)
		if ((typeof SG_init_page) != 'undefined' && (typeof SGSurvey) != 'undefined') {
			var domain = $SQ('#sg_SubmitButton').data("domain");
			var survey = null;

			// SG_init_page still fails sometimes, if poll.js is partially loaded
	        try
	        {
				SG_init_page($SQ('#survey-wrapper-<?= $this->survey->external_id ?>'));
				survey = new SGSurvey(SGAPI.surveyData["<?= $this->survey->external_id ?>"], false);
				survey.InitPage(3);

				// If we've made it this far, everything has loaded properly.
				clearInterval(repeatUntilEmbedLoads);
				setTimeout(function() { // add delay to frame resizing, otherwise height is calculated while elements are being rendered, causing funky behaviour
					$SQ.remoteControl.loadComplete(true, 62+$SQ('.sg-question-set').totalHeight());
				}, 200);

				// Make the radio buttons clickable
				var elemRadios = $SQ('input:radio');
				elemRadios.each(function(){
					$SQ(this).bind({
						click: function(event){
							$SQ(this).attr('checked', 'checked');
							
							// Simulate what survey.Vote(domain) does... which is submit the vote via ajax
							var vote=$SQ("#sg_FormFor<?= $this->survey->external_id ?>").serialize();
							var link=["http://",domain,"/s3/polljs/<?= $this->survey->external_id ?>-<?= $this->survey->external_key ?>?_vote=",escape(vote)].join("");
							$SQ.ajax({url:link,dataType:"jsonp"});
							
							$SQ.ajaxWithAuth({
								url : "http://<?= BASE_DOMAIN ?>/api/survey/user-poll-submit?survey_id=<?= $this->survey->id ?>",
								success : function (r, s) {}
							});

							$SQ.remoteControl.alertMessage('The Starbar is aware of this poll completion!');

							survey.ShowResults(domain);
							setTimeout(function() {
								$SQ('#sb-survey-completed').fadeIn(500);
							}, 500);
						}
					});
				});
				
				$SQ.getScript("http://platform.twitter.com/widgets.js", function(){
					function handleTweetEvent(event){
						if (event) {
							// @todo Tweet has occured, reward user!
						}
					}
					twttr.events.bind('tweet', handleTweetEvent);
				});
	        }
	        catch (err) {}
		}
	}

	var repeatUntilEmbedLoads = setInterval(enableClickableRadios, 100);

</script>
<div id="sayso-starbar-embed">
	<div id="sb-survey-completed">
		<? if ($this->survey->premium) { ?>
			<p>Excellent! You earned <strong class="sb_theme_textHighlight_alt">2 Notes</strong> &amp;  <strong class="sb_theme_textHighlight_alt">500 Chops</strong></p>
		<? } else { ?>
			<p>Excellent! You earned <strong class="sb_theme_textHighlight">1 Note</strong> &amp;  <strong class="sb_theme_textHighlight">250 Chops</strong></p>
		<? } ?>
		<p class="sb_embedShare">
			<a class="sb_externalShare"
				href="http://www.facebook.com/dialog/feed?app_id=<?= urlencode($this->facebook_app_id) ?>&link=<?= urlencode($this->share_link) ?>&caption=<?= urlencode($this->facebook_share_caption) ?>&picture=<?= urlencode($this->facebook_share_image_url) ?>&redirect_uri=<?= urlencode($this->facebook_share_callback_url) ?>">
				<img src="http://<?= BASE_DOMAIN ?>/images/generic/facebook-share-icon.png" alt="Facebook" />
			</a>
			<a class="twitter-share-button"
				data-related="<?= $this->twitter_share_related_users ?>"
				data-hashtags="<?= $this->twitter_share_hashtags ?>"
				data-via="<?= $this->twitter_share_via_user ?>"
				data-url="<?= $this->share_link ?>"
				data-text="<?= $this->twitter_share_text ?>"
				data-count="none"
				href="https://twitter.com/intent/tweet">
					<img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_twitter.png" alt="Twitter" />
			</a>

			Share this poll to earn extra points
		</p>
	</div>
</div>
