<div class="sb_header">
	<h2 class="sb_title"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" /> Surveys</h2>
	<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_header_survey.png" alt="Surveys" class="sb_alignRight" />
</div><!-- .sb_header -->
<div class="sb_popBoxInner sb_triangle-solid">
	<div class="sb_popContent">
		<p align="right"><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/surveys" class="sb_theme_iconChange sb_nav_element" rel="sb_popBox_surveys">Switch Survey</a></p>
		<iframe src="http://www.surveygizmo.com/s3/<?= $this->survey->external_id ?>/<?= $this->survey->external_key ?>?bundle_of_joy=" width="100%" height="95%"></iframe>
	</div><!-- .sb_popContent -->
</div><!-- .sb_popBoxInner -->
