<?= $this->partial('remote/init-remote.phtml', null, array('starbar' => $this->starbar)); ?>
<div id="sayso-starbar-external">
	<script type="text/javascript">document.write("<scr"+"ipt type=\"text/javascript\" src=\"//www.surveygizmo.com/s3/polljs/<?= $this->survey->external_id ?>-<?= $this->survey->external_key ?>/\"></scr"+"ipt>");</script>
</div>
<link href='/css/surveygizmo/polls-<?= $this->starbar->short_name ?>.css' rel='stylesheet' media='all' type='text/css' />
<script type="text/javascript">
	$SQ(function () {
		function enableClickableRadios() {
			// Ensure that poll.js is loaded (it's loaded at the bottom of the SG content)
			if ((typeof SG_init_page) != 'undefined' && (typeof SGSurvey) != 'undefined') {
				var externalContentElem = $SQ('#sayso-starbar-external');
				var domain = $SQ('#sg_SubmitButton').data("domain");
				var survey = null;

				// SG_init_page still fails sometimes, if poll.js is partially loaded
				try
				{
					SG_init_page($SQ('#survey-wrapper-<?= $this->survey->external_id ?>'));
					survey = new SGSurvey(SGAPI.surveyData["<?= $this->survey->external_id ?>"], false);
					survey.InitPage(3);

					// If we've made it this far, everything has loaded properly.
					clearInterval(repeatUntilEmbedLoads);

					$i = 15; // Check if CSS has loaded a maximum of 15 times, i.e. for 3000 ms, or 3 seconds
					// After that assume it has (or give up regardless) and show the poll
					var cssCheckInterval = setInterval(function(){
						if (externalContentElem.css('display') == 'inline-table') { // Our css is loaded!
							clearInterval(cssCheckInterval);
							externalContentElem.css('display', 'block');
							$SQ.remoteControl.loadComplete(true, 62+$SQ('.sg-survey-form').outerHeight());
						}
						$i--;
						if ($i < 1) externalContentElem.css('display', 'inline-table');
					}, 200);

					// Make the radio buttons clickable
					var elemRadios = $SQ('input:radio');
					elemRadios.each(function(){
						$SQ(this).bind({
							click: function(event){
								$SQ(this).attr('checked', 'checked');

								// Simulate what survey.Vote(domain) does... which is submit the vote via ajax
								var vote=$SQ("#sg_FormFor<?= $this->survey->external_id ?>").serialize();
								var link=["//",domain,"/s3/polljs/<?= $this->survey->external_id ?>-<?= $this->survey->external_key ?>?_vote=",escape(vote)].join("");
								$SQ.ajax({url:link,dataType:"jsonp"});

								$SQ.ajax({
									dataType:"jsonp",
									url : "//<?= BASE_DOMAIN ?>/api/survey/user-poll-submit?renderer=jsonp&survey_id=<?= $this->survey->id ?>&user_id=<?= $this->user_id ?>&user_key=<?= $this->user_key ?>&starbar_id=<?= $this->starbar_id ?>&external_choice_id="+$SQ(this).attr('value'),
									beforeSend : function(x) {
										if (x && x.overrideMimeType) {
											x.overrideMimeType("application/j-son;charset=UTF-8");
										}
									},
									success : function (response, status, jqXHR) {
										$SQ.remoteControl.updateGame(response.game);
									}
								});

								survey.ShowResults(domain);
								setTimeout(function() {
									$SQ('#sb-survey-completed').fadeTo(500, 1);
								}, 500);
							}
						});
					});

					$SQ.getScript("//platform.twitter.com/widgets.js", function(){
						function handleTweetEvent(event){
							if (event) {
								$SQ.remoteControl.handleTweet('poll', <?= $this->survey->id ?>);
								$SQ('.sb_externalShare_twitter').bind('click', function(e) {
									e.preventDefault();
									e.stopPropagation();
									return false;
								});
							}
						}
						twttr.events.bind('tweet', function(event) { handleTweetEvent(event) });
					});
				}
				catch (err) {}
			}
		}

		var repeatUntilEmbedLoads = setInterval(enableClickableRadios, 100);
	});

</script>
<div id="sayso-starbar-embed">
	<div id="sb-survey-completed">
		<? if ($this->survey->reward_category == "premium") { ?>
			<p>Excellent! You earned <strong class="sb_theme_textHighlight_alt">50 Notes</strong> &amp; <strong class="sb_theme_textHighlight_alt">500 Chops</strong></p>
		<? } else { ?>
			<p>Excellent! You earned <strong class="sb_theme_textHighlight">25 Notes</strong> &amp; <strong class="sb_theme_textHighlight">250 Chops</strong></p>
		<? } ?>
		<div class="sb_externalShares">
			<!-- FACEBOOK -->
			<a class="sb_externalShare sb_externalShare_facebook" rel="sb_mini-note-reward_facebook" 	href="#"
				onclick="return $SQ.remoteControl.handleFacebookShare('//www.facebook.com/dialog/feed?app_id=<?= urlencode($this->facebook_app_id) ?>&link=<?= urlencode($this->share_link) ?>&caption=<?= urlencode($this->facebook_share_caption) ?>&picture=<?= urlencode($this->facebook_share_image_url) ?>&redirect_uri=<?= urlencode($this->facebook_share_callback_url) ?>&name=<?= urlencode($this->facebook_title) ?>&description=<?= urlencode($this->facebook_description) ?>', 'poll', <?= $this->survey->id ?>);">
				Facebook Share
			</a>
			<span class="sb_mini-note-reward sb_mini-note-reward_facebook" id="sb_mini-note-reward_facebook">+50</span>
			<!-- / facebook -->

			<! -- TWITTER -->
			<script type="text/javascript">
				$SQ.getScript("//platform.twitter.com/widgets.js", function(){
					function handleTweetEvent(event){
						if (event) {
							$SQ('#sayso-starbar').trigger('frameCommunication', ['handleTweet', {
								shared_type: 'starbar',
								shared_id: window.sayso.starbar.id
							}]);
						}
					}
					twttr.events.bind('tweet', function(event) { handleTweetEvent(event) });
				});
			</script>

			<div class="sb_externalShare sb_externalShare_twitter" rel="sb_mini-note-reward_twitter">
				<a class="twitter-share-button"
					data-related="<?= $this->twitter_share_related_users ?>"
					data-hashtags="<?= $this->twitter_share_hashtags ?>"
					data-via="<?= $this->twitter_share_via_user ?>"
					data-url="<?= $this->share_link ?>"
					data-text="<?= $this->twitter_share_text ?>"
					data-count="none"
					href="https://twitter.com/intent/tweet">
				</a>
			</div>

			<span class="sb_mini-note-reward sb_mini-note-reward_twitter" id="sb_mini-note-reward_twitter">+50</span>
			<!-- / twitter -->
			Share this poll to earn extra points
		</div>
	</div>
</div>
