<script type="text/javascript">
	window.opener.refreshConnectExternal('facebook');
	setTimeout(function() {
		$SQ('#sb-survey-completed').fadeIn(500)
	}, 1000);
</script>
<div id="sayso-starbar-embed">
	Thank you, you have successfully connected your Facebook account.<br /><br />
	<a href="#" onclick="window.close(); return false;">Take me back!</a><br /><br />
	<div id="sb-survey-completed">
		<p>Congratulations! You earned <strong class="sb_theme_textHighlight_alt">4 Notes</strong> &amp;  <strong class="sb_theme_textHighlight_alt">1000 Chops</strong></p>
	</div>
</div>
