	<div class="sb_header">
	<a href="http://www.saysollc.com" target="_blank"><img src="//<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="Hello Music" /></a>
	</div><!-- .sb_header -->  
	<div class="sb_popBoxInner">
	<div class="sb_popContent">
		<div class="sb_tabs">
		<ul>
			<li><a href="#onboard_tabs_1">I'm In!</a></li>
			<li><a href="#onboard_tabs_2">What Can I Do?</a></li>
			<li><a href="#onboard_tabs_3">What Do I Get?</a></li>
			<li><a href="#onboard_tabs_4">Get Started</a></li>
		</ul>
		
		<div id="onboard_tabs_1" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Welcome!</h2>
			<h3>We designed the steps below to help you get oriented. If you find you need additional help, feel free to <a href="mailto:hellomusic@say.so">contact us</a>.</h3>
			<p align="center"><big>By installing the Say.So Music Bar, you’ve achieved Musician level, and earned 1000 Chops and 100 Notes.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_chops"><strong class="sb_theme_textHighlight">"Chops"</strong> are the currency of influence. You earn them for sharing your expertise, experience and opinion, and your Chops determine your access to increasingly important levels of access and influence.</li>
				<li class="sb_img_notes"><strong class="sb_theme_textHighlight">"Notes"</strong> are almost as good as cash. Virtually everything you do earns you Notes, which can be redeemed for all manner of Hello Music goodies (<a class="sb_nav_element" rel="sb_popBox_rewards" href="//local.sayso.com/starbar/hellomusic/rewards">see the Rewards Center</a>)</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_1 -->
		<div id="onboard_tabs_2" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Give Your Opinion, Share It and Earn!</h2>
			<p align="center"><big>Your point of view and opinion are invaluable. Express yourself through fun polls and surveys, and earn points by sharing Daily Deals.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_polls"><strong class="sb_theme_textHighlight">Polls</strong> are quick hits of opinion we’d like you to share. Answer as many or as few as you’d like, and for each one we’ll drop a little something in your gig bag.</li>
				<li class="sb_img_surveys"><strong class="sb_theme_textHighlight">Surveys</strong> are the big money gigs. These are important efforts to gauge how we are doing, and we’ll make sure you are compensated accordingly. </li>
				<li class="sb_img_deals"><strong class="sb_theme_textHighlight">Deals - </strong> You know about the Daily Deals. We've incorporated them into the Hello Music Say.So and any time you check them out, or share them to Facebook or Twitter, we'll compensate you with Notes and Chops. Plus we have added exclusive deals for Hello Music Say.So members only. No purchase necessary.</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_2 -->
		<div id="onboard_tabs_3" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Here's What You Get.</h2>
			<p align="center"><big>Help us better serve your musical needs and you’ll earn Notes, virtual currency redeemable for rewards and entry to giveaways.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_gear"><strong class="sb_theme_textHighlight">Great Prizes.</strong> Almost everything you do in Hello Music Say.So earns you Notes. Use these to redeem prizes from the Rewards Center.</li>
				<li class="sb_img_prizes"><strong class="sb_theme_textHighlight">A Chance To Win A Prize Giveaways.</strong> Redeem your Notes for entry tokens for our giveaways. Buy as many entry tokens for each giveaway as you want and increase your odds of winning.</li>
				<li class="sb_img_hottest"><strong class="sb_theme_textHighlight">Hottest Daily Deals.</strong> Ever log in to the Daily Deals only to find that perfect piece of gear was already sold out? Never Again! Get the jump on the masses and get the gear you need. Hello Music Say.So members also get access to EXCLUSIVE deals - so check back often!</li>
			</ul>	  
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_3 -->
		
		<div id="onboard_tabs_4" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Okay, Let’s Get Started!</h2>
			<p align="center" style="margin-top: 15px;"><a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_hg"><img src="//<?= BASE_DOMAIN ?>/images/hellomusic/img_profile-survey.png" alt="Take the Profile Survey" /></a><br /><strong>Completing the Profile Survey takes a minute, but we will reward you with a hefty amount of Notes and grant you automatic access to our giveaways.</strong></p>
			<br />
			<br />
			<h2 align="center">Not ready to take the Profile Survey yet?  <br />Check out some quick-hit activities.</h2>
			<p align="center" style="margin-top: 10px;">
				<a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/polls" class="sb_nav_element" rel="sb_popBox_polls"><img src="//<?= BASE_DOMAIN ?>/images/hellomusic/img_badge_polls.png" alt="Polls" style="margin: 0px 10px;" /></a>
				<a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/surveys" class="sb_nav_element" rel="sb_popBox_surveys"><img src="//<?= BASE_DOMAIN ?>/images/hellomusic/img_badge_surveys.png" alt="Surveys" style="margin: 0px 10px;" /></a>
				<a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/daily-deals" class="sb_nav_element" rel="sb_popBox_daily-deals"><img src="//<?= BASE_DOMAIN ?>/images/hellomusic/img_badge_deals.png" alt="Deals" style="margin: 0px 10px;" /></a>
			</p>	   
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_4 -->
		
		</div><!-- .sb_tabs -->
	</div><!-- .sb_popContent -->
	</div><!-- .sb_popBoxInner -->
