  <div class="sb_header">
  	<a href="http://www.saysollc.com" target="_blank"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="Hello Music" /></a>
  </div><!-- .sb_header -->  
  <div class="sb_popBoxInner">
    <div class="sb_popContent">
    	<div class="sb_tabs">
        <ul>
          <li><a href="#onboard_tabs_1">I'm In!</a></li>
          <li><a href="#onboard_tabs_2">What Can I Do?</a></li>
          <li><a href="#onboard_tabs_3">What Do I Get?</a></li>
          <li><a href="#onboard_tabs_4">Okay, Let's Rock</a></li>
        </ul>
        
        <div id="onboard_tabs_1" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2 class="sb_title" align="center">Congratulations! You've Got Rhythm.</h2>
            <p align="center"><big>By installing the Hello Music Beat Bar, you achieved Musician Level, and earned 1000 Chops and 100 Notes.</big></p>
            <br />
            <ul class="sb_lineList">
            	<li class="sb_img_chops"><strong class="sb_theme_textHighlight">"Chops"</strong> are the currency of influence. You earn them for sharing your expertise, experience and opinion, and your <strong class="sb_theme_textHighlight">Chops</strong> determine your access to increasingly important levels of access and influence.</li>
              	<li class="sb_img_notes"><strong class="sb_theme_textHighlight">"Notes"</strong> are almost as good as cash. Virtually everything you do in the BeatBar earns you Notes, which can be redeemed for all manner of HelloMusic goodies (see the Rewards Center)s</li>
            </ul>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_1 -->
        <div id="onboard_tabs_2" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2 class="sb_title" align="center">Give Your Opinion, Share It And Earn!</h2>
            <p align="center"><big>Your point-of-view and opinion is invaluable. Express that agency through fun polls, surveys and product choices.</big></p>
            <br />
            <ul class="sb_lineList">
            	<li class="sb_img_polls"><strong class="sb_theme_textHighlight">Polls</strong> are quick hits of opinion we'd like you to share.  Answer as many or as few as you like, and for each one we'll grease your virtual palms with lucre. </li>
              <li class="sb_img_surveys"><strong class="sb_theme_textHighlight">Surveys</strong> are the meaty earning opportunities. These are important efforts to gauge the course of our ship and the music industry, and commensurately valued.</li>
              <li class="sb_img_deals"><strong class="sb_theme_textHighlight">Deals - </strong> You know about the Daily Deals. We've incorporated them into the BeatBar and any time you check them out, or share them to Facebook or Twitter, we'll compensate you with Notes and Chops. No purchase necessary.</li>
            </ul>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_2 -->
        <div id="onboard_tabs_3" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2 class="sb_title" align="center">What do I Get?</h2>
            <p align="center"><big>Privileges and Stuff! Help us better serve you, and you'll earn virtual currency redeemable for actual goods!</big></p>
            <br />
            <ul class="sb_lineList">
            	<li class="sb_img_gear"><strong class="sb_theme_textHighlight">Free Gear.</strong> Virtually everything you do in the Beat Bar earns you Notes, which can be redeemed for all manner of Hello Music goodies. Check out the Rewards Center for a full list of swag, and hurry before they dissapear!</li>
              <li class="sb_img_prizes"><strong class="sb_theme_textHighlight">A Chance To Win The Weekly &amp; Monthly Giveaways. </strong> We give out the best prizes during our weekly and montly giveaways. To get in on it just redeem your Notes for entry tokens. Buy as many entry tokens for each of the giveaways – the more tokens you buy the better your odds winning.</li>
              <li class="sb_img_hottest"><strong class="sb_theme_textHighlight">Hottest Daily Deals.</strong> Tired of finding out about the perfect Daily Deal then finding out it's already sold out? Never again! Be the first to find out.</li>
            </ul>      
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_3 -->
        
        <div id="onboard_tabs_4" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2 class="sb_title" align="center">Okay, Let's Rock</h2>
            <p align="center" style="margin-top: 15px;"><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_lg"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_influencer-survey.png" alt="Take the Influencer Survey" /></a><br /><strong>Lay down a bass line-- the Influencer Survey is worth big <br />Notes and automatic access to the sweet weekly giveaways!</strong></p>
            <br />
            <br />
            <h2 align="center">Not ready to take the Influencer Survey yet? <br />Check out some quick-hit activities.</h2>
            <p align="center" style="margin-top: 10px;">
            	<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/polls" class="sb_nav_element" rel="sb_popBox_polls"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_badge_polls.png" alt="Polls" style="margin: 0px 10px;" /></a>
              <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/surveys" class="sb_nav_element" rel="sb_popBox_surveys"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_badge_surveys.png" alt="Surveys" style="margin: 0px 10px;" /></a>
              <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/daily-deals" class="sb_nav_element" rel="sb_popBox_daily-deals"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_badge_deals.png" alt="Deals" style="margin: 0px 10px;" /></a>
            </p>       
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_4 -->
        
      </div><!-- .sb_tabs -->
    </div><!-- .sb_popContent -->
  </div><!-- .sb_popBoxInner -->
