  <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_onboard_guitar.png" alt="Guitar" class="img_onboard" />
  
  <div class="sb_header">
  	<a href="http://www.saysollc.com" target="_blank"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="Hello Music" /></a>
  </div><!-- .sb_header -->  
  <div class="sb_popBoxInner">
    <div class="sb_popContent">
    	<div class="sb_tabs">      	
      	<h3 class="sb_title">Take a Quick Tour</h3>
        <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=23" class="sb_surveyLaunch sb_nav_element" rel="sb_popBox_surveys_lg">Get Started!</a>
        <ul>
          <li><a href="#onboard_tabs_1"></a></li>
          <li><a href="#onboard_tabs_2">What Can I Do?</a></li>
          <li><a href="#onboard_tabs_3">What Can I Get?</a></li>
        </ul>
        
        <div id="onboard_tabs_1" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2 class="sb_title" align="center">Congratulations! You have rhythm.</h2>
            <p align="center"><big>By installing the Hello Music BeatBar you reached the Musician level,<br /> and earned <span class="sb_theme_textHighlight">1000 Chops</span> and <span class="sb_theme_textHighlight">100 Notes</span>... and there're a lot more<br /> where those came from!</big></p>
            <br />
            <ul class="sb_lineList">
            	<li class="sb_img_chops"><strong class="sb_theme_textHighlight">"Chops"</strong> are the currency of influence. You earn them for sharing your expertise, experience and opinion, and your <strong class="sb_theme_textHighlight">Chops</strong> determine your access to increasingly important levels of access and influence.</li>
              	<li class="sb_img_notes"><strong class="sb_theme_textHighlight">"Notes"</strong> are almost as good as cash. Virtually everything you do in the BeatBar earns you Notes, which can be redeemed for all manner of Hello Music goodies (see the Rewards Center)</li>
            </ul>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_1 -->
        <div id="onboard_tabs_2" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2 class="sb_title" align="center">Earn, Baby, Earn!</h2>
            <p align="center"><big>... by answering Polls, taking Surveys and checking out the Daily Deals... right here in the BeatBar.</big></p>
            <br />
            <ul class="sb_lineList">
            	<li class="sb_img_polls"><strong class="sb_theme_textHighlight">Polls</strong> are quick hits of opinion we'd like you to share.  Answer as many or as few as you like, and for each one we'll grease your virtual palms with lucre.</li>
              <li class="sb_img_surveys"><strong class="sb_theme_textHighlight">Surveys</strong> are the meaty earning opportunities. These are important efforts to gauge the course of our ship and the music industry, and commensurately valued.</li>
              <li class="sb_img_deals"><strong class="sb_theme_textHighlight">Deals - </strong> You know about the Daily Deals.  We've incorporated them into the BeatBar and any time you check them out, or share them to Facebook or Twitter, we'll compensate you with Notes and Chops.  No purchase necessary.</li>
            </ul>
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_2 -->
        <div id="onboard_tabs_3" class="sb_tabPane">
          <div class="sb_scrollPane">
          	<h2 class="sb_title" align="center">What Can I Get?</h2>
            <p align="center"><big>
            Free gear. Extra discounts and coupons. Entries to weekly gear giveaways. Every Note earned is redeemable for great gear, discounts and musician services. Every ounce of Chops achieved unlocks access to valuable giveaways.</big></p>
            <p align="center"><big>If you manage to level-up your Chops to <span class="sb_theme_textHighlight">BUSKER</span> class, you'll be eligible for entry into the weekly giveaways.</big></p>
            <p align="center"><big>When your Chops earn you <span class="sb_theme_textHighlight">MEMBER OF THE BAND</span> status, you'll be one of a select few eligible for the first-month giveaway of a Gibson Acoustic Guitar!</big></p>            
          </div><!-- .sb_scrollPane -->
        </div><!-- #tab_3 -->
      </div><!-- .sb_tabs -->
    </div><!-- .sb_popContent -->
  </div><!-- .sb_popBoxInner -->
