<div id="sb_slideshow">
  <div class="sb_promoBG sb_promo_week1">
  	<div class="sb_slide">
      <div class="sb_header">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" />
      </div><!-- .sb_header -->
      <div class="sb_promo_details">
      	<p>Marshall Electronics V89 Condenser<br />Microphone and Sony 7506 Headphones</p>
        <p><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards" class="sb_nav_element sb_theme_button" rel="sb_popBox_rewards"><span class="sb_theme_buttonArrow">Get Entry Tokens</span></a></p>
        <p style="line-height: 15px"><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_lg">Influencer Survey</a> to be eligible for the giveaways.</small></p>
      </div><!-- .sb_promo_details -->
    </div><!-- .sb_slide -->
  </div><!-- .sb_promo_week1 -->
  <div class="sb_promoBG sb_promo_week2">
  	<div class="sb_slide">
      <div class="sb_header">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" />
      </div><!-- .sb_header -->
      <div class="sb_promo_details">
      	<p>Toca Synergy Series Congas, SDVR12 Djembe, and a LP Black Beauty Cowbell.</p>
        <p><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards" class="sb_nav_element sb_theme_button" rel="sb_popBox_rewards"><span class="sb_theme_buttonArrow">Get Entry Tokens</span></a></p>
        <p style="line-height: 15px"><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_lg">Influencer Survey</a> to be eligible for the giveaways.</small></p>
      </div><!-- .sb_promo_details -->
    </div><!-- .sb_slide -->
  </div><!-- .sb_promo_week2 -->
  <div class="sb_promoBG sb_promo_week3">
  	<div class="sb_slide">
      <div class="sb_header">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" />
      </div><!-- .sb_header -->
      <div class="sb_promo_details">
      	<p>Akai MiniAK and a Arturia Dr. Bob Synth Software.</p>
        <p><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards" class="sb_nav_element sb_theme_button" rel="sb_popBox_rewards"><span class="sb_theme_buttonArrow">Get Entry Tokens</span></a></p>
        <p style="line-height: 15px"><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_lg">Influencer Survey</a> to be eligible for the giveaways.</small></p>
      </div><!-- .sb_promo_details -->
    </div><!-- .sb_slide -->
  </div><!-- .sb_promo_week3 -->
  <div class="sb_promoBG sb_promo_week4">
  	<div class="sb_slide">
      <div class="sb_header">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/logo_hellomusic.png" alt="HelloMusic logo" width="70" />
      </div><!-- .sb_header -->
      <div class="sb_promo_details" style="width: 260px;">
      	<p>The Takamine EF340SCGN has a solid cedar top, mahogany neck and sides and rosewood fretboard for a great warm vintage tone.</p>
        <p><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards" class="sb_nav_element sb_theme_button" rel="sb_popBox_rewards"><span class="sb_theme_buttonArrow">Get Entry Tokens</span></a></p>
        <p style="line-height: 15px"><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_lg">Influencer Survey</a> to be eligible for the giveaways.</small></p>
      </div><!-- .sb_promo_details -->
    </div><!-- .sb_slide -->
  </div><!-- .sb_promo_week4 -->
</div><!-- #sb_slideshow -->
<div id="sb_slideshow_nav">
	<span class="sb_prev">prev</span>
  <span class="sb_next">next</span>
</div><!-- #sb_slideshow_nav -->
