<div class="sb_header">
    <h2 class="sb_title">Rewards Center</h2>
</div><!-- .sb_header -->
<div class="sb_scrollPane">
    <p>Make sure to get your tokens for the weekly giveaways and keep earning to be eligible for the final giveaway.</p>
    <p><strong class="sb_theme_textHighlight">Select an item below</strong></p>
  
  <div class="sb_rewards">   
    <?= $this->partialLoop('hellomusic/reward.phtml', $this->rewards) ?>
  </div><!-- .sb_rewards -->
</div><!-- .sb_scrollPane -->

<div id="sb_rewardsOverlay"></div>
<script language="javascript">
    $SQ(function(){
        var sayso = window.sayso;
        var overlay = $SQ('#sayso-starbar #sb_rewardsOverlay');

        $SQ(document).bind('sb_cbox_cleanup', function () {
            overlay.hide();
        });
        
        // select a reward
        $SQ('#sayso-starbar .sb_rewards')
            .find('.sb_rewardItem')
            .not('.sb_rewardItem_disabled')
            .unbind('click').bind('click', function(e){
                
                var container = $SQ(this).dataContainer();
                
                $SQ.ajaxWithAuth({
                    url : 'http://' + sayso.baseDomain + '/starbar/hellomusic/reward-redeem',
                    data : { good_id : container.getId() },
                    success : function (response) {
                        overlay.html(response.data.html).show();
                        // open color box
                        $SQ.sb_colorbox({
                            width:"220px", height:'450px',
                            inline: true, initialWidth: 50, initialHeight: 50,
                            speed: 500, overflow: 'hidden', transition: 'fade',
                            href:"#sb_rewardsOverlay"
                        });
                    }
                });
        });
    });
</script>