<?php

$reward = $this->model;
/* @var $reward Gaming_BigDoor_Good */
$gamer = $reward->getGame()->getGamer();
$notes = $gamer->getCurrencyByTitle('notes')->current_balance;
$percentNotesToCost = round(((int) $notes / (int) $reward->cost) * 100);
if ($percentNotesToCost > 100) $percentNotesToCost = 100;

?>
<div class="sb_rewardItem <?= $reward->isRedeemable() ? '' : 'sb_rewardItem_disabled' ?>">
    <?php if (!$reward->isRedeemable()) : ?>
    <div class="sb_rewardItem_disabledMsg">
        <h1 class="sb_textError">!</h1>
        <p>Must complete<br /><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/embed-survey?survey_id=1" class="sb_nav_element" rel="sb_popBox_surveys_hg" title="Take premium survey now!" style="position: relative; top: -5px;">Premium Survey</a></p>
    </div><!-- .sb_rewardItem_disabledMsg -->
    <?php endif ?>
    <div class="sb_rewardHeader">
        <?= $reward->title ?>
    </div><!-- .sb_rewardHeader -->   
    <div class="sb_rewardImg">
        <img src="<?= $reward->url_preview ?>" alt="Reward" />
    </div><!-- .sb_rewardImg -->
    <div class="sb_rewardBase">
        <div class="sb_user-points-box">                    
            <div class="sb_progress_bar"><span class="sb_currency_percent" style="width: <?= $percentNotesToCost ?>%"></span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> <?= $reward->cost ?></span></div>
        </div><!-- .user-points-box -->
        <?php if (!$reward->isRedeemable()) : ?>
        <p class="sb_reward_levelReq"><span>Survey Requirement</span></p>
        <?php endif ?>
        <span class="sb_theme_button sb_theme_button_grey">Redeem</span>
    </div><!-- .sb_rewardBase -->
</div><!-- .sb_rewardItem -->