<div class="sb_header">
	<h2 class="sb_title">Rewards Center</h2>
</div><!-- .sb_header -->
<div class="sb_scrollPane">
	<p>Make sure to get your tokens for the weekly giveaways and keep earning to be eligible for the final giveaway.</p>
	<p><strong class="sb_theme_textHighlight">Select an item below</strong></p>
  
  <div class="sb_rewards">    
    <div class="sb_rewardItem sb_rewardItem_disabled">
    	<div class="sb_rewardItem_disabledMsg">
      	<h1 class="sb_textError">!</h1>
        <p>Must be Level 2 - Busker</p>
      </div><!-- .sb_rewardItem_disabledMsg -->
      <div class="sb_rewardHeader">
        $25 Ticketmaster Gift Certificate
      </div><!-- .sb_rewardHeader -->  	
      <div class="sb_rewardImg">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_reward.jpg" alt="Reward" />
      </div><!-- .sb_rewardImg -->
      <div class="sb_rewardBase">
      	<div class="sb_user-points-box">					
					<div class="sb_progressBar"><span class="sb_progressBarPercent">40</span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> 2000</span></div>
				</div><!-- .user-points-box -->
        <p class="sb_reward_levelReq"><span>Level Requirement</span></p>
        <a href="" class="sb_theme_button sb_theme_button_grey">Redeem</a>
      </div><!-- .sb_rewardBase -->
    </div><!-- .sb_rewardItem -->
    
    
    
    <div class="sb_rewardItem">
      <div class="sb_rewardHeader">
        $25 Ticketmaster
      </div><!-- .sb_rewardHeader -->  	
      <div class="sb_rewardImg">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_reward.jpg" alt="Reward" />
      </div><!-- .sb_rewardImg -->
      <div class="sb_rewardBase">
      	<div class="sb_user-points-box">					
					<div class="sb_progressBar"><span class="sb_progressBarPercent">100</span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> 1000</span></div>
				</div><!-- .user-points-box -->
        <p class="sb_reward_levelReq"></p>
        <a href="" class="sb_theme_button">Redeem</a>
      </div><!-- .sb_rewardBase -->
    </div><!-- .sb_rewardItem -->
    
    <div class="sb_rewardItem sb_rewardItem_disabled">
    	<div class="sb_rewardItem_disabledMsg">
      	<h1 class="sb_textError">!</h1>
        <p>Must be Level 2 - Busker</p>
      </div><!-- .sb_rewardItem_disabledMsg -->
      <div class="sb_rewardHeader">
        $25 Ticketmaster Gift Certificate
      </div><!-- .sb_rewardHeader -->  	
      <div class="sb_rewardImg">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_reward.jpg" alt="Reward" />
      </div><!-- .sb_rewardImg -->
      <div class="sb_rewardBase">
      	<div class="sb_user-points-box">					
					<div class="sb_progressBar"><span class="sb_progressBarPercent">40</span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> 2000</span></div>
				</div><!-- .user-points-box -->
        <p class="sb_reward_levelReq"><span>Level Requirement</span></p>
        <a href="" class="sb_theme_button sb_theme_button_grey">Redeem</a>
      </div><!-- .sb_rewardBase -->
    </div><!-- .sb_rewardItem -->    
    
    <div class="sb_rewardItem">
      <div class="sb_rewardHeader">
        $25 Ticketmaster Certificate
      </div><!-- .sb_rewardHeader -->  	
      <div class="sb_rewardImg">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_reward.jpg" alt="Reward" />
      </div><!-- .sb_rewardImg -->
      <div class="sb_rewardBase">
      	<div class="sb_user-points-box">					
					<div class="sb_progressBar"><span class="sb_progressBarPercent">100</span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> 1000</span></div>
				</div><!-- .user-points-box -->        
        <p class="sb_reward_levelReq"></p>
        <a href="" class="sb_theme_button">Redeem</a>
      </div><!-- .sb_rewardBase -->
    </div><!-- .sb_rewardItem -->
    
  </div><!-- .sb_rewards -->
</div><!-- .sb_scrollPane -->

<div style="display:none">
  <div id="sb_rewardsOverlay">
  	<div class="sb_rewardItem">
      <div class="sb_rewardHeader">
        $25 Ticketmaster Gift Certificate
      </div><!-- .sb_rewardHeader -->  	
      <?php
			/*
			<!-- BEGIN LANDING -->
      <div class="sb_rewardImg">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_reward_lg.jpg" alt="Reward" />
      </div><!-- .sb_rewardImg -->
      
      <div class="sb_rewardBase">
      	<div class="sb_user-points-box">					
					<div class="sb_progressBar"><span class="sb_progressBarPercent">100</span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> 2000</span></div>
				</div><!-- .user-points-box -->
        <p>Redeem your Notes for a entry Token into the Week One Giveaway - xxx prize. The more tokens you purchase the better your chance of winning.</p>
        <a href="#" class="sb_theme_button sb_theme_button_grey">Redeem</a>
      </div><!-- .sb_rewardBase -->
			<!-- END LANDING -->
			*/
			?>
      <!-- BEGIN SHIPPING ADDRESS CONFIRM -->
      <div class="sb_rewardImg">
        <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_reward_lg.jpg" height="85" alt="Reward" />
      </div><!-- .sb_rewardImg -->
      <div class="sb_rewardOrder">
      	<div class="sb_column_5050BG">
        	<div class="sb_column50">
          	Current Balance
            <div class="sb_user-points-box">					
              <div class="sb_progressBar"><span class="sb_progressBarPercent">100</span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> 2000</span></div>
            </div><!-- .user-points-box -->
          </div><!-- .sb_column50 -->
          <div class="sb_column50">
          	Ending Balance
            <div class="sb_user-points-box">					
              <div class="sb_progressBar"><span class="sb_progressBarPercent">50</span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> 1000</span></div>
            </div><!-- .user-points-box -->
          </div><!-- .sb_column50 -->
        </div><!-- .column_5050BG -->
        <p><strong>Shipping Address</strong><a href="" class="sb_textError sb_alignRight">Edit</a></p> 
        <p>Jane wynter<br />
        121 Simpson Ave<br />
        Suite 201<br />
        Boston, MA. 01720</p>
        <p align="center">My information is correct<br clear="all" />
        <a href="" class="sb_theme_button">Place Order</a></p>
      </div><!-- .sb_rewardOrder -->
      <!-- END SHIPPING ADDRESS CONFIRM -->
    </div><!-- .sb_rewardItem -->
  </div><!-- #sb_rewardsOverlay -->
</div>