<?php

$game = $this->game;
/* @var $game Game_Starbar */
$good = $this->good;
/* @var $good Gaming_BigDoor_Good */


$gamer = $game->getGamer();

$currentBalance = (int) $gamer->getCurrencyByTitle('notes')->current_balance;
$itemCost = (int) $good->cost;

$percentUserBalanceToCost = round(($currentBalance / $itemCost) * 100);
if ($percentUserBalanceToCost > 100) $percentUserBalanceToCost = 100;

$balanceAfter = $currentBalance - $itemCost;
$percentUserBalanceRemaining = round(($balanceAfter / $currentBalance) * 100);

$goodIsToken = $good->hasAttribute('giveaway_token');

if ($goodIsToken) {
	$maximumQuantity = floor($currentBalance/$itemCost);
	if ($maximumQuantity > 5) $maximumQuantity = 5;
}

?>

<div id="sb_rewardItem" class="sb_rewardItem" data-id="<?= $good->getId() ?>">

    <div id="sb_reward_step1" class="sb_reward_step" style="background-color: #383838">
        <!-- BEGIN LANDING -->
        <div class="sb_rewardHeader"><span><?= $good->title ?></span></div>      
        <div class="sb_rewardImg">
            <img src="<?= $good->url_full ?>" alt="<?= $good->title ?>" />
        </div><!-- .sb_rewardImg -->
        <div class="sb_rewardBase">
            <div class="sb_user-points-box">                    
                <div class="sb_progress_bar"><span class="sb_currency_percent" style="width: <?= $percentUserBalanceToCost ?>%"></span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> <span><?= $itemCost ?></span></span></div>
            </div><!-- .user-points-box -->
            <?php if ($goodIsToken) : ?>
                <p class="sb_rewardDescription">Redeem your Notes for an entry Token to win <strong><?= $good->description ?></strong></p>
            <?php else : ?>
                <p class="sb_rewardDescription">Redeem your Notes for <?= $good->description ?></p>
            <?php endif ?>
            <span class="sb_theme_button">Redeem</span>
        </div><!-- .sb_rewardBase -->
        <!-- END LANDING -->
    </div><!-- #sb_reward_step1 -->

    <div id="sb_reward_step2" class="sb_reward_step" style="display: none;">
        <!-- BEGIN SHIPPING ADDRESS CONFIRM -->
        <div class="sb_rewardHeader"><span><?= $good->title ?></span></div><!-- .sb_rewardHeader -->      
        <div class="sb_rewardImg">
            <img src="<?= $good->url_full ?>" alt="<?= $good->title ?>" />
        </div><!-- .sb_rewardImg -->
        <div class="sb_rewardOrder">
            <div class="sb_column_5050BG">
                <div class="sb_column50">
                    Current Balance<br clear="all" />
                    <div class="sb_user-points-box" style="margin-top: 0px">                    
                        <div class="sb_progress_bar sb_ui-progressbar sb_ui-widget sb_ui-widget-content sb_ui-corner-all"><span class="sb_currency_percent sb_ui-progressbar-value sb_ui-widget-header sb_ui-corner-left" style="width: 100%"></span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> <span><?= $currentBalance ?></span></span></div>
                    </div><!-- .user-points-box -->
                </div><!-- .sb_column50 -->
                <div class="sb_column50">
                    Ending Balance<br clear="all" />
                    <div class="sb_user-points-box" style="margin-top: 0px">                    
                        <div class="sb_progress_bar sb_ui-progressbar sb_ui-widget sb_ui-widget-content sb_ui-corner-all"><span class="sb_currency_percent sb_ui-progressbar-value sb_ui-widget-header sb_ui-corner-left" style="width: <?= $percentUserBalanceRemaining ?>%"></span><span class="sb_progressBarValue"><img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_note_sm.png" alt="Notes" /> <span><?= $balanceAfter ?></span></span></div>
                    </div><!-- .user-points-box -->
                </div><!-- .sb_column50 -->
            </div><!-- .column_5050BG -->
            <div class="sb_step2Actions">
                <?php if ($goodIsToken) : ?>
                    <p>
                    	<strong>Quantity:</strong>
                        <select name="sb_itemQuantity">
                        	<?php for ($i = 1; $i <= $maximumQuantity; $i++) : ?>
                            	<option><?= $i ?></option>
                            <?php endfor ?>
                        </select>
                    </p>
                    <p>Tokens will appear in your account and you will be automatically entered into the Week One giveaway</p>
                <?php else : ?>
                    <p><strong>Shipping Address: </strong></p> 
                    <p id="sb_personalInfo"><input name="sb_first_name" type="text" placeholder="First Name" /> <input name="sb_last_name" type="text" placeholder="Last Name" /><br />
                    <input name="sb_address_1" type="text" placeholder="Address" /><br />
                    <input name="sb_address_2" type="text" /><br />
                    <input name="sb_city" type="text" placeholder="City" />, <input name="sb_state" type="text" placeholder="State" /> <input name="sb_zip" type="text" placeholder="Zip" /></p>
                <?php endif ?>
            </div>
            <p align="center">My information is correct<br clear="all" />
            <span class="sb_theme_button">Place Order</span></p>
        </div><!-- .sb_rewardOrder -->
        <!-- END SHIPPING ADDRESS CONFIRM -->
    </div><!-- #sb_reward_step2 -->

    <div id="sb_reward_step3" class="sb_reward_step" style="display: none;">        
         <img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_ajax-loader.gif" alt="Loading..." id="sb_img-loading" style="margin: 50px auto; display:block; text-align: center;" />
        <!-- ajax loaded after order is complete -->
    </div><!-- #sb_reward_step3 -->
   
</div><!-- .sb_rewardItem -->
<script language="javascript">
    $SQ(function(){
        var sayso = window.sayso;
        var rewardSteps = $SQ('#sb_rewardItem .sb_reward_step');
				var loadingImg = $SQ('#sb_rewardItem #sb_img-loading');
    
        var step1 = rewardSteps.eq(0),
            step2 = rewardSteps.eq(1),
            step3 = rewardSteps.eq(2);

				// set up the progress bars (copied from starbar-new.js)
				var reward_progressBarElems = $SQ('.sb_progress_bar', rewardSteps);
				var reward_currencyPercentElems = $SQ('.sb_currency_percent', rewardSteps);
				reward_progressBarElems.each(function(){
						if (!$SQ(this).hasClass('sb_ui-progressbar')) {
							$SQ(this).addClass('sb_ui-progressbar sb_ui-widget sb_ui-widget-content sb_ui-corner-all');
						}
				});
			
				reward_currencyPercentElems.each(function() {
					var $SQthis = $SQ(this);
					if (!$SQthis.hasClass('sb_ui-progressbar-value')) {
						$SQthis.addClass('sb_ui-progressbar-value sb_ui-widget-header sb_ui-corner-left');
					}
				});

        $SQ('#sb_rewardItem .sb_theme_button').each(function(){
            $SQ(this).click(function(e){
                var currentBox = $SQ(this).parents('.sb_reward_step');
                var nextBox = currentBox.next();								
                
                switch (currentBox.attr('id')) {
                    case 'sb_reward_step1' : // intro
                        nextBox.show();
                        currentBox.replaceWith(nextBox);
                        break;
                    case 'sb_reward_step2' : // address/confirm/place order
                        var quantity = $SQ('#sb_reward_step2 select'),
                            personalInfo = step2.find('#sb_personalInfo');
                        
                        var params = { 
                            good_id : <?= $good->getId() ?>,
                            quantity : (quantity.length ? quantity.val() : 1)
                        };
												
                        if (personalInfo.length) {
                            params.first_name = $SQ('.sb_first_name', personalInfo).val();
                            params.last_name = $SQ('.sb_last_name', personalInfo).val();
                            params.address_1 = $SQ('.sb_address_1', personalInfo).val();
                            params.address_2 = $SQ('.sb_address_2', personalInfo).val();
                            params.city = $SQ('.sb_city', personalInfo).val();
                            params.state = $SQ('.sb_state', personalInfo).val();
                            params.zip = $SQ('.sb_zip', personalInfo).val();
                        }
												
												// ghetto solution for loading image b/c beforeSend wasn't working. :(
												$SQ('.sb_rewardOrder',currentBox).html(loadingImg);
												
                        $SQ.ajaxWithAuth({
                            url : 'http://' + sayso.baseDomain + '/starbar/hellomusic/reward-redeemed',
                            data : params,
                            beforeSend: function(){
														
                            },
                            success : function (response) {
																nextBox.show();
                                sayso.log(response.game);                                                                
                                $SQ('#sayso-starbar').trigger('frameCommunication', ['updateGame', {
                                    newGame: response.game
                                }]);
                                $SQ('#sayso-starbar #sb_img-loading').hide();                                
                                currentBox.replaceWith(response.data.html);
                            }
                        });
                        break;
                }
                
            });
        });

        // update balance remaining based on quantity selected
        step2.find('.sb_step2Actions select').bind('change', function () {
            
            var itemsCost = <?= $itemCost ?> * ($SQ(this).val()),
                balanceAfter = <?= $currentBalance ?> - itemsCost,
                pointsBox = step2.find('.sb_user-points-box').eq(1);
                
            // update text 
            pointsBox.find('span.sb_progressBarValue span').text(balanceAfter);
            
            // update progress bar
            pointsBox.find('span.sb_currency_percent').css('width', Math.round((balanceAfter / <?= $currentBalance ?>) * 100) + '%');
        });


        // email order to ?
        // shipping address OR quantity
        // 

                
    });
</script>