<script type="text/javascript">
	setTimeout(function() {
		$S('#sb-survey-disqualified').fadeIn(500)
	}, 1000);
</script>
<div id="sayso-starbar-embed">
	Sorry, it appears that you do not qualify for <strong class="sb_theme_textHighlight"><?= $this->survey->title ?></strong>. Don't worry, we'll still give you the notes and chops for trying!<br /><br />
	<div id="sb-survey-disqualified">
		<? if ($this->survey->premium) { ?>
			<p>You earned <strong class="sb_theme_textHighlight_alt">4 Notes</strong> &amp;  <strong class="sb_theme_textHighlight_alt">1000 Chops</strong></p>
		<? } else { ?>
			<p>You earned <strong class="sb_theme_textHighlight">2 Notes</strong> &amp;  <strong class="sb_theme_textHighlight">500 Chops</strong></p>
		<? } ?>
	</div>
</div>
