<?= $this->partial('remote/init-remote.phtml', null, array('starbar' => $this->starbar)); ?>
<script type="text/javascript">
	setTimeout(function() {
		$SQ('#sb-survey-disqualified').fadeIn(500)
	}, 500);

	$SQ.remoteControl.updateGame(null);

	$SQ.getScript("http://platform.twitter.com/widgets.js", function(){
		function handleTweetEvent(event){
			if (event) {
				// @todo Tweet has occured, reward user!
			}
		}
		twttr.events.bind('tweet', handleTweetEvent);
	});
</script>
<div id="sayso-starbar-embed">
	Sorry, it appears that you do not qualify for the <strong class="sb_theme_textHighlight"><?= $this->survey->title ?></strong> survey. Don't worry, we'll still give you the notes and chops for trying!<br /><br />
	<div id="sb-survey-disqualified">
		<? if ($this->survey->premium) { ?>
			<p>You earned <strong class="sb_theme_textHighlight_alt">4 Notes</strong> &amp;  <strong class="sb_theme_textHighlight_alt">1000 Chops</strong></p>
		<? } else { ?>
			<p>You earned <strong class="sb_theme_textHighlight">2 Notes</strong> &amp;  <strong class="sb_theme_textHighlight">500 Chops</strong></p>
		<? } ?>
		<p class="sb_embedShare">
			<a class="sb_externalShare" href="#"
				onclick="window.open('http://www.facebook.com/dialog/feed?app_id=<?= urlencode($this->facebook_app_id) ?>&link=<?= urlencode($this->share_link) ?>&caption=<?= urlencode($this->facebook_share_caption) ?>&picture=<?= urlencode($this->facebook_share_image_url) ?>&redirect_uri=<?= urlencode($this->facebook_share_callback_url) ?>&name=<?= urlencode($this->facebook_title) ?>&description=<?= urlencode($this->facebook_description) ?>', 'sb_window_open', 'location=1,status=1,scrollbars=0,width=981,height=450'); return false;">
				<img src="http://<?= BASE_DOMAIN ?>/images/generic/facebook-share-icon.png" alt="Facebook" />
			</a>
			<a class="twitter-share-button"
				data-related="<?= $this->twitter_share_related_users ?>"
				data-hashtags="<?= $this->twitter_share_hashtags ?>"
				data-via="<?= $this->twitter_share_via_user ?>"
				data-url="<?= $this->share_link ?>"
				data-text="<?= $this->twitter_share_text ?>"
				data-count="none"
				href="https://twitter.com/intent/tweet">
					<img src="http://<?= BASE_DOMAIN ?>/images/generic/logo_twitter.png" alt="Twitter" />
			</a>
			Share this survey to earn extra points
		</p>
	</div>
</div>
