<?= $this->partial('remote/init-remote.phtml', null, array('starbar' => $this->starbar)); ?>
<script type="text/javascript">
	setTimeout(function() {
		$SQ('#sb-survey-completed').fadeTo(500, 1);
		$SQ.remoteControl.updateGame(null);
		$SQ.remoteControl.hideOverlay();
	}, 500);

	$SQ.getScript("//platform.twitter.com/widgets.js", function(){
		function handleTweetEvent(event){
			if (event) {
				$SQ.remoteControl.handleTweet('survey', <?= $this->survey->id ?>);
			}
		}
		twttr.events.bind('tweet', function(event) { handleTweetEvent(event) });
	});
</script>
<div id="sayso-starbar-embed">
	<br />
	Thank you for completing the <strong class="sb_theme_textHighlight"><?= $this->survey->title ?></strong> survey!<br /><br />
	<div id="sb-survey-completed">
		<? if ($this->survey->premium) { ?>
			<p>Excellent! You earned <strong class="sb_theme_textHighlight_alt">500 Notes</strong> &amp;  <strong class="sb_theme_textHighlight_alt">5000 Chops</strong></p>
		<? } else { ?>
			<p>Excellent! You earned <strong class="sb_theme_textHighlight">50 Notes</strong> &amp;  <strong class="sb_theme_textHighlight">500 Chops</strong></p>
		<? } ?>
		<div class="sb_externalShares">
			<a class="sb_externalShare" href="#"
				onclick="window.open('//www.facebook.com/dialog/feed?app_id=<?= urlencode($this->facebook_app_id) ?>&link=<?= urlencode($this->share_link) ?>&caption=<?= urlencode($this->facebook_share_caption) ?>&picture=<?= urlencode($this->facebook_share_image_url) ?>&redirect_uri=<?= urlencode($this->facebook_share_callback_url) ?>&name=<?= urlencode($this->facebook_title) ?>&description=<?= urlencode($this->facebook_description) ?>', 'sb_window_open', 'location=1,status=1,scrollbars=0,width=981,height=450'); return false;">
				<img src="//<?= BASE_DOMAIN ?>/images/generic/facebook-share-icon.png" alt="Facebook" />
			</a>
			<span class="sb_mini-note-reward"><?= ($this->survey->premium ? "50" : "25") ?></span>
			<a class="twitter-share-button"
				data-related="<?= $this->twitter_share_related_users ?>"
				data-hashtags="<?= $this->twitter_share_hashtags ?>"
				data-via="<?= $this->twitter_share_via_user ?>"
				data-url="<?= $this->share_link ?>"
				data-text="<?= $this->twitter_share_text ?>"
				data-count="none"
				href="https://twitter.com/intent/tweet">
					<img src="//<?= BASE_DOMAIN ?>/images/generic/logo_twitter.png" alt="Twitter" />
			</a>
			<span class="sb_mini-note-reward"><?= ($this->survey->premium ? "50" : "25") ?></span>
			Share this survey to earn extra points
		</div>
		<br />
		<? if ($this->next_survey->id) { ?>
			Try the next survey: "<a href="#" onclick="$SQ.remoteControl.openSurvey(<?= $this->next_survey->id ?>)"><?= ($this->next_survey->title) ?></a>"
		<? } ?>
	</div>
</div>
