<div class="sb_header">
	<h2 class="sb_title">My Account</h2>
</div><!-- .sb_header -->
<div class="sb_scrollPane">
	<ul class="sb_lineList">
		<li>
			<h3 class="sb_title">Levels</h3>
			<div class="sb_userLevelIcons sb_userLevel_earned">
				<div class="sb_userLevelImg sb_userLevel_musician"></div>
				<p>
					Musician<br />
					<small class="sb_chopsEarned">1000 Chops</small>
				</p>
			</div><!-- .sb_userLevelBox -->
			<div class="sb_userLevelIcons sb_userLevel_current">
				<div class="sb_userLevelImg sb_userLevel_busker"></div>
				<p>
					<strong class="sb_theme_textHighlight">Busker</strong><br />
					<small class="sb_chopsEarned">2000 Chops</small>
				</p>
			</div><!-- .sb_userLevelBox -->
			<div class="sb_userLevelIcons sb_userLevel_next">
				<div class="sb_userLevelImg sb_userLevel_band-member"></div>
				<p>
					Band Member<br />
					<small class="sb_chopsEarned">3000 chops</small>
				</p>
			</div><!-- .sb_userLevelBox -->
			<div class="sb_userLevelIcons sb_userLevel_next">
				<div class="sb_userLevelImg sb_userLevel_empty"></div>
				<p>
					<br />
				</p>
			</div><!-- .sb_userLevelBox -->
			<div class="sb_userLevelIcons sb_userLevel_next">
				<div class="sb_userLevelImg sb_userLevel_empty"></div>
				<p>
					<br />
				</p>
			</div><!-- .sb_userLevelBox -->
		</li>
		<li>
			<div class="sb_column5050">
				<div class="sb_column50">
					<h3 class="sb_title">Chops</h3>
					<div class="sb_user-level-box">
						<span class="sb_user-level-star"></span>
						<div class="sb_progressBar"><span class="sb_progressBarPercent sb_currency_percent_chops">60</span><span class="sb_progressBarValue sb_currency_balance_chops">450</span></div>
					</div><!-- .user-level-box -->
					<small>Level up at 1000 Chops</small>
				</div><!-- .sb_column50 -->
				<div class="sb_column50">
					<h3 class="sb_title">Notes</h3>
					<div class="sb_user-points-box">
						<span class="sb_imgNote"></span>
						<div class="sb_progressBar"><span class="sb_progressBarPercent">0</span><span class="sb_progressBarValue sb_currency_balance_notes">125</span></div>
					</div><!-- .user-points-box -->
					<strong><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards" class="sb_rewardsCenterLink sb_nav_element" rel="sb_popBox_rewards">Rewards Center<span class="sb_img_nextTriangle"></span></a></strong>
				</div><!-- .sb_column50 -->
			</div><!-- .sb_column_5050 -->
		</li>
		<li>
			<h3 class="sb_title">My Purchases</h3>
			<p>
				<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_reward.jpg" class="sb_img_purchase" /> 
				<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_reward.jpg" class="sb_img_purchase" /> 
				<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_reward.jpg" class="sb_img_purchase" />
				<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_reward.jpg" class="sb_img_purchase" /> 
			</p>
		</li>
	</ul>
</div><!-- .sb_scrollPane -->
