<div class="sb_header">
	<h2 class="sb_title">Send to a Friend</h2>
</div><!-- .sb_header -->
<div class="sb_scrollPane">
	<p>Enter email addresses or import your address book below</p>
	<textarea style="height: 40px">Separate emails with commas</textarea>
	<p class="sb_importShare"><span>Import From</span> <a href=""><img src="//<?= BASE_DOMAIN ?>/images/generic/img_share_gmail.png" alt="Gmail" /></a> <a href=""><img src="//<?= BASE_DOMAIN ?>/images/generic/img_share_outlook.png" alt="Outlook" /></a> <a href=""><img src="//<?= BASE_DOMAIN ?>/images/generic/img_share_yahoo.png" alt="Yahoo" /></a> <a href=""><img src="//<?= BASE_DOMAIN ?>/images/generic/img_share_aol.png" alt="AOL" /></a> <a href=""><span>Other</span></a></p>
<br />
<h3 class="sb_theme_textHighlight">Customize Your Message</h3>
<p><textarea style="height: 80px; margin-bottom: 5px">Wanna help me keep the beat? Get the Say.So Music Bar by Hello Music, give your opinion, get access to exclusive deals, and a chance to win a sweet Takamine Acoustic and other great gear!
Join me?
 </textarea></p>
 <p align="right">
 	<a href="" class="sb_theme_button">Send</a>
 </p>
  
</div><!-- .sb_scrollPane -->