<div class="sb_column6040BG">
	<div class="sb_column60">
		<div class="sb_header">
			<h2 class="sb_titlePlain">Welcome Back, <strong><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/user-level" class="sb_nav_element" rel="sb_popBox_user-level"><?= $this->user->getTitle() ?></a></strong></h2>
		</div><!-- .sb_header -->
		<div>
			<ul class="sb_lineList">
				<li>
					<? if ($this->facebook_social->identifier) { ?>
						<img class="sb_userImg sb_alignLeft" src="http://graph.facebook.com/<?= $this->facebook_social->identifier ?>/picture?type=square" alt="<?= $this->user->getTitle() ?>" />
					<? } else { ?>
						<img class="sb_userImg sb_alignLeft" src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_user.jpg" alt="<?= $this->user->getTitle() ?>" />
					<? } ?>
					<p class="sb_nextToUserImage">
						<strong>Username:</strong> <span id="sb_profile_username" <? if (!$this->user->username) { ?>class="sb_jeip"<? } ?>><?= $this->user->getTitle() ?></span><br />
						<?= $this->user_email->email ?>
					</p>
				</li>
				<li>
					<div class="sb_alignLeft" style="padding-top: 5px;">
						<a href="http://www.facebook.com/pages/SaySo/290443177649449" target="_new">Follow us on Facebook!</a>
					</div>
					<div class="sb_alignRight">
						<div id="fb-root"></div>
						<script>
							(function(d, s, id) {
								var js, fjs = d.getElementsByTagName(s)[0];
								if (d.getElementById(id)) {return;}
								js = d.createElement(s); js.id = id;
								js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
								fjs.parentNode.insertBefore(js, fjs);
							}(document, 'script', 'facebook-jssdk'));
						</script>
						<iframe src="http://www.facebook.com/plugins/like.php?locale=en_US&amp;href=http://www.facebook.com/pages/SaySo/290443177649449&amp;layout=standard&amp;show_faces=false&amp;width=300&amp;action=like&amp;font=verdana&amp;colorscheme=light&amp;height=24" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:54px; height:24px; margin-right: 10px;" allowTransparency="true"></iframe>
					</div>
				</li>
				<li>
					<h2 class="sb_titlePlain">Link Your Accounts</h2>
					<a style="float: right" href="#" onclick='$SQ.ajaxWithAuth({url : "http://<?= BASE_DOMAIN ?>/api/user/reset-external", success : function (r, s) {} });'>Reset account links</a>
					<p>
						<? if ($this->facebook_social->user_id) { ?>
							<span id="sb_profile_facebook" class="sb_connect_facebook sb_connected">http://www.facebook.com</span>
						<? } else { ?>
							<span href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/facebook-connect" id="sb_profile_facebook" class="sb_connect_facebook sb_unconnected">http://www.facebook.com</span>
						<? } ?>
						<? if ($this->twitter_social->user_id) { ?>
							<span id="sb_profile_twitter" class="sb_connect_twitter sb_connected">http://www.twitter.com</span>
						<? } else { ?>
							<span href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/twitter-connect-redirect" id="sb_profile_twitter" class="sb_connect_twitter sb_unconnected">http://www.twitter.com</span>
						<? } ?>
					</p>
				</li>
			</ul>
		</div>
	</div><!-- .sb_column60 -->
	<div class="sb_column40">  	
		<div class="sb_scrollPane" style="height: 260px;">
		<div class="sb_header">
			<h2 class="sb_titlePlain">What's New Today</h2>
		</div><!-- .sb_header -->
		<ul class="sb_lineList">
			<li>
				<? if ($this->count_new_polls) { ?><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/polls" class="sb_nav_element" rel="sb_popBox_polls"><?= $this->count_new_polls ?> New Polls</a><br /><? } ?>
				<? if ($this->count_new_surveys) { ?><a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/surveys" class="sb_nav_element" rel="sb_popBox_surveys"><?= $this->count_new_surveys ?> New Surveys</a><br /><? } ?>
				<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/daily-deals" class="sb_nav_element" rel="sb_popBox_daily-deals">4 New Daily Deals</a>
			</li>
		</ul>
		<div class="sb_header">
			<h2 class="sb_titlePlain">My Stats</h2>
		</div><!-- .sb_header -->

		<p>
			<strong>Level 1. <span class="sb_userLevelColor1">Musician</span></strong>
		</p>
		<p>
			<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/user-level" class="sb_nav_element" rel="sb_popBox_user-level">80 Notes</a><br />
			<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/user-level" class="sb_nav_element" rel="sb_popBox_user-level">430 Chops</a><br />
			<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/user-level" class="sb_nav_element" rel="sb_popBox_user-level">Redeem Rewards</a>
		</p>
		<br />
		<p>
			<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/user-share" class="sb_theme_button sb_nav_element" rel="sb_popBox_user-share"><span class="sb_theme_buttonArrow">Recommend to a Friend</span></a>
		</p>
    <br />    
		<div class="sb_header">
			<h2 class="sb_titlePlain">Documents</h2>
		</div><!-- .sb_header -->
    <p>
    	<a href="http://<?= BASE_DOMAIN ?>/docs/Terms & Conditions.pdf">Terms &amp; Conditions</a><br />
      <a href="http://<?= BASE_DOMAIN ?>/docs/SaySo_Privacy_Policy.pdf">Privacy Policy</a><br />
      <a href="http://<?= BASE_DOMAIN ?>/docs/HelloMusic_Rewards_Rules.pdf">Rewards Rule</a>
    </p>
		</div><!-- .sb_scrollPane -->
	</div><!-- .sb_column40 -->
</div><!-- .sb_column6040BG -->
