  <div class="sb_popBoxInner sb_triangle-solid">
    <div class="sb_popContent">
    	<div class="sb_column6040BG">
        <div class="sb_column60">
          <div class="sb_header">
          <h2 class="sb_titlePlain">Welcome Back, <strong class="sb_theme_textHighlight">Alfonso</strong></h2>
          </div><!-- .sb_header -->
          <div class="sb_scrollPane">
          	<ul class="sb_lineList">
            	<li>
              	<img src="http://<?= BASE_DOMAIN ?>/images/hellomusic/img_user.jpg" alt="User" width="40" class="sb_alignLeft" />
                <p style="margin-left: 50px">
                <strong>Username:</strong> <div id="sb_profile_username">Rands</div><br />
                Randy.Scottson@gmail.com
                </p>
              </li>
              <li>
              	[ FACEBOOK LIKE BUTTON ]
            	</li>
              <li>
              <h2 class="sb_titlePlain">Link Your Accounts</h2>
              <p>
              	<a href="" class="sb_connect_facebook sb_connected">Facebook Connect</a>
                <a href="" class="sb_connect_twitter sb_unconnected">Twitter Connect</a>
              </p>
              <p>
                <a href="">Edit Accounts</a>
              </p>
              </li>
            </ul>
          </div><!-- .sb_scrollPane -->
        </div><!-- .sb_column60 -->
        <div class="sb_column40">
          <div class="sb_header">
            <h2 class="sb_titlePlain">What's New Today</h2>
          </div><!-- .sb_header -->
          	<ul class="sb_lineList">
              <li>
              <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/polls" class="sb_nav_element" rel="sb_popBox_polls">4 New Polls</a><br />
              <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/surveys" class="sb_nav_element" rel="sb_popBox_surveys">2 New Polls</a><br />
              <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/daily-deals" class="sb_nav_element" rel="sb_popBox_daily-deals">6 New Daily Deals</a>
              </li>
          	</ul>
            <div class="sb_header">
            <h2 class="sb_titlePlain">My Stats</h2>
          </div><!-- .sb_header -->

            <p>
            	<strong>Level 1. <span class="sb_userLevelColor1">Musician</span></strong>
            </p>
            <p>
            	<a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/user-level" class="sb_nav_element" rel="sb_popBox_user-level">80 Notes</a><br />
              <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/user-level" class="sb_nav_element" rel="sb_popBox_user-level">430 Chops</a><br />
              <a href="http://<?= BASE_DOMAIN ?>/starbar/hellomusic/user-level" class="sb_nav_element" rel="sb_popBox_user-level">Redeem Rewards</a>
            </p>
            <br />
            <p>
            	<a href="" class="sb_theme_button"><span class="sb_theme_buttonArrow">Recommend to a Friend</span></a>
            </p>
        </div><!-- .sb_column40 -->
      </div><!-- .sb_column6040BG -->
    </div><!-- .sb_popContent -->
  </div><!-- .sb_popBoxInner -->
