<div class="sb_header">
	<h2 class="sb_title">My Account</h2>
</div><!-- .sb_header -->
<div class="sb_scrollPane">
	<ul class="sb_lineList">
		<li>
			<h3 class="sb_title">Levels</h3>
			<div class="sb_user_level_icons_container">
			</div>
		</li>
		<li>
			<div class="sb_column5050">
				<div class="sb_column50">
					<h3 class="sb_title">Chops</h3>
					<div class="sb_user-level-box">
						<span class="sb_user-level-star"></span>
						<div class="sb_progress_bar"><span class="sb_currency_percent" data-currency="chops"></span><span class="sb_progressBarValue sb_currency_balance" data-currency="chops"></span></div>
					</div><!-- .user-level-box -->
					<small>Level up at <span class="sb_currency_balance_next_level"></span> Chops</small>
				</div><!-- .sb_column50 -->
				<div class="sb_column50">
					<div class="sb_alignLeft">
						<h3 class="sb_title">Notes</h3>
						<div class="sb_user-points-box">
							<span class="sb_imgNote"></span>
							<div class="sb_progress_bar"><span class="sb_currency_percent"></span><span class="sb_progressBarValue sb_currency_balance" data-currency="notes"></span></div>
						</div><!-- .user-points-box -->
					</div>
					<strong><a href="//<?= BASE_DOMAIN ?>/starbar/hellomusic/rewards" class="sb_rewardsCenterLink sb_nav_element" rel="sb_popBox_rewards"><span class="sb_img_nextTriangle"></span>Rewards Center</a></strong>
				</div><!-- .sb_column50 -->
			</div><!-- .sb_column_5050 -->
		</li>
		<li>
			<h3 class="sb_title">My Purchases</h3>
			<div class="sb_user_purchases">
			</div>
		</li>
	</ul>
</div><!-- .sb_scrollPane -->
