<div class="modal-header">
    <h2>sign in</h2>
    <a class="close modal-close" title="Close">close</a>
</div>
<div id="sign-in" class="modal-content">
    <div id="sign-in-form"> 
        <form method="post" action="/api/user/login" enctype="application/x-www-form-urlencoded">            
            <fieldset>
                <legend></legend>
                <ul>
                    <li><input type="text" placeholder="username" name="username" class="first-focus" /></li>
                    <li><input type="password" placeholder="password" name="password" /></li>
                    <li><a class="button">sign in</a></li>
                </ul>
            </fieldset>
        </form>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        // setup the login form
        a.forms.ajax($('#sign-in-form form'), '/user/login');
    });
</script>