<?php

$pollFrequencies = new Lookup_Collection_PollFrequency(); $pollFrequencies->lookup();
$emailFrequencies = new Lookup_Collection_EmailFrequency(); $emailFrequencies->lookup();
$surveyTypes = new Lookup_Collection_SurveyType(); $surveyTypes->lookup();
$ethnicBackgrounds = new Lookup_Collection_EthnicBackground(); $ethnicBackgrounds->lookup();
$genders = new Lookup_Collection_Gender(); $genders->lookup();

?>

<div id="sign-up">
	<h2>Sign up!</h2>
	<form id="registration-form" method="POST" action="/api/user/register">
		<input type="hidden" name="auth_key" value="<?= Api_Registry::getConfig()->api->authKey ?>">
		<fieldset>
			<legend>Username &amp; Password</legend>
			<p>
				<label for="username" class="required">Username</label>
				<input name="username" id="username" type="text" class="input_text">
			</p>
			<p>
				<label for="password" class="required">Password</label>
				<input name="password" id="password" type="password" class="input_text">
			</p>
			<p>
				<label for="password_verify" class="required">Verify Password</label>
				<input name="password_verify" id="password_verify" type="password" class="input_text">
			</p>
		</fieldset>
		<fieldset>
			<legend>Personal Info</legend>
			<p>
				<label for="first_name" class="required">First Name</label>
				<input name="first_name" id="first_name" type="text" class="input_text">
			</p>
			<p>
				<label for="last_name" class="required">Last Name</label>
				<input name="last_name" id="last_name" type="text" class="input_text">
			</p>
			<p>
				<label for="email" class="required">Email</label>
				<input name="email" id="email" type="text" class="input_text">
			</p>
			<p>
				<label class="required">Gender</label>
				<?php $male = $genders[1]; $female = $genders[2]; ?>
				<input type="radio" name="gender_id" id="gender_<?= $male->getId() ?>" value="<?= $male->getId() ?>" />
				<label for="gender_<?= $male->getId() ?>" class="required label_short"><?= $male->getTitle() ?></label>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<input type="radio" name="gender_id" id="gender_<?= $female->getId() ?>" value="<?= $female->getId() ?>" />
				<label for="gender_<?= $female->getId() ?>" class="required label_short"><?= $female->getTitle() ?></label>
				<span class="custom-error" name="gender_id" style="display: none;" />
			</p>
			<p>
				<label for="birth_year" class="required">Birth Year</label>
				<select name="birth_year" id="birth_year">
					<option value="">Choose ...</option>
					<?php for ($i = 2000; $i > 1930; $i--) : ?>
						<option value="<?= $i ?>"><?= $i ?></option>
					<?php endfor ?>
				</select>
			</p>
			<p>
				<label class="required" for="ethnicity">Heritage</label>
				<select name="ethnicity_id" id="ethnicity">
					<option value="">Choose...</option>
					<?php foreach ($ethnicBackgrounds as $ethnicBackground) : ?>
					<option value="<?= $ethnicBackground->getId() ?>"><?= $ethnicBackground->getTitle() ?></option>
					<?php endforeach ?>
				</select>
			</p>
			<p>
				<label for="timezone">Time Zone</label>
				<select name="timezone" id="timezone">
					<option value="">Choose...</option>
					<?php foreach (TimeZone::getAllOffsets() as $offset => $label) : ?>
						<option value="<?= urlencode($offset) ?>"><?= $label ?></option>
					<?php endforeach ?>
				</select>
				<input type="hidden" name="timezone_type" value="utc" />
			</p>
		</fieldset>
		<fieldset>
			<legend>Preferences</legend>
			<p>
				<h3>How often do you want to earn by giving your opinion?</h3>
				<table width="100%">
					<tbody>
						<tr>
							<th></th>
							<?php foreach ($emailFrequencies as $frequency) : ?>
								<th><strong><?= $frequency->getTitle() ?></strong><br /><small><?= $frequency->extra ?></small></th>
							<?php endforeach ?>
						</tr>
						<tr>
							<td><strong>Emails</strong></td>
							<?php foreach ($emailFrequencies as $frequency) : ?>
								<td><input type="radio" name="email_frequency_id" value="<?= $frequency->getId() ?>" /></td>
								<!--td rowspan="2"><?= $frequency->extra ?></td-->
							<?php endforeach ?>
							
						</tr>
						<tr>
							<td><strong>Polls</strong></td>
							<?php foreach ($pollFrequencies as $frequency) : ?>
								<td><input type="radio" name="poll_frequency_id" value="<?= $frequency->getId() ?>" /></td>
							<?php endforeach ?>
						</tr>
					</tbody>
				</table>
				<p class="custom-error" name="email_frequency_id" style="display: none;"></p>
				<p class="custom-error" name="poll_frequency_id" style="display: none;"></p>
				<h3>On what subjects and industries do you want to weigh in on?</h3>
				<table width="100%">
					<?php 
					$rows = array_chunk($surveyTypes->getArray(), 3);
					foreach ($rows as $row) :
					?>
					<tr>
						<?php foreach ($row as $surveyType) : ?>
						<td>
							<input type="checkbox" name="survey_type_id[]" value="<?= $surveyType->getId() ?>" />&nbsp;
							<label><?= ucwords($surveyType->getTitle()) ?></label>
						</td>
						<?php endforeach ?>
					</tr>
					<?php endforeach ?>
				</table>
				<div class="custom-error" name="survey_type_id" style="display: none;"></div>
			</p>
		</fieldset>
		<fieldset>
			<legend>Get Started!</legend>
			<input type="submit" value="Register Now" class="btn_submit">
		</fieldset>
	</form>
</div>
<?= $this->partial('partials/get-the-app.phtml') ?>
<script type="text/javascript">
	$(function () {
		a.forms.ajax($('#registration-form'), '/user/create');
	});
</script>