<? if (!$this->survey_already_completed) { ?>
	<div class="sb_outerOverlay"></div>
<? } ?>
<div class="sb_header embed">
	<h2 class="sb_title">
	<img src="//<?= BASE_DOMAIN ?>/images/machinima/surveys_logo.png" alt="Machinima logo" />
	</h2>
</div><!-- .sb_header -->
<p class="sb_alignRight"><a href="//<?= BASE_DOMAIN ?>/starbar/machinima/surveys" class="sb_theme_iconChange sb_nav_element" rel="sb_popBox_surveys">Switch Survey</a></p>
<? if ($this->survey->reward_category == "premium" || $this->survey->reward_category == "profile") { ?>
	<div class="sb_theme_textHighlight_alt sb_survey_title embed"><?= $this->survey->title ?></div>
<? } else { ?>
	<div class="sb_survey_title embed"><?= $this->survey->title ?></div>
<? } ?>

<? if ($this->survey_already_completed) { ?>
	<br />
	You have already completed this survey.
<? } elseif ($this->survey->status == "inactive") { ?>
	<br />
	This survey is currently unavailable. Please try again later.
<? } else { ?>
	<div id="starbar-survey-<?= $this->survey->id ?>" class="sb_survey_container"></div>
	<script type="text/javascript">
		var protocol = ('https:' == $SQ.sayso.location.protocol ? 'https:' : 'http:');

		var iframeWidth = 500;
		var iframeHeight = 295;

		var link = protocol
			+ "//<?= BASE_DOMAIN ?>/starbar/machinima/survey-redirect?survey_id=<?= $this->survey->id ?>&next_survey_id=<?= $this->next_survey_id ?>&user_id="
			+ $SQ.sayso.starbar.user.id
			+ "&user_key=" + $SQ.sayso.starbar.user.key
			+ "&starbar_id=" + $SQ.sayso.starbar.id;

		<? if ($this->survey->requires_age && $this->user_age) { ?>
			link += "&age=<?= $this->user_age?>";
		<? } ?>

		<? if ($this->survey->size == "large") { ?>
			link += "&size=large";
			iframeWidth = 640;
			iframeHeight = 410;
		<? } ?>

		var iframeContainerId = "starbar-survey-<?= $this->survey->id ?>";

		$SQ.insertCommunicationIframe(link, iframeContainerId, iframeWidth, iframeHeight, 'auto'); // Add new iframe!
	</script>
<? } ?>
