	<div class="sb_header">
	<img src="//<?= BASE_DOMAIN ?>/images/machinima/logo_machinima_onboard.png" alt="Machinima" />
	</div><!-- .sb_header -->
	<div class="sb_popBoxInner">
	<div class="sb_popContent">
		<div class="sb_tabs">
		<ul>
			<li><a href="#onboard_tabs_1">I'm In!</a></li>
			<li><a href="#onboard_tabs_2">What Can I Do?</a></li>
			<li><a href="#onboard_tabs_3">What Do I Get?</a></li>
			<li><a href="#onboard_tabs_4">Get Started</a></li>
		</ul>

		<div id="onboard_tabs_1" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Welcome!</h2>
			<h3>We designed the steps below to help you get oriented with Machinima | Recon. If you find you need additional help, feel free to <a href="mailto:machinima@say.so">contact us</a>.</h3>
			<p align="center"><big>By becoming a member of Machinima Recon, you've achieved the level 1, and earned extra Xp and Coins.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_experience_currency"><strong class="sb_theme_textHighlight">"Experience"</strong> Experience Points (XP) is the currency of influence. You earn them for sharing your expertise, experience and opinion, and your XP determines your access to increasingly important levels of access and influence.</li>
				<li class="sb_img_redeemable_currency"><strong class="sb_theme_textHighlight">"Coins"</strong> are almost as good as cash. Virtually everything you do earns you Coins, which can be redeemed for all manner of goodies from Machinima | Recon. (<a class="sb_nav_element" rel="sb_popBox_rewards" href="/starbar/machinima/rewards">see the Rewards Center</a>)</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_1 -->
		<div id="onboard_tabs_2" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Give Your Opinion, Share It and Earn!</h2>
			<p align="center"><big>Your point of view and opinion are invaluable. Express yourself through fun polls and surveys, and earn XP and Coins by watching fun videos.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_polls"><strong class="sb_theme_textHighlight">Polls</strong> are quick hits of opinion we’d like you to share. Answer as many or as few as you’d like, and for each one we’ll drop a little something in your Machinima | Recon wallet.</li>
				<li class="sb_img_surveys"><strong class="sb_theme_textHighlight">Surveys</strong> are the big money opportunities. These are important efforts to gauge how we are doing, and we’ll make sure you are compensated accordingly.</li>
				<li class="sb_img_spotlight"><strong class="sb_theme_textHighlight">Spotlight - </strong> Rate game trailers and watch the newest video content. Share them on Facebook or Twitter, we'll compensate you with XP and Coins. No purchase necessary. The more you participate the more you earn and the more you earn the bigger the rewards and discounts you get!</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_2 -->
		<div id="onboard_tabs_3" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Here's What You Get.</h2>
			<p align="center"><big>Help us better serve your Machinima | Recon needs and you’ll earn Coins, virtual currency redeemable for prizes and opportunities.</big></p>
			<br />
			<ul class="sb_lineList">
				<li class="sb_img_prizes"><strong class="sb_theme_textHighlight">Great Prizes.</strong> Almost everything you do as a Machinima | Recon member earns you Coins. Use these to redeem prizes from the Rewards Center.</li>
				<li class="sb_img_giveaways"><strong class="sb_theme_textHighlight">A Chance To Win A Prize Giveaways. </strong> Redeem your Coins for entry tokens for our giveaways. Buy as many entry tokens for each giveaway as you want and increase your odds of winning.</li>
			</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_3 -->

		<div id="onboard_tabs_4" class="sb_tabPane">
			<div class="sb_scrollPane">
			<h2 class="sb_title" align="center">Okay, Let’s Get Started!</h2>
			<p align="center" style="margin-top: 15px;"><a href="//<?= BASE_DOMAIN ?>/starbar/machinima/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg"><img src="//<?= BASE_DOMAIN ?>/images/machinima/img_profile-survey.png" alt="Take the Profile Survey" /></a><br /><strong>Completing the Profile Survey takes a minute, but we will reward you with a hefty number of Coins and grant you automatic access to our giveaways.</strong></p>
			<br />
			<br />
			<h2 align="center">Not ready to take the Profile Survey yet?  <br />Check out some quick-hit activities.</h2>
			<p align="center" style="margin-top: 10px;">
				<a href="//<?= BASE_DOMAIN ?>/starbar/machinima/polls" class="sb_nav_element" rel="sb_popBox_polls"><img src="//<?= BASE_DOMAIN ?>/images/machinima/img_badge_polls.png" alt="Polls" style="margin: 0px 10px;" /></a>
				<a href="//<?= BASE_DOMAIN ?>/starbar/machinima/surveys" class="sb_nav_element" rel="sb_popBox_surveys"><img src="//<?= BASE_DOMAIN ?>/images/machinima/img_badge_surveys.png" alt="Surveys" style="margin: 0px 10px;" /></a>
				<a href="//<?= BASE_DOMAIN ?>/starbar/machinima/spotlight" class="sb_nav_element" rel="sb_popBox_spotlight"><img src="//<?= BASE_DOMAIN ?>/images/machinima/img_badge_quizzes.png" alt="Ppotlight" style="margin: 0px 10px;" /></a>
			</p>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tab_4 -->

		</div><!-- .sb_tabs -->
	</div><!-- .sb_popContent -->
	</div><!-- .sb_popBoxInner -->
