<div id="sb_slideshow">
	<div class="sb_promoBG sb_promo_week1">
		<div class="sb_slide">
			<div class="sb_header no-border">
				<img src="//<?= BASE_DOMAIN ?>/images/machinima/logo_big.png" alt="Snakkle logo" />
			</div><!-- .sb_header -->

			<div class="sb_promo_details" style="width: 250px; top: 80px; left: 5px;">
				<p>Use your XX&#39;s to buy tokens to enter the Giveaway - the more tokens you get the better your chances of winning!</p>
				<p class="sb_promo_link">
					<a href="//<?= BASE_DOMAIN ?>/starbar/machinima/rewards?chosen_good_id=first" class="sb_nav_element sb_theme_textHighlight_alt" rel="sb_popBox_rewards"></a>
					</p>
				<p><small><strong class="sb_theme_textHighlight">Remember</strong> - Take the <a href="//<?= BASE_DOMAIN ?>/starbar/machinima/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg">Influencer Survey</a> to be eligible for the giveaways.</small></p>
			</div><!-- .sb_promo_details -->

		</div><!-- .sb_slide -->
	</div><!-- .sb_promo_week1 -->
</div><!-- #sb_slideshow -->