<?= $this->partial('remote/init-remote.phtml', null, array('starbar' => $this->starbar)); ?>
<script type="text/javascript">
	$SQ(function () {
		setTimeout(function() {
			$SQ('#sb-survey-disqualified').fadeTo(500, 1);
			$SQ.remoteControl.updateGame(null);
			$SQ.remoteControl.hideOverlay();
		}, 200);

		$SQ.getScript("//platform.twitter.com/widgets.js", function(){
			function handleTweetEvent(event){
				if (event) {
					$SQ.remoteControl.handleTweet('survey', <?= $this->survey->id ?>);
					$SQ('.sb_externalShare_twitter').bind('click', function(e) {
						e.preventDefault();
						e.stopPropagation();
						return false;
					});
				}
			}
			twttr.events.bind('tweet', function(event) { handleTweetEvent(event) });
		});
	});
</script>
<div id="sayso-starbar-embed">
	<br />
	<? if (!$this->survey->premium) { ?>
		Sorry, it appears that you do not qualify for the <strong class="sb_theme_textHighlight"><?= $this->survey->title ?></strong> survey. Don't worry, we'll still give you some Bucks and Stars for trying!<br /><br />
	<? } ?>
	<div id="sb-survey-disqualified">
		<? if ($this->survey->reward_category == "premium") { ?>
			<p>Nice! You still banked <strong class="sb_theme_textHighlight_alt">75 Bucks</strong> &amp; <strong class="sb_theme_textHighlight_alt">1000 Stars</strong>. Remember to check out the Rewards Center to redeem your Bucks for stuff!</p>
			<? $shareReward = 30 ?>
		<? } elseif ($this->survey->reward_category == "profile") { ?>
			<p>You earned <strong class="sb_theme_textHighlight">50 Bucks</strong> &amp;	<strong class="sb_theme_textHighlight">500 Stars</strong></p>
			<? $shareReward = 15 ?>
		<? } else { ?>
			<p>You earned <strong class="sb_theme_textHighlight">25 Bucks</strong> &amp;	<strong class="sb_theme_textHighlight">250 Stars</strong></p>
			<? $shareReward = 8 ?>
		<? } ?>
		<div class="sb_externalShares">
			<a class="sb_externalShare sb_externalShare_facebook" rel="sb_mini-snakkle-reward_facebook" href="#"
				onclick="$SQ.remoteControl.handleFacebookShare('//www.facebook.com/dialog/feed?app_id=<?= urlencode($this->facebook_app_id) ?>&link=<?= urlencode($this->share_link) ?>&caption=<?= urlencode($this->facebook_share_caption) ?>&picture=<?= urlencode($this->facebook_share_image_url) ?>&redirect_uri=<?= urlencode($this->facebook_share_callback_url) ?>&name=<?= urlencode($this->facebook_title) ?>&description=<?= urlencode($this->facebook_description) ?>', 'survey', <?= $this->survey->id ?>); return false;">
				<img src="//<?= BASE_DOMAIN ?>/images/generic/facebook-share-icon.png" alt="Facebook" />
			</a>
			<span class="sb_mini-snakkle-reward sb_mini-snakkle-reward_facebook" id="sb_mini-snakkle-reward_facebook">+<?= $shareReward ?></span>
			<div class="sb_externalShare sb_externalShare_twitter" rel="sb_mini-snakkle-reward_twitter">
				<a class="twitter-share-button"
					data-related="<?= $this->twitter_share_related_users ?>"
					data-hashtags="<?= $this->twitter_share_hashtags ?>"
					data-via="<?= $this->twitter_share_via_user ?>"
					data-url="<?= $this->share_link ?>"
					data-text="<?= $this->twitter_share_text ?>"
					data-count="none"
					href="https://twitter.com/intent/tweet">
						<img src="//<?= BASE_DOMAIN ?>/images/generic/logo_twitter.png" alt="Twitter" />
				</a>
			</div>
			<span class="sb_mini-snakkle-reward sb_mini-snakkle-reward_twitter" id="sb_mini-snakkle-reward_twitter">+<?= $shareReward ?></span>
			Share this survey to earn extra points
		</div>
	</div>
		<br />
		<? if ($this->next_survey->id) { ?>
			Try the next survey: "<a href="#" onclick="$SQ.remoteControl.openSurvey(<?= $this->next_survey->id ?>); return false;"><?= ($this->next_survey->title) ?></a>"
		<? } ?>
</div>
<script type="text/javascript">
	// SET UP EXTERNAL SHARE BEHAVIORS
	$SQ('.sb_externalShare').each(function(){
		// for some reason, the hover behavior set in the CSS is totally ignored. :(
			$SQ(this).hover(function(){
				$SQPoints = $SQ('#'+$SQ(this).attr('rel'));
				$SQ(this).css('background-position','0px -20px');
				$SQPoints.show();
			},
			function(){
				$SQPoints = $SQ('#'+$SQ(this).attr('rel'));
				$SQ(this).css('background-position','0px 0px');
				$SQPoints.hide();
			});

	}); // end btnExternalShare
</script>
