<div class="sb_header">
	<img src="//<?= BASE_DOMAIN ?>/images/machinima/surveys_logo.png" alt="Machinima logo" />
</div><!-- .sb_header -->
<div class="sb_tabs">
	<ul>
		<? if ($this->count_new_surveys) { ?>
			<li><a href="#surveys_tabs_1"><?= $this->count_new_surveys ?> New!</a></li>
		<? } else { ?>
			<li><a href="#surveys_tabs_1">New</a></li>
		<? } ?>
		<? if ($this->count_completed_surveys || $this->count_disqualified_surveys) { ?>
			<li><a href="#surveys_tabs_2">Completed</a></li>
		<? } ?>
		<? if ($this->count_archived_surveys) { ?>
			<li><a href="#surveys_tabs_3">Archive</a></li>
		<? } ?>
	</ul>
	<div id="surveys_tabs_1" class="sb_tabPane">
		<p class="sb_tabHeader">
			Earn <strong class="sb_theme_textHighlight sb_tooltip" title="XP - determine your access to increasingly important levels of influence.">XP</strong> &amp;
			<strong class="sb_theme_textHighlight sb_tooltip" title="Coins - are almost as good as cash and can be redeemed for goods in the Rewards Center.">Coins</strong> for each Survey you complete. Share with your friends to earn extra points and you&#39;ll be that much closer to winning the big giveaway.
		</p>
		<? if (!$this->count_new_surveys) { ?>
		<div id="surveys_tabs_3" class="sb_tabPane">
			<p>Nice job, looks like you've taken all the surveys! Check back soon to earn more Coins and XP!</p>
		</div><!-- #tabs_3 -->
	<? } ?>

		<? if ($this->profile_survey_id) { ?>
			<p class="sb_tabHeader">
				Don't forget to complete the <a href="//<?= BASE_DOMAIN ?>/starbar/machinima/embed-survey?survey_id=<?= $this->profile_survey_id ?>" class="sb_nav_element" rel="sb_popBox_surveys_hg">Profile Survey</a> to unlock the goodies in the reward center.
			</p>
		<? } ?>
		<div class="sb_scrollPane">
			<? $this->displaySurveys('new', $this->starbar) ?>
		</div><!-- .sb_scrollPane -->
	</div><!-- #tabs_1 -->

	<? if ($this->count_completed_surveys || $this->count_disqualified_surveys) { ?>
		<div id="surveys_tabs_2" class="sb_tabPane">
			<p class="sb_tabHeader">All of your completed surveys are listed below.</p>
			<div class="sb_scrollPane">
				<ul class="sb_outlineList">
					<? $this->displaySurveys('completed', $this->starbar) ?>
					<? $this->displaySurveys('disqualified', $this->starbar) ?>
				</ul>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tabs_2 -->
	<? } ?>

	<? if ($this->count_archived_surveys) { ?>
		<div id="surveys_tabs_3" class="sb_tabPane">
			<p class="sb_tabHeader">We'd still love your opinion on these archived surveys, and you can still earn by completing them! Same deal &ndash; earn <strong class="sb_theme_textHighlight">Coins</strong> &amp; <strong class="sb_theme_textHighlight">XP</strong> for each one you complete.</p>
			<div class="sb_scrollPane">
				<? $this->displaySurveys('archived', $this->starbar) ?>
				<br />
				<? if ($this->count_new_surveys) { ?>
					<p align="right"><a href="#" class="sb_nav_tabs sb_theme_button" rel="1"><span class="sb_theme_buttonArrow">Take a New Survey</span></a></p>
				<? } ?>
			</div><!-- .sb_scrollPane -->
		</div><!-- #tabs_3 -->
	<? } ?>

</div><!-- .tabs -->
