<div class="sb_header">
	<img src="//<?= BASE_DOMAIN ?>/images/machinima/my_account_logo.png" alt="Machinima logo" />
	<!-- <h2 class="sb_title">My Account</h2> -->
</div><!-- .sb_header -->
<div class="sb_scrollPane">
	<ul class="sb_lineList">
		<li>
			<span class="sb_title">Levels</span>
			<div class="sb_userLevel_cycle">

				<div class="sb_userLevel_nav" id="sb_userLevel_prev"></div>

				<div class="sb_user_level_icons_container">

					<!-- all icons live inside of here, groups of 4 inside div class="sb_userLevelIcons_group" -->
					<!--
					The icon for the user's current level needs to be the active slide. Configurable in starbar-new.js
					Panels without the user's current level have 4 picks
					-->

				</div>
				<!-- .sb_user_level_icons_container -->

				<div class="sb_userLevel_nav" id="sb_userLevel_next"></div>

			</div><!-- .sb_userLevel_cycle -->
		</li>
		<li>
			<div class="sb_column5050">

				<div class="sb_column50 points">
					<span class="sb_title"><span class="sb_currency_title" data-currency-type="experience"></span></span>
					<div class="sb_user-level-box">
						<span class="sb_imgExperienceCurrency"></span>
						<div class="sb_progress_bar"><span class="sb_currency_percent" data-currency-type="experience"></span><span class="sb_progressBarValue sb_currency_balance" data-currency-type="experience"></span></div>
					</div><!-- .user-level-box -->
					<small>Level up at <span class="sb_currency_balance_next_level"></span> <span class="sb_currency_title" data-currency-type="experience"></span></small>
				</div><!-- .sb_column50 -->

				<div class="sb_column50 level">
					<div class="sb_alignLeft">
						<span class="sb_title"><span class="sb_currency_title" data-currency-type="redeemable"></span></span>
						<div class="sb_user-points-box">
							<span class="sb_imgRedeemableCurrency"></span>
							<div class="sb_progress_bar"><span class="sb_currency_percent"></span><span class="sb_progressBarValue sb_currency_balance" data-currency-type="redeemable"></span></div>
						</div><!-- .user-points-box -->
					</div>
				</div><!-- .sb_column50 -->

				<strong>
						<a href="//<?= BASE_DOMAIN ?>/starbar/machinima/rewards" class="sb_rewardsCenterLink sb_nav_element" rel="sb_popBox_rewards">
							<div class="sb_img_nextTriangle_rewards"></div>
						</a>
				</strong>
			</div><!-- .sb_column_5050 -->
		</li>
		<li>
			<span class="sb_title">My Purchases</span>
			<?
			if( $this->badges ) {
				echo "<div>\n";
			 	foreach( $this->badges as $badge )
			 		echo '<img src="//'. BASE_DOMAIN . '/client/missions/mission/'.$badge['short_name'].'/images/Mission_Badge_Purchases.png" class="sb_user_purchase_img sb_tooltip" title="'.$badge['title'].' Badge" />' . "\n";
				echo "</div>\n";
			}
			?>
			<div class="sb_user_purchases">
			</div>
		</li>
	</ul>
</div><!-- .sb_scrollPane -->
