<?php

// customer/starbar short name

$shortName = strtolower(Zend_Controller_Front::getInstance()->getRequest()->getControllerName()); 

?>
<script type="text/javascript">

	// base domain, etc per the current server environment
	
	if (!window.sayso) window.sayso = {};
	if (!window.sayso.baseDomain) {
		window.sayso.baseDomain = '<?= Registry::getConfig()->baseDomain ?>';
		window.sayso.environment = '<?= Registry::getPseudoEnvironmentName() ?>';
	}
</script>

<!-- SIMULATED customer login (popup) -->
<div id="login-click-area" style="position: relative; height: 115px;"></div>

<div id="simulate-login" style="background: white; opacity: 1; padding: 10px; margin: auto; border: solid 2px black; width: 300px; font-family: Verdana; font-size: .8em; z-index: 10000; position: relative; display: none;">
	<h2 style="margin: 2px;">Login <small id="simulate-login-status" style="font-size: .6em; color: green;"><?= $this->userLoggedIn ? '(logged in)' : '' ?></small></h2>
	<p style="margin: 2px;">Enter <strong>email</strong> to simulate user login</p>
	<small style="margin: 2px;">Changing email addresses (while the app is installed) simulates logging in as a different user</small>
	<form method="post" action="/client/<?= $shortName ?>/login">
		<p>
			<input type="hidden" name="uuid_type" value="<?= $this->uuidType ?>" />
			<input class="email" type="text" name="uuid" value="<?= $this->uuid ?>" style="width: 200px; font-size: 1.3em;" />&nbsp;<input class="submit" type="submit" name="simulate_submit" value="Login" />
		</p>
	</form>
	<? if( $this->userLoggedIn ) { ?>
		<form method="post" action="/client/<?= $shortName ?>/logout">
			<input class="submit" type="submit" name="simulate_logout" value="Logout" />
		</form>
	<? } ?>
</div>

<?= $this->partial($shortName . '/embed.phtml', array('shortName' => $shortName)) ?>
<script src="/js/jquery-1.7.1.min.js" type="text/javascript"></script>
<script src="/js/jquery.form.min.js" type="text/javascript"/></script>
<script type="text/javascript">

	// login popup
	sayso.client.loginCallback = function () {
		$('#simulate-login').show();
	}		
	// ajax form
	$('#simulate-login form').ajaxForm({
		url : $(this).attr('action'),
		type : 'post',
		dataType : 'jsonp',
		success : function (response) {
			window.location.reload();
		}
	});
	$('#login-click-area').on('click', function(){$('#simulate-login').toggle();});
</script>
