<!DOCTYPE html>
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
       Remove this if you use the .htaccess -->
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title></title>
<meta name="description" content="">
<link rel="stylesheet" href="css/starbar.css">
<link rel="stylesheet" href="css/smoothness/jquery-ui-1.8.13.custom.css">
</head>
<body>

<?php echo $this->layout()->content; ?>

<!-- /player-console -->
<script type="text/javascript" language="javascript" src="/js/jquery-1.6.1.min.js"></script>
<script type="text/javascript" language="javascript" src="/js/jquery-ui-1.8.13.custom.min.js"></script>
<script type="text/javascript" language="javascript" src="/js/jquery.tinyscrollbar.min.js"></script>
<script type="text/javascript" language="javascript" src="/js/jquery.cookies.2.2.0.min.js"></script>
<script type="text/javascript" language="javascript" src="/js/jquery.starbar.js"></script>
<!--[if lt IE 7 ]>
    <script src="/js/libs/dd_belatedpng.js"></script>
    <script>DD_belatedPNG.fix('img, .png_bg'); // Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
    <![endif]-->
</body>
</html>