<?php
// Breadcrumbs code
/**
* If a match is found here for the controller/action/table, the appropriate label is used. If not, the breadcrumb is derived
*
* @var mixed
*/

?>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Say.So | CMS</title>
		<?= $this->headLink(); ?>
				<?php printf("<!--csshelper included below-->"); ?>
				<?= $this->cssHelper(); ?>

				<?php printf("<!--csshelper included above-->"); ?>


		<?= $this->headScript(); ?>
				<?= $this->javascriptHelper(); ?>

		<?= $this->headLink()->setStylesheet($this->baseUrl().'/css/jquery-ui-1.8.2.custom.css'); ?>



	<?php

	// Use jQuery to override column widths if needed.
	if ($this->jquerywidth) { ?>
			<script type='text/javascript'>($SQ(document).ready(function() {
				<?php foreach($this->jquerywidth as $key=>$value) { ?>
							$SQ('<?=$key?>').css(<?=$value?>);
				<?php } ?>
			}));
			</script>
		<?php }	?>

	</head>
	<body>
		<div id="layout">


					<div id="common">

							<ul class="cmsMenu">

								<li><a href="/cms/admin">Home</a></li>
								<li><a href="/cms/user">User</a></li>

								<li><a href="#url">Metrics</a>
									<ul>
										<li><a href="/cms/admin/view/table/metrics_log">Log</a></li>
										<li><a href="/cms/admin/view/table/metrics_page_view">Page View</a></li>
										<li><a href="/cms/admin/view/table/metrics_search">Search</a></li>
										<li><a href="/cms/admin/view/table/metrics_social_activity">Social Activity</a></li>
									</ul>
								</li>

								<li><a href="#url">Study</a>
									<ul>
										<li><a href="/cms/admin/view/table/study">Study</a></li>
										<li><a href="#url">Avail</a></li>
										<li><a href="#url">Avail Domain Map</a></li>
										<li><a href="#">Cell</a>
										<ul>
										<li><a href="/cms/admin/view/table/study_cell">Cell</a></li>
										<li><a href="#url">Cell Assignment</a></li>
										<li><a href="#url">Cell Qualifier Browsing</a></li>
										<li><a href="#url">Cell Qualifier Search</a></li>
										<li><a href="#url">Cell Qualifier Search Engines Map</a></li>
										<li><a href="#url">Cell Tag Map</a></li>
										</ul>
										</li>
										<li><a href="#">Creative</a>
										<ul>
										<li><a href="#url">Creative</a></li>
										<li><a href="#url">Creative Data</a></li>
										<li><a href="#url">Creative Map</a></li>
										<li><a href="#url">Creative Tag Map</a></li></ul>
										</li>
										<li><a href="#url">Domain</a></li>
										<li><a href="/cms/admin/view/table/study_quota">Quota</a></li>
										<li><a href="#url">Search Engines Map</a></li>
										<li><a href="#url">Social Activity Map</a></li>
										<li><a href="#url">Survey</a></li>
										<li><a href="#url">Survey Criterion</a></li>
										<li><a href="#url">Survey Criterion Map</a></li>
										<li><a href="#url">Survey Map</a></li>
										<li><a href="#url">Tag</a></li>
										<li><a href="#url">Tag Domain Map</a></li>
									</ul>
								</li>
								<li><a href="#url">Polls/Surveys/Quizzes</a>
									<ul>
										<li><a href="/cms/admin/view/table/survey">Polls/Surveys</a></li>
										<li><a href="/cms/admin/view/table/quiz">Quizzes</a></li>
										<!--<li><a href="/cms/admin/view/table/survey_question">Question</a></li>
										<li><a href="/cms/admin/view/table/survey_question_choice">Question Choice</a></li>
										<li><a href="#url">Question Group</a></li>
										<li><a href="#url">Question Choice Group</a></li>
										<li><a href="#url">Question Response</a></li>
										<li><a href="/cms/admin/view/table/survey_response">Response</a></li>
										<li><a href="#url">User Map</a></li>-->
									</ul>
								</li>
								<!--<li><a href="#url">User</a>
									<ul>
										<li><a href="#url">User</a></li>
										<li><a href="#url">Address</a></li>
										<li><a href="#url">Avatar</a></li>
										<li><a href="#url">Child</a></li>
										<li><a href="#url">Email</a></li>
										<li><a href="#url">Gaming</a></li>
										<li><a href="#url">Key</a></li>
										<li><a href="#url">Role</a></li>
										<li><a href="#url">Social</a></li>
										<li><a href="#url">State</a></li>
									</ul>
								</li>-->
								<li><a href="#">The Closet</a>
									<ul>
										<li><a href="#url">Admin</a>
											<ul>
												<li><a href="/cms/admin/view/table/admin_role">Role</a></li>
												<li><a href="/cms/admin/view/table/admin_user">User</a></li>
												<li><a href="/cms/admin/view/table/admin_user_admin_role">User/Admin</a></li>
											</ul>
										</li>
										<!--<li><a href="#url">External</a>
											<ul>
												<li><a href="#url">User</a></li>
												<li><a href="#url">User/Install</a></li>
											</ul>
										</li>-->
										<li><a href="#url">Lookup</a>
											<ul>
												<li><a href="/cms/admin/view/table/lookup_age_range">Age Range</a></li>
												<li><a href="/cms/admin/view/table/lookup_email_frequency">Email Frequency</a></li>
												<li><a href="/cms/admin/view/table/lookup_ethnicity">Ethnicity</a></li>
												<li><a href="/cms/admin/view/table/lookup_gender">Gender</a></li>
												<li><a href="/cms/admin/view/table/lookup_income_range">Income Range</a></li>
												<li><a href="/cms/admin/view/table/lookup_poll_frequency">Poll Frequency</a></li>
												<li><a href="/cms/admin/view/table/lookup_quota_percentile">Quota Percentile</a></li>
												<li><a href="/cms/admin/view/table/lookup_search_engines">Search Engines</a></li>
												<li><a href="/cms/admin/view/table/lookup_social_activity_type">Social Activity Type</a></li>
												<li><a href="/cms/admin/view/table/lookup_survey_type">Survey Type</a></li>
												<li><a href="/cms/admin/view/table/lookup_timeframe">Timeframe</a></li>
											</ul>
										</li>
										<li><a href="#url">Notification</a>
											<ul>
												<li><a href="#url">Message</a></li>
												<li><a href="#url">Message Group</a></li>
												<li><a href="#url">Message User Map</a></li>
											</ul>
										</li>
										<li><a href="#url">Starbar</a>
											<ul>
												<li><a href="/cms/admin/view/table/starbar">Starbar</a></li>
												<li><a href="/cms/admin/view/table/economy">Economy</a></li>
												<li><a href="/cms/admin/view/table/starbar_content">Content</a></li>
												<li><a href="/cms/admin/view/table/starbar_user_map">User Map</a></li>
											</ul>
										</li>
									</ul>
								</li>
							</ul>
					</div>
<div class="clear"></div><div class="breadcrumbs">
<?php
//echo $this->navigation()->menu();
//echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render();
//echo 'You are in: '.$this->navigation()->breadcrumbs()->setLinkLast(true)->setMinDepth(0)->render();

 echo $this->breadcrumb;
 echo ($this->BackLink)?"<br />".$this->BackLink:"";

//echo $this->breadcrumb();
?>
<div id="system-message" title="System message"></div>
<?php
$flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');
$messages	   = $flashMessenger->getMessages();
if (sizeof($messages) > 0)
{
	$messages = $flashMessenger->getMessages();
	if(!empty($messages))
	{
		echo "\n<script>\nwindow._saysoMessages = ['",  implode("','", $messages) , "'];\n</script>\n";
	}
}
?>
</div>

			<div id="main" role="main">
			<?php

			    printf(" <span class='system-message'>%s</span>",$this->message) ;
				?>

				<?= $this->layout()->content ?>

			</div>
		</div>
	</body>
</html>