<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Say.So | CMS</title>
		<?= $this->headLink(); ?>
                <?php printf("<!--csshelper included below-->"); ?>
                <?= $this->cssHelper(); ?>
                <?php printf("<!--csshelper included above-->"); ?>


		<?= $this->headScript(); ?>
                <?= $this->javascriptHelper(); ?>
		 <?php printf("<!--jQuery  included below-->"); ?>
		<?///= $this->jQuery(); ?>
		 <?php printf("<!--jQuery  included above-->"); ?>
		<?= $this->headLink()->setStylesheet($this->baseUrl().'/css/jquery-ui-1.8.2.custom.css'); ?>

	</head>
	<body>
		<div id="layout">
			<header>

					<span class="common">
					<!--	<ul>
							<li><a id="menu-surveys" href="/cms/admin/" title="Survey"><span>Tablej List</span></a></li>
							<li> | </li>
							<li><a id="menu-reload" href="/cms/admin/reload" title="Survey"><span>Refresh Tables</span></a></li>

						</ul> -->
						<div class="clear"></div>
					</span>

			</header>
			<div id="main" role="main">
			    <?php
			    	printf("<span class='system-message'>%s</span>",$this->message) ;
			    ?>

			    <?= $this->layout()->content ?>

			</div>
		</div>
	</body>
</html>