<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Say.So | CMS</title>
		<?= $this->headLink(); ?>
                <?php printf("<!--csshelper included below-->"); ?>
                <?= $this->cssHelper(); ?>
                <?php printf("<!--csshelper included above-->"); ?>


		<?= $this->headScript(); ?>
                <?= $this->javascriptHelper(); ?>
		 <?php printf("<!--jQuery  included below-->"); ?>
		<?///= $this->jQuery(); ?>
		 <?php printf("<!--jQuery  included above-->"); ?>
		<?= $this->headLink()->setStylesheet($this->baseUrl().'/css/jquery-ui-1.8.2.custom.css'); ?>

	</head>
	<body>
		<div id="layout">
			<header>

					<span class="common">
						<ul>
							<li><a id="menu-surveys" href="/cms/surveys/" title="Survey"><span>Survfffeys</span></a></li>
							<li> | </li>
							<li><a id="menu-surveys" href="/cms/polls/" title="Survey"><span>Polls</span></a></li>
							<li> | </li>
							<li><a id="menu-studies" href="/cms/study/" title="Crate And Manage Studies"><span>Studies</span></a></li>
							<li> | </li>
							<li><a id="menu-metrics" href="/cms/metrics/" title="Real-Time Metrics"><span>Metrics</span></a></li>
							<li> | </li>
							<li><a id="menu-users" href="/cms/user/" title="User Management"><span>Admins</span></a></li>
						</ul>
						<div class="clear"></div>
					</span>

			</header>
			<div id="main" role="main">
			    <?php

			    $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');
			    $messages	   = $flashMessenger->getMessages();
			    $messages  = (sizeof($messages)>0)?implode("','", $messages):"&nbsp;";
			    printf("<span class='system-message'>%s</span>",$messages) ;

			    ?>

			    <?= $this->layout()->content ?>

			</div>
		</div>
	</body>
</html>
