<!-- application/views/scripts/surveys/index.phtml -->
<h1>Surveys</h1>
<table id="surveys">
    <tr>
        <th>Title</th>
        <th>Type</th>
        <th>Created</th>
        <th></th>
    </tr>


    <h2><?php printf("There are %s Surveys", $this->numberOfSurveys); ?></h2>
    <p><?php printf("%s",$this->addLink); ?></p>
    <?php $class = "odd"; ?>
    <?php foreach ($this->surveyCollection as $key => $survey): ?>
    <?php if ($class=="odd") $class="even"; else $class="odd";?>
        <tr class="<?php echo $class; ?>">
            <td class="col1">
                <a href="<?php echo $this->baseUrl('/cms/surveys/show/id/' . $survey->id) ?>">
                    <?php echo $survey->title; ?>
                </a>
            </td>
            <td class="col2">
                <?php echo $survey->type; ?>
            </td>
            <td class="col3"><?php echo $survey->created ?></td>
            <td class="col4">
                <a href="<?php echo $this->baseUrl('/cms/surveys/edit/id/' . $survey->id) ?>"><img src="<?php echo $this->baseUrl();?>/images/icons/edit.png" style='width:16px;' alt="Edit" Title="Edit" /></a>
                <a href="<?php echo $this->baseUrl('/cms/surveys/del/id/' . $survey->id) ?>"><img src="<?php echo $this->baseUrl();?>/images/icons/delete.png" style='width:16px;' alt="Delete" Title="Delete" /></a>
            </td>
        </tr>
    <?php  endforeach ?>

</table>